### ISSUE TITLE
How to customize the "Splitter" in tfidfvectorizer parameters?

### ISSUE THREAD

**Issue by xiuxiuxiaodi** [jpmml/sklearn2pmml#100]
I try to rewrite the default "splitter" function, but the result is not right.
1.First I try to extend the class "Splitter" and overwrite the "__call__"" function
2.modify the "__call__" function in the package
3.directlty pass my costumized function
All the above were failed！ How can I realize my demand?

**Comment by vruusmann** [comment]
The string splitting algorithm is hard-coded; it must be performed exactly as defined in the PMML 4.3 specification.

If you need to use a (radically-) different string splitting algorithm, then you should let the DMG.org - the maintainers of the PMML specification - know about it: https://mantis.dmg.org
