### ISSUE TITLE
FileNotFoundError: File b'Iris.csv' does not exist

### ISSUE THREAD

**Issue by MGES** [jpmml/sklearn2pmml#102]
I use the Usage's examples“a simple decision tree model for the classification of iris species”
and “a more elaborate logistic regression model for the same”【https://github.com/MGES/sklearn2pmml】
but the error is 
"**_FileNotFoundError: File b'Iris.csv' does not exist_**".

Note:
Python3.7.0
Pycharm2018.1.4
sklearn2pmml-0.37.0
sklearn0.0
sklearn-pandas1.7.0
pandas0.23.4

Please correct me if I'm wrong.
Thanks a lot,

**Comment by MGES** [comment]
@vruusmann

**Comment by vruusmann** [comment]
You can find the `Iris.csv` file here:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/csv/Iris.csv

**Comment by MGES** [comment]
Thank you very much!
