### ISSUE TITLE
How to fix Unknown label type: 'continuous'

### ISSUE THREAD

**Issue by hanhandata** [jpmml/sklearn2pmml#103]
Hi Vilu,

My python model code random forest the output is probability of default, possible to convert using PMML?
when i try fit y with float type, notif error in below. Can you help me for this?

> 
> df_x.info()
> age                          5 non-null int64
> num_of_dependence            5 non-null int64
> work_year                    5 non-null int64
> monthly_salary               5 non-null float64
> 
> df_y.info()
> RangeIndex: 5 entries, 0 to 4
> Data columns (total 1 columns):
> PD    5 non-null float64
> dtypes: float64(1)
> memory usage: 112.0 bytes
> 
> pipeline.fit(df_x,df_y)

got error

> ValueErrorTraceback (most recent call last)
> <ipython-input-21-43ac8935a963> in <module>()
>       1 
> ----> 2 pipeline.fit(df_x,df_y)
> 
> /apps/miniconda/envs/py27/lib/python2.7/site-packages/sklearn/pipeline.pyc in fit(self, X, y, **fit_params)
>     268         Xt, fit_params = self._fit(X, y, **fit_params)
>     269         if self._final_estimator is not None:
> --> 270             self._final_estimator.fit(Xt, y, **fit_params)
>     271         return self
>     272 
> 
> /apps/miniconda/envs/py27/lib/python2.7/site-packages/sklearn/ensemble/forest.pyc in fit(self, X, y, sample_weight)
>     269         self.n_outputs_ = y.shape[1]
>     270 
> --> 271         y, expanded_class_weight = self._validate_y_class_weight(y)
>     272 
>     273         if getattr(y, "dtype", None) != DOUBLE or not y.flags.contiguous:
> 
> /apps/miniconda/envs/py27/lib/python2.7/site-packages/sklearn/ensemble/forest.pyc in _validate_y_class_weight(self, y)
>     455 
>     456     def _validate_y_class_weight(self, y):
> --> 457         check_classification_targets(y)
>     458 
>     459         y = np.copy(y)
> 
> /apps/miniconda/envs/py27/lib/python2.7/site-packages/sklearn/utils/multiclass.pyc in check_classification_targets(y)
>     170     if y_type not in ['binary', 'multiclass', 'multiclass-multioutput',
>     171             'multilabel-indicator', 'multilabel-sequences']:
> --> 172         raise ValueError("Unknown label type: %r" % y_type)
>     173 
>     174 
> 
> **ValueError: Unknown label type: 'continuous'**

**Comment by vruusmann** [comment]
Most likely a variation of #101 - the Python data type of `df_y` is something strange, and should be changed to `numpy.array`.
