### ISSUE TITLE
Score in tree and score in xml

### ISSUE THREAD

**Issue by Hedgehogues** [jpmml/sklearn2pmml#106]
[DecisionTreeBoxPacker.pmml.txt](https://github.com/jpmml/sklearn2pmml/files/2423798/DecisionTreeBoxPacker.pmml.txt)

[tree.dot.txt](https://github.com/jpmml/sklearn2pmml/files/2423800/tree.dot.txt)
![tree](https://user-images.githubusercontent.com/4973667/46142238-fe105e00-c25e-11e8-86a3-753502ec2361.png)

Hello I have a problem. In my dot file and ppml-file, I have deifferent scores. I use a RandomForestRegressor from sklearn.

**Comment by vruusmann** [comment]
> I have deifferent scores.

Examples?

In brief, JPMML-SkLearn has reorganized the decision tree data structure from binary splits to multi-way splits (in order to make the tree more compact), but it hasn't lost or changed any relevant information. Your node scores are simply located in different places.

**Comment by Hedgehogues** [comment]
```
seed = 42
np.random.seed(42)
x = np.random.rand(20, 5)
y = np.random.rand(20)

from sklearn2pmml import sklearn2pmml, sklearn
from sklearn2pmml.pipeline import PMMLPipeline

dt_ = DecisionTreeRegressor(random_state=seed)

pipeline = PMMLPipeline([
    ("regressor", dt_)
])

pipeline.steps[0][1].fit(x, y)
sklearn2pmml(pipeline, "dt_.pmml", with_repr = True)


from subprocess import call
from IPython.display import Image
from sklearn.tree import export_graphviz

dt_.fit(x, y)
export_graphviz(dt_, out_file='tree_.dot')
call(['dot', '-Tpng', 'tree_.dot', '-o', 'tree_.png', '-Gdpi=100'])

Image(filename = 'tree_.png')
```

I generate dot-file and pmml-file. Score are different. Please explain me what mean filed "score" and how i can extract "mse" and "sample"? 

![tree_](https://user-images.githubusercontent.com/4973667/46217707-69cff500-c34b-11e8-875d-60f5a4d4defa.png)
[dt_.pmml.txt](https://github.com/jpmml/sklearn2pmml/files/2428752/dt_.pmml.txt)
[tree_.dot.txt](https://github.com/jpmml/sklearn2pmml/files/2428753/tree_.dot.txt)

**Comment by vruusmann** [comment]
You should be calling `PMMLPipeline.fit(X, y)` directly, but that doesn't change anything about this issue.

Try the following code:
```Python
pipeline = PMMLPipeline([
    ("regressor", dt_)
])
pipeline.fit(x, y)
pipeline.configure(compact = False, flat = False)
```

The PMML data structure is exactly the same as the Scikit-Learn (exported in DOT file format) data structure.

**Comment by Hedgehogues** [comment]
Thank you for your fix. This is very important for me.

Yes, this line fixed my problem `pipeline.configure(compact = False, flat = False)`. But I cannot find this line into README [here](https://github.com/jpmml/sklearn2pmml). Please, get me link to doc. 

Now, I got these files (attach) with your fix. But as before I don't find "mse" and "samples" also as it is done in dotfile. Please, explain me this. 

[dt_.pmml.txt](https://github.com/jpmml/sklearn2pmml/files/2429481/dt_.pmml.txt)
[tree_.dot.txt](https://github.com/jpmml/sklearn2pmml/files/2429482/tree_.dot.txt)
![tree_](https://user-images.githubusercontent.com/4973667/46229456-5da95f00-c36e-11e8-8f6f-e0d3a0bb4edd.png)
