### ISSUE TITLE
Is there a doc for instructing how to develop customized python script and java programs that adapt to jpmml?

### ISSUE THREAD

**Issue by liubinpoem** [jpmml/sklearn2pmml#108]
I developed some python programs in preprocessing data  such as Chi and WOE, but it can not be converted to pmml. If there is a doc or a standard on guiding how to develop the python model and java code, it will help a lot. And many other developers can help to develop useful program.  Any suggestions ?

**Comment by vruusmann** [comment]
See the [SkLearn2PMML-Plugin](https://github.com/jpmml/sklearn2pmml-plugin) project.

You would need to first write a Python class (that extends SkLearn's `TransformerMixin`), and when you are satisfied with its functionality, write a corresponding JPMML-SkLearn class (that extends `sklearn.Transformer`). The latter is an abstract class; the conversion logic must be put inside the `#encodeFeatures(List<Feature>, SkLearnEncoder)` method.

Alternatively, if you think that your transformer classes could be useful for the wider community, then you should publish them as a standalone Python project/package. I could then help you with implementing the JPMML-SkLearn side of things.

**Comment by liubinpoem** [comment]
Thanks a lot, I'll have a try.

**Comment by liubinpoem** [comment]
One more suggestion for your consideration, maybe you could write a step by step tutorial on guiding how to  write plugin program. I think there are a lot of guys like me need that. Thanks a lot.
