### ISSUE TITLE
converting to PMML an existing model

### ISSUE THREAD

**Issue by ftk1000** [jpmml/sklearn2pmml#111]
I am interested in converting to PMML a model which has been already built.
There are several reasons for that. E.g.,
1/ I would like to evaluate a model on various test sets before deciding on its conversion to PMML
2/ I may want to save the model in PKL format
So, I was trying to take an existing model (XGBOOST model in my case) and save it as PMML file.
Is there a way to do that?

**Comment by vruusmann** [comment]
Option one (assuming the pickle object contains a single estimator instance):
```Python
obj = pickle.load(..)
pipeline = PMMLPipeline([
  ("estimator", obj)
])
# No need to call pipeline#fit, because the `obj` already is/contains a fitted estimator
sklearn2pmml(pipeline, "pipeline.pmml")
```

Option two (assuming the pickle object contains a pipeline of transformers and an estimator):
```Python
from sklearn2pmml import make_pmml_pipeline

obj = pickle.load(...)
pipeline = make_pmml_pipeline(obj)
sklearn2pmml(pipeline, "pipeline.pmml")
```

See https://github.com/jpmml/sklearn2pmml/blob/master/sklearn2pmml/__init__.py#L107-L128
