### ISSUE TITLE
java.lang.IllegalArgumentException while using OneHotEncoder on Non-integer categorical column

### ISSUE THREAD

**Issue by steadyfish** [jpmml/sklearn2pmml#112]
Hi

There seems to be some issue with PMML generation when the pipeline includes a OneHotEncoder() step on non-integer categorical columns. This may be similar to #53, #61  

Error:
`sklearn2pmml(pipeline, 'pipeline_lin.pmml', debug = True)`
```
python: 3.6.5
sklearn: 0.20.0
sklearn.externals.joblib: 0.12.5
pandas: 0.23.0
sklearn_pandas: 1.7.0
sklearn2pmml: 0.39.0
java: N/A
Executing command:
java -cp C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\guava-26.0-jre.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\h2o-genmodel-3.20.0.9.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\istack-commons-runtime-3.0.5.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\javax.activation-api-1.2.0.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\jaxb-api-2.3.0.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\jaxb-core-2.3.0.1.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\jaxb-runtime-2.3.0.1.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\jcommander-1.72.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\jpmml-converter-1.3.3.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\jpmml-h2o-1.0.1.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\jpmml-lightgbm-1.2.2.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\jpmml-sklearn-1.5.8.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\jpmml-xgboost-1.3.3.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\pmml-agent-1.4.5.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\pmml-model-1.4.5.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\pmml-model-metro-1.4.5.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\pyrolite-4.21.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\serpent-1.23.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\slf4j-api-1.7.25.jar;C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\resources\slf4j-jdk14-1.7.25.jar org.jpmml.sklearn.Main --pkl-pipeline-input C:\Users\fake_user\AppData\Local\Temp\pipeline-gn2lcrh7.pkl.z --pmml-output C:\fake_user_directory\pipeline_lin.pmml
Standard output is empty
Standard error:
Oct 24, 2018 1:16:42 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Oct 24, 2018 1:16:42 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 31 ms.
Oct 24, 2018 1:16:42 PM org.jpmml.sklearn.Main run
INFO: Converting..
Oct 24, 2018 1:16:42 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException
        at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:51)
        at sklearn.Initializer.encodeFeatures(Initializer.java:41)
        at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:202)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException
        at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:51)
        at sklearn.Initializer.encodeFeatures(Initializer.java:41)
        at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:202)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)

Preserved joblib dump file(s): C:\Users\Fake_User\AppData\Local\Temp\pipeline-gn2lcrh7.pkl.z
Traceback (most recent call last):

  File "<ipython-input-116-b1714df1c6aa>", line 1, in <module>
    sklearn2pmml(pipeline, dir_path + 'pipeline_sgd.pmml', debug = True)

  File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\__init__.py", line 243, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

Reproducible example:
```
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, OneHotEncoder
from sklearn_pandas import DataFrameMapper
from sklearn.linear_model import LinearRegression
from sklearn2pmml.pipeline import PMMLPipeline


df = pd.DataFrame([(0, 0, 'asd'), (0.5, 0,'asd'), (0.7, 0.5, 'asd'), (1, 3.5, 'asd'), (2, 3.0, 'asd'), (2, 8.5, 'dsa'), (3, 0.2, 'dsa')], columns = ['Y', 'X1', 'X2'])
X = df[['X1', 'X2']]
Y = df['Y']

scaler_def = (['X1'], MinMaxScaler())
encode_def = (['X2'], OneHotEncoder()) 

prep_mapper = DataFrameMapper([
        scaler_def, encode_def
        ], input_df = True, 
        df_out = True,
        default = None)

pipeline = PMMLPipeline([('encoder', prep_mapper), ('reg', LinearRegression())])

pipeline.fit(X, Y)

# Error while saving model in PMML format
sklearn2pmml(pipeline, 'pipeline_lin.pmml', debug = True)

```

**Comment by vruusmann** [comment]
Thanks for a very thorough problem report.

Looking into `DataFrameMapper.java` line 51 shows that this exception is thrown when the value of the `DataFrameMapper.default` attribute is something else than the boolean constant `False`. In your case, it is `None`.

I think that `default = False` would be functionally equivalent to `default = None` here. After the code change everything should be OK (ie. the `OneHotEncoder` step works as advertised) - can you test and report back?

**Comment by vruusmann** [comment]
> can you test and report back?

My bad - since you provided an almost fully reproducible example (there's a only `from sklearn2pmml import sklearn2pmml` directive missing), then I was able to perform this code change to `default = None` myself.

The exception now becomes:
```
SEVERE: Failed to convert
java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
        at sklearn.preprocessing.OneHotEncoder.encodeFeatures(OneHotEncoder.java:83)
        at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
```

That's now a legit `OneHotEncoder` conversion issue. In brief, the converter expects the value of `OneHotEncoder.values` attribute to be a list of numbers, but it appears to be a list of strings in this case. I assume that all string list elements are parseable to integers, so it shouldn't difficult to fix.

**Comment by vruusmann** [comment]
In other words, this issue reflects to shortcomings of the JPMML-SkLearn library:

1. The converter for `DataFrameMapper` should treat `default = None` the same as `default = None`.
2. The converter for `OneHotEncoder` should be prepared to parse the elements of `OneHotencoder.values` if necessary.

**Comment by steadyfish** [comment]
Hi @vruusmann,

Agree with your findings. This also seems to be caused by latest changes on the [sklearn library (version 0.20)](http://scikit-learn.org/stable/whats_new.html#version-0-20-0) which includes allowing non-integer categorical columns as inputs to `OneHotEncoder()`

> String or pandas Categorical columns can now be encoded with `OneHotEncoder` or `OrdinalEncoder`

While necessary downstream changes to JPMML-SkLearn library are worked upon, could you suggest a workaround for achieving this `OneHotEncoder` like transformation within the PMMLpipeline?

**Comment by vruusmann** [comment]
> For (1), how to handle cases where some of the inputs need to be kept without any transformation?

Simply map those columns to the `None` transformer. This trick is explained in the sklearn_pandas README file.

Please note that if you mention all columns in the `DataFrameMapper` specification, then you can also replace `default = None` with `default = False`.

Example:
```Python
mapper = DataFrameMapper([
  (["x"], None)
])
```

**Comment by steadyfish** [comment]
I tried this approach but ran into another issue - 

```
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Expected 0 element(s), got 5 element(s)
        at org.jpmml.sklearn.ClassDictUtil.checkSize(ClassDictUtil.java:63)
        at sklearn.Initializer.encodeFeatures(Initializer.java:39)
        at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:202)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)
```

I'm not able to understand why `sklearn.Initializer.encodeFeatures(Initializer.java:39)` is expecting 0 features.

Code:
```
import pandas as pd
from sklearn.preprocessing import MinMaxScaler, LabelBinarizer, StandardScaler
from sklearn_pandas import DataFrameMapper
from sklearn.linear_model import LinearRegression
from sklearn2pmml.pipeline import PMMLPipeline
from sklearn2pmml import sklearn2pmml

df = pd.DataFrame([(0, 0, 'asd', 1), (0.5, 0,'asd', 1), (0.7, 0.5, 'asd', 2), (1, 3.5, 'ad', 2), 
                   (2, 3.0, 'asd', 3), (2, 8.5, 'dsa', 4), (3, 0.2, 'dsa', 0.6)], columns = ['Y', 'X1', 'X2', 'X3'])
X = df[['X1', 'X2', 'X3']]
Y = df['Y']

prep1_cont = [(['X1'], MinMaxScaler()), (['X3'], MinMaxScaler())]
prep1_cat = [(['X2'], LabelBinarizer())]
prep1_mapper = DataFrameMapper(prep1_cont + prep1_cat, input_df = True, df_out = True, default = False)
temp = prep1_mapper.fit_transform(X, Y)

prep2_cont = [(['X1'], StandardScaler())]
prep2_none = gen_features(columns = [[col] for col in temp.columns.difference(['X1'])], classes = None)
prep2_mapper = DataFrameMapper(prep2_cont + prep2_none, input_df = True, df_out = True, default = False)

pipeline = PMMLPipeline([ ('prep1', prep1_mapper),
                          ('prep2', prep2_mapper),
                          ('reg', LinearRegression())])
pipeline.fit(X, Y)

# sklearn2pmml conversion fails
sklearn2pmml(pipeline, dir_path + 'pipeline_lin.pmml', debug = True)
```

Could you suggest what's wrong here with my code?

**Comment by vruusmann** [comment]
> Could you suggest what's wrong here with my code?

If you want to have two `DataFrameMapper` objects in the beginning of your pipeline, you must make them "equal" by using `FeatureUnion`:

```Python
pipeline = PMMLPipeline([
  ("mappers", FeatureUnion([
    ('prep1', prep1_mapper),
    ('prep2', prep2_mapper)
  ])),
  ('reg', LinearRegression())
])                      
```

At the moment you have them "unequal" - the "prep1" step is sending data to "prep2" step, which is not allowed.

The exeception message "java.lang.IllegalArgumentException: Expected 0 element(s), got N element(s)" means that the corresponding transformer must always be on the first position of the pipeline.

**Comment by steadyfish** [comment]
Hi @vruusmann 

For the above test example, I can get around this restriction just by specifying multiple transformers within single DataFrameMapper, like this -

```python
prep_mapper = DataFrameMapper([(['X1'], [MinMaxScaler(), StandardScaler()]), 
                               (['X2'], LabelBinarizer()), (['X3'], [MinMaxScaler(), None])], 
                        input_df = True, df_out = True, default = False)
```

For a more complex examples, I was not sure how can I achieve this so I was wondering why this is not allowed -
> At the moment you have them "unequal" - the "prep1" step is sending data to "prep2" step, which is not allowed.

For e.g. how to generate PMML for the following pipeline - 

![image](https://user-images.githubusercontent.com/1509829/47727545-f3b4fb80-dc32-11e8-93e0-a209bad40bc4.png)

**Comment by cockroachzl** [comment]
@vruusmann Has this issue of applying sklearn OneHotEncoder to categorical columns of string types been fixed? I still encounter this issue with the latest version of jpmml-sklearn.

**Comment by vruusmann** [comment]
> Has this issue of applying sklearn OneHotEncoder to categorical columns of string types been fixed?

@cockroachzl Probably not. But you can always use `LabelBinarizer` or `LabelEncoder + OneHotEncoder` as a workaround.

IIRC, older versions of Scikit-Learn didn't allow OHE on string columns, that's why this behaviour is missing in the JPMML-SkLearn library.
