### ISSUE TITLE
java.lang.IllegalArgumentException when exporting a pipeline which can successfully predict

### ISSUE THREAD

**Issue by HongHuangNeu** [jpmml/sklearn2pmml#113]
I have created a PMMLPipeline which contains two DataFrameMapper and one classifier. The pipeline can successfully predict, but when exporting the pipeline to pmml file, I got the following error:

***********************************************************************************************
java.lang.IllegalArgumentException: Expected 0 element(s), got 9 element(s)
	at org.jpmml.sklearn.ClassDictUtil.checkSize(ClassDictUtil.java:63)
	at sklearn.Initializer.encodeFeatures(Initializer.java:39)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:202)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: Expected 0 element(s), got 9 element(s)
	at org.jpmml.sklearn.ClassDictUtil.checkSize(ClassDictUtil.java:63)
	at sklearn.Initializer.encodeFeatures(Initializer.java:39)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:202)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Preserved joblib dump file(s): /var/folders/p_/tdkm1f5159vdght67bhbc8rh0000gn/T/pipeline-u3DMaz.pkl.z`

**********************************************************************************************

The following is the code snippet:

*********************************************************************************************
mapper = DataFrameMapper([
    (['sbp'], MinMaxScaler()),
    (['tobacco'], MinMaxScaler()),
    ('ldl', None),
    ('adiposity', None),
    ('famhist',LabelEncoder() ),
    ('typea', None),
    ('obesity', None),
    ('alcohol', None),
    (['age'], FunctionTransformer(np.log))
],
df_out=True)

mapper2 = DataFrameMapper([
    ('sbp', None),
    ('tobacco', None),
    ('ldl', None),
    ('adiposity', None),
    (['famhist'],OneHotEncoder(categories='auto') ),
    ('typea', None),
    ('obesity', None),
    ('alcohol', None),
    ('age', None)
],
df_out=True)

pipeline = PMMLPipeline([
   ('mapper', mapper),
    ('mapper1',mapper2),
   ("classifier",GradientBoostingClassifier())
])

vv=pipeline.fit(heart_data[heart_data.columns.difference(["chd"])] ,heart_data["chd"] )
print vv

#print pipeline.transform(heart_data[heart_data.columns.difference(["chd"])])

print pipeline.predict(heart_data[heart_data.columns.difference(["chd"])])

sklearn2pmml(pipeline, "lrHeart.pmml", with_repr = True,debug=True)
***************************************************************************************

The exception is caused in the sklearn2pmml method. 
When there is only 'mapper' and 'classifier', everything is fine. But where there are 2 mappers, sklearn2pmml complains about argument numbers. Any ideas?

**Comment by vruusmann** [comment]
> When there is only 'mapper' and 'classifier', everything is fine. But where there are 2 mappers, sklearn2pmml complains about argument numbers.

First, it does not make much sense to chain two `DataFrameMapper` steps one after another like this (the second one would be dealing with transformed column names/values, not the original ones). Second, a `DataFrameMapper` must be on a first position, because it "initializes" feature definitions.

If you want to combine multiple `DataFrameMapper` steps, then they all need to be on the first position. This is easy to achieve using the `FeatureUnion` meta-transformation:

```Python
union = FeatureUnion([
  ("first", mapper1),
  ("second", mapper2)
])
```

Then:

```Python
pipeline = PMMLPipeline([
  ("union", union),
  ("estimator", estimator)
])
```

**Comment by vruusmann** [comment]
> java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
>  at sklearn.preprocessing.OneHotEncoder.encodeFeatures(OneHotEncoder.java:83)
>  at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)

That's an exact duplicate of https://github.com/jpmml/sklearn2pmml/issues/112

> Is there a recommended way to encode string features and export the flow to pmml?

Replace `[OneHotEncoder(), LabelEncoder()]` with `[LabelBinarizer()]`
