### ISSUE TITLE
PMML feature names defaults to "x1", "x2" when converting trained xgbmodel to PMML

### ISSUE THREAD

**Issue by ftk1000** [jpmml/sklearn2pmml#117]
Hi,
this is a follow up on issue #111 "**_converting to PMML an existing model_**" closed on Oct 17.
I have a data frame X2df  with columns "Weight", "Salary", "Age" etc

If I create a PMML as follows
```
pipeline = PMMLPipeline( [("classifier", xgb.XGBClassifier( max_depth=3, n_estimators=5, learning_rate=0.05 ))])

pipeline.fit(X2df, y)

sklearn2pmml(pipeline, "test0.pmml", with_repr=True)
```

then in "test0.pmml" file feature names look as expected:
```
<DataField name="Weight" optype="continuous" dataType="float"/>
<DataField name="Salary" optype="continuous" dataType="float"/>
<DataField name="Age" optype="continuous" dataType="float"/>
```

However, if I take a pre-trained xgbmodel
`xgbmodel = xgb.XGBClassifier( max_depth=3, n_estimators=5, learning_rate=0.05 ).fit(X2df, y)
`
and try to generate PMML out of it as follows
```python
pipeline = PMMLPipeline( [( "classifier", xgbmodel )])
sklearn2pmml(pipeline, "test1.pmml", with_repr=True)
```
then in test1.pmml file feature names are default names:
```
<DataField name="x1" optype="continuous" dataType="float"/>
<DataField name="x2" optype="continuous" dataType="float"/>
<DataField name="x3" optype="continuous" dataType="float"/>
```
How do I enable proper feature names in this case?

Thanks

**Comment by vruusmann** [comment]
> How do I enable proper feature names in this case?

The pre-trained xgbmodel does not contain any feature names. Therefore, you need to specify `PMMLPipeline.active_fields` and `PMMLPipeline.target_fields` attributes manually - as Numpy arrays of strings.

For example:
```Python
pipeline = PMMLPipeline( [( "classifier", xgbmodel )])
pipeline.active_fields = numpy.asarray(["Weight", "Salary", "Age"])
pipeline.target_fields = numpy.asarray(["Prediction"])
sklearn2pmml(pipeline, "test1.pmml", with_repr=True)
```
