### ISSUE TITLE
debug=True error

### ISSUE THREAD

**Issue by Leviclt** [jpmml/sklearn2pmml#120]
import pandas
iris_df = pandas.read_csv("iris.csv")

from sklearn_pandas import DataFrameMapper
from sklearn.preprocessing import LabelBinarizer

names = ['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width']

mapper_lgb = DataFrameMapper([
(names, None),
('degrees', LabelBinarizer()),
])

from sklearn.tree import DecisionTreeClassifier
from sklearn2pmml.pipeline import PMMLPipeline

pipeline = PMMLPipeline([
("mapper", mapper_lgb),
("classifier", DecisionTreeClassifier()),

])

pipeline.fit(iris_df[iris_df.columns.difference(["Species"])], iris_df["Species"])

from sklearn2pmml import sklearn2pmml

sklearn2pmml(pipeline, "DecisionTreeIris.pmml", with_repr = True) # this is ok
sklearn2pmml(pipeline, "DecisionTreeIris.pmml", with_repr = True, debug=True) # but thisi is fail

report

UnicodeDecodeError Traceback (most recent call last)
in ()
30 from sklearn2pmml import sklearn2pmml
31
---> 32 sklearn2pmml(pipeline, "DecisionTreeIris.pmml", with_repr = True, debug=True)

~\AppData\Roaming\Python\Python36\site-packages\sklearn2pmml_init_.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug)
237 print("Standard output is empty")
238 if(len(error) > 0):
--> 239 print("Standard error:\n{0}".format(error.decode("UTF-8")))
240 else:
241 print("Standard error is empty")

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd4 in position 4: invalid continuation byte

**Comment by Leviclt** [comment]
can you tell me  why debug=True is fail  but without  set this  parameter  is ok

**Comment by vruusmann** [comment]
> who can tell me why debug=True is fail

If `option = True`, then the Python process reads all bytes from the standard error and output streams of the underlying Java process, and tries to convert them to a printable string using `decode("UTF-8")`:
https://github.com/jpmml/sklearn2pmml/blob/master/sklearn2pmml/__init__.py#L233-L241

Your Python process appears to be producing bytes that do not represent an UTF-8 encoded string. This is most likely a character set issue. What is your default character set?

If `option = False`, then the standard and output streams of the Java process are simply ignored.

**Comment by vruusmann** [comment]
Potential workaround: the `sklearn2pmml._java_version()` could print the name of the default character encoding, so that the `sklearn2pmml.sklearn2pmml()` method could use it instead of "UTF-8".
