### ISSUE TITLE
Not able to replace invalid values to missing or any other value in PMML

### ISSUE THREAD

**Issue by apurvaanand1** [jpmml/sklearn2pmml#130]
I have a categorical feature and I want to replace the invalid_values (unseen data) for that feature either with missing value or with any other string. I tried using:
```
[CategoricalDomain( invalid_value_treatment = 'as_missing',missing_value_treatment = "as_value", missing_value_replacement = "NA",missing_values="NA"), LabelBinarizer()]
```
However the unseen data does not seem to be replaced.

**Comment by vruusmann** [comment]
Scikit-Learn has the concept of missing values, but not the concept of invalid values. PMML has them both.

So, the `CategoricalDomain` transformer only detects and replaces missing values (as instructed by `missing_values`, `missing_value_replacement` and `missing_value_treatment` attributes). The Python side completely ignores `invalid_value_replacement` and `invalid_value_treatment` attributes, but they are recognized by the SkLearn2PMML converter, and stored in the PMML document, so all PMML document consumers (such as the JPMML-Evaluator library) will know what to do when encountering an invalid value.

**Comment by vruusmann** [comment]
What could be a workaround?

Option one: the `CategoricalDomain` constructor should accept a list of valid category values, and treat all input values that are not contained in that list as invalid values: `CategoricalDomain(valid_values = ["red", "yellow", "green"])`.

Option two: the `CategoricalDomain` constructor should accept a list of invalid category values instead. If an input value is contained in that list, it will be subjected to invalid value treatment: `CategoricalDomain(invalid_values = ["pink", "cyan"])`.

**Comment by vruusmann** [comment]
The proposed `CategoricalDomain.valid_values` and `CategoricalDomain.invalid_values` attributes are purely fictional in this point. I was just throwing out some ideas about how to address your use case.

Both options have their own advantages and disadvantages. Maybe they should be both implemented, but could be activated only one by one.

**Comment by vruusmann** [comment]
This issue is related to #62 and #72

Looks like a significant cluster of problems/missing functionality.
