### ISSUE TITLE
Format OutputField attribute name

### ISSUE THREAD

**Issue by sthuemm** [jpmml/sklearn2pmml#132]
Is there a way to change the format of the name in the Outputfield tag? Currently the name is being output as probability(<class-name>). In the tool where I am currently using the PMML file, the name is interpreted as a function because of the format and therefore cannot be used.

**Comment by vruusmann** [comment]
> Is there a way to change the format of the name in the OutputField tag?

Not during conversion. But you can always post-process the newly generated PMML, and perform whatever field name replacements you like.

> Currently the name is being output as probability().

This is an excellent convention. Won't be changed.

> In the tool where I am currently using the PMML file, the name is interpreted as a function because of the format and therefore cannot be used.

Must be this issue: https://github.com/siddhi-io/siddhi/issues/1025

This tool should be fixed - either by escaping user input, or by updating the underlying user input parsing grammar.

In the upcoming JPMML-Evaluator library version there are two special-purpose interfaces `org.jpmml.evaluator.InputMapper` and `org.jpmml.evaluator.ResultMapper` that can be used to perform arbitrary field name "munging".
