### ISSUE TITLE
cutTransformer doesn't allow for numeric labels

### ISSUE THREAD

**Issue by xiaowei1234** [jpmml/sklearn2pmml#134]
Not sure if this is an easy fix or if there is a workaround. I understand typically cutTransformer transforms continuous data to categorical. But is it possible to have it also transform continuous to continuous data type? See below

```python
make_pipeline(ContinuousDomain(), SimpleImputer()
        , CutTransformer(bins=[0, 100, 2001], labels=[0.1, 0.5])
```

This pipeline actually works in regular sklearn pipeline or PMMLPipeline. However, when I try to convert the pipeline into an PMML file I get the following error.

```
java.lang.IllegalArgumentException: List attribute 'sklearn2pmml.preprocessing.CutTransformer.labels' contains an unsupported value (Java class java.lang.Double)
```

The use case for this type of transformation is for "weight of evidence" binning, typically used for credit risk models

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException:  List attribute 'sklearn2pmml.preprocessing.CutTransformer.labels' contains an unsupported value

That's a completely arbitrary restriction, and could be easily relaxed by allowing list elements to be of type `java.lang.Object` (instead of `java.lang.String`) here:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn2pmml/preprocessing/CutTransformer.java#L113

In the meantime, can't you work around this by specifying `labels=["0.1", "0.5"]`?

**Comment by xiaowei1234** [comment]
specifying labels=["0.1", "0.5"] would turn them into categorical variables which would need a labelbinarizer step and would turn one variable into two in this example. I want cutTransformer pipeline to still return only one column (column of values either 0.1 or 0.5) for the model not two columns.

**Comment by vruusmann** [comment]
If you know for sure that all values in the string column are castable to numeric values, then another workaround would be to apply `sklearn2pmml.preprocessing.ExpressionTransformer` to the outcome of `CutTransformer`. Something like this:
```python
mapper = DataFrameMapper([
  (["input"], [ContinuousDomain(), CutTransformer(..), ExpressionTransformer("int(X[0])")])
])
```

Then again, I can't recall if `ExpressionTransformer` knows how to handle the `int()` function already.

**Comment by xiaowei1234** [comment]
the pipeline `fit` was fine using `ExpressionTransformer("int(X[0])")`. However, when trying to convert to PMML file there was an error of `java.lang.IllegalArgumentException: int`

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException: int

The Python expression-to-PMML translator component only knows about `pandas.isnull` and `pandas.notnull` functions:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/javacc/expression.jj#L90-L107

It needs to be explicitly taught about `int(..)`, `float(...)`, etc. functions.

Well, we have a nice cluster of issues/feature requests open now. A fully fixed SkLearn2PMML package should become available in the first half of next week.

**Comment by xiaowei1234** [comment]
wow thats fast! I eagerly await the update.

**Comment by xiaowei1234** [comment]
I can't believe how fast you have solved this. Do you take donations? I can Paypal some money to your openscoring email account

**Comment by vruusmann** [comment]
@xiaowei1234 If you put me in contact with your manager, then I might explain to him/her how my business really works. That's fairly complicated stuff.
