### ISSUE TITLE
Java is not installed, or the Java executable is not on system path

### ISSUE THREAD

**Issue by Brucetangjianping** [jpmml/sklearn2pmml#139]
![image](https://user-images.githubusercontent.com/12164467/54329918-be8fcf80-464e-11e9-915f-0d82a5fb96d7.png)
as above picture show, when I use sklearn2pmml save xgboost model, sometimes there throw that RuntimeError.however my cdh cluster server have installed java
![image](https://user-images.githubusercontent.com/12164467/54330168-aff5e800-464f-11e9-940c-43bd7e334ac8.png)

**Comment by vruusmann** [comment]
It's 100% configuration issue - Python's `Popen()` function is operating in an environment, where the `java.exe` is not available on system path. Maybe it's something Anaconda specific (use a regular Python setup instead), maybe you're using different user account which has a different `PATH` environment variable set than your current user account?

I can't do anything about such configuration issues.
