### ISSUE TITLE
Engimatic SimpleImputer error

### ISSUE THREAD

**Issue by xiaowei1234** [jpmml/sklearn2pmml#140]
HI Villu,

This cryptic error pops up when I use SimpleImputer. Here is the following code. If you comment out the line with SimpleImputer it runs fine. Also note that if you replace the 
`('code1', make_pipeline(lk_pipe, col_trans2))` line with
`('code1', PMMLLabelBinarizer())`
it will run fine as well

```
import pandas as pd
import numpy as np
from sklearn_pandas import DataFrameMapper
from sklearn2pmml.decoration import ContinuousDomain
from sklearn2pmml import PMMLPipeline, sklearn2pmml
from sklearn.pipeline import FeatureUnion
from sklearn.linear_model import LogisticRegression
from sklearn2pmml.preprocessing import LookupTransformer, ExpressionTransformer, PMMLLabelBinarizer
from sklearn.pipeline import make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

manual_df = pd.DataFrame({'code1': ['a', 'b', 'c'], 'code2': [-1, -1, 5], 'other': [1,2,3]})
y = np.array([0,0,1])
other = DataFrameMapper([(['other'], ContinuousDomain())])
lk_pipe = make_pipeline(LookupTransformer({'a': 'b', 'b': 'd'}, 'Z'), PMMLLabelBinarizer())
col_trans2 = ColumnTransformer([('last', 'drop', [0])], remainder='passthrough')
look = DataFrameMapper([
    ('code1', make_pipeline(lk_pipe, col_trans2))
    , ('code2', LookupTransformer({5: 1}, 0))
])
# express = ExpressionTransformer('X[0]+X[1]')

# look_express = make_pipeline(look, express)

fu = FeatureUnion([
 ('feat1', other)
, ('feat2', look)
])

pipe = PMMLPipeline([
    ('fu', fu)
    , ('imp', SimpleImputer(strategy='median'))
    , ('clf', LogisticRegression())
])
xpipe = PMMLPipeline([
     ('fu', fu)
])
```

error message
```
Standard output is empty
Standard error:
Mar 14, 2019 2:01:57 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Mar 14, 2019 2:01:57 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 33 ms.
Mar 14, 2019 2:01:57 PM org.jpmml.sklearn.Main run
INFO: Converting..
Mar 14, 2019 2:01:57 PM sklearn2pmml.pipeline.PMMLPipeline encodePMML
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Mar 14, 2019 2:01:57 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.UnsupportedOperationException
	at org.jpmml.converter.ObjectFeature.toContinuousFeature(ObjectFeature.java:32)
	at org.jpmml.converter.regression.RegressionModelUtil.createRegressionTable(RegressionModelUtil.java:244)
	at org.jpmml.converter.regression.RegressionModelUtil.createBinaryLogisticClassification(RegressionModelUtil.java:114)
	at org.jpmml.converter.regression.RegressionModelUtil.createBinaryLogisticClassification(RegressionModelUtil.java:88)
	at sklearn.linear_model.LinearClassifier.encodeModel(LinearClassifier.java:74)
	at sklearn.linear_model.logistic.LogisticRegression.encodeOvRModel(LogisticRegression.java:140)
	at sklearn.linear_model.logistic.LogisticRegression.encodeModel(LogisticRegression.java:61)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:215)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.UnsupportedOperationException
	at org.jpmml.converter.ObjectFeature.toContinuousFeature(ObjectFeature.java:32)
	at org.jpmml.converter.regression.RegressionModelUtil.createRegressionTable(RegressionModelUtil.java:244)
	at org.jpmml.converter.regression.RegressionModelUtil.createBinaryLogisticClassification(RegressionModelUtil.java:114)
	at org.jpmml.converter.regression.RegressionModelUtil.createBinaryLogisticClassification(RegressionModelUtil.java:88)
	at sklearn.linear_model.LinearClassifier.encodeModel(LinearClassifier.java:74)
	at sklearn.linear_model.logistic.LogisticRegression.encodeOvRModel(LogisticRegression.java:140)
	at sklearn.linear_model.logistic.LogisticRegression.encodeModel(LogisticRegression.java:61)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:215)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-52-e98c852857fb> in <module>()
----> 1 sklearn2pmml(pipe, 'trial.pmml', with_repr=True)

~/anaconda3/lib/python3.6/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    250                                 print("Standard error is empty")
    251                 if retcode:
--> 252                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    253         finally:
    254                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by vruusmann** [comment]
JPMML conversion libraries use a special `org.jpmml.converter.ObjectFeature` feature type do denote "obscure" columns. As a matter of precaution, the converter does not let you use such columns for anything (erring on the safe side - if there's a risk of producing an invalid PMML document, then lets not generate a PMML document at all).

If you apply `SimpleImputer` to a column whose data type is something else than `integer`, `float`, `double` or `string`, then you'll get this dreaded `ObjectFeature`:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/impute/ImputerUtil.java#L75-L85

You're currently applying `SimpleImputer` to multiple columns, so it's difficult to point out which one of them is the problematic one.

**Comment by vruusmann** [comment]
What's the exact point of your code example? Are you 1) actually trying to solve some business problem, or 2) simply combining stuff to see if/when/how my PMML converter breaks?

If it's more of the former case, then I'd suggest you to think about simplifying the pipeline. For example, you should be using `compose.ColumnTransformer` instead of a `FeatureUnion` of multiple `DataFrameMapper` objects.

Again, let's keep this issue open as a reminder, that this particular `UnsupportedOperationException` should provide a informative message - something like "The behaviour of <column name> is unknown, and therefore it cannot be used as input to other feature transformers/estimators".

**Comment by xiaowei1234** [comment]
ah ok, the datatypes might be getting messed up by the lookupTransformer.

**Comment by xiaowei1234** [comment]
I am trying to create a process for creating a model. The process is more of a traditional statistical modeling process and not ML. It requires some more complicated feature engineering which is why I am having a fair amount of trouble with the pipelining

**Comment by vruusmann** [comment]
> The process is more of a traditional statistical modeling process and not ML

Any other Python packages that you might need? For example, would [StatsModels](https://www.statsmodels.org/stable/index.html) algorithms together with R/Patsy-style formulas be relevant?

> It requires some more complicated feature engineering

Examples?

Wouldn't be too difficult to build some custom transformers, and make them part of the SkLearn2PMML/JPMML-SkLearn stack.

**Comment by xiaowei1234** [comment]
Right now I am struggling with two operations which i got to work on a ipynb file example file but not in the actual code.

The first one is the problem in this thread. I have a categorical column of values that need to be mapped into a smaller set of values (hence using lookuptransformer). I then use PMMLLabelbinarizer to transform the mapped values to 1/0's. Lastly I use ColumnTransformer to drop the first column created by the previous 2 processes (to avoid the dummy variable trap)

The second problem is binning of continuous variables, i.e. transforming a variable that goes from 0-100 into 5 discrete (not modeled as continuous) values (i.e. 0-20 = 1.2, 21-25 = 1.4, 26-100 = 2.1)
For this problem I am using ContinuousDomain followed by CutTransformer.

I chose to use dataframewrapper + featureunion instead of columntransformer because columnTransformer has a check built-in where it raises an error if cutTransformer returns a float.

**Comment by vruusmann** [comment]
Played a bit with your example code.

The issue is that if you do `[LookupTransformer(<string>), LabelBinarizer(), Imputer()]`, then from the Scikit-Learn perspective you're imputing binarized 0/1 values, but from the PMML perspective you're still imputing the string output of the lookup transform. This is so, because string one-hot-encoding and  binarization are effectively no-ops in PMML.

If you think about it, then it's conceptually "useless" to apply imputer to individual columns of a binarized matrix.

In case of string columns, you should do imputation before the `LabelBinarizer` or `LabelEncoder` step. As discussed previously, `PMMLLabelBinarizer` only makes sense if you want to dispatch missing values directly to the estimator; it's not intended to be interfaced with an imputer.

**Comment by xiaowei1234** [comment]
Thanks Villu, I managed to workaround it by specifying the imputer in different places
