### ISSUE TITLE
ImportError: cannot import name 'LookupTransformer'

### ISSUE THREAD

**Issue by puifais** [jpmml/sklearn2pmml#142]
Hello,

I am getting
`ImportError: cannot import name 'LookupTransformer'`

When I tried to do
`from sklearn2pmml.preprocessing import LookupTransformer`

Note that I am able to import other things from sklearn2pmml such as
`from sklearn2pmml.decoration import ContinuousDomain, CategoricalDomain`

I noticed that [ sklearn2pmml/sklearn2pmml/preprocessing/__init__.py ](url) has LookupTransformer class. But I'm not sure why I cannot import it.

Here are versions of relevant things in my environment.
* Jupyter=1.0
* pandas=0.24.2
* scikit-learn=0.20.3
* sklearn2pmml=0.25.0
* java=1.8.0_181

**Comment by vruusmann** [comment]
> sklearn2pmml=0.25.0

Please upgrade. The current version is 0.43.0.
