### ISSUE TITLE
Generating "business decision"-type OutputField elements

### ISSUE THREAD

**Issue by sjkelleyjr** [jpmml/sklearn2pmml#149]
I'd like to get the PMML behavior present in the documentation (see [Example 3 here](http://dmg.org/pmml/v4-1/Output.html)) for outputting a variable (in the case of the documentation "waive" or "refer") based on the predicted probability output by a model (in the case of the documentation FinalResult).  Does this functionality exist in sklearn2pmml?  If so, how is it achieved? If not, where can I look in the code to contribute this as a PR?

**Comment by vruusmann** [comment]
> Does this functionality exist in sklearn2pmml?

Essentially, you're interested in taking the prediction of a model, and post-processing it. In the JPMML ecosystem lingo it's called "decision engineering".

> If so, how is it achieved?

The underlying Scikit-Learn library does not provide "decision engineering" support. The estimator is the last step in the pipeline, and you can't have any transformation steps after that (the output of the estimator would be input to the transformer).

The `PMMLPipeline` class has special-purpose `predict_transformer`, `predict_proba_transformer` and `apply_transformer` that let you invoke "decision engineering" sub-pipelines using the output of `predict(X)`, `predict_proba(X)` and `apply(X)` methods, respectively:
https://github.com/jpmml/sklearn2pmml/blob/master/sklearn2pmml/pipeline/__init__.py#L47-L51

There's an example about using `predict_proba_transformer` here (binning the predicted probability of the "event" class into three categories):
https://github.com/openscoring/papis.io#h2oai-distributed-random-forest-drf-classification-in-scikit-learn

At the moment all "decision engineering" sub-pipelines are generating regular `OutputField` elements. It would be nice if there was a special Sklearn2PMML syntax for marking them selectively as "final business decisions" - changing the value of the `OutputField@feature` attribute from `transformedValue` to `decision`.
