### ISSUE TITLE
ExpressionTransformer outputs a column vector

### ISSUE THREAD

**Issue by tyers** [jpmml/sklearn2pmml#159]
Hi Villu,
 I might be missing something obvious here, but is there any way to coerce the output from an ExpressionTransformer in to a plain value rather than a column vector.
For instance in my pipeline i'm using a dataframe mapper definition like this to compute the number of days between 2 dates:
``` python
(['DATE1','DATE2'],[DateDomain(),DaysSinceYearTransformer(year=2019),ExpressionTransformer("X[0] - X[1]"),ContinuousDomain(missing_value_treatment='as_value', missing_value_replacement=-1)],{'alias':'DATE_DIFFERENCE'})
```

When this is combined with other features i'm getting a type error (the object column is the output from the above transformation):
```
TypeError: no supported conversion for types: (dtype('int64'), dtype('float64'), dtype('float64'), dtype('float64'), dtype('O'), dtype('int32'), dtype('int64'), dtype('int32'), dtype('float64'),
```
thanks

**Comment by vruusmann** [comment]
One obvious issue with your pipeline is that you have two `Domain` decorators following each other - first `DateDomain` and then `ContinuousDomain`.

A `Domain` decorator should only occur in the first position. Hence, get rid of the `ContinuousDomain` and see if it solves your problem.

If I'm not mistaken, then the sequence `[DateDomain(), DaysSinceYearTransformer(), ExpressionTransformer()]` should be missing value-tolerant. If you need to ensure that you have a non-missing value at the end of this sequence, then please consider using some Scikit-Learn Imputer transformer, or a plain old `ExpressionTransformer("X[0] if pandas.notnull(X[0]) else -1")`

**Comment by tyers** [comment]
Hi Villu,
Thanks for the advice - i stuck the Cont Domain in there to try and correct the issue; switching out for the expression above sorts things out nicely. 
Seems i must have some invalid dates somewhere in my data to result in nulls coming out the end of the transform.
