### ISSUE TITLE
LookupTransformer within ColumnTransformer - ValueError: The output of the transformer should be 2D (scipy matrix, array, or pandas DataFrame)

### ISSUE THREAD

**Issue by ebouvier** [jpmml/sklearn2pmml#160]
Hello,
I would like to use a LookupTransformer within a ColumnTransformer:
```
from sklearn.compose import ColumnTransformer
from sklearn2pmml.preprocessing import LookupTransformer
import pandas as pd

dico = {0:-5.9, 1:-3.3, 2:-4.2}

transfo = ColumnTransformer([ 
    ("lt", LookupTransformer(dico, 0), ["pre0"] )
    ],
    remainder='passthrough'
) 

df = pd.DataFrame({'pre0':[2, 0, 1, 2], 
                   'pre1':[99, 56, 85, 78],
                   })

transfo.fit_transform(df)
```
and I get the following error:

> ValueError: The output of the 'lt' transformer should be 2D (scipy matrix, array, or pandas DataFrame).

I've tried to replace the `LookupTransformer` by `ExpressionTransformer("-X[0]+1")`, which works.
I've also compared the output of `ExpressionTransformer("-X[0]+1").fit_transform(df[['pre0']])` and `LookupTransformer(dico, 0).fit_transform(df[['pre0']])` and ended up with a small transformation of [the last line of the LookupTransformer transform method](https://github.com/jpmml/sklearn2pmml/blob/master/sklearn2pmml/preprocessing/__init__.py#L140) into `return numpy.vectorize(func)(X).reshape(len(X),1)`. The above example then returns 
```
[[-4.2 99. ]
 [-5.9 56. ]
 [-3.3 85. ]
 [-4.2 78. ]]
```
as expected.

Does it seem to you to be the right thing to do ? and then should the java counterpart be accordingly updated ?

Kind regards,

Elvire

**Comment by vruusmann** [comment]
Does `LookupTransformer` within `sklearn_pandas.DataFrameMapper` work for you?

> Does it seem to you to be the right thing to do ?

Do you know any definitive resources about developing custom Scikit-Learn transformers? Specifically, how should a one-dimensional result be formatted - as column vector, as row vector, as two-dimensional matrix `(values, )` or `(, values)`, or something else?

Right now, the correctness of SkLearn2PMML custom transformers is "asserted" by running unit tests on them (eg. using `nosetest`).

> and then should the java counterpart be accordingly updated ?

The Java side uses its own high level meta-model for keeping track of feature transformations. It's completely independent of the Python side "column vector" vs "row vector" nonsense, and definitely does not need changing because of this issue.

**Comment by ebouvier** [comment]
Hello Villu,

Thanks for your prompt reply !

> Does `LookupTransformer` within `sklearn_pandas.DataFrameMapper` work for you?

```
from sklearn_pandas import DataFrameMapper

dfm = DataFrameMapper([
    ('pre0', LookupTransformer(dico, 0)),
    ('pre1', None)
    ], 
    input_df=True,
    df_out=False
)
dfm.fit_transform(df)
```
returns
```
array([[-4.2, 99. ],
       [-5.9, 56. ],
       [-3.3, 85. ],
       [-4.2, 78. ]])
```
no matters the shape of the `LookupTransformer` result. But we can not chain `DataFrameMapper`s and, actually, the small example I gave in my previous message is already a part of a `DataFrameMapper`, so I can't substitute a `DataFrameMapper` to my current `ColumnTransformer`.

> Do you know any definitive resources about developing custom Scikit-Learn transformers?

Unfortunately, no. All I know is that [sklearn.base.TransformerMixin](https://scikit-learn.org/stable/modules/generated/sklearn.base.TransformerMixin.html) returns a 

> numpy array of shape [n_samples, n_features_new] 

and the error message I get when I try to use a `LookupTransformer `within a `ColumnTransformer`, of course.
