### ISSUE TITLE
Variables in RuleSetClassifier

### ISSUE THREAD

**Issue by ebouvier** [jpmml/sklearn2pmml#162]
Hello,
Is there a way to have a business rule that outputs a variable rather than a hard-coded value?
If we use RuleSetClassifier:
```
import pandas as pd
from sklearn2pmml.ruleset import RuleSetClassifier

df = pd.DataFrame({'abs': [-0.1, -1.2, -0.8, -3.6],
                   'rel': [0.982, 0.921, 0.989, 0.939]
                  })

classifier = RuleSetClassifier([
    ("X[0] < -1", "X[1]"),
    ("X[0] >= -1", 1),
], default_score = 1)

classifier.predict(df)
```
unfortunately, we get:
```
0       1
1    X[1]
2       1
3    X[1]
```
rather than 
```
0        1
1    0.921
2        1
3    0.939
```
Replacing [l. 20](https://github.com/jpmml/sklearn2pmml/blob/master/sklearn2pmml/ruleset/__init__.py#L20) by `return eval(score)` seems to do the trick, but I'm not sure it does not break anything else, nor if the [java counterpart](https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn2pmml/ruleset/RuleSetClassifier.java#L64) should be updated for creating a PMML.

**Comment by vruusmann** [comment]
> Is there a way to have a business rule that outputs a variable rather than a hard-coded value?

No, it's not possible.

The [`RuleSetModel` element](http://dmg.org/pmml/v4-3/RuleSet.html) associates predicates with category labels. Hence, the right-hand side must be a scalar constant, not a variable.

You should probably use a transformer (not an estimator) in such a scenario.
