### ISSUE TITLE
The file input stream takes too long

### ISSUE THREAD

**Issue by sin-en-2009** [jpmml/sklearn2pmml#165]
I used the following code to load the PMML file, **but it took a long time to load。**

try {
		        	long begin = System.currentTimeMillis();
		        	File file = new File(path);
				    **InputStream inputStream = new FileInputStream(file);
					pmml = org.jpmml.model.PMMLUtil.unmarshal(inputStream);**
					long end = System.currentTimeMillis();
					System.out.println((end-begin)/1000+"s");
}

result：186s

**Why is this code going so fast when I use it in your project (org.jpmml.pmml-evaluator)?**
result：7s

**Comment by vruusmann** [comment]
Closing, as I don't see any SkLearn2PMML-related question/issue here.
