### ISSUE TITLE
Convert double to float in pmml

### ISSUE THREAD

**Issue by liyinxiao** [jpmml/sklearn2pmml#168]
LGBMClassifier, LGBMRegressor, LGBMRanker stores data as double, but doubles are slow to evaluate in pmml. It will be helpful to provide an option, where we can choose to convert double into float, before generating the pmml file.

**Comment by vruusmann** [comment]
> doubles are slow to evaluate in pmml

Switching between `double` vs `float` might have some impact during model training, when the algorithm needs to deal with very large numeric matrices.

During evaluation, when there's only one data record (ie. matrix row) at hand, this has no effect. Also, the PMML approach itself is more about making models easy to use, not hyper-super performance.

> we can choose to convert double into float, before generating the pmml file.

By arbitrarily switching between data types, you risk making your models non-reproducible. It means that after such "conversion", your model might start making different predictions than before.

So, won't fix anything here.

**Comment by liyinxiao** [comment]
I agree with "no fix" here. It turns out the better approach is to change threshold types from double to float in lightgbm, which is what I did to solve this problem.

**Comment by vruusmann** [comment]
> .. change threshold types from double to float in lightgbm

How do you do that? 

Does this "switch" change anything about LightGBM text files? For example, does the formatting/representation of split threshold values get truncated (eg. from ~15 decimal places to ~7 decimal places)?

**Comment by liyinxiao** [comment]
> > .. change threshold types from double to float in lightgbm
> 
> How do you do that?
> 
> Does this "switch" change anything about LightGBM text files? For example, does the formatting/representation of split threshold values get truncated (eg. from ~15 decimal places to ~7 decimal places)?

Yes, and this requires no change from the jpmml library.
