### ISSUE TITLE
Unable to install this package on Anaconda

### ISSUE THREAD

**Issue by ginahanspal** [jpmml/sklearn2pmml#169]
I am unable to install sklearn2pmml into my Anaconda environment. Any tips on how I can make this work in Jupyter notebooks? Thanks a lot!!

**Comment by vruusmann** [comment]
> I am unable to install sklearn2pmml into my Anaconda environment.

What's the exact nature of the problem? Some error message, perhaps even an error with a full stack trace?

The SkLearn2PMML package is available via PyPI, and installs nicely with `pip install sklearn2pmml`.

Haven't investigated Anaconda support ever (I've got the impression that it's a "workaround" mostly for Windows platform users, no?), so would be interested to hear an actual user story/complaint here.

**Comment by ginahanspal** [comment]
Hi,
I was able to figure it out. I had to pip install the package via Conda prompt and not the general cmd prompt. 
Thank you!
