### ISSUE TITLE
failure save pmml file on PMMLPipeline

### ISSUE THREAD

**Issue by ma2331550908** [jpmml/sklearn2pmml#170]
**code：**
```
from sklearn.cluster import KMeans
from sklearn.externals import joblib
from sklearn import cluster
import numpy as np

data = np.random.rand(10,3)
print(data)
estimator=KMeans(n_clusters=2,init='k-means++',n_jobs=1)
from sklearn2pmml import PMMLPipeline, sklearn2pmml
km_pipeline = PMMLPipeline([("KM", estimator)])
km_pipeline.fit(data)
sklearn2pmml(km_pipeline, "KM.pmml",debug = True)
```

**output：**
```
python: 3.6.5
sklearn: 0.19.1
sklearn.externals.joblib: 0.11
pandas: 0.23.4
sklearn_pandas: 1.8.0
sklearn2pmml: 0.45.0
java: 1.8.0_162
Executing command:
java -cp /opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/guava-27.1-jre.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/h2o-genmodel-3.24.0.3.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/h2o-tree-api-0.3.7.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/istack-commons-runtime-3.0.8.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/jakarta.activation-api-1.2.1.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/jakarta.xml.bind-api-2.3.2.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/jaxb-runtime-2.3.2.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/jcommander-1.72.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-converter-1.3.7.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-h2o-1.0.6.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-lightgbm-1.2.7.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.5.14.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.3.8.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-agent-1.4.11.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-model-1.4.11.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-model-metro-1.4.11.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/pyrolite-4.23.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/serpent-1.23.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/slf4j-api-1.7.25.jar:/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.25.jar org.jpmml.sklearn.Main --pkl-pipeline-input /tmp/pipeline-2jtgssnz.pkl.z --pmml-output KM.pmml
Standard output is empty
Standard error:
七月 23, 2019 10:29:48 上午 org.jpmml.sklearn.Main run
信息: Parsing PKL..
七月 23, 2019 10:29:48 上午 org.jpmml.sklearn.Main run
严重: Failed to parse PKL
net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for dill._dill._import_module)
	at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)
	at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:732)
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:200)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for dill._dill._import_module)
	at net.razorvine.pickle.objects.ClassDictConstructor.construct(ClassDictConstructor.java:23)
	at net.razorvine.pickle.Unpickler.load_reduce(Unpickler.java:732)
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:200)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:77)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:98)
	at org.jpmml.sklearn.Main.run(Main.java:104)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Preserved joblib dump file(s): /tmp/pipeline-2jtgssnz.pkl.z
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-12-9ce1da2e1a30> in <module>()
     14 
     15 km_pipeline.fit(data)
---> 16 sklearn2pmml(km_pipeline, "KM.pmml",debug = True)

/opt/conda3/lib/python3.6/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    250                                 print("Standard error is empty")
    251                 if retcode:
--> 252                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    253         finally:
    254                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by ma2331550908** [comment]
On the same machine python2 is ok
**code**
```
from sklearn.cluster import KMeans
from sklearn.externals import joblib
from sklearn import cluster
import numpy as np

data = np.random.rand(10,3)
print(data)
estimator=KMeans(n_clusters=2,init='k-means++',n_jobs=1)
from sklearn2pmml import PMMLPipeline, sklearn2pmml
km_pipeline = PMMLPipeline([("KM", estimator)])
km_pipeline.fit(data)
sklearn2pmml(km_pipeline, "KM.pmml",debug= True)
```

**output**
python: 2.7.15
sklearn: 0.19.1
sklearn.externals.joblib: 0.11
pandas: 0.23.4
sklearn_pandas: 1.8.0
sklearn2pmml: 0.45.0
java: 1.8.0_162
Executing command:
java -cp /opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/guava-27.1-jre.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/h2o-genmodel-3.24.0.3.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/h2o-tree-api-0.3.7.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/istack-commons-runtime-3.0.8.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/jakarta.activation-api-1.2.1.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/jakarta.xml.bind-api-2.3.2.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/jaxb-runtime-2.3.2.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/jcommander-1.72.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-converter-1.3.7.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-h2o-1.0.6.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-lightgbm-1.2.7.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.5.14.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.3.8.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/pmml-agent-1.4.11.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/pmml-model-1.4.11.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/pmml-model-metro-1.4.11.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/pyrolite-4.23.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/serpent-1.23.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/slf4j-api-1.7.25.jar:/opt/conda2/lib/python2.7/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.25.jar org.jpmml.sklearn.Main --pkl-pipeline-input /tmp/pipeline-P3mcqT.pkl.z --pmml-output KM.pmml
Standard output is empty
Standard error:
七月 23, 2019 11:34:15 上午 org.jpmml.sklearn.Main run
信息: Parsing PKL..
七月 23, 2019 11:34:15 上午 org.jpmml.sklearn.Main run
信息: Parsed PKL in 16 ms.
七月 23, 2019 11:34:15 上午 org.jpmml.sklearn.Main run
信息: Converting..
七月 23, 2019 11:34:15 上午 sklearn2pmml.pipeline.PMMLPipeline initFeatures
警告: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.active_fields' is not set. Assuming [x1, x2, x3] as the names of active fields
七月 23, 2019 11:34:15 上午 org.jpmml.sklearn.Main run
信息: Converted in 159 ms.
七月 23, 2019 11:34:15 上午 org.jpmml.sklearn.Main run
信息: Marshalling PMML..
七月 23, 2019 11:34:16 上午 org.jpmml.sklearn.Main run
信息: Marshalled PMML in 681 ms.

Preserved joblib dump file(s): /tmp/pipeline-P3mcqT.pkl.z

**Comment by vruusmann** [comment]
> net.razorvine.pickle.PickleException: expected zero arguments for construction of ClassDict (for dill._dill._import_module)

In Python3 environment, your pipeline object is "contaminated" with some CPython objects from the Dill library.

Your example code doesn't seem to import or use any Dill classes explicitly. Therefore, your example code is either fake (you're actually using Dill for something that you're not showing), or your `from sklearn.externals import joblib` is importing a Dill-powered version of Joblib.

Don't use Dill.
