### ISSUE TITLE
feature request:: allow lookuptransformer to intake multiple data types

### ISSUE THREAD

**Issue by xiaowei1234** [jpmml/sklearn2pmml#173]
In sklearn2pmml 0.43 LookupTransformer can take a dict with multiple input data types, e.g. `LookupTransformer({'true':1, True: 1},0})`

However, current version will output an error saying that multiple data types are not allowed. It would be great if multiple data types were still allowed.

Also, on a side note, is there a better method than LookupTransformer to transform a boolean column to a binary 0/1 column?

**Comment by vruusmann** [comment]
> It would be great if multiple data types were still allowed.

Allowing such behaviour would make pipelines more error prone. At the PMML level, the lookup transformer still performs a mapping between columns of certain/fixed data types (eg. input column contains all string values, output column contains all boolean values).

It must be the case that the old version of SkLearn2PMML package was performing this "unification of column value types" silently for you.

> Also, on a side note, is there a better method than LookupTransformer to transform a boolean column to a binary 0/1 column?

Depends on the size of input/output data spaces, and if there is some pattern to it.

The PMML specification provides a `NormDiscrete` element for such purpose: http://dmg.org/pmml/v4-3/Transformations.html#xsdElement_NormDiscrete

However, quick search in SkLearn2PMML/JPMML-SkLearn stack shows that there are currently no transformer classes that would use this element during conversion (it's only used by neural network models for binarizing categorical input fields).

You should be able to do manual binarization using `ExtpressionTransformer`, by comparing left side to the right side using the `==` operator: `ExpressionTransformer["X['fruit'] == 'orange'"]`

Do you have any Python code example about your binarization needs?

**Comment by xiaowei1234** [comment]
Thanks for the reply Villu,

below is a code block I am referring to. I am just wondering if there was a better way than resorting to lookuptransformer to do the transformation of boolean values.

```
import pandas as pd
import numpy as np
from sklearn_pandas import DataFrameMapper
from sklearn2pmml import PMMLPipeline, sklearn2pmml
from sklearn.linear_model import LogisticRegression
from sklearn.impute import SimpleImputer
from sklearn2pmml.preprocessing import LookupTransformer

manual_df = pd.DataFrame({'other': [True, False, True, True, np.nan]})
y = np.array([0,0,1,1,1])
other = DataFrameMapper([('other', LookupTransformer({True: 1}, 0))])
pipe = PMMLPipeline([
    ('fu', other)
    , ('imp', SimpleImputer(strategy='median'))
    , ('clf', LogisticRegression())
])
```

**Comment by vruusmann** [comment]
>  I am just wondering if there was a better way to do the transformation of boolean values.

The PMML representation of logistic regression is able to handle boolean features directly (eg. for each boolean feature there would be two `CategoricalPredictor` elements - one for `true` values, and the other for `false` values).

You only need to do this encoding from boolean to numeric just to make Scikit-Learn happy (as SkLearn algorithms operate on uniformuly typed numeric data matrices).

I would say that your current approach for converting booleans to 0/1 values using `LookupTransformer({True: 1}, 0)` is probably the most optimal/concise one. However, if your data column may contain missing/invalid values (eg. `np.nan`), then the converter may misbehave.

Maybe I would "prefix" the workflow for the "other" column with a `CategoricalDomain` that specifies explicit missing value and invalid value treatments (eg. invalid values are replaced with missing values), then does missing value imputation using `SimpleImputer`, and only then engages `LookupTransformer`.
