### ISSUE TITLE
Numpy array trained xgboost model gets PMML feature names start from x1

### ISSUE THREAD

**Issue by zhuobao** [jpmml/sklearn2pmml#174]
when using numpy array as input to xgboost XGBClassifier based PMMLPipeline, the feature names written down to the PMML file starts from **x1**, but NOT **x0**. 
This **counter-conventional** behavior, as Python starts from 0, cause error when loading back PMML and score on a pandas frame generated from the numpy array using the 0 starting convention. 

#### packages used
* python==3.6
* xgboost==0.90
* sklearn==0.21.2
* sklearn2pmml==0.48.0
* jpmml_evaluator_python==0.2.1

Below are the code pieces to reproduce the finding. 

#### 1. train a plain model as reference

```python
# python 3.6
# loading packages
import xgboost as xgb
import numpy as np
from sklearn.datasets import load_digits

# loading data, the digits 0/1 dataset
digits = load_digits(2) 
y = digits['target']
X = digits['data']

# simply fit, scoring and get the class probability
xgb_model = xgb.XGBClassifier().fit(X, y)
pred_prob = xgb_model.predict_proba(X)
pred_prob[:10]

# array([[0.99667495, 0.00332507],
#       [0.0031895 , 0.9968105 ],
#       [0.99684745, 0.00315253]
# ...
```

#### 2. re-train using PMML pipeline and make PMML file
```python
import xgboost as xgb
from sklearn2pmml.pipeline import PMMLPipeline
from sklearn2pmml import sklearn2pmml

# put up single element pipeline
pipeline = PMMLPipeline([
    ('xgb', xgb.XGBClassifier())
])

# following sklearn2pmml manual
pipeline=pipeline.fit(X, y)
sklearn2pmml(pipeline=pipeline, pmml='./xgb.pmml', with_repr=True)

# scoring
pipeline.predict_proba(X)

# array([[0.99667495, 0.00332507],
#       [0.0031895 , 0.9968105 ],
#       [0.99684745, 0.00315253],
#     ...
```
The pipeline trained model matches the simple plain xgb model in step 1

#### 3. load-back PMML and score on the same numpy array

following v0.2.1 version manual of `jpmml_evaluator_python`

```python
# setup background
from jpmml_evaluator.py4j import launch_gateway, Py4JBackend
gateway = launch_gateway()
backend = Py4JBackend(gateway=gateway)

# load back PMML file to the scoring engine
from jpmml_evaluator import Evaluator, LoadingModelEvaluatorBuilder
evaluatorBuilder = LoadingModelEvaluatorBuilder(backend) \
    .setLocatable(True) \
    .loadFile("./xgb.pmml")

evaluator = evaluatorBuilder.build().verify()

# print model feature names 
input_fields: List = evaluator.getInputFields()
print("Input fields: " + str([inputf.getName() for inputf in input_fields]))

# Input fields: ['x11', 'x20', 'x21', 'x28', 'x29', 'x34', 'x35', 'x37', 'x42', 'x43', 'x51', 'x59']

# retro-score the numpy array X
import pandas as pd
row_cnt, col_cnt = X.shape

# using Python default convention, which is also used in xgboost package
xpdf_s0 = pd.DataFrame(
    X, 
    columns=['x%s' % i for i in range(col_cnt)]
)  # starting from 0
evaluator.evaluateAll(xpdf_s0)   # returning a pandas frame

# probability(0) | probability(1) | y
# -- | -- | --
# 0.004611 | 0.995389 | 1
# 0.430197 | 0.569803 | 1
# 0.004611 | 0.995389 | 1
# ...
# got unmatched with original model scoring result

# using the "counter-conventional" 1-starting sequencing
xpdf_s1 = pd.DataFrame(
    X, 
    columns=['x%s' % (i+1) for i in range(col_cnt)]
) # starting from 1
evaluator.evaluateAll(xpdf_s1)   # returning a pandas frame

# probability(0) | probability(1) | y
# -- | -- | --
# 0.996675 | 0.003325 | 0
# 0.003190 | 0.996811 | 1
# 0.996847 | 0.003153 | 0
# got match with scoring result
# proofing the counter conventional behavior

# close up session
gateway.shutdown()
```
It shows the PMML names are written down starting from 1 and could cause some trouble.

**Comment by vruusmann** [comment]
Thanks for taking the time to write a very detailed issue report.

Anyway, I think that the current behaviour is correct/the desired one, because in PMML you refer to fields (aka features) by name, not by position.

For example, "x1" should be read/interpreted as "feature whose name is x1". There is no basis for alternative interpretations, such as "feature on the first position".

If you're unhappy with default feature naming conventions, then you can always override them by specifying the `PMMLPipeline.active_fields` attribute:
```python
pipeline = PMMLPipeline([...])
pipeline.fit(numpy_X, numpy_y)
pipeline.active_fields = ["0", "1", "2", ..., "n"]
pipeline.target_fields = ["y"]
```

**Comment by zhuobao** [comment]
thanks for providing the solution. However, I strongly recommend to mention this default behavior and the solution in the document, since it is different from the conventions from the others. Regards.

**Comment by vruusmann** [comment]
This behaviour is mentioned in the documentation. And if feature names are not set (eg. the case with Numpy arrays) then SkLearn2PMML/JPMML-SkLearn stack issues a special warning that "feature names are not set, using default feature names".

BTW, you could always wrap Numpy arrays as Pandas DataFrame (using `copy = False` for maximum efficiency), so that you'd always have explicit control over column/feature names.
