### ISSUE TITLE
SimpleImputer() issue with strategy='most_frequent'

### ISSUE THREAD

**Issue by adw-ara** [jpmml/sklearn2pmml#176]
I don't know if this issue has been observed, but the 'most_frequent' impute strategy seems to have trouble dealing with cases where a single mode is not present.   This is not a required feature from my standpoint, but I thought I would post it.  

In my case, I had around 100 samples of various real numbers, used the 'most_frequent' impute in the SimpleImputer(), and got something like this as a result:

```xml
<Constant dataType="double">{obj=[B@68135e, dtype={names=null, obj=f8, values=null, w_size=-1, flags=0, subdescr=null, copy=1, align=0, alignment=-1, version=3, __class__=numpy.dtype, order=<}, __class__=numpy.core.multiarray.scalar}</Constant>
```

As opposed to something like this:

`<Constant dataType="double">14.0</Constant>`

I know that someone wouldn't practically use the 'most_frequent' option in this sort of case, but it seems that if a mode isn't identified, than a median or other result should be returned.  It could also be that this is just an issue on my end.

**Comment by vruusmann** [comment]
Looks like that an instance of `numpy.core.Scalar` is not "unpacked" into a `java.lang.Number` in this case.

Should filter the elements through `ScalarUtil#decode(Object)` here:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/impute/SimpleImputer.java#L70

**Comment by vruusmann** [comment]
Appears to be fixed already.
