### ISSUE TITLE
Support for `IsolationForest.max_features` attribute

### ISSUE THREAD

**Issue by magdanowak** [jpmml/sklearn2pmml#177]
I'm using sklearn's IsolationForest model and noticed a bug in how the pmml file is generated. For each tree in the model, the same columns appear in ModelSchema, no matter which were originally used. It results in wrong pmml file and completely random predictions being generated by the model itself (confirmed by reading in the model using `pypmml`). 

I'm using `sklearn==0.21.2`, `sklearn2pmml==0.48.0`.

Here's an example reproducing the error:

```python
from xml.etree import ElementTree

import pandas as pd
import sklearn 
import sklearn2pmml
from sklearn.ensemble import IsolationForest

print(sklearn.__version__)
print(sklearn2pmml.__version__)

# Generate data
rng = np.random.RandomState(42)
X = pd.DataFrame(0.3 * rng.randn(100, 4), columns=list('abcd'))

#Train model
forest = IsolationForest(behaviour='new', n_estimators=5, random_state=rng, 
                         contamination='auto', max_features=2)
forest.fit(X)

#Show features for each estimator
for i in forest.estimators_features_:
    print([X.columns[j] for j in i])

#Create pipeline and save it
pipeline = sklearn2pmml.PMMLPipeline([
    ("forest", forest)
])
sklearn2pmml.sklearn2pmml(pipeline, "classifier_test.pmml", with_repr=True)

#Read in the model and show data used by each model
with open("classifier_test.pmml", 'r') as f:
    x = ElementTree.parse(f)
namespace = {'p': 'http://www.dmg.org/PMML-4_3'}

for treemodel in x.findall('p:MiningModel/p:Segmentation/p:Segment/p:TreeModel', namespace):
    print([field.get('name') for field in treemodel.findall('p:MiningSchema/p:MiningField', namespace)])

```

**Comment by vruusmann** [comment]
First of all, you should be training your IsolationForest model indirectly via `(PMML)Pipeline.fit(X)`, not directly via `IsolationForest.fit(X)`. The `PMMLPipeline.fit(X)` method takes care of collection features names (and whatever other metainfo there might be available).

> It results in wrong pmml file and completely random predictions being generated by the model itself 

The ordering of `MiningSchema/MiningField` elements is not significant. It doesn't make sense to compare the ordering of SkLearn feature list elements to `MiningSchema/MiningField` list element names.

It looks like the root cause of this issue is the use of `max_features` attribute.

**Comment by magdanowak** [comment]
The issue isn't with the order of `MiningSchema/MiningField`, it's with the fact that it shows wrong features (the same set of features in each `TreeModel`). The issue persist whether you fit the model outside the pipeline or within it.

I take it the `max_features` attribute is not supported at all?

**Comment by vruusmann** [comment]
> I take it the max_features attribute is not supported at all?

Somehow it was missed in the earlier versions.

Starting from SkLearn2PMML version 0.49.0 (available in PyPI for some days already), everything works fine.
