### ISSUE TITLE
`CategoricalDomain.missing_value_treatment` value should be added to the set of valid values

### ISSUE THREAD

**Issue by zhxt95** [jpmml/sklearn2pmml#178]
Hi, vruusmann 
I got the following IllegalArgumentException when  I try to generate PMML file:
```
Standard output is empty
Standard error:
Sep 11, 2019 5:32:01 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Sep 11, 2019 5:32:01 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 68 ms.
Sep 11, 2019 5:32:01 PM org.jpmml.sklearn.Main run
INFO: Converting..
Sep 11, 2019 5:32:01 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Field f41 has valid values [bank, chat, creditcard, loan, other, payment]
	at org.jpmml.converter.PMMLEncoder.toCategorical(PMMLEncoder.java:222)
	at sklearn.preprocessing.LabelBinarizer.encodeFeatures(LabelBinarizer.java:99)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:196)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: Field f41 has valid values [bank, chat, creditcard, loan, other, payment]
	at org.jpmml.converter.PMMLEncoder.toCategorical(PMMLEncoder.java:222)
	at sklearn.preprocessing.LabelBinarizer.encodeFeatures(LabelBinarizer.java:99)
	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
	at sklearn.Initializer.encodeFeatures(Initializer.java:41)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:81)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:196)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
````
I've read you reply in #61 , so I checked my data and find it is exactly all string type with missing value as None:
`train_ftr['f41'].unique()`
> array(['other', 'chat', None, 'loan', 'bank', 'creditcard', 'payment'],
      dtype=object)

Then I follow the debug message and go to the `org.jpmml.converter.PMMLEncoder.toCategorical` method's code and I found that there is a check `if((existingValues).equals(values))` to make sure all the transforms in the pipeline to have the save valid_values (I guess that's the purpose for the check).

However, since this feature has missing value, I use `CategoricalDomain` to fill missing value with `missing_value_replacement` first and then encode the feature, like this:
```
dfm_LabelBinarizer = DataFrameMapper(
    [(c,[CategoricalDomain(invalid_value_treatment='as_missing',
                           missing_value_treatment='as_value',
                           missing_value_replacement = 'NA'),
         LabelBinarizer()])
     for c in categoricalDomain],
    df_out=True)
```
And after pipeline fitting,  feature `f41`'s two transformers looks like:
`problem_CategoricalDomain.data_`
> array(['bank', 'chat', 'creditcard', 'loan', 'other', 'payment'],
      dtype=object)

`problem_LabelBinarizer.classes_`
> array(['NA', 'bank', 'chat', 'creditcard', 'loan', 'other', 'payment'],
      dtype='<U10')

I guess the problem is that `LabalBinarizer` takes the `missing_value_replacement`(`NA`) as its legal input which makes it has different valid_value with  `CategoricalDomain`. Or did I make any mistakes using the package?

**Comment by vruusmann** [comment]
This exception signals that two categorical feature transformers (`CategoricalDomain` and `LabelBinarizer`) are reporting different valid values spaces.

A quick workaround is to suppress the former valid value space, by specifying `CategoricalDomain(with_data = False)`.

**Comment by zhxt95** [comment]
It works setting `with_data=False`. Thanks a lot.

**Comment by yairdata** [comment]
the treatment of invalid categorical values that is suggested in [https://openscoring.io/blog/2020/02/23/sklearn_feature_specification_pmml/](url) not working for me.
my use is : 
`mapper = DataFrameMapper(
  [([cat_column], [ CategoricalDomain(with_data=False,invalid_value_treatment='as_is'),LabelEncoder()]) for cat_column in categorical_columns] +
  [(numeric_columns, ContinuousDomain())]
)`
the generated pmml contains:
`CategoricalDomain(dtype=None,
                                              invalid_value_replacement=None,
                                              invalid_value_treatment='as_is',
                                              missing_value_replacement=None,
                                              missing_value_treatment='as_is',
                                              missing_values=None,
                                              with_data=False,
                                              with_statistics=True)`
but still the DataField has all categorical values , and apparently is checking the new values against it.
the error i get is:
`ValueError: ['my_field']: y contains previously unseen labels: 'my_value'`
maybe the LabelEncoder is masking the needed bahaviour?
what can i do besides editing the pmml manually is i need the new values to accept the 'as_is' treatment ?

**Comment by vruusmann** [comment]
@yairdata You have at several different issues at play here.

> ValueError: ['my_field']: y contains previously unseen labels: 'my_value'

You've omitted the full stack trace, but I believe that this error was raised by Scikit-Learn's `LabelEncoder` transformer class.

The `CategoricalDomain` is behaving exactly as requested - it is passing invalid values (here, `y=my_value`) on to the `LabelEncoder`, which then crashes.

I can't change the behaviour of `LabelEncoder`. Please raise a new issue with the Scikit-Learn project, and ask them to make `LabelEncoder` invalid value tolerant.

> the generated pmml contains:

You've pasted Python code here. What's the PMML markup like? I believe it has `DataField@invalidValueTreatment="asIs"`, which is in agreement with your domain specification.

> maybe the LabelEncoder is masking the needed bahaviour?

Correct, the converter for `LabelEncoder` is also populating `DataField/Value` child elements:
https://github.com/jpmml/jpmml-sklearn/blob/1.6.1/src/main/java/sklearn/preprocessing/LabelEncoder.java#L58 and https://github.com/jpmml/jpmml-sklearn/blob/1.6.1/src/main/java/sklearn/preprocessing/EncoderUtil.java#L66

The solution would be to disable the `SkLearnEncoder#toCategorical(FieldName, List<?>)` method invocation somehow.

> what can i do besides editing the pmml manually is i need the new values to accept the 'as_is' treatment ?

If you have `DataField@invalidValueTreatment="asIs"`, then it will accept previously unseen category levels without problem.

If your application is exhibiting different behaviour, then please provide some evidence.
