### ISSUE TITLE
Can not install sklearn2pmml in conda

### ISSUE THREAD

**Issue by dongyidongyi** [jpmml/sklearn2pmml#180]
Hi all, I tried to install sklearn2pmml in conda.

when I use the syntexes, the error was that "the following packages are not available from current channels". 

`conda install sklearn2pmml`
`conda install -c conda-forge sklearn2pmml`
`conda -install -c calex`

Then I found in anaconda site that sklearn2pmml under "calex" is only for linux, I am running conda on windows, so I tried with the syntex below:

`conda install - c lreading sklearn2pmml`

and this time, it shows me that "Found conflicts! looking for incompatible packages", and then "UnsatisfiableError: The following specifications were found to be incompatible with each other"
"Package openssl conflicts for: ......"
...
> Package sklearn-pandas conflicts
> sklearn2pmml -> sklearn-pandas
....

there are list of conflicts packages. Does it mean that my python versions and other libraries are too new? if so, how? Should I regress my python version?

Or is there a work around to do so without regress other packages?

**Comment by vruusmann** [comment]
The official distribution channel for the `sklearn2pmml` package is PyPI. There is no official distribution channel for Anaconda.

> Does it mean that my python versions and other libraries are too new?

You must be referring to this third-party conda site: https://anaconda.org/calex/sklearn2pmml

It's `sklearn2pmml` version 0.8.2, which is 3+ years old - no wonder it is not compatible with latest package/Python versions.

The solution is to install the latest sklearn2pmml package version (0.49.0) from PyPI.

**Comment by dongyidongyi** [comment]
That works, thanks!

So I used
`pip install sklearn2pmml`
and this installs sklearn2pmml package to my python
