### ISSUE TITLE
can sklearn2pmml transforme simply a joblib model file to pmml without retrain the model?

### ISSUE THREAD

**Issue by dongyidongyi** [jpmml/sklearn2pmml#181]
I am having a trouble getting the same model by training my XGBoost directly and via the pipeline. So I wonder if in sklearn2pmml, exists maybe an option that I can directly transform the joblib model I got from XGBoost library alone to pmml file?

**Comment by vruusmann** [comment]
There is no need to retrain anything.

The `sklearn2pmml` package operates on Scikit-Learner wrapper estimator objects `XGBClassifier` and `XGBRegressor`. If you have an XGBoost booster object at hand (eg. retrieved from archive), then you can create these wrapper estimator objects manually:

```python
classifier = XGBClassifier()
classifier._Booster = xgb.train(...)

pipeline = PMMLPipeline([
  ("classifier", classifier)
])

sklearn2pmml(pipeline, "xgboost.pmml")
```

Alternatively, you may dump the XGBoost booster object to a file in a local filesystem, and use the [JPMML-XGBoost](https://github.com/jpmml/jpmml-xgboost) command-line conversion application.
