### ISSUE TITLE
Feature_names mismatch issue in pipeline fit

### ISSUE THREAD

**Issue by dongyidongyi** [jpmml/sklearn2pmml#182]
**I have no problem fitting my XGBoost model alone with validating on training and testing data sets**

`
xgtrain_37vars = xgb.DMatrix(xtrain_top37vars, label=y_train)
xgtrain_37vars.save_binary('train37_data.buffer')
xgtest_37vars = xgb.DMatrix(xtest_top37vars, label=y_test)
xgtest_37vars.save_binary('test37_data.buffer')

param = {'max_depth': 1, 'eta': 0.1, 'objective': 'binary:logistic'}
param['nthread'] = 4
param['eval_metric'] = 'auc'
evallist = [(xgtrain_37vars, 'train'), (xgtest_37vars, 'recent')]

bst = xgb.train(param, xgtrain_37vars, num_round, evallist, early_stopping_rounds= 639)`

**however, when i use pipeline, it shows the error message of feature_names mismatch, what happens, what should I do?**

`
import xgboost
from sklearn_pandas import DataFrameMapper
from xgboost.sklearn import XGBClassifier

from sklearn2pmml.pipeline import PMMLPipeline

param_dist = {'max_depth': 1, 'learning_rate': 0.1, 'objective': 'binary:logistic', 'num_round':639,'n_jobs':4}

pipeline = PMMLPipeline([
("mapper", DataFrameMapper([(i, None) for i in xtrain_top37vars.columns])),
("classifer", XGBClassifier(**param_dist))
])

#pipeline.fit(xtrain_top37vars, y_train,classifer__eval_metric='auc')
pipeline.fit(xtrain_top37vars, y_train,classifer__eval_set=[xgtrain_37vars, xgtest_37vars],classifer__eval_metric='auc')
`
it shows me the error message below:

> ValueError: feature_names mismatch: ['f0', 'f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7', 'f8', 'f9', 'f10', 'f11', 'f12', 'f13', 'f14', 'f15', 'f16', 'f17', 'f18', 'f19', 'f20', 'f21', 'f22', 'f23', 'f24', 'f25', 'f26', 'f27', 'f28', 'f29', 'f30', 'f31', 'f32', 'f33', 'f34', 'f35'] ['COD_CLAS_NOTE_BALOISE_DOSS_0.0', 'MNT_PRECIB_DOSS_NEW2', 'MNT_DDE', 'MA_MNT_REVN_PRINC', 'MA_NBR_ANC_PROF', 'REGION_IND2_Other DEPARTMENT', 'MA_NBR_ANC_CCP', 'MA_MNT_CHARGE_AUTR_PRET', 'REGION_IND2_93', 'MA_COD_TYP_CTRT_TRVL_I', 'TOP_FRAUDE_DONNE_Y', 'COD_MAT_83.0', 'COD_MAT_86.0', 'NBR_MENS', 'MNT_MENS_CRED_RACH', 'MA_NBR_JOUR_DBT_MOIS', 'MA_COD_PROF_TITU_62.0', 'INT_5000', 'MA_MNT_CUMUL_EPARG_LIQUIDE', 'TYP_CPTE_J', 'MNT_CAPCTE_RBT_MAX', 'COD_BANQ_PRE_GRP_Missing', 'MA_MNT_PRET_IMMO_HS_LBP', 'NBR_PERS_FOYER_FISCAL', 'MA_NBR_CARTE', 'COD_CANAL_S', 'COD_CANAL_I', 'COD_SS_CANAL_SIEB_301.0', 'COD_MAT_82.0', 'MA_MNT_LOYER', 'MA_NBR_ANC_ADR', 'MA_COD_PROF_TITU_52.0', 'REGION_IND2_75,94,95', 'MA_COD_PROF_TITU_21.0', 'COD_DOMN_DES_ETUDE_0.0', 'MA_MNT_ALLOC_FAM']
expected f31, f19, f14, f23, f2, f11, f4, f33, f1, f22, f29, f6, f27, f18, f13, f34, f35, f17, f16, f30, f10, f32, f24, f8, f0, f21, f26, f3, f5, f12, f28, f7, f15, f25, f9, f20 in input data
training data did not have the following fields: MA_NBR_JOUR_DBT_MOIS, COD_MAT_83.0, REGION_IND2_Other DEPARTMENT, TOP_FRAUDE_DONNE_Y, MA_MNT_REVN_PRINC, COD_MAT_86.0, MNT_MENS_CRED_RACH, COD_CANAL_S, COD_MAT_82.0, REGION_IND2_75,94,95, MA_COD_PROF_TITU_62.0, MA_COD_PROF_TITU_52.0, MA_NBR_CARTE, REGION_IND2_93, MA_MNT_CHARGE_AUTR_PRET, MA_COD_TYP_CTRT_TRVL_I, COD_CANAL_I, MNT_PRECIB_DOSS_NEW2, MA_MNT_LOYER, MA_MNT_ALLOC_FAM, MA_COD_PROF_TITU_21.0, COD_DOMN_DES_ETUDE_0.0, NBR_MENS, MA_MNT_CUMUL_EPARG_LIQUIDE, MNT_CAPCTE_RBT_MAX, MA_NBR_ANC_ADR, COD_SS_CANAL_SIEB_301.0, TYP_CPTE_J, MA_MNT_PRET_IMMO_HS_LBP, MA_NBR_ANC_CCP, INT_5000, COD_CLAS_NOTE_BALOISE_DOSS_0.0, MNT_DDE, NBR_PERS_FOYER_FISCAL, COD_BANQ_PRE_GRP_Missing, MA_NBR_ANC_PROF

**Comment by vruusmann** [comment]
This `ValueError` is raised by some Python package other than the `sklearn2pmml` package. Please take a look at its stack trace to see what/where.
