### ISSUE TITLE
DaysSinceYearTransformer does not persist year parameter

### ISSUE THREAD

**Issue by tyers** [jpmml/sklearn2pmml#184]
Hi Villu,
I'm implementing a feature that utilises the DaysSinceYearTransformer - this is embedded as part DataFrameMapper transformation, which is then included in a sklearn Pipeline.
Everything is working fine until I try to run some hyperparameter tuning on the pipeline, at which point i get an error: 
```
File "C:\ProgramData\Anaconda3\lib\site-packages\sklearn2pmml\preprocessing\__init__.py", line 71, in __init__
    if year < 1900:

TypeError: '<' not supported between instances of 'NoneType' and 'int'
```

It seems that when the DaysSinceYearTransformer the year property is not being set within the object itself, and is just being forwarded to the inherited DurationTransformer class:
```
transformer = DaysSinceYearTransformer(year = 1960)
print(transformer)
> DaysSinceYearTransformer(year=None)
```

Have done some testing, and updating the __init__ of the inherited DurationTransformer looks to correct the issue:
```
	def __init__(self, year):
		if year < 1900:
			raise ValueError("Year {0} is earlier than 1900".format(year))
		self.year=year
		self.epoch = datetime(year, 1, 1, tzinfo = None)
```

Thanks
Chris

**Comment by vruusmann** [comment]
Legit diagnostics and a solution - hyperparameter tuning (eg. using `GridSearchCV`) is generating clones of the original transformer/estimator, and successfull Scikit-Learn cloning requires you to preserve all constructor parameters inside the class(?).

Therefore, this cloneability issue affects other SkLearn2PMML custom transformers and estimators as well. I wonder if there's some built-in utility method for automating these checks during unit testing (ie. assert that custom transformer is cloneable).
