### ISSUE TITLE
Attempt to rename a non-existent Field fails

### ISSUE THREAD

**Issue by tyers** [jpmml/sklearn2pmml#185]
Hi Villu,
I'm running in to an issue when i'm performing the final conversion to PMML.
I've stripped my pipeline down to the bare minimum (a single transformation in a DataFrameMapper and a GradientBoostingClassifier).
The PMMLPipeline ends up looking like this:
```
PMMLPipeline(steps=[('preprocessor', DataFrameMapper(default=False, df_out=False,
                features=[(['MA_INCOME'],
                           [SimpleImputer(add_indicator=False, copy=True,
                                          fill_value=-1, missing_values=nan,
                                          strategy='constant', verbose=0)],
                           {'alias': 'MA_INCOME_VALUE'})],
                input_df=False, sparse=False)),
       ('classifier', GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=15,
                           max_features='sqrt', max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=50, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=200,
                           n_iter_no_change=None, presort='auto',
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False))])
```

When i execute sklearn2pmml against this pipeline i get the following exception raised:
```
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Field MA_INCOME is undefined
        at org.jpmml.converter.PMMLEncoder.removeDerivedField(PMMLEncoder.java:173)
        at org.jpmml.sklearn.SkLearnEncoder.renameFeature(SkLearnEncoder.java:58)
        at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:85)
        at sklearn.Initializer.encodeFeatures(Initializer.java:41)
        at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
        at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:83)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: Field MA_INCOME is undefined
        at org.jpmml.converter.PMMLEncoder.removeDerivedField(PMMLEncoder.java:173)
        at org.jpmml.sklearn.SkLearnEncoder.renameFeature(SkLearnEncoder.java:58)
        at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:85)
        at sklearn.Initializer.encodeFeatures(Initializer.java:41)
        at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
        at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:83)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)
```
Is there something obvious i am doing wrong here?
Thanks
Chris

**Comment by vruusmann** [comment]
Must be a side-effect of using the `DataFrameMapper.features.alias` option. Needs investigation.

In the meantime, you can rename columns using the `sklearn2pmml.decoration.Alias` meta-transformer class.

**Comment by tyers** [comment]
Villu,
Thanks for the hint, i was under the impression that the alias option in the dfm would have carried through to the pmml pipeline.
I've updated the trivial example above to use decoration.Alias, and i'm still getting the same exception raised:
```
PMMLPipeline(steps=[('preprocessor', DataFrameMapper(default=False, df_out=True,
                features=[(['MA_INCOME'],
                           [Alias(name='MA_INCOME_VALUE', prefit=False,
                                  transformer=SimpleImputer(add_indicator=False,
                                                            copy=True,
                                                            fill_value=-1,
                                                            missing_values=nan,
                                                            strategy='constant',
                                                            verbose=0))])],
                input_df=False, sparse=False)),
       ('classifier', GradientBoostingClassifier(criterion='friedman_mse', init=None,
                           learning_rate=0.1, loss='deviance', max_depth=15,
                           max_features='sqrt', max_leaf_nodes=None,
                           min_impurity_decrease=0.0, min_impurity_split=None,
                           min_samples_leaf=50, min_samples_split=2,
                           min_weight_fraction_leaf=0.0, n_estimators=200,
                           n_iter_no_change=None, presort='auto',
                           random_state=42, subsample=1.0, tol=0.0001,
                           validation_fraction=0.1, verbose=0,
                           warm_start=False))])
```
```
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Field MA_INCOME is undefined
        at org.jpmml.converter.PMMLEncoder.removeDerivedField(PMMLEncoder.java:173)
        at org.jpmml.sklearn.SkLearnEncoder.renameFeature(SkLearnEncoder.java:58)
        at sklearn2pmml.decoration.Alias.encodeFeatures(Alias.java:60)
        at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
        at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
        at sklearn.Initializer.encodeFeatures(Initializer.java:41)
        at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
        at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:83)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)

Exception in thread "main" java.lang.IllegalArgumentException: Field MA_INCOME is undefined
        at org.jpmml.converter.PMMLEncoder.removeDerivedField(PMMLEncoder.java:173)
        at org.jpmml.sklearn.SkLearnEncoder.renameFeature(SkLearnEncoder.java:58)
        at sklearn2pmml.decoration.Alias.encodeFeatures(Alias.java:60)
        at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
        at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:73)
        at sklearn.Initializer.encodeFeatures(Initializer.java:41)
        at sklearn.Transformer.updateAndEncodeFeatures(Transformer.java:85)
        at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:83)
        at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)
```
and here is the debug information if that would be useful:
```
python: 3.7.3
sklearn: 0.21.3
sklearn2pmml: 0.49.0
joblib: 0.13.2
sklearn_pandas: 1.8.0
pandas: 0.24.2
numpy: 1.16.2
java: N/A
```

**Comment by vruusmann** [comment]
>  i was under the impression that the alias option in the dfm would have carried through to the pmml pipeline.

Your intuition is correct. However, looks like the latest codebase has a problem with "field scope optimization" if the field has been renamed.

I believe that the error disappears if you don't use field renaming (eg. wouldn't it be possible to simply rename your DF column(s)?).

The "field scope optimization" logic (moving `DerivedField` elements closer to model elements that use them) was introduced not long time ago (perhaps a few months old). So, some older SkLearn2PMML package version might be able to deal with renamed fields correctly.

That's an interesting issue. Will look deeper into it when I have time to focus.

**Comment by tyers** [comment]
So, I've had a poke around and i am able to generate PMML successfully when I do not rename the output fields from the dataframemapper (using either the alias decoration or property).

However, if i switch up to a more complex pipeline where i have included multiple transformations of the same column I then have issues due to multiple instances of the same output column name.

I've not been able to find a working version on sklearn2pmml - i have worked back a far as v0.45.0 while experiencing the same error, but then with v0.44.0 i get errors relating to the SimpleImputer not being supported (which i believe is due to sklearn refactoring that class in v0.21)

**Comment by vruusmann** [comment]
> i am able to generate PMML successfully when I do not rename the output fields from the dataframemapper (using either the alias decoration or property).

Renaming columns (before feeding the data to `GradientBoostedClassifier`) works on my computer (search for usages of `Alias`): https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py

That's why I was quite sure that it should work everywhere else too.

> I then have issues due to multiple instances of the same output column name.

That looks like a compretely different issue (many `OutputField` elements using the same name?). Care to extract it into a MVP, and open a different bug report?

> I've not been able to find a working version on sklearn2pmml

The "field scope optimization" logic is implemented by class `org.jpmml.converter.visitors.DerivedFieldRelocator`, which was introduced into the JPMML-Converter library in this commit:
https://github.com/jpmml/jpmml-converter/commit/a87bc8cb049d5325dc43e127933f27d6a88765dd

The first JPMML-Converter release version to include this class is 1.3.9. Now, therefore, you should use a SkLearn2PMML package version that is based on a JPMML-SkLearn library version that predates this release.

**Comment by vruusmann** [comment]
Fixing this issue is probably a one or two-line change to the `org.jpmml.converter.visitors.DerivedFieldRelocator` class.

**Comment by tyers** [comment]
> That looks like a compretely different issue (many `OutputField` elements using the same name?). Care to extract it into a MVP, and open a different bug report?

Having played around with this and the issue is actually in the DataFrameMapper as the naming conflict results in columns of incorrect type in the output dataframe. When using df_out=False resolves this issue.

> Renaming columns (before feeding the data to GradientBoostedClassifier) works on my computer (search for usages of Alias): https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py

Are you able to confirm the combination of package versions you are using during your testing above to see if i'm just stuck with some incompatibilities somewhere?

**Comment by vruusmann** [comment]
This issue is caused by the fact that `(Simple)Imputer` is a "lightweight" transformer, which can be represented in model schema using `MiningField` element attribute(s).

In the current case, the imputation of "MA_INCOME" leads to the following field-less PMML markup:
```xml
<MiningModel functionName="classification">
	<MiningSchema>
		<MiningField name="MA_INCOME" missingValueReplacement="-1.0" missingValueTreatment="asValue"/>
	</MiningSchema>
</MiningModel>
```

As "MA_INCOME" is a direct input field (represented using a `DataField` element) and not a transformed field (represented using `DerivedField` element), then the request to rename it is rejected.

I think this rejection is correct/desired behaviour (or would you like your model schema to start referring to this input field as "MA_INCOME_VALUE" instead of "MA_INCOME"?), so I'm not going converter's behaviour in any way. Granted, the exception message could be more helpful.

If you'd like to see the "MA_INCOME_VALUE" materialize in the form of a `DerivedField` element, then you need to perform some sort of "heavyweight" transformation on the "lightweight" imputed value. For example: `[SimpleImputer(), StandardScaler()].`

**Comment by tyers** [comment]
thanks Villu - that makes sense. I was unaware that there were effectively 2 classes of transformation with respect to the pmml representations. I've adjusted my dfm feature definitions to accommodate the above and all is working as expected.
