### ISSUE TITLE
how could I load and use a pmml file in xgboost library python?

### ISSUE THREAD

**Issue by dongyidongyi** [jpmml/sklearn2pmml#186]
Hello
 
I have created a pmml file from my model trained in python. I want to check if this gives me the same result as How could I load it back to my python code? with xgboost's library load?

thanks in advance

**Comment by vruusmann** [comment]
If you want to train models in Python, and score them later in Python as well, then you really don't need PMML intermediation layer. Simply use Pickle or Joblib serialization.

In all other cases, please check out the [JPMML-Evaluatpr-Python](https://github.com/jpmml/jpmml-evaluator-python) package/library.
