### ISSUE TITLE
error about model fit wiht sample_weight

### ISSUE THREAD

**Issue by xingfengzhang** [jpmml/sklearn2pmml#187]
hi , i want train model with sample_weight for each intance,the code like this
```python
rfpmml = PMMLPipeline([("classifier",rf)])
rfpmml.fit(x_train,y_train,weight)** 
```
here,the weight is the weight score for each intance about x_train,and the type is pandas.core.series.Series.

but i got the error,
TypeError: fit() takes from 2 to 3 positional arguments but 4 were given.

do u have any idea?

**Comment by vruusmann** [comment]
The method `PMMLPipeline.fit(X, y)` takes an optional `**fit_params` keywords argument parameter:
https://github.com/jpmml/sklearn2pmml/blob/master/sklearn2pmml/pipeline/__init__.py#L57

Therefore, the problem must be related to your variables `x_train`, `y_train` or `weight`. Perhaps one or more of them is a tuple?

Also, please be sure that you're using the latest SkLearn2PMML package version (should be 0.49.1 as of today).
