### ISSUE TITLE
ExpressionTransformer input parameters

### ISSUE THREAD

**Issue by leone281** [jpmml/sklearn2pmml#191]
Hello Villu,
I'd need to convert a variable from minutes to days dividing it by 1440.
I do this in my dataframe:
```
('timeBeforeDeparture', [ContinuousDomain(invalid_value_treatment = 'return_invalid', missing_value_replacement = -999), Alias(ExpressionTransformer('X/1440'), name = "timeBeforeDepartureInDays")]),
```

Pipeline fits and results seems ok but the PMML transformers tells me:
```
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Python expression 'X/1440' is either invalid or not supported
	at org.jpmml.sklearn.ExpressionTranslator.translate(ExpressionTranslator.java:37)
	at org.jpmml.sklearn.ExpressionTranslator.translate(ExpressionTranslator.java:24)
```

I tried to use // or \/ or numpy.divide. None works.
Problem seems to be the usage of X because if I specify a function using constants (i.e. ExpressionTransformer("100/10") then it works.

Could you please assist?
Thanks.
Regards,
Riccardo

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException: Python expression 'X/1440' is either invalid or not supported

Expression transformer applies to columns of a matrix/data frame. In Python syntax, you can address columns using index-based syntax `X[col_index]` or name-based syntax `X['col_name']`.

Right now you're using `X` in expression syntax, which means "complete data frame/matrix".

If you change your expression to `X[0] / 1440`, then it should work.

**Comment by vruusmann** [comment]
Keeping this issue open as a reminder to improve the exception message.

**Comment by leone281** [comment]
Hello Villu,
Thanks for your help.
The right answer is actually this one (almost yours):

(['timeBeforeDeparture'], [ContinuousDomain(invalid_value_treatment = 'return_invalid', missing_value_replacement = -999), Alias(ExpressionTransformer('X[0]/1440'), name = "timeBeforeDepartureInMinutes")]),

if you don't put [] on the name the fit method fails.
Thanks.
Regards,
Riccardo

**Comment by leone281** [comment]
Thanks Villu,
Improving the documentation would help here.
The name of the field in the dataframe has to be a list even if there is only one element. This is not specified anywhere.
Regards,
Riccardo

**Comment by vruusmann** [comment]
> The name of the field in the dataframe has to be a list even if there is only one element. This is not specified anywhere.

Upgrade to SkLearn2PMML version 0.49.2 first (released about 1 hour ago to PyPI).

If you do, then you'll start seeing an exception message "Name \'X\' refers to a row vector. Use an array indexing expression X[<column index>] or X[<column name>] to refer to a specific row vector element":
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/javacc/expression.jj#L546-L548

Of course, if the row vector contains exactly one element, then the Python-to-PMML expression translator component could assume `X[0]`. But I'm not going to enable it right now, because it would encourage "lazy programming style", which is likely to cause more trouble in the future.

**Comment by ban2903** [comment]
Hello Villu,
How can I use a scipy tools in ExpressionTransformer?

('feature', ExpressionTransformer('scipy.special.logit(X[0])'))

PMML said "No module name scipy"

(I know, that I can use numpy.ln(X[0]/(1-X[0])), but maybe scipy will work for me?)
