### ISSUE TITLE
make model contain verification data

### ISSUE THREAD

**Issue by linxid** [jpmml/sklearn2pmml#195]
How to make a model  contain verification data, which is representative set of data records.

**Comment by vruusmann** [comment]
You mean this warning message? https://github.com/jpmml/jpmml-sklearn/blob/1.5.24/src/main/java/sklearn2pmml/pipeline/PMMLPipeline.java#L280

It says that you should use the method `PMMLPipeline.verify(X)`, where `X` is a representative subset of the training dataset, or better yet, a special-purpose verification dataset which contains rows covering all possible edge and corner cases.

Some code examples:
https://github.com/jpmml/jpmml-sklearn/blob/1.5.24/src/test/resources/main.py#L148-L151
https://github.com/jpmml/jpmml-sklearn/blob/1.5.24/src/test/resources/main.py#L549-L552

**Comment by linxid** [comment]
OK, Thanks,
