### ISSUE TITLE
StackingClassifier

### ISSUE THREAD

**Issue by krovyakov12** [jpmml/sklearn2pmml#198]
Hello!

It seems sklearn2pmml doesn't support sklearn.ensemble.StackingClassifier((( 

Or is there any instructions for it?

**Comment by vruusmann** [comment]
> It seems sklearn2pmml doesn't support sklearn.ensemble.StackingClassifier.

Not true - see https://github.com/jpmml/jpmml-sklearn/commit/c0149413d6d5ab26481f3d089dfc8c2b94282922

Please upgrade to SkLearn2PMML version 0.51.0 (or newer)
