### ISSUE TITLE
java.lang.IllegalArgumentException when writing PMML pipeline

### ISSUE THREAD

**Issue by pegger0709** [jpmml/sklearn2pmml#204]
Hello,
I am making a pipeline of a decision tree to predict survival on the Titanic, but I am having trouble writing it to PMML. The weird part is that when I tried writing virtually the same pipeline a couple weeks ago, it worked just fine.

```
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn2pmml.pipeline import PMMLPipeline
from sklearn2pmml import sklearn2pmml

df = pd.read_csv('titanic.csv')
X = df.drop('survived', axis='columns')
y = df.survived

categorical_features = ['sex','embarked']
categorical_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='most_frequent')),
    ('encoder', OrdinalEncoder())
])
numeric_features = ['age','pclass']
numeric_transformer = Pipeline(steps=[
    ('imputer', SimpleImputer(strategy='median'))
])
preprocessor = ColumnTransformer(
    transformers=[
        ('categorical', categorical_transformer, categorical_features),
        ('numeric', numeric_transformer, numeric_features)        
    ],
    remainder='drop'
)
classifier = DecisionTreeClassifier(
    criterion='entropy',
    max_depth=5,
    min_impurity_decrease=0.01,
    min_samples_leaf=10
)

pipeline = PMMLPipeline(steps=[
    ('preprocessor', preprocessor),
    ('classifier', classifier)
])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1234)
pipeline.fit(X_train, y_train)
```
So far so good, I can even export the decision tree as a graphviz file and make it into a nice png picture. However when I run
`sklearn2pmml(pipeline, "titanic.pmml")`
then I get the output

```
Standard output is empty
Standard error:
Jan 20, 2020 4:02:38 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jan 20, 2020 4:02:38 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 28 ms.
Jan 20, 2020 4:02:38 PM org.jpmml.sklearn.Main run
INFO: Converting..
Jan 20, 2020 4:02:38 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: The transformer object (Python class sklearn.tree._classes.DecisionTreeClassifier) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:121)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:112)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:612)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:72)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.base/java.lang.Class.cast(Class.java:3605)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 8 more

Exception in thread "main" java.lang.IllegalArgumentException: The transformer object (Python class sklearn.tree._classes.DecisionTreeClassifier) is not a supported Transformer
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:121)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:112)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:612)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:72)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:203)
	at org.jpmml.sklearn.Main.run(Main.java:145)
	at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.base/java.lang.Class.cast(Class.java:3605)
	at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
	... 8 more
```
It seems to think that the classifier is a transformer, but I don't know how it would get that idea.

My version info is as follows:
python: 3.7.4
pandas: 1.0.0rc0
sklearn: 0.22.1
sklearn2pmml: 0.53.0

I know you have seen several similar questions before, but it doesn't seem to me like any of them are quite the same as mine.

Thanks so much for your help.
Philip

**Comment by vruusmann** [comment]
> The weird part is that when I tried writing virtually the same pipeline a couple weeks ago,

Must be related to Scikit-Learn version update from 0.22.0 to 0.22.1 somehow...

> java.lang.IllegalArgumentException: The transformer object (Python class sklearn.tree._classes.DecisionTreeClassifier) is not a supported Transformer

Strange, the latest JPMML-SkLearn library version (1.5.29) contains a mapping for this module/name combination:
https://github.com/jpmml/jpmml-sklearn/blob/1.5.29/src/main/resources/META-INF/sklearn2pmml.properties#L141

Will re-run my integration tests with Scikit-Learn version 0.22.1, and see if something breaks.

**Comment by vruusmann** [comment]
@pegger0709 Where can I find this `titanic.csv` file that you're using here?

I'd like to run this pipeline myself. Looks like my earlier comment might be wrong, and there's a completely different issue at play - the converter is expecting to find a `TransformerMixin` in some particular location, but is finding a non-`TransformerMixin` instead (`DecisionTreeClassifier`).

**Comment by pegger0709** [comment]
Hi Villu,
Thanks for your quick response. Github won't let me upload the csv, but [here](https://github.com/jpmml/sklearn2pmml/files/4089825/titanic.xlsx) is an xlsx version of the same file.

**Comment by vruusmann** [comment]
Works fine in my computer:
```python
from sklearn2pmml import sklearn2pmml

sklearn2pmml(pipeline, "Titanic.pmml", debug = True)
```

Debug output:
```
python: 3.7.2
sklearn: 0.22
sklearn2pmml: 0.53.0
joblib: 0.13.2
sklearn_pandas: 1.8.0
pandas: 0.25.1
numpy: 1.17.1
openjdk: 1.8.0_111
```

The resulting PMML file is attached as proof (added an `.txt` filename extension to make GitHub accept it).

[Titanic.pmml.txt](https://github.com/jpmml/sklearn2pmml/files/4090184/Titanic.pmml.txt)

**Comment by vruusmann** [comment]
Will update my `pandas`, `sklearn_pandas` and `sklearn` packages later today to see if that breaks anything (perhaps some classes have been relocated and/or renamed again).

My `sklearn2pmml` package looks okay (were're both using the same `0.53.0` version).

**Comment by vruusmann** [comment]
I've updated my Python setup to latest version of everything:
```
python: 3.7.2
sklearn: 0.22.1
sklearn2pmml: 0.53.0
joblib: 0.13.2
sklearn_pandas: 1.8.0
pandas: 0.25.3
numpy: 1.17.1
openjdk: 1.8.0_111
```

The conversion of your sample pipeline succeeds. Therefore, I believe that you're issue is still caused by an outdated SkLearn2PMML package version somehow (you're using one that doesn't provide Scikit-Learn 0.22.X compatibility). To double-check your position, apply the `debug = True` flag.

**Comment by pegger0709** [comment]
It's still not working when I do it in jupyter notebook, but when I run it through the PyCharm IDE, it works. Weird... Anyhow, thanks!

**Comment by vruusmann** [comment]
> It's still not working when I do it in jupyter notebook

You must be using different SkLearn2PMML versions in Jupyter vs. PyCharm IDE.

I'm running all my experiments in a command-line environment, so I'm 99.85% confident in my claims.
