### ISSUE TITLE
Compatibility warning with scikit-learn V0.22

### ISSUE THREAD

**Issue by myonlinematters** [jpmml/sklearn2pmml#208]
When using scikit-learn 0.22.1 in an Amazon Sagemaker python3 interpreter (that I have updated for scikit-learn 0.22, I get the following warning:

> home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.feature_selection.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.feature_selection. Anything that cannot be imported from sklearn.feature_selection is now part of the private API.

Is there a plan to update for better compatibility?

**Comment by vruusmann** [comment]
Please add more context to such compatibility warnings.

Right now, I'm assuming that it is related to this import statement:
https://github.com/jpmml/sklearn2pmml/blob/0.53.0/sklearn2pmml/__init__.py#L3

The SkLearn2PMML package aims to be compatible with all Scikit-Learn versions 0.18 and up. Will have to see if `from sklearn.feature_selection import SelectorMixin` works with those older versions or not.

**Comment by myonlinematters** [comment]
These import statements are what cause the warning to appear.  

from sklearn2pmml.pipeline import PMMLPipeline
from sklearn2pmml import sklearn2pmml

As to where in the code the issue arises. will leave that to you.
