### ISSUE TITLE
Preserving feature names

### ISSUE THREAD

**Issue by iftahg** [jpmml/sklearn2pmml#21]
Is it possible to preserve feature names for the estimators?

For example if I fit a RandomForest classifier with a feature named 'feature1', the PMML classifier will currently have a feature named 'x1' instead.

I know that using a Mapper I could preserve the feature names but for my current needs it is an overkill.

**Comment by vruusmann** [comment]
The `RandomForestClassifier` object does not contain feature names. If you want to override default names (eg. "x1", "x2", "x3"), then you have to construct and pass a `DataFrameMapper` object to the `sklearn2pmml` method.

You can create a dummy `DataFrameMapper` object (that specifies the names of thousand columns) using a single line of Python application code. That's not overkill.

Or are you suggesting that "x1", "x2", etc. should be renamed to "feature1", "feature2", etc?

**Comment by KidCrippler** [comment]
@vruusmann I had the exact same problem.
I'm not a very proficient python programmer and couldn't get around wrapping my model with an "identity" mapper that only modifies the predictor names from x1, x2, etc... to whatever I want them to be.
Can you please provide a more detailed explanation on how to do that?

10x

**Comment by vruusmann** [comment]
@KidCrippler I'm not a Python expert either, so I'm going to construct the `DataFrameMapper` object using four lines of Python application code (instead of one as advertised above). The idea is to map a list of strings to a `None` transformation:

```Python
iris_active_fields = ["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"]
iris_target_field = "Species"

iris_mapper = sklearn_pandas.DataFrameMapper([
    (iris_active_fields, None),
    (iris_target_field, None)
])

sklearn2pmml(iris_classifier, iris_mapper, "Iris.pmml")
```
