### ISSUE TITLE
how to choose the version of pmml

### ISSUE THREAD

**Issue by wqh17101** [jpmml/sklearn2pmml#210]
Hi there,i want to get the pmml 4.0,but it seems that it can only generate 4.3 pmml.
So is there any way to generate 4.0 by sklearn2pmml or convert 4.3 pmml to 4.0?

**Comment by vruusmann** [comment]
> i want to get the pmml 4.0

Why?

> it seems that it can only generate 4.3 pmml.

Correct. Be forewarned that pretty soon (Q2 2020), the SkLearn2PMML package will begin emitting PMML schema version 4.4 documents.

> So is there any way to generate 4.0 by sklearn2pmml or convert 4.3 pmml to 4.0?

Really depends on the model type. The representation of most model types is identical between 4.0 and 4.3 (and 4.4), so it might be possible to perform the "conversion" simply by replacing the PMML XML namespace URI.

The JPMML-Model library contains class annotations, which let you programmatically keep track of PMML schema version compliance levels.

**Comment by wqh17101** [comment]
> > i want to get the pmml 4.0
> 
> Why?
An old decision engine only supports pmml 4.0.
I have no choice for the work.

**Comment by vruusmann** [comment]
> > Why?
>
> An old decision engine only supports pmml 4.0.

Your old decision engine probably recognizes only a very limited set of model types. So, your model "conversion" needs are very model type-specific, not generic.

Please follow my suggestion and try the XML namespace URI replacement hack. If it works, then you can write a small Python wrapper function that edits SkLearn2PMML generated locally.

**Comment by wqh17101** [comment]
Thank you for your help, i will try.
