### ISSUE TITLE
Use pre-trained data transformations (PCA) in pipeline

### ISSUE THREAD

**Issue by jmc-bbk** [jpmml/sklearn2pmml#211]
Hi 👋 ,

I'm looking at using this package to convert my model into pmml. Reading the documentation I see that it uses sklearn's concept of a `pipeline`. As far as I'm aware, if using a data transformation in the pipeline (e.g. PCA), the PCA will be fitted and then transform the data each time the pipeline is called.

I have a pretrained PCA that I wish to transform the data with (rather than running a fresh PCA each time).

Is it possible to achieve this with `sklearn2pmml`?

My desired output would be as follows:

- load data
- transform data with prefitted PCA
- make predictions on data with prefitted XGBoost model

But I understand that pipeline in this case would:

- load data
- fit PCA
- transform data
- make predictions on data with preditted XGBoost model

Sorry if this question has been answered elsewhere.

Thanks!

**Comment by vruusmann** [comment]
Estimator steps in a pipeline are fitted when the `(PMML)Pipeline.fit(X, y)` is called. If you initialize a `(PMML)Pipeline` with pre-fitted estimator steps, and do not call the `fit(X, y)` method, then nothing bad happens to them - they stay as they.

The only downside of not calling `PMMLPipeline.fit(X, y)` is that `PMMLPipeline.active_fields` and `PMMLPipeline.target_fields` remain uninitialized (the converter will notice and complain about this afterwards). However, you shall be free to initialize those two attributes manually at any time.

The converter does not care if the `PMMLPipeline` was constructed using 1) pre-fitted estimator steps or 2) blank estimator steps that were fitted using `(PMML)Pipeline.fit(X, y)`.

Here's a small script:
```python
prefittedPCA = pickle.load(..)
prefittedEstimator = pickle.load(...)

pipeline = PMMLPipeline([
  ("pca", prefittedPCA),
  ("estimator", prefittedEstimator)
])
pipeline.active_fields = [...]
pipeline.target_fields = [...]

sklearn2pmml(pipeline, "PrefittedPipeline.pmml")
```
