### ISSUE TITLE
saving pmml from pipeline with SelectFirstClassifier produces "SelectFirstClassifier does not specify the number of input features" error

### ISSUE THREAD

**Issue by petr-ponomarenko** [jpmml/sklearn2pmml#215]
Have two pmml pipelines like this:
```
mapper = DataFrameMapper(
 ... some mapping
    )
classifier = LGBMClassifier(objective = "binary", **lgbmc_args)
pipeline_a = PMMLPipeline([
        ("mapper", mapper),
        ("classifier", classifier)
    ])
pipeline_a.fit(df, df["label"])
```
Then making pipeline with classifier selection using 2 such pipelines:
```
pipeline_t = PMMLPipeline([('conditional_pipeline',
    SelectFirstClassifier([('0 present', pipeline_a, 'X[0] == X[0]'), 
        ('0 missing', pipeline_n, 'X[0] != X[0]')]))])
```
This pipeline works great in python, but can not save as pmml:
`sklearn2pmml(pipeline_t,"test.pmml")`
```
Standard output is empty
Standard error:
Apr 20, 2020 8:23:54 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Apr 20, 2020 8:23:55 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 157 ms.
Apr 20, 2020 8:23:55 PM org.jpmml.sklearn.Main run
INFO: Converting..
Apr 20, 2020 8:23:55 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: The transformer object of the first step (Python class sklearn2pmml.ensemble.SelectFirstClassifier) does not specify the number of input features
	at sklearn2pmml.pipeline.PMMLPipeline.initActiveFields(PMMLPipeline.java:522)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:214)
	at org.jpmml.sklearn.Main.run(Main.java:228)
	at org.jpmml.sklearn.Main.main(Main.java:148)

Exception in thread "main" java.lang.IllegalArgumentException: The transformer object of the first step (Python class sklearn2pmml.ensemble.SelectFirstClassifier) does not specify the number of input features
	at sklearn2pmml.pipeline.PMMLPipeline.initActiveFields(PMMLPipeline.java:522)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:214)
	at org.jpmml.sklearn.Main.run(Main.java:228)
	at org.jpmml.sklearn.Main.main(Main.java:148)
```
Enviroment:
java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-1~deb9u1-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

The scikit-learn version is 0.22.2.post1.
The pandas version is 0.25.3.
The sklearn_pandas version is 1.8.0.
The sklearn2pmml version is 0.55.4.

**Comment by petr-ponomarenko** [comment]
I think this is related to https://github.com/jpmml/sklearn2pmml/issues/201 
What is the best way to tell the main pipeline what is the structure of incoming data and preserve DataFrameMappers intact in the pipeline_a and pipeline_n

**Comment by petr-ponomarenko** [comment]
I found some temporary workaround by placing an aggregate DataFramerMapper as a first step before SelectFirstClassifier, and then having ColumnTransformer that drops columns before each classifier, but now I get another issue when converting to pmml file (predicate translation issue).
My code:
```
classifier_a = LGBMClassifier(objective = "binary", **lgbmc_args)
mapper = DataFrameMapper(...some mapping)
pipeline_n = PMMLPipeline([("dropfirstcol",ColumnTransformer([("dropfirst", 'drop', [0])],
    remainder='passthrough')), 
    ("classifier",classifier_b)])
pipeline_t= PMMLPipeline([("mapper",mapper),
    ("selector",SelectFirstClassifier([('selectfirst', classifier_a, 'X[0] == X[0]'), 
        ('selectsecond', pipeline_n, 'X[0] != X[0]')]))])
pipeline_t.fit(df,df['label'])
sklearn2pmml(pipeline_t, "./test_select_classifier.pmml")
```
Error:
```
Standard output is empty
Standard error:
Apr 21, 2020 3:30:22 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Apr 21, 2020 3:30:23 AM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 132 ms.
Apr 21, 2020 3:30:23 AM org.jpmml.sklearn.Main run
INFO: Converting..
Apr 21, 2020 3:30:23 AM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.ClassCastException: org.dmg.pmml.FieldName cannot be cast to java.lang.String
	at org.jpmml.sklearn.PredicateTranslator.ComparisonExpression(PredicateTranslator.java:216)
	at org.jpmml.sklearn.PredicateTranslator.LogicalAndExpression(PredicateTranslator.java:124)
	at org.jpmml.sklearn.PredicateTranslator.LogicalOrExpression(PredicateTranslator.java:103)
	at org.jpmml.sklearn.PredicateTranslator.Predicate(PredicateTranslator.java:97)
	at org.jpmml.sklearn.PredicateTranslator.translatePredicateInternal(PredicateTranslator.java:91)
	at org.jpmml.sklearn.PredicateTranslator.translate(PredicateTranslator.java:29)
	at sklearn2pmml.ensemble.SelectFirstUtil.encodeModel(SelectFirstUtil.java:73)
	at sklearn2pmml.ensemble.SelectFirstUtil.encodeClassifier(SelectFirstUtil.java:49)
	at sklearn2pmml.ensemble.SelectFirstClassifier.encodeModel(SelectFirstClassifier.java:53)
	at sklearn2pmml.ensemble.SelectFirstClassifier.encodeModel(SelectFirstClassifier.java:28)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:234)
	at org.jpmml.sklearn.Main.run(Main.java:228)
	at org.jpmml.sklearn.Main.main(Main.java:148)

Exception in thread "main" java.lang.ClassCastException: org.dmg.pmml.FieldName cannot be cast to java.lang.String
	at org.jpmml.sklearn.PredicateTranslator.ComparisonExpression(PredicateTranslator.java:216)
	at org.jpmml.sklearn.PredicateTranslator.LogicalAndExpression(PredicateTranslator.java:124)
	at org.jpmml.sklearn.PredicateTranslator.LogicalOrExpression(PredicateTranslator.java:103)
	at org.jpmml.sklearn.PredicateTranslator.Predicate(PredicateTranslator.java:97)
	at org.jpmml.sklearn.PredicateTranslator.translatePredicateInternal(PredicateTranslator.java:91)
	at org.jpmml.sklearn.PredicateTranslator.translate(PredicateTranslator.java:29)
	at sklearn2pmml.ensemble.SelectFirstUtil.encodeModel(SelectFirstUtil.java:73)
	at sklearn2pmml.ensemble.SelectFirstUtil.encodeClassifier(SelectFirstUtil.java:49)
	at sklearn2pmml.ensemble.SelectFirstClassifier.encodeModel(SelectFirstClassifier.java:53)
	at sklearn2pmml.ensemble.SelectFirstClassifier.encodeModel(SelectFirstClassifier.java:28)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:234)
	at org.jpmml.sklearn.Main.run(Main.java:228)
	at org.jpmml.sklearn.Main.main(Main.java:148)
```

**Comment by petr-ponomarenko** [comment]
Finally solved by using only < , > and str(True) in predicates like so X[0] > -9997 and encoding none values with -9999 (my values are mostly above -10).

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException: The transformer object of the first step (Python class sklearn2pmml.ensemble.SelectFirstClassifier) does not specify the number of input features.

The first step of the topmost/outermost pipeline must be an estimator or a transformer that contains information about the number of data columns. Suitable candidates for the latter are `sklearn_pandas.DataFrameMapper` and `sklearn.compose.ColumnTransformer`.

If you don't want to do any feature engineering at the topmost/outermost pipeline level, then you can simply specify a "passthrough" columntransformer there: `ColumnTransformer([], remainder = "passthrough")`.

**Comment by vruusmann** [comment]
> 'X[0] == X[0]'

The left-hand side of the predicate must be a feature, and the right-hind side must be some constant expression. For example, `X[0] < 0` or `X[0] == "red"`.

Right now your right-hand side is also a feature. The PMML specification does not permit comparing fields against other fields.

**Comment by liuhuanshuo** [comment]
@vruusmann 

hi,villu。I also encountered the same problem.

Is there a way to judge based on None here, for example, X == None , the pandas.isna/pandas.isnull that can be used in ExpressionTransformer before cannot be used

**Comment by vruusmann** [comment]
Determining the "number of input features" for `SelectFirstClassifier` is tricky, because child estimators may be "heterogeneous", meaning that they expect a different number of input features each.

Consider, for example, the "select first" logic that is presented in https://github.com/jpmml/sklearn2pmml/issues/369#issuecomment-1413566516

The `dummy_clf` object is expecting zero (0) input features, but the `my_normal_pipeline` object is expecting a non-zero (was it 11?) input features.

To resolve this ambiguity, please make sure that the "number of input features" is make known to the PMML converter using alternative means. The simplest thing to do is to set the `PMMLPipeline.active_fields` attribute.

**Comment by vruusmann** [comment]
@liuhuanshuo If you want to select the model based on nullability check ("feature is missing", "feature is not missing"), then you can do it in many ways:

- Using `pandas.isna` and `pandas.notna` functions (numeric features).
- Using `pandas.isnull` and `pandas.notnull` functions (object-like features such as string features).
- Using plain old `<X> is None` and `<X> is not None` identity comparison expressions (object-like features)

For example:
``` python
estimator = SelectFirstEstimator([
  ("feat_not_missing", make_first_estimator(), "pandas.notnull(X[0])"),
  ("feat_missing", make_second_estimator(), "pandas.isnull(X[0])")
])
```
I personally prefer a pattern, where I test for one condition, and then catch everything that didn't match it with a `True` constant expression:

``` python
estimator = SelectFirstEstimator([
  ("feat_not_missing", make_first_estimator(), "pandas.notnull(X[0])"),
  ("feat_missing", make_second_estimator(), str(True))
])
```

**Comment by liuhuanshuo** [comment]
@vruusmann Thanks for the prompt response for sklearn2pmml users


I fully remember that in the previous question, you told me the problems that need to be paid attention to when judging null values in sklearn2pmml.https://github.com/jpmml/jpmml-evaluator-python/issues/17#issuecomment-1365667706

>  Using pandas.isna and pandas.notna functions (numeric features). 

Regardless of whether I use `pandas.isna/pandas.notna/pandas.isnull/pandas.notnull,` it can be judged that np.nan is True if it is run alone, but if it is used in SelectFirstClassifier,use like below
```python
pipeline_t = PMMLPipeline([('conditional_pipeline',
    SelectFirstClassifier([
        ('model_1', model_1, "pandas.notna(X[-2])"), 
        ('model_2', model_2, "pandas.isna(X[-2])")]))])
```
 then will fail, prompting the following error . I don't know if my version of `sklearn2pmml` is too low(0.90.1)?
```
NameError: ("name 'pandas' is not defined", 'occurred at index 0')
```

> Using plain old <X> is None and <X> is not None identity comparison expressions (object-like features)

If use `is None` to judge, according to the previous information, this will not work at all, because `np.nan == None` is inherently False,

so the following code will directly enter `model_1`, regardless of whether `X[-2]` is np.nan
```
pipeline_t = PMMLPipeline([('conditional_pipeline',
    SelectFirstClassifier([
        ('model_1', model_1, "X[-2] is not None"), 
        ('model_2', model_2, "X[-2] is None")]))])
```

**Comment by liuhuanshuo** [comment]
> The dummy_clf object is expecting zero (0) input features, but the my_normal_pipeline object is expecting a non-zero (was it 11?) input features.

Yes, the task I need to achieve is actually very simple.

My input has 13 columns,

- model_1 needs to input 11 columns, it is an `LR` model
- model_2 (that is, the model I built with dummy, which predicts 0 no matter what) needs to input three columns.

The purpose is, if `None`(`np.nan`) appears in the specified three columns, it is predicted to be 0, otherwise let those 11 columns enter `model_1`

So I chose SelectFirstClassifier, but now there is a problem with the determination of missing values.

**Comment by vruusmann** [comment]
> NameError: ("name 'pandas' is not defined", 'occurred at index 0')

The `pandas.isna/notna` function cannot be resolved in your Python environment. You need to do `import pandas` in the beginning of your Python script.

> If use is None to judge, according to the previous information, this will not work at all, because np.nan == None is inherently False,

Exactly - that's why I suggested using different "nullability checks" with different data types - numeric vs. object-like.

The `pandas.isna` supports Pandas-specific missing value placeholders (the `pandas.NA` constant).

> The purpose is, if None(np.nan) appears in the specified three columns, it is predicted to be 0, otherwise let those 11 columns enter model_1

```python
import pandas

ensemble = SelectFirstClassifier([
  ("has_missing", dummy_clf, "pandas.isnull(X[0]) or pandas.isnull(X[1]) or pandas.isnull(X[2])"),
  ("does_not_have_missing", my_default_pipeline, str(True))
])
```

The `pandas.isnull` function knows about the `NaN` value:

```python
import pandas
x = float("NaN")
pandas.isnull(x)
```

The list of supported function translations is here: https://github.com/jpmml/jpmml-python/blob/1.1.11/pmml-python/src/main/java/org/jpmml/python/FunctionUtil.java#L69-L89

It would be nice if the Python-to-PMML translator had limited "vectorization" support, so that it would be possible to write the above missingless check as `pandas.isnull(X[0:2])`. But IIRC, this hasn't been implemented yet, so you need to type each array element out separately (or create a small helper Python function that generates those expression strings for you).

**Comment by liuhuanshuo** [comment]
Dear Villu @vruusmann 

I know exactly what you mean, but what I'm trying to say is, this won't work

> The pandas.isnull function knows about the NaN value:

For example, when I use the following code to predict, I still get an error
```python
import pandas 

pipeline_t = PMMLPipeline([
                           ("mapper_3",mapper_3),
                           ('conditional_pipeline',
    SelectFirstClassifier([
        ('model_1', model_1, "pandas.isnull(X[0])"), 
        ('model_2', model_2, str(True))]))])

pipeline_t.predict_proba(test_data)
```
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-1248-5edf325c8d3c> in <module>
----> 1 pipeline_t.predict_proba(x_original_plus_3feas.head(5))

~/.local/lib/python3.7/site-packages/sklearn2pmml/pipeline/__init__.py in predict_proba(self, X, **predict_proba_params)
     89         def predict_proba(self, X, **predict_proba_params):
     90                 Xt = self._transform(X)
---> 91                 return self.steps[-1][-1].predict_proba(Xt, **predict_proba_params)
     92 
     93         def apply(self, X):

~/.local/lib/python3.7/site-packages/sklearn2pmml/ensemble/__init__.py in predict_proba(self, X)
    302 
    303         def predict_proba(self, X):
--> 304                 return self._predict("predict_proba", X)

~/.local/lib/python3.7/site-packages/sklearn2pmml/ensemble/__init__.py in _predict(self, predict_method, X)
    272                 mask = numpy.zeros(X.shape[0], dtype = bool)
    273                 for name, estimator, predicate in self.steps:
--> 274                         step_mask = eval_rows(X, lambda X: eval(predicate), dtype = bool)
    275                         step_mask[mask] = False
    276                         if numpy.sum(step_mask) < 1:

~/.local/lib/python3.7/site-packages/sklearn2pmml/util/__init__.py in eval_rows(X, func, dtype)
     47                 if isinstance(X, Series):
     48                         return X.apply(func)
---> 49                 return X.apply(func, axis = 1)
     50         nrow = X.shape[0]
     51         Xt = numpy.empty(shape = (nrow, ), dtype = dtype)

/data1/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py in apply(self, func, axis, broadcast, raw, reduce, result_type, args, **kwds)
   6911             kwds=kwds,
   6912         )
-> 6913         return op.get_result()
   6914 
   6915     def applymap(self, func):

/data1/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py in get_result(self)
    184             return self.apply_raw()
    185 
--> 186         return self.apply_standard()
    187 
    188     def apply_empty_result(self):

/data1/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py in apply_standard(self)
    290 
    291         # compute the result using the series generator
--> 292         self.apply_series_generator()
    293 
    294         # wrap results

/data1/anaconda3/lib/python3.7/site-packages/pandas/core/apply.py in apply_series_generator(self)
    319             try:
    320                 for i, v in enumerate(series_gen):
--> 321                     results[i] = self.f(v)
    322                     keys.append(v.name)
    323             except Exception as e:

~/.local/lib/python3.7/site-packages/sklearn2pmml/ensemble/__init__.py in <lambda>(X)
    272                 mask = numpy.zeros(X.shape[0], dtype = bool)
    273                 for name, estimator, predicate in self.steps:
--> 274                         step_mask = eval_rows(X, lambda X: eval(predicate), dtype = bool)
    275                         step_mask[mask] = False
    276                         if numpy.sum(step_mask) < 1:

~/.local/lib/python3.7/site-packages/sklearn2pmml/ensemble/__init__.py in <module>

NameError: ("name 'pandas' is not defined", 'occurred at index 0')

```

I'm absolutely sure I imported pandas correctly, but it just doesn't work!

And, I found that it is only invalid in `SelectFirstClassifier`, but it can be used in `ExpressionTransformer`!

For example, the following code would work
```
ExpressionTransformer("1 if pandas.isnull(X[1]) else 0")
```

I don't know if you are sure where this problem occurs, my `sklearn2pmml` version is `0.90.1`，It seems that in SelectFirstClassifier, it doesn't recognize pandas

**Comment by liuhuanshuo** [comment]
> The list of supported function translations is here: https://github.com/jpmml/jpmml-python/blob/1.1.11/pmml-python/src/main/java/org/jpmml/python/FunctionUtil.java#L69-L89

[Because in the link you provided](https://github.com/jpmml/jpmml-python/blob/1.1.11/pmml-python/src/main/java/org/jpmml/python/FunctionUtil.java#L69-L89), I found that `numpy` is also supported, so I tried to use `numpy.isnan` to judge the null value, very good, the following code works in the pipeline
```python
pipeline_t = PMMLPipeline([
                           ("mapper_3",mapper_3),
                           ('conditional_pipeline',
    SelectFirstClassifier([
        ('model_2', model_2, 'numpy.isnan(X[-2])'), 
        ('model_1', model_1, str(True))]))])

```
But a similar error was reported when saving pmml, this time I didn’t know numpy when saving!
```
Standard output is empty
Standard error:
Feb 07, 2023 2:27:32 PM sklearn2pmml.pipeline.PMMLPipeline initTargetFields
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming [y] as the name of target fields
Exception in thread "main" java.lang.IllegalArgumentException: Name 'numpy' is not defined
	at org.jpmml.python.DataFrameScope.getFeature(DataFrameScope.java:65)
	at org.jpmml.python.PredicateTranslator.NameInvocationExpression(PredicateTranslator.java:459)
	at org.jpmml.python.PredicateTranslator.PrimaryExpression(PredicateTranslator.java:383)
	at org.jpmml.python.PredicateTranslator.ComparisonExpression(PredicateTranslator.java:281)
	at org.jpmml.python.PredicateTranslator.LogicalAndExpression(PredicateTranslator.java:228)
	at org.jpmml.python.PredicateTranslator.LogicalOrExpression(PredicateTranslator.java:207)
	at org.jpmml.python.PredicateTranslator.Predicate(PredicateTranslator.java:201)
	at org.jpmml.python.PredicateTranslator.translatePredicateInternal(PredicateTranslator.java:195)
	at org.jpmml.python.PredicateTranslator.translatePredicate(PredicateTranslator.java:34)
	at sklearn2pmml.ensemble.SelectFirstUtil.encodeModel(SelectFirstUtil.java:79)
	at sklearn2pmml.ensemble.SelectFirstUtil.encodeClassifier(SelectFirstUtil.java:46)
	at sklearn2pmml.ensemble.SelectFirstClassifier.encodeModel(SelectFirstClassifier.java:74)
	at sklearn2pmml.ensemble.SelectFirstClassifier.encodeModel(SelectFirstClassifier.java:29)
	at sklearn.Estimator.encode(Estimator.java:118)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:187)
	at com.sklearn2pmml.Main.run(Main.java:91)
	at com.sklearn2pmml.Main.main(Main.java:66)

```

**Comment by vruusmann** [comment]
> I know exactly what you mean, but what I'm trying to say is, this won't work
> 
> `NameError: ("name 'pandas' is not defined", 'occurred at index 0')`
>

Okay, my bad - the `pandas.isnull`, `pandas.isna`, etc. functionas are supported in the **_expression context_**, but not in the **_predicate context_** (simplified, inline boolean expression). For example, they work in `ExpressionTransformer`, but they don't work as `SelectFirstClassifier` or `EstimatorChain` filters.

This is so, because they are translated by different JPMML-Python library components.

The only option is to go with the `<X> is None` or `<X> is not None` filter predicates. Actually, it should be the case that these predicates give bad predictions in Python environment (ie. miss the `numpy.NaN` value), but they will give good predictions in (J)PMML environment.

**Comment by vruusmann** [comment]
This looks like a serious deficiency. Will attempt to address it during this week.
