### ISSUE TITLE
CategoricalDomain with multiple features

### ISSUE THREAD

**Issue by nicolas2lee** [jpmml/sklearn2pmml#216]
Hi,

I am facing a problem with data preprocessing, when I define a DataframeMapper, I could not add multiple columns in a single CategoricalDomain, like below:
`mapper = DataFrameMapper([ (['ProductCD', 'card4', 'M6'], 
[CategoricalDomain(), SimpleImputer(strategy='most_frequent'), OneHotEncoder()]),
])`

But when define a column for each CategoricalDomain, it works well. I want to understand that CategoricalDomain could accept only one single column ? And why or maybe I had misunderstood  ? E.g.:
`mapper = DataFrameMapper([
 (['ProductCD'], [CategoricalDomain(), SimpleImputer(strategy='most_frequent'), OneHotEncoder()]),
 (['card4'], [CategoricalDomain(), SimpleImputer(strategy='most_frequent'), OneHotEncoder()]),
])`

**Comment by vruusmann** [comment]
> I could not add multiple columns in a single CategoricalDomain

Your observation is correct - the `CategoricalDomain` decorator class only accepts one column at a time.

Summary of decorator "arities":
- `ContinuousDomain` - one or more
- `CategoricalDomain`, `OrdinalDomain` - exactly one
- `DateDomain`, `DateTimeDomain` - one or more
- `MultiDomain` - one or more

If you need to decorate multiple categorical columns, then simply loop over them. What's wrong with that approach?

**Comment by nicolas2lee** [comment]
Nothing wrong, but it is more convenient to support multi columns. For example, I am migrating sklearn pipeline to pmml pipeline, since sklearn pipeline supported multi columns and pmml pipeline did not, so I need to change. And also, when having more than 5 columns, I think it is still more practical.

**Comment by vruusmann** [comment]
> For example, I am migrating sklearn pipeline to pmml pipeline

Simply replace `sklearn.pipeline.Pipeline` with `sklearn2pmml.pipeline.PMMLPipeline`.

Your original pipeline didn't have any domain decorators(?). Introducing `CategoricalDomain` (or any other domain decorator) makes sense if there's some new information to be added - for example, specifying missing or invalid value treatment.
