### ISSUE TITLE
i can't find the "samples"、"value" etc attributes of each node in GBDT pmml(cart tree) after sklearn2pmml

### ISSUE THREAD

**Issue by mrlittleyo** [jpmml/sklearn2pmml#217]
i can't find the "samples"、"value" etc attributes of each node in GBDT pmml(cart tree) after sklearn2pmml

**Comment by vruusmann** [comment]
By default, the SkLearn2PMML package only generates attributes that are required for making predictions (scoring the model).

The majority of predictive analytics applications have no need for the description of the training dataset (eg. the count of data records at each node). However, if your application needs this information, then you can activate various SkLearn2PMML conversion options that activate the generation of different kinds of extra attributes.

For starters, see:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/tree/TreeUtil.java#L71-L222

Resolution: everything works as intended/advertised, won't change.

**Comment by mrlittleyo** [comment]
> By default, the SkLearn2PMML package only generates attributes that are required for making predictions (scoring the model).
> 
> The majority of predictive analytics applications have no need for the description of the training dataset (eg. the count of data records at each node). However, if your application needs this information, then you can activate various SkLearn2PMML conversion options that activate the generation of different kinds of extra attributes.
> 
> For starters, see:
> https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/tree/TreeUtil.java#L71-L222
> 
> Resolution: everything works as intended/advertised, won't change.

hello， can I pass in parameters in python to let the pmml  files output attributes such as samples and values?
