### ISSUE TITLE
i'm wondering why default operator="greaterOrEqual" in xgboost pmml,but default operator="lessOrEqual" in gbdt pmml.

### ISSUE THREAD

**Issue by mrlittleyo** [jpmml/sklearn2pmml#218]
Hello,i'm wondering why default operator="greaterOrEqual" in xgboost pmml,but default operator="lessOrEqual" in gbdt pmml.Can i keep them consistent by giving some parameters

**Comment by vruusmann** [comment]
> i'm wondering why default operator="greaterOrEqual" in xgboost pmml,but default operator="lessOrEqual" in gbdt pmm

It's because XGBoost and LightGBM are different algorithms by different vendors, and they are free to implement split bounds as they like.

JPMML conversion libraries "inherit" split bounds from the base ML framework. Feel free to consult with XGBoost and/or LightGBM source code.
