### ISSUE TITLE
PMML model doesn't process data with missing fields correctly

### ISSUE THREAD

**Issue by ddzhem** [jpmml/sklearn2pmml#223]
Hi!
While trying to use pmml models in production environment, we encountered a problem with our pipelines. In short, pipeline looks like this: DataFrameMapper -> SelectFirstClassifier. In each step of SelectFirstClassifier there's a ColumnTransformer with ExpressionTransformer and SimpleImputer inside for each column used in this step, and a LogisticRegression in the end. 
When making predictions with this pipeline, everything is ok, but after conversion to .pmml it doesn't seem to work on data with missing features, the predictions are equal to None.
I attached a model example for reproducing the error. It doesn't have a SelectFirstClassifier, but the problem still persists.
Though in code attached we make prediction with pypmml model, the problem also appears to be with pure pmml file.

[pmml_error2.txt](https://github.com/jpmml/sklearn2pmml/files/4669219/pmml_error2.txt)

**Comment by vruusmann** [comment]
Thanks for a reproducible example!

The SkLearn2PMML package is doing 100% correct job. And if you evaluate the PMML file with the [JPMML-Evaluator-Python](https://github.com/jpmml/jpmml-evaluator-python) package, then you get 100% correct predictions back.

Therefore, I must conclude that the problem is in PyPMML package.

**Comment by vruusmann** [comment]
My experiment:

```python
test_dict.to_csv("test_dict.csv", na_rep = "N/A", index = False)
test_dict1.to_csv("test_dict1.csv", na_rep = "N/A", index = False)
```

Then evaluated using JPMML-Evaluator command-line application:
```
$ java -jar pmml-evaluator-example-executable-1.5-SNAPSHOT.jar --model test.pmml --input test_dict.csv --output test_dict-output.csv
$ java -jar pmml-evaluator-example-executable-1.5-SNAPSHOT.jar --model test.pmml --input test_dict1.csv --output test_dict1-output.csv
```
