### ISSUE TITLE
sklearn2pmml pmml options

### ISSUE THREAD

**Issue by XScarlett** [jpmml/sklearn2pmml#227]
Hi vruusmann,

can i set **missingValueStrategy** as **lastPrediction** using `configure(self, **pmml_options)`? and how? 
What options does pmml_options contain? Where can I view the description document?

thanks.

**Comment by vruusmann** [comment]
> can i set missingValueStrategy as lastPrediction using configure(self, **pmml_options)?

You can't override the default value of individual attributes this way. If you're not happy with them, then you'd need to implement PMML class model modification code, for example, using the Visitor API.

The PMML options mechanism is for choosing between alternative representations of the Spark ML model data structure. For example, it is possible to rearrange binary-splits to multi way-splits, which reduces the size of the decision tree model considerably.

> What options does pmml_options contain? Where can I view the description document?

You're not my customer, and therefore you're not entitled to extra/private documentation.

All PMML options inherit from the `org.jpmml.sparkml.HasSparkMLOptions` marker interface. You should open its type hierarchy in IDE, and see where it leads you in the JPMML-SparkML library.

**Comment by vruusmann** [comment]
Sorry, if you're working with SkLearn2PMML/JPMML-SkLearn stack, then see the `org.jpmml.sklearn.HasSkLearnOptions` marker interface instead.
