### ISSUE TITLE
Replace function & capture groups

### ISSUE THREAD

**Issue by bindernet** [jpmml/sklearn2pmml#228]
Hi Villu.
I'm trying to do a replace with a regex, and use the captured groups in the substitution.
Is this supported? It's not clear to me from the standard and I can't find any examples.
It's currently outputing the substitute string verbatim to the next transformation.

I am using the replacement transformer from sklearn2pmml and it's generating
PMML like this:
 ``` 
<DerivedField name="trxNorm2" optype="categorical" dataType="string">
	<Apply function="replace">
		<FieldRef field="normalizedDateTime"/>
		<Constant dataType="string">(\d{1,2})/(\d{1,2})/(\d{2,4})( .*?)(:\d\d\d)$</Constant>
		<Constant dataType="string">\3-\2-\1 \4</Constant>
	</Apply>
</DerivedField>
```
Am I missing something obvious?
EDIT: I had a look at Functions.java which uses the Matcher replaceAll method 
According to the documentation this uses a $ for group substitution where as Python uses a \ 
Could that be the issue? 

Thanks.

**Comment by vruusmann** [comment]
Given this new information, I've transfered this issue to SkLearn2PMML/JPMML-SkLearn ecosystem.

Most likely, will need to tweak Python code.

**Comment by bindernet** [comment]
Believe it or not the python pcre lib uses another convention. {} by default.
https://pypi.org/project/python-pcre/

It's a difficult one because I'm guessing that doing a regex on a regex is a route to madness 😀

**Comment by vruusmann** [comment]
>  the python pcre lib uses another convention

The `python-pcre` package looks quite outdated - last updated in Oct 2015.

Perhaps SkLearn2PMML package should include a native PCRE library itself, and configure it in full PCRE-compatibility mode. So that group references would all be `$\d` in Python, PMML and JPMML-Evaluator by default.

**Comment by vruusmann** [comment]
At minimum, the `ReplaceTransformer` could detect if the replacement string contains any backslash characters, and if true, raise a more meaningful error.
