### ISSUE TITLE
Convert trained xgboost model to pmml format

### ISSUE THREAD

**Issue by Smilexuhc** [jpmml/sklearn2pmml#232]
How can I convert a trained xgboost model to pmml format. Can you give a example.

**Comment by vruusmann** [comment]
What have you tried, what's the exact technical problem?

For starters, see the README file of the [JPMML-XGBoost](https://github.com/jpmml/jpmml-xgboost) project.

**Comment by Smilexuhc** [comment]
The excat problem is that I need to convert a trained xgboost model file to pmml format for online deployment. I can not use pmml pipeline to retrain my model, for I trained xgboost in batch:
```python
for df_batch in reader:  
    y_batch = df_batch[self.label_col].values
    x_batch = df_batch.drop([self.label_col], axis=1).values
    model = XGBClassifier(self.hparams, n_estimators=self.num_boost_round)
    if global_steps == 0:
        model = model.fit(X=x_batch, y=y_batch)
    else:
        model = model.fit(X=x_batch, y=y_batch, xgb_model=model[-1])
    self._models.append(model)
    global_steps += 1
```
Can PMMLPipeline train xgboost model in such way?

**Comment by vruusmann** [comment]
In essence, you want to train XGBoost models in "continuation mode" by supplying an existing model instance to the `XGBClassifier.fit(X, y)` method as the `xgb_model` parameter.

The `sklearn2pmml.pipeline.PMMLPipeline` class extends `sklearn.pipeline.Pipeline`, and as such supports fit parameters. Have you tried passing the existing model as a fit parameter?

Assuming that the classifier step is called `classifier`, it should be possible to pass the existing model as a `classifier__xgb_model` fit parameter:

```python
pipeline = PMMLPipeline([
  ("classifier", XGBClassifier())
])
pipeline.fit(x_batch, y_batch, classifier__xgb_model = my_xgbclassifier)
```

**Comment by Smilexuhc** [comment]
@vruusmann Thank you for your reply. I have thought of the method you mentioned that pass the  previous xgboost model in `pipeline.fit(x_batch,y_batch, xgb_model=my_xgb)`, but I need to get a new model(xgb or sklearn model file) after each step. I can simply get it by `model = model.fit()`. How can I do it based on PMMLPipeline?

**Comment by vruusmann** [comment]
As pointed out above, `PMMLPipeline` is a subclass of `Pipeline`. You can access the fitted estimator (aka the final estimator) as `PMMLPipeline.final_estimator` attribute.

Alternatively, you can train XGBoost models manually (as shown in https://github.com/jpmml/sklearn2pmml/issues/232#issuecomment-643769862), and in the end, when the training is finished, build a `PMMLPipeline` instance out of the fitted XGBoost model:

```python
classifier = XGBClassifier()
classifier.fit(X, y, xgb_model = ...)

from sklearn2pmml import make_pmml_pipeline

pmml_pipeline = make_pmml_pipeline(classifier, active_fields = [..], target_fields = [..])
```

**Comment by Smilexuhc** [comment]
Thanks
