### ISSUE TITLE
Initializing the `<Model>@modelName` attribute

### ISSUE THREAD

**Issue by vruusmann** [jpmml/sklearn2pmml#234]
Two ways to do it:

1. As a `PMMLPipeline` attribute, to be specified via the `PMMLPipeline` constructor.
2. As a PMML conversion option, to be specified via the `PMMLPipeline.configure(**pmml_options)` method.

**Comment by kantoniak** [comment]
Hello @vruusmann, could you provide some guidance how to set the model name? This is a new feature and I'm having a hard time to find examples. Diving into code I found a `pmml_name_` dict entry, but setting this value didn't help.

I'm trying to set `modelName` for a `RegressionModel`, code below uses `sklearn2pmml@0.68.0` from anaconda:
```python
classifier = PMMLPipeline(
    steps=[
        ('preprocessor', preprocessor),
        ('classifier', lr)])
# ...
classifier.configure(pmml_name_ = 'Test model name')
sklearn2pmml(classifier, output_path, with_repr = True)
```
This is output XML I get:
```
<PMML...>
    <RegressionModel functionName="classification" algorithmName="sklearn.linear_model._logistic.LogisticRegression" normalizationMethod="logit">
    <!-- ... -->
    </RegressionModel>
</PMML>
```
I would appreciate your help.

**Comment by vruusmann** [comment]
> Diving into code I found a pmml_name_ dict entry, but setting this value didn't help.

Set it directly on the estimator object:

```python
lr = LogisticRegression()
lr.pmml_name_ = "MyModel"

pipeline = PMMLPipeline([
  ("classifier", lr)
])
```

The `PMMPipeline#configure(pmml_name_ = "MyModel")` won't work, because it creates a wrapper `pmml_options_` dict attribute (equivalent to `lr.pmml_options_ = dict(pmml_name_ = "MyModel")`).

**Comment by vruusmann** [comment]
The `pmml_name_` attribute is intended for customizing `DerivedField` element names (overrides the default machine-generated name `<function>([<features>])`).

But since it's such a nice convention, it can now be used to set the Model element name as well.

**Comment by kantoniak** [comment]
Thank you!
