### ISSUE TITLE
Deprecation warning when using sklearn >= 0.18

### ISSUE THREAD

**Issue by MaxNoe** [jpmml/sklearn2pmml#24]
`sklearn.cross_validation` got deprecated in favor of `sklearn.model_selection`

**Comment by vruusmann** [comment]
This warning appeared after you upgraded from SkLearn 0.17 to 0.18?

The `sklearn2pmml` package does not import or use any functionality from the `sklearn.cross_validation` module. It follows that this warning is emitted by SkLearn internal workings, and there's nothing that I can do to make it go away.

Perhaps the SkLearn library has some sort of global configuration option/flag, where you can adjust your preferred warning level.

**Comment by MaxNoe** [comment]
Ah, sorry. The import happens in `sklearn_pandas` not in `sklearn2pmml`.

**Comment by vruusmann** [comment]
Could be happening in several places.

At least we have it "documented" now. Quick Googling didn't reveal any easy options for silencing those warnings.
