### ISSUE TITLE
invalid_value_treatment in CategoricalDomain throws error with versions 0.49.1 and higher

### ISSUE THREAD

**Issue by PavelZeger** [jpmml/sklearn2pmml#244]
Hello.
I'm trying to create a pmml file from XGBoost pipeline:
```
estimator = xgb.XGBClassifier(**xgboost_parameters)
mapper = DataFrameMapper([(i, None) if j != 'object' and j != 'bool' else
                                  (i, [CategoricalDomain(
                                      missing_value_treatment="as_value",
                                      invalid_value_treatment="as_missing",
                                      # invalid_value_treatment="as_is",
                                      missing_value_replacement=input_dataframe_x[i].value_counts().idxmax(),
                                      invalid_value_replacement=input_dataframe_x[i].value_counts().idxmax()),
                                      LabelEncoder()])
                                  for i, j in zip(input_dataframe_x.columns.values, input_dataframe_x.dtypes.values)],
                                 input_df=True,
                                 df_out=True)

pipeline = PMMLPipeline([("mapper", mapper), ("classifier", estimator)])
pipeline.fit(input_dataframe_x, input_dataframe_y)
print(pipeline)
sklearn2pmml(pipeline, pmml_file_name, with_repr=True, debug=True)
```
As you wrote in one of opened issue here and as I saw in the source code the only way to run this mapper is to change to _"as_is"_ flag, but I cannot use the previous versions in order to leave the code with _"as_missing"_ flag. 
Also if I'm trying to use versions prior 0.47 I'm getting errors related to _joblib_ library, for example:
```ImportError: cannot import name 'comb'```   
or
```AttributeError: module 'sklearn.externals.joblib' has no attribute '__version__'```   

My versions currently are:

python: 3.6.8
sklearn: 0.21.3
sklearn2pmml: 0.49.0
joblib: 0.14.1
sklearn_pandas: 1.8.0
pandas: 1.1.1
numpy: 1.19.1
xgboost 0.90

Which version do I need to use for python 3, sciti-learn, sklearn2pmml, joblib, sklearn_pandas and xgboost in order to leave the code with the current parameter **invalid_value_treatment="as_missing"**?
I would appreciate if you can help with that issue!

**Comment by vruusmann** [comment]
> sklearn2pmml: 0.49.0

If you're not my customer, then you shouldn't raise issues about legacy/archived versions.

> Which version do I need to use ..

You should always use the latest SkLearn2PMML package version (that is available in PyPI).

The current issue is about redundant/conflicting domain decorator attributes. You're supplying values for all possible `CategoricalDomain` attributes, but you should be supplying values for a subset of them, based on your actual data preparation logic/needs.

Here, you cannot supply `CategoricalDomain.invalid_value_treatment="as_missing"` and `invalid_value_replacement=input_dataframe_x[i].value_counts().idxmax())` together. This instruction reads "if the input value is missing then replace it with $input_dataframe_x[i].value_counts().idxmax()) and a missing value". It should be one (`input_dataframe_x[i].value_counts().idxmax())`) or the other (`missing`), but not both.
