### ISSUE TITLE
Support for imblearn models

### ISSUE THREAD

**Issue by damienlancry** [jpmml/sklearn2pmml#248]
Hi, Great library thank you very much for it!

I work a lot with imblearn models, in particular the BalancedRandomForestClassifier, and I would like to know if there is a plan for sklearn2pmml to support imblearn models in your roadmap. If not, would you consider adding it? I would be interested in contributing, but I would probably need some directions. 

at the moment I defined a function to convert a imblearn BalancedRandomForestClassifier to pmml by simply overriding all attributes of an unfitted sklearn RandomForestClassifier, but that feels a bit hacky and only works with BalancedRandomForestClassifier:
```
def imblearn2pmml(imbpipeline, path, with_repr = False, debug = False):
    rfc = RandomForestClassifier()
    brfc = imbpipeline.steps[0][1]
    rfc.n_classes_ = brfc.n_classes_
    rfc.classes_ = brfc.classes_
    rfc.n_features_ = brfc.n_features_
    rfc.n_outputs_ = brfc.n_outputs_
    rfc.estimators_ = brfc.estimators_
    skpipeline = PMMLPipeline([("classifier", rfc)])
    skpipeline.active_fields = imbpipeline.active_fields
    sklearn2pmml(skpipeline, path, with_repr = with_repr, debug = debug)

df = pd.read_csv("data")
imbpipeline = PMMLPipeline([("classifier", BalancedRandomForestClassifier(bootstrap=False))])
imbpipeline.fit(df[df.columns.difference(["class"])], df["class"])
imblearn2pmml(imbpipeline, "imbpipeline.pmml", with_repr = True, debug = True)
```

**Comment by vruusmann** [comment]
> I would like to know if there is a plan for sklearn2pmml to support imblearn models

I'd like to support every reasonably popular ML framework/library, but I've only got one life :/

> I defined a function to convert a imblearn BalancedRandomForestClassifier to pmml by simply overriding all attributes of an unfitted sklearn RandomForestClassifier

Looks like imblearn.ensemble.`BalancedRandomForestClassifier` is a direct subclass of `sklearn.ensemble.RandomForestClassifier`:
https://github.com/scikit-learn-contrib/imbalanced-learn/blob/master/imblearn/ensemble/_forest.py#L81

If so, then the default random forest converter should be able to process imblearn's random forests right out of the box.

The quick way to test the above hypothesis is to add a line `imblearn.ensemble._forest.BalancedRandomForestClassifier = sklearn.ensemble.forest.ForestClassifier` into the converter mapper file `META-INF/sklearn2pmml.properties`: https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/resources/META-INF/sklearn2pmml.properties

**Comment by vruusmann** [comment]
> The quick way to test the above hypothesis is to add a line into the converter mapper file.

It's fairly difficult to modify SkLearn2PMML built-in converter mapper file.

However, it's possible to create a SkLearn2PMML package plugin that contains a custom converter mapper file (and nothing else), and append it to the SkLearn2PMML classpath using the `user_classpath` argument:

```python
pipeline = PMMLPipeline([..])
pipeline.fit(X, y)

sklearn2pmml(pipeline, "imblearn-pipeline.pmml", user_classpath = "/path/to/imblearn.jar")
```

I've attached a fully-functional demo `imblearn.jar` file (please remove the `.txt` filename extension, which was added to work around GitHub limitations).

Would be nice to hear if this quick fix works or not (I've coded it but not run it, because I don't have an up-to-date imblearn package installed).

[imblearn.jar.txt](https://github.com/jpmml/sklearn2pmml/files/5350348/imblearn.jar.txt)

**Comment by vruusmann** [comment]
For JPMML's perspective of Imbalanced-Learn, see https://openscoring.io/blog/2020/10/24/converting_sklearn_imblearn_pipeline_pmml/
