### ISSUE TITLE
PMML 4.2 compatible

### ISSUE THREAD

**Issue by mrshanth** [jpmml/sklearn2pmml#25]
The following link which had the PMML 4.2 compatible version, provided in the Google groups is not available anymore:
```https://github.com/jpmml/sklearn2pmml.git@8304e7466c9138a081aa09ca1a3af5c74c8df150```

I tried installing the older version of sklearn2pmml from local directory. I tried versions which were committed before Aug 2016, but installation is not proper. PMMLPipeline is not available.
```
from sklearn2pmml import P 
pkg_resources platform
```

The other versions also have the same issue. Kindly, suggest a solution.

**Comment by vruusmann** [comment]
Commit identifiers got updated in early February 2017 when tagging all `sklearn2pmml` package versions. So, let's talk in terms of release versions (see https://github.com/jpmml/sklearn2pmml/releases), not commit identifiers from now on.

To produce PMML 4.2, you must use a `sklearn2pmml` package version that includes JPMML-SkLearn version `1.0-SNAPSHOT` dependency; all JPMML-SkLearn version 1.0.X, 1.1.X and 1.2.X versions are already producing PMML 4.3.

The last such `sklearn2pmml` package is version 0.9.7:
https://github.com/jpmml/sklearn2pmml/releases/tag/0.9.7

You should be able to get it like this:
```
pip install --user git+https://github.com/jpmml/sklearn2pmml.git@0.9.7
```

**Comment by vruusmann** [comment]
> PMMLPipeline is not available.

Python class `sklearn2pmml.PMMLPipeline` was introduced in `sklearn2pmml` version 0.14.0.

If you're using a legacy version of `sklearn2pmml` package, then you must consult the corresponding README.md file for usage instructions.

**Comment by mrshanth** [comment]
Thanks.

**Comment by liaicheng** [comment]
which release for PMML 4.2 is the lastest?
