### ISSUE TITLE
sklearn2pmml is not scalable, it takes a lot of time to run ...

### ISSUE THREAD

**Issue by sharonzagh** [jpmml/sklearn2pmml#251]
Before I did the update of the version of the sklearn2pmml from 0.61.0 to 0.62.0 the following code didn't work 
Now it is running but it takes a lot of time even though the dataset I am using has a shape of (1000,) 

```
def add_expression(mapper, input_fields: list, expression: str, alias: str):
    feature_defs =  [
        (col , [ExpressionTransformer(expression), 
                Alias(CastTransformer(float), name=alias)
               ],
        {'alias': alias}
    )
        for col in input_fields
    ]
    mapper.features = mapper.features + feature_defs

recorder= DataFrameMapper([])

str_expression1 = ( 1.076 if X[0] == 'missing' else ( 0.016 if X[0] == '0' else ( 0.0 if X[0] == '1' else (0.5))))

str_expression2 = ( 10.061 if X[0] == '0' else ( 5.81 if X[0] == '2' else ( 4.587 if X[0] == '1' else ( 3.594 if X[0] == '8' else ( 2.807 if X[0] == '3' else ( 2.381 if X[0] == '10' else ( 2.078 if X[0] == '5' else ( 1.958 if X[0] == '9' else ( 0.917 if X[0] == 'missing' else ( 0.44 if X[0] == '4' else ( 0.414 if X[0] == '6' else ( 0.0 if X[0] == '17' else ( 0.0 if X[0] == '18' else ( 0.0 if X[0] == '90' else ( 0.0 if X[0] == '11' else ( 0.0 if X[0] == '88' else ( 0.0 if X[0] == '12' else (0.5))))))))))))))))))

add_expression(recorder,[[feature1]], str_expression1,feature1_new)
add_expression(recorder,[[feature2]], str_expression2,feature2_new)

pipeline = PMMLPipeline([
    ("mapper", recorder),
    ("select", ColumnTransformer([("passthrough", "passthrough", cat_cols2)], remainder='drop')),
    ("classifier", XGBClassifier())
])
```

NB: with only add the feature of str_expression1, it works and run 
when we add the feature of str_expression2, it doesn't print any error but it is running for hours .. 

Do you have a workaround of this issue maybe ?

**Comment by vruusmann** [comment]
The solution is to choose a proper transformation type.

The goal is to perform a lookup table operation? Right now you're using `sklearn2pmml.preprocessing.ExpressionTransformer` with a massive hand-coded if-else statement. However, you should be using `sklearn2pmml.preprocessing.LookupTransformer` with a dict argument instead.

It's Python interpreter that is having difficulty `eval()`-ing this massive hand-coded if-else statement. The performance of the SkLearn2PMML/JPMML-SkLearn stack is 100% OK.
