### ISSUE TITLE
model's explaination of pmml

### ISSUE THREAD

**Issue by binxixi** [jpmml/sklearn2pmml#254]
In the example, there are three models(PCA,KBest,LR) in the parameters of pipeline. 
Q1 :   So which model is ultimately transformed to pmml ,   and how to distinguish when I use pmml ?
Q2 :   We can get result of pipeline.score . it means accurancy or something else ?

Hope for your help  and  thanks a lot.

pipeline = PMMLPipeline([
	("mapper", DataFrameMapper([
		(["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"], [ContinuousDomain(), SimpleImputer()])
	])),
	**("pca", PCA(n_components = 3)),
	("selector", SelectKBest(k = 2)),
	("classifier", LogisticRegression(multi_class = "ovr"))**
])
pipeline.fit(iris_X, iris_y)
pipeline.verify(iris_X.sample(n = 15))

from sklearn2pmml import sklearn2pmml

sklearn2pmml(pipeline, "LogisticRegressionIris.pmml", with_repr = True)

**Comment by vruusmann** [comment]
> In the example, there are three models(PCA,KBest,LR) in the parameters of pipeline.

Let's be clear about terminology:

- `PCA` - (feature-) transformer. Synthesizes new columns (based on existing columns) into the data frame.
- `KBest` - (feature-) selector. Reduces the number of columns in the data frame.
- `LR` - classification model (aka classifier). Approximates the function between features and the target.

> Q1 : So which model is ultimately transformed to pmml , and how to distinguish when I use pmml ?

All pipeline steps that are needed for making a prediction are converted to PMML. The converter knows what to do, there is no need to assist it or review its work.

> Q2 : We can get result of pipeline.score . it means accurancy or something else ?

SkLean2PMML pipelines extends standard Scikit-Learn pipelines. Therefore, `sklearn2pmml.pipeline.PMMLPipeline` score has exactly the same meaning/interpretation as `sklearn.pipeline.Pipeline` score.

You should loop up the answer from Scikit-Learn documentation yourself.
