### ISSUE TITLE
DateTimeDomain Issue

### ISSUE THREAD

**Issue by pmmlsavvy** [jpmml/sklearn2pmml#256]
I would like to declare a datetime feature when I build the PMML using sklearn2PMML.
As advised, I use the DateTimeDomain() decorator as the first section of the recorder. I then get a "ravel is not a function" error from pandas, in the file util.py, line 25.
Digging into the util.py code of Sklearn2PMML, I can see that in the function flat_transform, the variable X is a pandas dataframe the first time it's being called. Therefore I updated it to first transform the object to a numpy (to_numpy() - in case it's a pandas object). The program is then able to run and the PMML thus generates the PMML file as expected.

Can you please advise?
Is this a correct fix?

**Comment by vruusmann** [comment]
> Digging into the util.py code of Sklearn2PMML, I can see that in the function flat_transform, the variable X is a pandas dataframe the first time it's being called.

The `sklearn2pmml.util.flat_transform(X, func)` utility function is supposed to operate on "homogeneous" data matrices only.

Pandas' `DataFrame` represents an "hetereogeneous" data matrix. It is not expected to be raveled to a 1D array, and then reshaped back to a 2D array.

In that sense, the error message is on point.

> Is this a correct fix?

If it fixes your issue, then it is a right fix for you.

> Can you please advise?

I would advise to decorate columns one by one. In that case, the `DateTimeDomain` decorator class would be seeing a one-column data matrix at a time, and it wouldn't need to mess with ravel/reshape at all.

I'm actually surprised that this error is even possible. I had the impression that `DataFrameMapper` always passes a Numpy array to the mapped transformers.

**Comment by MC55652** [comment]
Thank you for your reply.
I tried to decorate the column one by one, as you advised, and it sort out the ravel issue.
The new problem is in the function to_pydatetime in the util.py file, where the function pandas.to_datetime convert to series and then the floor function is not working. 
For technical reasons, we can't edit the code in production environment. Is it possible to change the code in a new version?

**Comment by vruusmann** [comment]
> The new problem is in the function to_pydatetime in the util.py file, where the function pandas.to_datetime convert to series and then the floor function is not working.

A reproducible code example?

According to the above comment, it appears that the `sklearn2pmml.util.to_pydatetime(X, dtype)` utility function is not working at all (all code paths start with `Xt = pandas.to_datetime(X)` and end with `Xt.floor(str)`).

**Comment by MC55652** [comment]
This is an exampled code:

    recorder = DataFrameMapper([], input_df=True)

    def add_date_domain(mapper, features: list):
        feature_defs = [
            (col, [DateTimeDomain()]) for col in features
        ]
        mapper.features = mapper.features + feature_defs


    add_date_domain(recorder, dates_with_time)

    recorder.df_out = True
    X_train_pmml = recorder.fit_transform(crude_df,y_train)

**Comment by vruusmann** [comment]
> This is an exampled code:

How do I execute this code to see the claimed error?

**Comment by vruusmann** [comment]
Consider the following example:

```python
from sklearn_pandas import DataFrameMapper
from sklearn2pmml.decoration import DateDomain, DateTimeDomain

import pandas

X = pandas.DataFrame([["2020-11-01T09:00:01Z"], ["2020-11-02T10:00:01Z"], ["2020-11-03T11:00:01Z"]], columns = ["timestamp"])
print(X)

mapper = DataFrameMapper([
	("timestamp", DateDomain()),
	("timestamp", DateTimeDomain())
])
Xt = mapper.fit_transform(X)
print(Xt)
```

Works fine on my computer.

**Comment by vruusmann** [comment]
Exact duplicate of #226
