### ISSUE TITLE
Counting the number of words with PMML

### ISSUE THREAD

**Issue by sharonzagh** [jpmml/sklearn2pmml#259]
Hi, 
I want to count the number of words with PMML 

Here is the code: 
```
df_X = pd.DataFrame()
df_X['Color'] = ['blue','red','yellow','black']
y_X = [1,0,0,1]

mapper = DataFrameMapper([
   (['Color'], [CategoricalDomain(),  ExpressionTransformer("numpy.size(X[0])", dtype = numpy.float64),
])
pipeline= PMMLPipeline([
    ("mapper", mapper)
    ,("classifier", XGBClassifier())
])
pipeline2.fit(df_X, y_X)
sklearn2pmml(pipeline2, "pmml_model.pmml")
```

Here is the error I get: 
```
Standard output is empty
Standard error:
Dec 01, 2020 5:34:35 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Dec 01, 2020 5:34:35 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 24 ms.
Dec 01, 2020 5:34:35 PM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
Dec 01, 2020 5:34:35 PM sklearn2pmml.pipeline.PMMLPipeline initTargetFields
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Dec 01, 2020 5:34:35 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: size
... 
```
Could you assist ? 
Regards

**Comment by vruusmann** [comment]
> I want to count the number of words with PMML

You probably can't do it using the `numpy.size` function?

The intent of the above example is not very clear to me. In your example code, you can only write down the feature transformation part, there's no need for a full-blown pipeline (with a dummy XGBoost estimator as the final step).

For example:
```python
import pandas
X = pandas.DataFrame()
X['Color'] = ['blue','red','yellow','black']

import numpy
numpy.size(X)
```

This example prints `4`, which is the number of rows in the data frame.

**Comment by vruusmann** [comment]
In other words, `numpy.size(X[0])` prints you the number of cells in the first column of a data frame.

**Comment by sharonzagh** [comment]
What I want to compute is the number of word for each row, the output here should be [1,1,1,1]  
and the output should be [2,3,1,1] for X['word'] = ['Hello miss','I am new','hi','bye']

**Comment by vruusmann** [comment]
First, show me how you'd do it in pure Python.

This won't work:
```python
import numpy
numpy.size('I am new')
```

**Comment by vruusmann** [comment]
Can you find a way to count words in a sentence using Python regular expressions?

**Comment by sharonzagh** [comment]
numpy.size('I am new'.split(' '))

**Comment by vruusmann** [comment]
The "string split" function is not part of PMML built-in functions. Hence the new question - can you split/count using Python regular expressions?

**Comment by sharonzagh** [comment]
you mean re.split(" ", 'I am new') ?

**Comment by vruusmann** [comment]
> you mean re.split(" ", 'I am new') ?

That would be too easy.

The only tools that you have are re.matches and `re.sub` and `re.search`:
https://docs.python.org/3/library/re.html

I'm sure somebody at StackOverflow could do it.

**Comment by vruusmann** [comment]
Here's an idea: take the input string, and perform a "replace all" operation that replaces all variable-length words with a fixed-length character. Then, the number of words can be measured as the length of the resulting string!

For example: replacing all words with a character `1`. In such a case, the sentence `I am new` becomes `111`. The number of words is the length of this string - 3.

It's not very elegant, but it should be fairly robust.

**Comment by sharonzagh** [comment]
Thanks !

**Comment by vruusmann** [comment]
> For example: replacing all words with a character 1. In such a case, the sentence I am new becomes 111.

You'd probably need to do the replacement in two steps - first replace words with `"1"`, and then replace the whitespace between them with an empty string `""`.

The replacements can be made using `sklearn2pmml.preprocessing.ReplaceTransformer`.

General pattern:
```python
mapper = DataFrameMapper([
  (["Color"], [ReplaceTransformer(/*replace words with 1*/), ReplaceTransformer(/* replace whitespace with an empty string*/), ExpressionTransformer("len(X[0])")])
])
```

If you figure out appropriate Python regular expressions, then please post them here as well. Your future self/team members might come looking after this stuff one day.
