### ISSUE TITLE
how to save a 4.3 version pmml model?

### ISSUE THREAD

**Issue by topxxuki** [jpmml/sklearn2pmml#260]
```
import pandas
from sklearn.datasets import load_iris
iris_df = load_iris()
iris_X = iris_df.data
iris_y = iris_df.target
from sklearn.tree import DecisionTreeClassifier
from sklearn2pmml.pipeline import PMMLPipeline
pipeline = PMMLPipeline([
        ("classifier", DecisionTreeClassifier())
        ])
pipeline.fit(iris_X, iris_y)
from sklearn2pmml import sklearn2pmml
sklearn2pmml(pipeline, "DecisionTreeIris.pmml", with_repr = True)
```

I get a model with 4.4 version
![image](https://user-images.githubusercontent.com/18697846/104281294-41eb0800-54e8-11eb-8758-14fc5ea87918.png)

actually I want to save a model in 4.3,can I?

**Comment by vruusmann** [comment]
The switch from PMML 4.3 schema version to 4.4 schema version happened in ~may 2020. Therefore, if you want to generate PMML 4.3 schema version documents, then you should use converter tools and libraries that were released before that time.

Talking about the SkLearn2PMML/JPMML-SkLearn stack specifically:

- PMML 4.3: Last compatible release SkLearn2PMML 0.56.2 which is based on JPMML-SkLearn 1.5.38.
- PMML 4.4: First compatible release SkLearn2PMML 0.57.0, which is based on JPMML-SkLearn 1.6.0.

So, looks like you should install SkLearn2PMML version 0.56.2 right now. You shall miss all newer features and functionality, but that's that.

Alternatively, you may use the JPMML-Translator application to convert PMML documents between different schema versions and data formats (XML, JSON, YAML, ProtoBuf, binary). This is a commercial offering - please contact me directly for more details.

**Comment by AraceliAL** [comment]
Good afternoon! I would like to do the same thing. Save PMML model into version 4.3 instead of 4.4. The problem is that when I downgrade the sklearn2pmml library to version 0.56, then the following error arises:

`AttributeError: 'PMMLPipeline' object has no attribute 'apply_transformer'`

Just like indicated here: https://stackoverflow.com/questions/69730527/downgrading-pmml-4-4-to-4-3-version

Thanks a lot in advance!! :)
