### ISSUE TITLE
Support for older version of pmml files

### ISSUE THREAD

**Issue by mcoplan11** [jpmml/sklearn2pmml#262]
There should be an additional parameter to specify the version of pmml file used to export.

for example,

`sklearn2pmml(pipeline, "logmodel_readmission_2.pmml" , version=4.3)
`

**Comment by vruusmann** [comment]
Closing as exact duplicate of https://github.com/jpmml/sklearn2pmml/issues/262

**Comment by vruusmann** [comment]
> There should be an additional parameter to specify the version of pmml file used to export.

Why would I want to create legacy PMML schema version documents?

Who is going tto pay for their development and maintenance?
