### ISSUE TITLE
Multiple actions on the same feature

### ISSUE THREAD

**Issue by MC55652** [jpmml/sklearn2pmml#264]
Hi,

Can you please advise on the following issue.
I'd like to conduct multiple actions on the same string feature.
More specifically, I need to engineer a feature as a substring of a given feature, subject to a condition on another substring.

I've tried the following approaches:
1. Use the [:] operator inside the expresssion transformer (as it's part of Numpy's universal operators). However I get an error upon creating the PMML, see here:
Code:

def hourOfDate(mapper: DataFrameMapper, dateColumn: str):
    '''
    Determines the hour value of a datetime.

    '''
    
    mapper.features = mapper.features + [(
        [dateColumn],
        [as_date( result_with_datetime = False),
         CastTransformer(str),
         ExpressionTransformer("'-999.01' if (X[0][0:4]=='1900') else X[0][11:13]"),
         Alias(CastTransformer(float), name=f"{dateColumn}_hour")
         ], {'alias': f"{dateColumn}_hour"}
    )]

Error:

> SEVERE: Failed to convert
java.lang.IllegalArgumentException: Python expression ''-999.01' if (X[0][0:4]=='1900') else X[0][11:13]' is either invalid or not supported

2. A two-steps approach of first duplicating the feature, then trying to refer to both its copies upon engineering the new feature. However the copied feature isn't available for the second step I just described.
Code:

def hourOfDate(mapper: DataFrameMapper, dateColumn: str):
    '''
    Determines the hour value of a datetime.

    '''
    mapper.features = mapper.features + [(
        [dateColumn],[
         Alias(CastTransformer(str), name=f"{dateColumn}2")
         ], {'alias': f"{dateColumn}2"}
    )]
    
    mapper.features = mapper.features + [(
        [dateColumn, f"{dateColumn}2"],
        [ColumnTransformer([
                ('dateColumn', [as_date(result_with_datetime = False),  CastTransformer(str), SubstringTransformer(0, 4)], [0]),
               (f'{dateColumn}2', [as_date(result_with_datetime = False),  CastTransformer(str), SubstringTransformer(11, 13)], [1]),
            ]),
         ExpressionTransformer("-999.01 if (X[0]== '1900') else X[1]"),
         Alias(CastTransformer(float), name=f"{dateColumn}_hour")
         ], {'alias': f"{dateColumn}_hour"}
    )]

Error:

> KeyError: "['dateoffirstt2'] not in index"

Thanks.

**Comment by vruusmann** [comment]
@MC55652 

Can you please:

1. Report one bug/feature request per one GitHub issue.
2. Use a meaningful issue title.
3. When reporting a Java/Python exceptions, then provide a few lines of exception stack trace. Right now I can see the error message, but I don't see where it was raised. Exception stack traces are very meaningful information. 
4. Format your code example properly.
5. Provide a small self-contained reproducible test case that I could copy&paste into Python console, and run it immediately.
6. Tell me more about your environment. At minimum, the SkLearn2PMML package version.

**Comment by vruusmann** [comment]
Regarding the first issue ("Python expression ... is either invalid or not supported") - you're trying to use double array indexing syntax, where the first array dimension is the feature column index, and the second array dimension is the substring function.

Double array indexing syntax is supported since JPMML-Python 1.0.8 (https://github.com/jpmml/jpmml-python/commit/fcfde900cfd631c90a5ceb79adeb27f38b8f484a).

Please upgrade your SkLearn2PMML package version to the latest, and it will be resolved.

**Comment by vruusmann** [comment]
Regarding the second issue ("KeyError: ['dateoffirstt2'] not in index") - it's a generic Numpy array indexing error. I don't see how it's related to SkLearn2PMML package.

Your code example does not define or reference the specified column ("dateoffirstt2").

Sorry, I have no idea what's going on in your secret application code.

**Comment by vruusmann** [comment]
@MC55652 If you need to calculate "hour of day" (based on a datetime), then consider using the `dateSecondsSinceMidnight` built-in function (http://dmg.org/pmml/v4-4/BuiltinFunctions.html#datesecondssincemidnight).

Take this value, divide by `60 * 60`, and you'll have the right answer.

This built-in function is implemented as the `sklearn2pmml.preprocessing.SecondsSinceMidnight` transformer:
https://github.com/jpmml/sklearn2pmml/blob/0.66.1/sklearn2pmml/preprocessing/__init__.py#L131-L147
