### ISSUE TITLE
Error message: "java.lang.IllegalArgumentException: Attribute 'xgboost.sklearn.XGBClassifier._le' not set"

### ISSUE THREAD

**Issue by Sam-Ch** [jpmml/sklearn2pmml#265]
Hi vruusmann,

I got the following IllegalArgumentException when I tried to run this piece of code to generate the PMML file in a, which was able to run through previously. There was some messiness with the package versions that I was playing around with (changing versions), and then no matter reverting back to the version that was able to run through or installing the newest version no longer worked. And the same exception occurred in both cases.

Packages' versions that were supposed to work are:
```
python: 3.6.10
sklearn: 0.23.2
sklearn2pmml: 0.63.1
joblib: 1.0.1
sklearn_pandas: 2.0.2
pandas: 1.1.4
numpy: 1.19.3
java: 1.8.0_191
```

The code:
```
X_pmml = raw_data_pmml.loc[:,~raw_data_pmml.columns.isin(rm_list)]    #removing useless columns
X_pmml = X_pmml.select_dtypes(exclude=['datetime'])   #remove datetime format columns
X_pmml = hf.cleanupInfNABool(X_pmml)    #remove Infs and NAs & convert bool to numeric (self-created helper function)

X_pmml = X_pmml.loc[:, ~X_pmml.columns.isin(['is_origination'])]    #remove target variable
y_pmml = raw_data_pmml['is_origination'].astype("int64")   #create target variable

#change object columns to strings
columns = X_pmml.select_dtypes(include=['object']).columns.values.tolist()
for col in columns:
    X_pmml = X_pmml.astype({col: str})

#create the mapper
cat_columns = X_pmml.select_dtypes(include=['object']).columns.values.tolist()
feature_defs = [(col_name, [CategoricalDomain(invalid_value_treatment = "as_is"),LabelBinarizer()]) for col_name in cat_columns]
num_columns = X_pmml.select_dtypes(include=['float64', 'int64']).columns.values.tolist()
feature_defs.append((num_columns,None))
mapper = DataFrameMapper(feature_defs)

#set the classifier
classifier = XGBClassifier(n_estimators = int(optimizer.max['params']['n_estimators']), n_jobs = -1, 
                           subsample = round(optimizer.max['params']['subsample'],2), 
                           reg_lambda = round(optimizer.max['params']['reg_lambda'],2), 
                           reg_alpha = round(optimizer.max['params']['reg_alpha'],2),
                           min_child_weight = round(optimizer.max['params']['min_child_weight'],2),
                           max_depth = int(optimizer.max['params']['max_depth']), 
                           learning_rate=round(optimizer.max['params']['learning_rate'],2),  
                           colsample_bytree = round(optimizer.max['params']['colsample_bytree'],2), 
                           #colsample_bylevel = optimizer.max['params']['colsample_bylevel'],
                           eval_metric = ['error','auc'],
                           use_label_encoder=False
                           )

#create pipeline
final_model_pipeline = PMMLPipeline([
    ("mapper", mapper),
    ("classifier", classifier)
])

#fit the model
final_model_pipeline.fit(X_pmml, y_pmml)
print('Fitted pipeline')
final_model_pipeline.target_fields = np.array(["is_origination"])

#final model output
sklearn2pmml(final_model_pipeline, "xgb_model_fit_conv_cfi_ccr_caa_" + str(version) + ".pmml", with_repr = True, debug=True)
print('pmml exported')

```

I think the error happened during the last line of code. The error messages are:
```Standard output is empty
Standard error:
Feb 22, 2021 3:29:44 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Feb 22, 2021 3:29:44 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 450 ms.
Feb 22, 2021 3:29:44 PM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
Feb 22, 2021 3:29:44 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: Attribute 'xgboost.sklearn.XGBClassifier._le' not set
	at org.jpmml.python.PythonObject.get(PythonObject.java:69)
	at sklearn.LabelEncoderClassifier.getLabelEncoder(LabelEncoderClassifier.java:40)
	at sklearn.LabelEncoderClassifier.getClasses(LabelEncoderClassifier.java:34)
	at sklearn.ClassifierUtil.getClasses(ClassifierUtil.java:32)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:135)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)

Exception in thread "main" java.lang.IllegalArgumentException: Attribute 'xgboost.sklearn.XGBClassifier._le' not set
	at org.jpmml.python.PythonObject.get(PythonObject.java:69)
	at sklearn.LabelEncoderClassifier.getLabelEncoder(LabelEncoderClassifier.java:40)
	at sklearn.LabelEncoderClassifier.getClasses(LabelEncoderClassifier.java:34)
	at sklearn.ClassifierUtil.getClasses(ClassifierUtil.java:32)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:135)
	at org.jpmml.sklearn.Main.run(Main.java:233)
	at org.jpmml.sklearn.Main.main(Main.java:151)
```
It also follows with "The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams"

I tried to search online regarding this specific error message (Attribute 'xgboost.sklearn.XGBClassifier._le' not set) and did not find other people meeting this exact case. The closest case I had found was either "'xgboost.sklearn.XGBClassifier._le' has an unsupported value" or "some other variable not set". Given that the code was working perfectly fine, I doubt it might be the version issue. However, I couldn't figure it out after few days of debugging. Is there any possibility that you might know where I went wrong?

Thanks in advance!

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException: Attribute 'xgboost.sklearn.XGBClassifier._le' not set

The converter is complaining that the fitted `XGBClassifier` object does not contain a `_le` attribute (list of target categories, encoded as `sklearn.preprocessing.LabelEncoder`).

In your Python code you're explicitly disabling this attribute:
```python
classifier = XGBClassifier(...,
  # THIS!
  use_label_encoder=False
)
```

Given this information, I believe you'll be able to figure out yourself how to make the `XGBClassifier._le` attribute come alive.

> sklearn2pmml: 0.63.1

Time to upgrade to 0.66.1

**Comment by vruusmann** [comment]
Keeping this issue open as a reminder to check how `XGBClassifier` stores target categories when the user disables the `_le` attribute.

Perhaps it falls back to the default (Scikit-Learn style-) `classes_` attribute.

**Comment by Sam-Ch** [comment]
Thanks for the quick response! Now I remembered I deliberately added 'use_label_encoder=False' because at some point I received a warning like this:
```
UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
```
Since I already treated my y as integers, I just added this parameter. Then the warning message disappeared.

Now I've removed that line of code (hope this make the XGBClassifier._le attribute come alive) but this time the same exception generated as in https://github.com/jpmml/jpmml-xgboost/issues/54
My xgboost version is 1.3.3, and I saw you commented, "Please note that XGBoost is still able to produce "proprietary binary" model files. As a quick workaround, you should order XGBoost to use it (instead of JSON)." Would you mind explaining it a little bit more? 

Appreciate your time and answer!

**Comment by vruusmann** [comment]
I'm currently using XGBoost 1.2.1 with Scikit-Learn 0.24.1, and specifying `XGBClassifier(use_label_encoder = False)` doesn't seem to have any visible effect - the `XGBClasifier._le` attribute is set regardless.

My `XGBClassifier` object seems to have both `_le` and `classes_` attributes available. So, the new approach is to try `_le` first and if not specified, fall back to `_classes`.

> "Please note that XGBoost is still able to produce "proprietary binary" model files. As a quick workaround, you should order XGBoost to use it (instead of JSON)."

See the source code of `XGBClassifier` for possible workarounds.

The interesting thing is that XGBoost 1.3.X R package defaults to binary model serialization, whereas the Scikit-Learn package defaults to JSON.

My advice today would be to downgrade to some XGBoost 1.2.X Scikit-Learn package.

**Comment by Sam-Ch** [comment]
It worked! After I reverted back to XGBoost 1.2.1 it all ran through. Thanks for your suggestions and patience!
