### ISSUE TITLE
PMMLPipeline memory

### ISSUE THREAD

**Issue by lqrz** [jpmml/sklearn2pmml#267]
Hi, is there an equivalent functionality to sklearn.pipeline.Pipeline's `memory` attribute?

Say, I have many preprocessing steps in the pipeline, and cause Im feeding an eval_set to my model (e.g. i'm using it's early stopping capability), that would mean I need to: 1) fit the preprocessors with the training data; 2) transform the validation holdout; 3) fit the pmml pipeline with the training (which will cause the preprocessors to be fit once again).

---
Example:

```python

# data
df_data_train_x, ds_data_train_y = ...
df_data_valid_x, ds_data_valid_y = ...
featurer = ...

# instantiate model
model_params = {...}
model = LGBMClassifier(**model_params)

# instantiate preprocessing pipeline
transforms = [...]
preprocessing_pipeline = DataFrameMapper(
    features=transforms,
    sparse=False,
    df_out=True,
    input_df=True,
    drop_cols=None
)

# transform validation set
_ = preprocessing_pipeline.fit(df_data_train_x, ds_data_train_y)
df_data_valid_x_encoded = preprocessing_pipeline.transform(df_data_valid_x)


# instantiate PMMLPipeline
pipeline = PMMLPipeline([
    ('preprocess', preprocessing_pipeline),
    ('classifier', model)
])

# fit PMMLPipeline (preprocessors + model)
_ = pipeline.fit(df_data_train_x, ds_data_train_y,
                 classifier__eval_set=(df_data_valid_x_encoded, ds_data_valid_y),
                 classifier__feature_name=featurer.get_transformed_all(),
                 classifier__categorical_feature=featurer.get_transformed_categorical())
```

**Comment by vruusmann** [comment]
The `sklearn2pmml.pipeline.PMMLPipeline` class is a direct subclass of the `sklearn.pipeline.Pipeline` class. As such, it should be able to support all standard functionality.

The `PMMLPipeline` constructor doesn't (re-)declare the `memory` attribute:
https://github.com/jpmml/sklearn2pmml/blob/0.66.1/sklearn2pmml/pipeline/__init__.py#L47-L54

But it would be trivial to add there.

**Comment by vruusmann** [comment]
A workaround for benefitting from `sklearn.pipeline.Pipeline` extra parameters - fit a `Pipeline` directly, and then wrap it inside a `PMMLPipeline` right before the conversion:

``` python
from sklearn2pmml import make_pmml_pipeline

pipeline = Pipeline([..], memory = ..., verbose = True)
pipeline.fit(X, y)

pmml_pipeline = make_pmml_pipeline(pipeline, active_fields = [...], target_fields = [...])
sklearn2pmml(pmml_pipeline, "pipeline.pmml")
```
