### ISSUE TITLE
Convenience method for transforming existing estimator objects to `PMMLPipeline` objects

### ISSUE THREAD

**Issue by rossmeissl** [jpmml/sklearn2pmml#27]
I have about a hundred sklearn classifiers (each stored pickled, if that matters) that I'd like to export to PMML. How can I apply this tool to an existing classifier, versus wrapping a new training process?

**Comment by vruusmann** [comment]
Simply wrap your pre-trained estimator object into a `sklearn.PMMLPipeline` object:
```Python
estimator = pickle.load(...)
pipeline = PMMLPipeline([
  ("pretrained-estimator", estimator)
])

sklearn2pmml(pipeline, "pretrained-estimator.pmml")
```

The main problem with using pre-trained estimators is that the resulting PMML document will be devoid of any supporting (meta-)information such as column names or data types. All input fields will be called `x{index}`, and they will be of some numeric data type (typically, `float` for decision tree-based model types, and `double` for all other model types).

If you have some knowledge about the "schema" of your pre-trained models, then it's possible to enhance the `sklearn2pmml.PMMLPipeline` object accordingly:
```Python
dataframemapper = pickle.load(...)
pipeline = PMMLPIpeline([
  ("pretrained-dataframemapper", dataframemapper),
  ("pretrained-estimator", estimator)
])
```
or
```Python
pipeline = PMMLPipeline([
  ("pretrained_estimator", estimator)
])
pipeline.target_field = "Species"
pipeline.active_fields = numpy.array(["Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width"])
```

**Comment by rossmeissl** [comment]
Thanks @vruusmann!

**Comment by vruusmann** [comment]
It would be nice to have utility method(s) for doing this kind of wrapping work. Furthermore, it could happen silently inside the `sklearn2pmml` function itself.

The underlying JPMML-SkLearn library has no problem accepting "raw" estimator objects:
https://github.com/jpmml/jpmml-sklearn/commit/7b258cdc3c2571424b55b003149811e8199f25d7

So, this limitation exists only in the `sklearn2pmml` package, in the form of the following `isinstance` check:
https://github.com/jpmml/sklearn2pmml/blob/master/sklearn2pmml/__init__.py#L128
