### ISSUE TITLE
Issue while generating PMML 

### ISSUE THREAD

**Issue by sachine123** [jpmml/sklearn2pmml#271]
Hi,

I am not able to generate PMML file while using OHE features, It's not picking the feature while calling following function

calculate_ohe_features(recorder,raw_features,final_features_for_model)
IN: recorder.features
o/p: [(['customEvents_partyState'],
  [Pipeline(steps=[('casttransformer', CastTransformer(dtype=<class 'str'>)),
                   ('alias',
                    Alias(name='to_lower32',
                          transformer=StringNormalizer(function='lowercase')))]),
   ExpressionTransformer(expr=" 1 if X[0] == 'OH' else 0"),
   Alias(name='customEvents_partyState_OH',
         transformer=CastTransformer(dtype=<class 'float'>))],
  {'alias': 'customEvents_partyState_OH'})]

attached error:

![image](https://user-images.githubusercontent.com/80760071/111307412-6b0e4d00-867f-11eb-9e09-9f1035d33488.png)
![image](https://user-images.githubusercontent.com/80760071/111307478-837e6780-867f-11eb-8206-b9a5fac4b59a.png)

**Comment by vruusmann** [comment]
The `generate_pmml(..)` function **_IS NOT_** part of the SkLearn2PMML package.

Please report your issue to the person/organization that authored it.
