### ISSUE TITLE
variable divide transformer in sklearn2pmml 

### ISSUE THREAD

**Issue by Lving** [jpmml/sklearn2pmml#273]
there are mean, sum, and so on , where there is not devision?

**Comment by vruusmann** [comment]
> there are mean, sum, and so on , where there is not devision?

The April fool's day is tomorrow.

However, if this is a serious question, then please add a valid code example about what you're trying to achieve. Division involving `n > 2` operands doesn't make sense to me.

**Comment by Lving** [comment]
thank you for answer me and apologise for that
below is my code
```
data_x = pd.DataFrame({
    # 'pet': ['cat', 'dog', 'dog', 'fish', 'cat', 'dog', 'cat', 'fish'], 
    'children': [4., 6, 3, 3, 2, 3, 5, 4],
    'salary':   [90., 24, 44, 27, 32, 59, 36, 27],})
data_y = pd.DataFrame({'y': [1, 0,0,0,0,1,0,1]})

class DevisionTransformer(BaseEstimator, TransformerMixin):
    def __init__(self):
        pass
    
    def fit(self, X, y=None):
        return self

    def transform(self, X):
        if hasattr(X, 'values'):
            X = X.values
        return np.divide(X[:,0], X[:,1])

mapper_df = DataFrameMapper([
    ('salary', None),
    ('children', None),
    (['salary', 'children'], DevisionTransformer()),
])

pipeline = PMMLPipeline([
    ('mapper', mapper_df),
    ('lr', LinearRegression())
])

pipeline.fit(data_x, data_y.values.ravel())
op= pipeline.predict(data_x)
sklearn2pmml(pipeline, 'transformerTest.xml', with_repr=True)

```
i have known custom tansformer will be failed  in `sklearn2pmml`.  question is how can i archive two variables division with sklearn2pmml? could you please give me some advise?

**Comment by vruusmann** [comment]
> i have known custom tansformer will be failed in sklearn2pmml.

You can write a custom PMML converter in about three minutes. See the source code of existing converters for inspiration.

> how can i archive two variables division with sklearn2pmml?

Use the `sklearn2pmml.preprocessing.ExpressionTransformer` transformer, which applies a Python language expression to a dataset.

Try the following:

```python
from sklearn2pmml.preprocessing import ExpressionTransformer

mapper_df = DataFrameMapper([
    (['salary', 'children'], ExpressionTransformer("X[0] / X[1]"))
])
```

**Comment by Lving** [comment]
It works!!!! thank you so much!!!!!  @vruusmann
