### ISSUE TITLE
Getting error  while running sklearn2pmml 

### ISSUE THREAD

**Issue by sachinsinha620** [jpmml/sklearn2pmml#277]
I have created a test dataframe as test_df = pd.DataFrame({'col1' : ['012','023','034']}) 
Then created below function ,
def fetch_substr(mapper: DataFrameMapper, var_sub : str):
  
    
    mapper.features = mapper.features + [(
        [var_sub],
        [
         
         CastTransformer(str),
         
         ExpressionTransformer("X[0][0:2]"),
         Alias(CastTransformer(float), name=f"{var_sub}_str")
         ], {'alias': f"{var_sub}_str"}
    )]

fetch_substr(recorder , 'col1')

recorder.fit_transform is working successfully but I am getting error 'java.lang.IllegalArgumentException: Python expression 'X[0][0:2]' is either invalid or not supported' while running sklearn2pmml

Please suggest what is the issue with X[0][0:2]

**Comment by vruusmann** [comment]
> Please suggest what is the issue with X[0][0:2]

I'd suggest you to update your SkLearn2PMML package version to latest.

The following works just fine on my computer:
```python
mapper = DataFrameMapper([
	(["Age"], ExpressionTransformer("1 if X[0] > 30 else (0.5 if X[0] > 20 else 0)")),
	(["Education"], [ExpressionTransformer("X[0][0:1]"), LabelBinarizer()])
])
classifier = DecisionTreeClassifier()

pipeline = PMMLPipeline([
	("mapper", mapper),
	("classifier", classifier)
])
pipeline.fit(df, df["Adjusted"])
```
