### ISSUE TITLE
The JPMML-SkLearn conversion application has failed.

### ISSUE THREAD

**Issue by 123thm** [jpmml/sklearn2pmml#279]
Hi Villu,
I'm trying to create a pmml file from the sklearn model below.But I get an error.
this is my code:
```python
model = tree.DecisionTreeClassifier(criterion="entropy", random_state=1, max_depth=5)  
pipeline = PMMLPipeline([("classifier", model)])
model.fit(x_train, y_train)  
sklearn2pmml(pipeline, "DecisionTreeIris.pmml", with_repr=True, debug=True)
```

python: 3.6.10
sklearn: 0.23.2
sklearn2pmml: 0.71.1
joblib: 0.16.0
sklearn_pandas: 2.1.0
pandas: 1.1.5
numpy: 1.16.0
java: 1.8.0_211

this is error:
```
Standard error:
五月 04, 2021 11:02:51 上午 org.jpmml.sklearn.Main run
信息: Parsing PKL..
五月 04, 2021 11:02:51 上午 org.jpmml.sklearn.Main run
信息: Parsed PKL in 28 ms.
五月 04, 2021 11:02:51 上午 org.jpmml.sklearn.Main run
信息: Converting PKL to PMML..
五月 04, 2021 11:02:51 上午 sklearn2pmml.pipeline.PMMLPipeline initTargetFields
警告: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
五月 04, 2021 11:02:51 上午 org.jpmml.sklearn.Main run
严重: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: The value of 'sklearn.tree._classes.DecisionTreeClassifier.classes_' attribute (Java class java.util.ArrayList) is not a supported array type
	at org.jpmml.python.PythonObject.getArray(PythonObject.java:171)
	at sklearn.Classifier.getClasses(Classifier.java:43)
	at sklearn.ClassifierUtil.getClasses(ClassifierUtil.java:32)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:137)
	at org.jpmml.sklearn.Main.run(Main.java:244)
	at org.jpmml.sklearn.Main.main(Main.java:161)

Exception in thread "main" java.lang.IllegalArgumentException: The value of 'sklearn.tree._classes.DecisionTreeClassifier.classes_' attribute (Java class java.util.ArrayList) is not a supported array type
	at org.jpmml.python.PythonObject.getArray(PythonObject.java:171)
	at sklearn.Classifier.getClasses(Classifier.java:43)
	at sklearn.ClassifierUtil.getClasses(ClassifierUtil.java:32)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:137)
	at org.jpmml.sklearn.Main.run(Main.java:244)
	at org.jpmml.sklearn.Main.main(Main.java:161)

Preserved joblib dump file(s): /tmp/pipeline-4jcz0h6y.pkl.z
Traceback (most recent call last):
  File "/home/thm/PycharmProjects/code/_pro_code/9_DTmodel.py", line 99, in <module>
    sklearn2pmml(pipeline, "DecisionTreeIris.pmml", with_repr=True, debug=True)
  File "/home/thm/anaconda3/envs/tensorflow/lib/python3.6/site-packages/sklearn2pmml/__init__.py", line 258, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```
Could you please tell me how to solve this problem?
thank you.

**Comment by vruusmann** [comment]
The exception message suggest that the value of `model.classes_` attribute is expected to be a Numpy array, but is actually a Python list.

How is it possible? The `DecisionTreeClassifier` model type has very proper integration test coverage?

Sure, the JPMML-SkLearn library could be more liberal and accept both Numpy arrays and Python lists there.

I think that the value of `model.classes_` attribute is derived based on the label argument. What's the type of the `y_train` variable? Is it a Python list also? If so, change it to Numpy array.

For example, does the followong work?
```python
model.fit(x_train, numpy.asarray(y_train))
```

**Comment by vruusmann** [comment]
> I think that the value of model.classes_ attribute is derived based on the label argument.

Tested this idea by taking the DecisionTreeIris sample from the README file, and changing the type of `iris_y` variable to Python list (and several others):
https://github.com/jpmml/jpmml-sklearn#the-python-side-of-operations-1

Whatever the type of `iris_y`, the type of the `classifier.classes_` attribute is always Numpy array in my tests:

```python
iris_y = list(iris_y)
print(iris_y.__class__)

classifier = DecisionTreeClassifier(min_samples_leaf = 5)

pipeline = PMMLPipeline([
    ("classifier", classifier)
])
pipeline.fit(iris_X, iris_y)

print(classifier.classes_.__class__)
```

Closing this issue as not reproducible.

Once there is a complete example available (model with actual data), would be happy to analyze it again.

**Comment by 123thm** [comment]
I have solved this problem according to your method , thank you very much.

**Comment by vruusmann** [comment]
> I have solved this problem according to your method

You mean converting the `y_train` variable to a Numpy array?

If so, then what was the original type of `y_train`? Some standard Scikit-Learn/Pandas type, or some custom type?

```python
print(y_train.__class__)
```

**Comment by 123thm** [comment]
I printed&nbsp; the type of y_train as&nbsp; <class 'pandas.core.series.Series'&gt;
then, I use&nbsp; the following method to convert the type to the numpy.ndarray
y_train = np.array(y_train)
I found an example, it uses train_test_split() method to split y_train can be successfully saved as pmml. So, I print out its value and type：
train_label <class 'numpy.ndarray'&gt; 
&nbsp;[[4.]
&nbsp;[2.]
&nbsp;[3.]
&nbsp;...
&nbsp;[0.]
&nbsp;[4.]
&nbsp;[2.]]

But my own value is like this：
y_train <class 'numpy.ndarray'&gt; 
&nbsp;[0 5 2 ... 2 0 4]
So, I use the following method to change the dimension of y_train to 1 column

.reshape((-1, 1))
Then I can save the model successfully.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jpmml/sklearn2pmml"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月5日(星期三) 下午3:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [jpmml/sklearn2pmml] The JPMML-SkLearn conversion application has failed. (#279)





  
I have solved this problem according to your method
  
You mean converting the y_train variable to a Numpy array?
 
If so, then what was the original type of y_train? Some standard Scikit-Learn/Pandas type, or some custom type?
 print(y_train.__class__)
