### ISSUE TITLE
Wrong datatype is displayed in DataField section of DataDictionary in the generated PMML

### ISSUE THREAD

**Issue by salmankhan05101987** [jpmml/sklearn2pmml#280]
We have a string variable with datatype as object(dtpe('O')) in pandas dataframe. After generating PMML file using sklearn2pmml , datatype displayed is double instead of string in DataField section of data dictionary in  the generated PMML

PFA the line displayed in PMML,
<DataField name = "variable_x" optype = "continuous" dataType = "double"/>

**Comment by vruusmann** [comment]
This report does not contain any actionable information.

Closing as invalid.
