### ISSUE TITLE
Double datatype is displayed in generated PMML instead of String

### ISSUE THREAD

**Issue by salmankhan05101987** [jpmml/sklearn2pmml#281]
In PMML file below line is coming with datatype as double instead of string. I tried doing typecasting at next line but it didn't help me. Could you please suggest how to make this line come as string in the generated PMML ?

Alias(ExpressionTransformer(" '18-34' if X[0]  >= 18 else '0-17'"))

**Comment by vruusmann** [comment]
> Could you please suggest how to make this line come as string in the generated PMML ?

See the `Expressiontransformer.dtype` attribute:

```python
ExpressionTransformer("'18-34' if X[0] >= 18 else '0-17'", dtype = str)
```
