### ISSUE TITLE
Identification of data columns for expression transformation purposes

### ISSUE THREAD

**Issue by nuttracy** [jpmml/sklearn2pmml#283]
Hi Villu,

I am working on an ensemble pipeline which includes 3 estimators (y1, y2, y3), and uses max(y1,y2) - y3 as a final output. Here is an overview:

```python
def func(x0):
    x = np.amax(x0[:,:2],axis = 1)
    return np.stack((x,x0[:,2]),axis = 1)

transformer = FunctionTransformer(func)
meta_estimator = LinearRegression()
meta_estimator.coef_ = np.array([1.0, -1.0]).T
meta_estimator.intercept_ = 0.0
meta_pipeline = Pipeline([
    ('func_transform', transformer),
    ('meta_estimator', meta_estimator)
])

pmml_pipeline = \
PMMLPipeline([
    ('stacking_estimators_output',FeatureUnion([
        ('base_pipeline_1', Pipeline([
            ("base_feature_filtering_1", base_feature_filtering1),
            ("base_estimator_1", StackingEstimator(base_estimator1)),
            ('keep_score1', keep_score1)
        ])),
        ('base_pipeline_2', Pipeline([
            ("base_feature_filtering_2", base_feature_filtering2),
            ("base_estimator_2", StackingEstimator(base_estimator2)),
            ('keep_score2', keep_score2)
        ])),
        ('base_pipeline_3', Pipeline([
            ("base_feature_filtering_3", base_feature_filtering3),
            ("base_estimator_3", StackingEstimator(base_estimator3)),
            ('keep_score3', keep_score3)
        ]))
    ])),
    ('meta_pipeline',meta_pipeline)
])
```
It works fine when saving to .joblib, but gives me the following error with sklearn2pmml
`java.lang.IllegalArgumentException: Attribute 'sklearn.preprocessing._function_transformer.FunctionTransformer.func' has an unsupported value (Java class net.razorvine.pickle.objects.ClassDictConstructor)`

I saw you've provided solution for a similar issue https://github.com/jpmml/sklearn2pmml/issues/51 using ExpressionTransformer. However, when I try to use ExpressionTransformer with DataFrameMapper in meta_pipeline, I couldn't find a correct column name to use. In my pipeline, DataFrameMapper is after featureUnion, so the input of DataFrameMapper is numpy array not pandas dataframe.
```
mapper = DataFrameMapper([
  ([**0, 1**], ExpressionTransformer("max(X[0],X[1])")),
])

meta_pipeline = Pipeline([
    ('func_mapper', mapper),
    ('meta_estimator', meta_estimator)
])
```

Could you please provide some suggestions?

Thanks a lot!

**Comment by vruusmann** [comment]
> It works fine when saving to .joblib

.. But if you load this joblib file into a clean Python environment, does it run fine, or does it complain that the definition of function `func(x0)` cannot be found?

You can't persist custom Python functions in Pickle data format. It's not a (J)PMML limitation.

> 'sklearn.preprocessing._function_transformer.FunctionTransformer.func' has an unsupported value (Java class net.razorvine.pickle.objects.ClassDictConstructor)

The Java unpickler is finding an unsupported Python class/function reference, and does not know what to do next.

>  when I try to use ExpressionTransformer with DataFrameMapper in meta_pipeline, I couldn't find a correct column name to use.

The `ExpressionTransformer` transformer class supports both name-based (eg. `X['my_col']`) and position-based (eg. `X[3]`) column references. You can even mix those two referencing schemes.

When using `DataFrameMapper` you can specify `DataFrameMapper(df_out = True)` convertes the output data from Numpy array to Pandas' `DataFrame`.

>  In my pipeline, DataFrameMapper is after featureUnion, so the input of DataFrameMapper is numpy array not pandas dataframe.

Alternatively, you can always create a custom transformer, which takes a Numpy array and a list of strings as input, and combines this information to a `DataFrame`.

> Could you please provide some suggestions?

Simplify your pipeline. Establish a structure which allows you to identify columns positionally.

**Comment by nuttracy** [comment]
Thanks Villu,

Here is what I've changed.

```
func_mapper = DataFrameMapper([
  (['y1', 'y2', 'y3'], ExpressionTransformer("max(X[0],X[1])-X[2]")),
],df_out = True)

X = pd.DataFrame(zip(y1, y2, y3), columns = ['y1','y2','y3'])
y_out = func_mapper.fit_transform(X)

meta_estimator = LinearRegression()
meta_estimator.coef_ = np.array([1.0]).T
meta_estimator.intercept_ = 0.0

meta_pipeline = Pipeline([
    ('pandarizer', FunctionTransformer(lambda x: pd.DataFrame(x, columns = ["y1", "y2", "y3"]))),
    ('func_mapper', func_mapper),
    ('meta_estimator', meta_estimator)
])
```
when I save the pipeline to pickle, got this error. 'PicklingError: Can't pickle <function <lambda> at 0x7f8f2cdaec20>: attribute lookup <lambda> on __main__ failed' Do you know where it comes from? Thanks!

**Comment by nuttracy** [comment]
> Alternatively, you can always create a custom transformer, which takes a Numpy array and a list of strings as input, and combines this information to a `DataFrame`.

Could you give me some examples on it? It seems that FunctionTransformer doesn't work here.

**Comment by vruusmann** [comment]
> Could you give me some examples on it?

Create a proper subclass of `sklearn.base.TransformerMixin`, which contains the same business logic in its `transform(X)` method.

**Comment by nuttracy** [comment]
I tried the following
```
import pandas
class PandaTransformer(BaseEstimator, TransformerMixin):
    """transform numpy array to pandas dataframe."""

    def __init__(self, col_names = ['y1','y2','y3']):
        self.col_names = col_names

    def fit(self, X, y = None):
        return self

    def transform(self, X):
        return pandas.DataFrame(X, columns = self.col_names)


meta_pipeline = Pipeline([
    ('pandarizer', PandaTransformer()),
    ('func_mapper', func_mapper),
    ('meta_estimator', meta_estimator)
])
```
But then I need to load this class before Ioading pickle file in a new environment, and also got the following error when using sklearn2pmml.
`java.lang.IllegalArgumentException: The transformer object (Python class __main__.PandaTransformer) is not a supported Transformer`
I guess it is because this class is not part of sklearn2pmml. Do you know if I can use any of the existing class in sklearn2pmml to do the 'PandasTransformer'?

Thanks!

**Comment by vruusmann** [comment]
> I tried the following

That's the Scikit-Learn/Python side of the solution.

> But then I need to load this class before Ioading pickle file in a new environment

How else would it make sense? Just like you have to import Scikit-Learn classes into a clean Python environment, you'd have to import your own custom transformer and estimator classes.

Start a reusable library, and make this class the first entry.

Somebody somewhere has probably already implemented such custom class (perhaps named it differently such as `NumpyArrayToPandasDataFrameTransformer`). You might want to do some research here.

> and also got the following error when using sklearn2pmml.

You'd need to inform the JPMML-SkLearn library (that underlies the SkLearn2PMML package) about your custom transformer class by inserting an appropriate mapping into the `sklearn2pmm.properties` file:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/resources/META-INF/sklearn2pmml.properties

> Do you know if I can use any of the existing class in sklearn2pmml to do the 'PandasTransformer'?

Finally, you'd need to write the corresponding JPMML-SkLearn transformer class that takes care of the Java side of things.

Trust me, it's not difficult at all :-)

Perhaps I should show the way. I just labelled this thread with the "blog" label, so perhaps someday I'll write a small tutorial based on exactly this use case (converting a Numpy array to Pandas data frame (for the purpose of making interfacing with ExpressionTransformer easier)).

**Comment by nuttracy** [comment]
Thank you Villu. I will do some research and see if somebody has already implemented this class. Please let me know if you have any updates on the tutorial, would like to learn from it :)

**Comment by kornilcdima** [comment]
Hey @nuttracy ) Did you succeed? If yes, please share the solution. I have the similar problem but with using IsotonicRegression for calibrating probas.

**Comment by nuttracy** [comment]
> Hey @nuttracy ) Did you succeed? If yes, please share the solution. I have the similar problem but with using IsotonicRegression for calibrating probas.

I couldn't find any implemented class. What I did for a workaround is to manually change the column name of ExpressionTransformer in PMML.

**Comment by hrampadarath** [comment]
Hi @nuttracy can you explain what you did to resolve the issue? I have exactly same problem.
