### ISSUE TITLE
Pickle file size limitation

### ISSUE THREAD

**Issue by victornoel** [jpmml/sklearn2pmml#287]
Hi,

Apparently when the pickle file created by sklearn2pmml and parsed in Java is "too big", we get the following exception:
```java
Standard error:
Jun 24, 2021 7:29:37 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jun 24, 2021 7:29:38 PM org.jpmml.sklearn.Main run
SEVERE: Failed to parse PKL
java.lang.NegativeArraySizeException: -1394647443
    at net.razorvine.pickle.PickleUtils.readbytes(PickleUtils.java:54)
    at net.razorvine.pickle.Unpickler.load_binbytes(Unpickler.java:510)
    at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:315)
    at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:83)
    at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
    at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:104)
    at org.jpmml.sklearn.Main.run(Main.java:173)
    at org.jpmml.sklearn.Main.main(Main.java:161)
```

I created an issue at https://github.com/irmen/pickle/issues/6 but I was wondering if you were aware of such limitation and potential workaround for this?

**Comment by vruusmann** [comment]
> Apparently when the pickle file created by sklearn2pmml and parsed in Java is "too big"

Are you sure it's a Java-side limitation? Perhaps it's inherent to the Pickle protocol (eg. all array lengths must not exceed signed/unsigned integer range?)

Can you unpickle this problematic Pickle file in Python environment (and everything works OK)?

> I created an issue at irmen/pickle#6

Yes, that's the correct location for reporting and analyzing it. The JPMML-SkLearn library relies on the Pickle library, so the fix needs to come that way.

Subscribed to the same issue!

**Comment by vruusmann** [comment]
Will close this issue once there's an updated Pickle library available.

**Comment by victornoel** [comment]
Indeed, I am not sure if it's really a Java limitation or just a limitation of pickle.

I will try with a newer pickle protocol by monkey patching the sklearn2pmml._dump method, because the stacktrace above shows that it's using pickle protocol 3 (which is strange since the default is protocol 4 with python 3.8 that I am using).

**Comment by victornoel** [comment]
I'm thinking maybe if this is really a pickle protocol limitation, to have the ability to pass the desired protocol to sklearn2pmml could be useful for the users? Or to use pickle.HIGHEST_PROTOCOL by default?

**Comment by vruusmann** [comment]
Based on ideas presented in https://github.com/irmen/pickle/issues/6#issuecomment-869742469 and https://github.com/irmen/pickle/issues/6#issuecomment-869868454 there could be a proprietary extension attribute `Booster.handle_file`, which points to a file in local filesystem that stores the XGBoost JSON dump.

Possible workflow during training:
```python
xgb = sklearn.XGBClassifier()
xgb.fit(X, y)
jsonPath = saveToFile(xgb._Booster.handle, "xgb.json")
# Delete old value
xgb._Booster.handle = None
# Set new value
xgb._Booster.handle_file = jsonPath
```

**Comment by vruusmann** [comment]
I'm afraid that the underlying JPMML-XGBoost library still tries to read the JSON dump into memory as `byte[]`, and will crash with the same dreaded 2G array size error.

The solution would be to parse and convert XGBoost content in "streaming" mode.

**Comment by victornoel** [comment]
@vruusmann from what I am reading, when you pickle an XGBoost model, it's not transformed to JSON, it's just transformed to what they call "memory snapshot" (cf https://xgboost.readthedocs.io/en/latest/tutorials/saving_model.html) i.e., a typical pickle. So I suppose I'm actually dealing with really 2Gi of data I guess… I'm still investigating things and will get back to you about it.

**Comment by vruusmann** [comment]
> from what I am reading, when you pickle an XGBoost model, it's not transformed to JSON, it's just transformed to what they call "memory snapshot"

If you're using XGBoost 1.3.X or newer, then this "memory snapshot" is formatted in JSON.

See for yourself - save the content of a fitted `XGBClassifier._Booster.handle` attribute to a file in local filesystem, and open it in a text editor.

There's a 2 GB JSON dump inside your pickle file. Crazy stuff!

**Comment by victornoel** [comment]
@vruusmann after pickling (with `pickle.dump`) a pipeline containing a `XGBRegressor` (xgboost 1.4.2) that was trained, I unpickled it again, and looked at this `handle`:
```
>>> p.named_steps.model._Booster.handle
c_void_p(94097333031824)
```

Is that what you are talking about? I feel like I'm missing someting :)

**Comment by vruusmann** [comment]
> p.named_steps.model._Booster.handle
> c_void_p(94097333031824)

Yes, that's a readable byte array, save it to a file in local filesystem.

You might want to check out XGBoost Scikit-Learn APIs to see how it's exactly done.

**Comment by victornoel** [comment]
Finally I managed to take the time to test properly different options when calling sklearn2pmml with my >2Go pipeline, and even when forcing the use of pickle (without joblib at all) protocol 5, I get a sightly different error, but nothing surprising considering the limit is on the Java side for array size bound by max int:
```
Exception in thread "main" net.razorvine.pickle.PickleException: pickle too large, can't read more than maxint
        at net.razorvine.pickle.PickleUtils.readbytes(PickleUtils.java:64)
        at net.razorvine.pickle.Unpickler.load_bytearray8(Unpickler.java:385)
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:355)
        at org.jpmml.python.PickleUtil$1.dispatch(PickleUtil.java:83)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:109)
        at org.jpmml.python.PickleUtil.unpickle(PickleUtil.java:104)
        at org.jpmml.sklearn.Main.run(Main.java:155)
        at org.jpmml.sklearn.Main.main(Main.java:143)
```

**Comment by victornoel** [comment]
Couldn't really find how to write the content of this handle object, if you have code to share it would help me to better understand and investigate workarounds :)

Also I tried with a xgboost 0.90 model and the same problem happens even though there shouldn't be any json serialized in that case.

**Comment by vruusmann** [comment]
The upstream project has closed the related issue as "won't fix".

Makes sense. A 2GB size limit should be enough for any piece of any model data structure (it's the Python side that's blowing up things, not the (J)PMML side).
