### ISSUE TITLE
Not happy with the default "compacted" representation of decision tree models

### ISSUE THREAD

**Issue by MarkEdgerton** [jpmml/sklearn2pmml#292]
Hi,

Firstly, I'd like to apologise as there is a very high likelihood I have done something wrong, also my first time on github. The problem:

I am using the sklearn2pmml function to export an sklearn DecisionTreeClassifier, using a rough equivalent of the code from the first example on the main page (have attached my file).
[examplecode.txt](https://github.com/jpmml/sklearn2pmml/files/6930407/examplecode.txt)

When I open the pmml file it generates in Notepad++ or notepad, the structure of the decisiontree is not, so far as I can tell, correct pmml representation of a tree. The root node has 4 child nodes below it as an example, and the second node also has 4 child nodes under it. I looked at the examples on the pmml website and this never occurs there. (Link as reference:  http://dmg.org/pmml/v4-1/TreeModel.html)

My pmml file is attached:
[Irispmml.txt](https://github.com/jpmml/sklearn2pmml/files/6930445/Irispmml.txt)

I'm trying to import these pmml files into a C# factory pattern in order to construct a decision tree I've made in that, so as you can imagine consistent/correct formatting is important for me here. If I've posted this in the wrong place please let me know.

**Comment by vruusmann** [comment]
Fixed the title for you.

The PMML specification allows a `Node` element to contain **any number** of `Node` child elements. In practice, it does not make sense to have exactly one child, but it makes sense to have three, four, five, etc. children.

You are probably thinking that all tree models that don't exactly look like balanced binary tree models are incorrect. That's not how things look and feel in the real world.

If you want to get Scikit-Learn style tree model representation, then you'd need to disable the tree model compaction/flattening algorithm (active by default):

```python
pipeline = PMMLPIpeline([
  ("classifier", DecisionTreeClassifier())
])
pipeline.fit(X, y)

# THIS!
pipeline.configure(compact = False, flat = False)

sklearn2pmml(pipeline, "DecisionTree.pmml")
```

**Comment by MarkEdgerton** [comment]
Thank you very much for your response. It would seem I need to do more reading on the different ways the nodes can be represented! Should I delete this thread since it was just a lack of understanding on my end or is it standard practice to leave it here?

**Comment by vruusmann** [comment]
> Should I delete this thread?

Let's keep it, because other people might be interested in seeing this discussion in the future as well.

If you have other questions/observations regarding the tree model data structure in PMML, also post them here.

**Comment by hamonk** [comment]
Thanks for leaving the question! I was looking for the same info.

If I may, where can I get documentation about these pipeline options? Is that Jpmml?

Between two environments (with different versions of sklearn2pmml), the newer environment generates PMML with some typing in the SimplePredicate lines like "_double(feature_name)_" instead of the plain "_feature_name_". 

I'm wondering if there's maybe a pipeline option to deactivate this feature.

**Comment by vruusmann** [comment]
> Where can I get documentation about these pipeline options?

You'd need to look into the source code of the [JPMML-SkLearn](https://github.com/jpmml/jpmml-sklearn) library.

The root marker interface is `org.jpmml.sklearn.HasSkLearnOptions`, which then has subinterfaces with model type-specific options.

For example, all decision tree options are collected into the `sklearn.tree.HasTreeOptions` marker interface:
https://github.com/jpmml/jpmml-sklearn/blob/master/pmml-sklearn/src/main/java/sklearn/tree/HasTreeOptions.java

> Between two environments (with different versions of sklearn2pmml), the newer environment generates PMML with some typing in the SimplePredicate lines like "double(feature_name)" instead of the plain "feature_name".

You should assume that newer package versions are doing better (more correct) job, not worse.

The `double(<name>)` wrapper function indicates that the input value is explicitly converted from whatever numeric type it was, into the `float64` numeric type. JPMML converters only generate such wrapper functions when actually needed (eg. if the input was already `float64`, it wouldn't be generated), it is not there just to irritate you.

> I'm wondering if there's maybe a pipeline option to deactivate this feature.

If the cast to `float64` is omitted, then the model becomes broken/unsafe in sense that it may make incorrect predictions for some inputs. Right now, I believe that the SkLearn2PMML/JPMML-SkLearn stack is able to fully reproduce Scikit-Learn decision paths, but if that's against you best interests, you may consider using alternative converters that have a bit more "relaxed attitude".

You can always perform an explicit cast yourself, and name the resulting interim feature more appropriately:
```python
from sklearn2pmml.decoration import Alias
from sklearn2pmm.preprocessing import CastTransformer

mapper = DataFrameMapper([
  ("feature_name", [ContinuousDomain(), Alias(CastExpression(dtype = float64), name = "new_feature_name")])
])
```
