### ISSUE TITLE
Problem with using with `imblearn.over_sampling.SMOTE()`

### ISSUE THREAD

**Issue by oren0e** [jpmml/sklearn2pmml#293]
I have a really hard time using this library with imblearn. I do use the imblearn `Pipeline`. Maybe there's a way to **not** use pipeline at all? This is my code:
```python
import pandas as pd
import numpy as np

from typing import Tuple, List

from imblearn.over_sampling import SMOTE
from imblearn.pipeline import Pipeline, make_pipeline

from sklearn_pandas import DataFrameMapper
from sklearn.model_selection import GridSearchCV, StratifiedKFold, train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import average_precision_score, make_scorer

from sklearn2pmml import sklearn2pmml
from sklearn2pmml.decoration import CategoricalDomain, ContinuousDomain
from sklearn2pmml.pipeline import PMMLPipeline
from sklearn2pmml import make_pmml_pipeline

raw_data = pd.read_excel("../data/data.xlsx")

feature_names = raw_data[["Seniority","Netassetworth","OwnerProfile", "LTV", "Duration", "Type", "AssetLiquidity", "Assetvolatility", "AssetIinsurance", "DefaultForm"]].columns.to_list()
target_name = raw_data[["Default"]].columns.to_list()
cat_columns = ["OwnerProfile", "Type", "AssetIinsurance"]
cont_columns = ["Seniority","Netassetworth", "LTV", "Duration", "AssetLiquidity", "Assetvolatility", "DefaultForm"]

X = raw_data.drop("Default", axis=1)
X.columns = feature_names
y = raw_data["Default"]
y.columns = target_name

RANDOM_STATE = 1473

X_grid_search, X_test, y_grid_search, y_test = train_test_split(X, y, test_size=0.15,
                                                              random_state=RANDOM_STATE,
                                                              stratify=y)
sc = StandardScaler()

mapper = DataFrameMapper(
[([cat_column], [CategoricalDomain(), sc]) for cat_column in cat_columns] +
[([cont_column], [ContinuousDomain(), sc]) for cont_column in cont_columns]
)
sampler = SMOTE()

imblearn_pipeline = Pipeline([
    ("mapper", mapper),
    ("sampler", sampler),
    ("classifier", LogisticRegression(random_state=RANDOM_STATE, max_iter=3000))
])

cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE)
scoring = {"PR-AUC": make_scorer(average_precision_score)}
params = {"classifier__C": [0.8, 0.5, 0.3, 0.1, 0.005, 0.001]}
searcher = GridSearchCV(imblearn_pipeline, param_grid=params, cv=cv, scoring=scoring, refit="PR-AUC", n_jobs=-1, verbose=4)

searcher.fit(X_grid_search, y_grid_search)
lr_clf = searcher.best_estimator_
lr_clf.fit(X_grid_search, y_grid_search)

sklearn2pmml(make_pmml_pipeline(lr_clf, active_fields=feature_names, target_fields=target_name),
            "csmodel_pipeline.pmml")
```
The last line gives me a traceback which basically says:
```
TypeError: All intermediate steps should be transformers and implement fit and transform or be the string 'passthrough' 'SMOTE()' (type <class 'imblearn.over_sampling._smote.base.SMOTE'>) doesn't
```

I also get a bunch of warnings when fitting that look something like the following:
```
ConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
```
```
UserWarning: Scoring failed. The score on this train-test partition for these parameters will be set to nan. Details: 
...
ValueError: ['Netassetworth']: Data contains 1 invalid values
```

What's wrong? My data has no missing values and all the values are correct, I suspect that somehow the pipeline screws the standardization with StandardScaler()

**Comment by vruusmann** [comment]
> But the main error is:
> TypeError: All intermediate steps should be transformers and implement fit and transform 

This error is coming from the Scikit-Learn library. 

> It implies that I cannot use this with imblearn as I understand.

You should be able to perform a grid search with ImbLearn pipeline. Simply combine the main lessons from the first and second article.

> Where can I find the options for invalid value treatment?

See the third article.

**Comment by vruusmann** [comment]
> >  But the main error is:
> >  TypeError: All intermediate steps should be transformers and implement fit and transform
>
> This error is coming from the Scikit-Learn library.

The point of this comment is that with base Scikit-Learn and ImbLearn library issues you should consult with the respective projects (eg. open a GitHub issue there).

Your stack trace does not indicate any malfunction from the SkLearn2PMML library part.

**Comment by vruusmann** [comment]
Edited the issue title to better reflect the topic.

In brief, the data validation error is raised either by `CategoricalDomain` or `ContinuousDomain` decorator classes.

If you don't want to perform sanity checks on your data, don't include these steps into your pipeline. However, I would argue that it's good to be notified about data inconsistencies during the model training time where they can be fixed (as opposed to model deployment time, where they cause the prediction to fail).

**Comment by oren0e** [comment]
I've changed the pipeline to this:
```python
mapper = DataFrameMapper([
    (feature_names, [StandardScaler()])
])
sampler = SMOTE()
```
And now I don't get warnings anymore. I don't think my "categorical" variables were really categorical, they are binary, which is not the same for the library I presume?

I continue not being able to save the `pmml` file, even if I apply the advice in the second link (the post about `imblearn`):
```python
pmml_pipeline = PMMLPipeline([
   ("pipeline", imblearn_pipeline) 
])

pmml_pipeline.fit(X_grid_search, y_grid_search)
pmml_pipeline.configure(compact=False)
sklearn2pmml(pmml_pipeline,
            "csmodel_pipeline.pmml", with_repr=True)
```
And I get:
```
Standard output is empty
Standard error:
Aug 11, 2021 3:20:30 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Aug 11, 2021 3:20:30 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 25 ms.
Aug 11, 2021 3:20:30 PM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
Aug 11, 2021 3:20:30 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: The transformer object (Python class imblearn.over_sampling._smote.base.SMOTE) is not a supported Transformer
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:108)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:95)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:651)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn.Composite.encodeFeatures(Composite.java:118)
	at sklearn.Composite.encodeModel(Composite.java:135)
	at sklearn.pipeline.PipelineClassifier.encodeModel(PipelineClassifier.java:86)
	at sklearn.Estimator.encode(Estimator.java:83)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:235)
	at org.jpmml.sklearn.Main.run(Main.java:226)
	at org.jpmml.sklearn.Main.main(Main.java:143)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.base/java.lang.Class.cast(Class.java:3818)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:43)
	... 11 more

Exception in thread "main" java.lang.IllegalArgumentException: The transformer object (Python class imblearn.over_sampling._smote.base.SMOTE) is not a supported Transformer
	at org.jpmml.python.CastFunction.apply(CastFunction.java:45)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:108)
	at sklearn.pipeline.Pipeline$1.apply(Pipeline.java:95)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:651)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at sklearn.Composite.encodeFeatures(Composite.java:118)
	at sklearn.Composite.encodeModel(Composite.java:135)
	at sklearn.pipeline.PipelineClassifier.encodeModel(PipelineClassifier.java:86)
	at sklearn.Estimator.encode(Estimator.java:83)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:235)
	at org.jpmml.sklearn.Main.run(Main.java:226)
	at org.jpmml.sklearn.Main.main(Main.java:143)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objects.ClassDict to sklearn.Transformer
	at java.base/java.lang.Class.cast(Class.java:3818)
	at org.jpmml.python.CastFunction.apply(CastFunction.java:43)
	... 11 more

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/var/folders/wy/xkgc1jh17tb5c_myd3zwp3th0000gn/T/ipykernel_41868/3347181986.py in <module>
----> 1 sklearn2pmml(pmml_pipeline,
      2             "csmodel_pipeline.pmml", with_repr=True)

~/.pyenv/versions/3.9.2/envs/sci/lib/python3.9/site-packages/sklearn2pmml/__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug, java_encoding)
    256                                 print("Standard error is empty")
    257                 if retcode:
--> 258                         raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
    259         finally:
    260                 if debug:

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```
In this approach I'm not using the `GridSearchCV` so even if I use `make_pmml_pipeline()`:
```python
searcher.fit(X_grid_search, y_grid_search)
lr_clf = searcher.best_estimator_
sklearn2pmml(make_pmml_pipeline(lr_clf, active_fields=feature_names, target_fields=target_name),
            "csmodel_pipeline.pmml", with_repr=True)
```
I get:
```
~/.pyenv/versions/3.9.2/envs/sci/lib/python3.9/site-packages/sklearn/pipeline.py in _validate_steps(self)
    166             if (not (hasattr(t, "fit") or hasattr(t, "fit_transform")) or not
    167                     hasattr(t, "transform")):
--> 168                 raise TypeError("All intermediate steps should be "
    169                                 "transformers and implement fit and transform "
    170                                 "or be the string 'passthrough' "

TypeError: All intermediate steps should be transformers and implement fit and transform or be the string 'passthrough' 'SMOTE()' (type <class 'imblearn.over_sampling._smote.base.SMOTE'>) doesn't
```

**Comment by vruusmann** [comment]
> I don't think my "categorical" variables were really categorical, they are binary, which is not the same for the library I presume?

Typically, you would use the `CategoricalDomain` with `string` and `bool(ean)` columns. A binary `integer` column (ie. all values are either `0` or `1`) is functionally equivalent to a boolean, and should be decorated as a categorical feature as well.

> java.lang.IllegalArgumentException: The transformer object (Python class imblearn.over_sampling._smote.base.SMOTE) is not a supported Transformer

What is your Imbalanced-Learn package version?

Looks like ImbLearn has renamed their classes (ie. there's an extra `base` module component):
https://github.com/jpmml/jpmml-sklearn/issues/163

> TypeError: All intermediate steps should be transformers and implement fit and transform

That's still a Scikit-Learn error (my `make_pmml_pipeline` is a lightweight wrapper around the `make_pipeline` function). You'd need to "escape" your Imblearn pipeline.

**Comment by oren0e** [comment]
@vruusmann My imbalanced-learn version is `0.8.0`.
How can I "escape" it? I need it to operate on incoming data to serve correct predictions

**Comment by vruusmann** [comment]
> My imbalanced-learn version is 0.8.0.

The SMOTE class name was "correct" in `0.7.0`, so you should downgrade to it (at least temporarily).

> How can I "escape" it? I need it to operate on incoming data to serve correct predictions

The second article explicitly states that you can't use `make_pmml_pipeline` with ImbLearn pipelines, AND suggests a workaround.

Oh dear, looks like the formatting of Python code is broken again in https://openscoring.io/blog :-(

**Comment by oren0e** [comment]
@vruusmann Thank you very much!
The solution was indeed to downgrade `imbalanced-learn` to `0.7.0`. With this, the following solution works:
```python
mapper = DataFrameMapper([
    (feature_names, [StandardScaler()])
])
sampler = SMOTE()

imblearn_pipeline = Pipeline([
    ("mapper", mapper),
    ("sampler", sampler),
    ("classifier", LogisticRegression(random_state=RANDOM_STATE, max_iter=3000))
])

cv = StratifiedKFold(n_splits=10, shuffle=True, random_state=RANDOM_STATE)
scoring = {"PR-AUC": make_scorer(average_precision_score)}
params = {"classifier__C": [0.8, 0.5, 0.3, 0.1, 0.005, 0.001]}
searcher = GridSearchCV(imblearn_pipeline, param_grid=params, cv=cv, scoring=scoring, refit="PR-AUC", n_jobs=-1, verbose=4)

searcher.fit(X_grid_search, y_grid_search)
lr_clf = searcher.best_estimator_
pmml_pipeline = PMMLPipeline([
   ("pipeline", lr_clf) 
])
pmml_pipeline.configure(compact=False)
sklearn2pmml(pmml_pipeline,
            "csmodel_pipeline.pmml", with_repr=True)
```

Yeah, about the the Python code formatting, I wanted to say something, but I figured it was too much to ask for in one issue :)

**Comment by vruusmann** [comment]
> The solution was indeed to downgrade imbalanced-learn to 0.7.0.

I'm expecting to update Python-to-Java class mapping in about week's time. After that you can upgrade to the latest ImbLearn again.

> With this, the following solution works:

The example is not showing imports, but I believe that the type of the `imblearn_pipeline` object is `imblearn.pipeline.Pipeline` (**_not_** the regular `sklearn.pipeline.Pipeline`).

> I think that it will be beneficial for others if you would rename the issue's title to something that includes imblearn

Just did so. We had two concurrent issues here, but in the end the GridSearchCV+ImbLearn combo prevailed.

I'm thinking about enabling comment in https://openscoring.io/blog, so in the future it will be possible to have more topical discusions there as well.

**Comment by oren0e** [comment]
> I'm expecting to update Python-to-Java class mapping in about week's time. After that you can upgrade to the latest ImbLearn again.

That's great, thanks!

> The example is not showing imports, but I believe that the type of the imblearn_pipeline object is imblearn.pipeline.Pipeline (not the regular sklearn.pipeline.Pipeline).

Yes, it's the imblearn pipeline, you can see the imports in the first post in this issue.
