### ISSUE TITLE
CutTransformer does not accept 'ordered' keyword argument 

### ISSUE THREAD

**Issue by mkuiack** [jpmml/sklearn2pmml#294]
Hi,

I'm trying to use cutTransformer to return 1 when a continuous column value is within a given interval, and 0 otherwise. With pandas.cut labels can be repeated if the ordered=False keyword argument is set. I think this can de added to cutTransformer with the other keywords. 

```python
# (0 <= Amount_Usd < 20)
("Amount_feature_type", DataFrameMapper([
  ('Amount_Usd', [CutTransformer(bins=[-np.inf, 0, 20, np.inf], labels=[0, 1, 0], ordered=False)])
                                        ])
)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/y4/92x41rl552g9xwst2nq57nf80000gn/T/ipykernel_29703/4287662043.py in <module>
     14 # (0 <= Amount_Usd < 20)
     15 ("Amount_feature_type", DataFrameMapper([
---> 16   ('Amount_Usd', [CutTransformer(bins=[-np.inf, 0, 20, np.inf], labels=[0, 1, 0],ordered=False)])
     17                                         ])
     18 ),

TypeError: __init__() got an unexpected keyword argument 'ordered'
```

**Comment by mkuiack** [comment]
I've found a work around:

```python
[CutTransformer(bins=[0, 2], labels=[1]), SimpleImputer(strategy='constant', copy=True, fill_value=0)]
```

**Comment by vruusmann** [comment]
> I'm trying to use CutTransformer to return 1 when a continuous column value is within a given interval, and 0 otherwise.

I'd suggest you to use the `sklearn2pmml.preprocessing.ExpressionTransformer` instead, because the intended "business logic" can be captured as a Python expression.

For example:
```python
from sklearn2pmml.preprocessing import ExpressionTransformer

bins = [0, 2]

binarizer = ExpressionTransformer("0 if X[0] >= {0} and X[0] <= {1} else 1".format(bins[0], bins[1]))
```

**Comment by vruusmann** [comment]
Closing as "won't fix", because the `CutTransformer` class is not supposed to provide 100% functional parity with the `pandas.cut` function.

If necessary, you should sort/reorder your bins in Python code, before invoking the `CutTransformer` constructor.

**Comment by mkuiack** [comment]
Great suggestion, thank you!
