### ISSUE TITLE
Put the package on PyPI

### ISSUE THREAD

**Issue by MaxNoe** [jpmml/sklearn2pmml#3]
This would make it installable via pip and dramatically ease handling the package as dependency.

**Comment by vruusmann** [comment]
It should happen when the underlying JPMML-SkLearn library reaches the `1.0` version.

**Comment by damienrj** [comment]
Any update on adding into pip?

**Comment by seanpquig** [comment]
Update on this?  Thanks.

**Comment by MaxNoe** [comment]
Please, just upload it. PyPI is not a collection of finished work. It's just a place where modules are made available.

**Comment by MaxNoe** [comment]
Also, jpmml-sklearn is >= 1.0 since half a year now
