### ISSUE TITLE
Sklearn2pmml 0.10.0 Throwing Java Exception

### ISSUE THREAD

**Issue by SJNell** [jpmml/sklearn2pmml#30]
I want to create a pmml file version 4.2 or lesser from Python and I could download sklearn2pmml version 0.10.0 on this regard. But it's stopping me with the Exception below when running this over my Windows 7 64 bit machine with Anaconda 2.5 and Python version 2.7.13 

Code
```
from sklearn_pandas import DataFrameMapper
default_mapper = DataFrameMapper([(i, None) for i in x_train.columns + ['Response']])

from sklearn2pmml import sklearn2pmml
sklearn2pmml(estimator=fit_cart, 
             mapper=default_mapper, 
             pmml="./DT.pmml")
```

Exception
```
CalledProcessError                        Traceback (most recent call last)
<ipython-input-17-8c8eafc3f31e> in <module>()
      5 sklearn2pmml(estimator=fit_cart, 
      6              mapper=default_mapper,
----> 7              pmml="./DT.pmml")

C:\Anaconda2\lib\site-packages\sklearn2pmml\__init__.pyc in sklearn2pmml(estimator, mapper, pmml, with_repr, debug)
     63                 if(debug):
     64                         print(" ".join(cmd))
---> 65                 subprocess.check_call(cmd)
     66         finally:
     67                 if(debug):

C:\Anaconda2\lib\subprocess.pyc in check_call(*popenargs, **kwargs)
    184         if cmd is None:
    185             cmd = popenargs[0]
--> 186         raise CalledProcessError(retcode, cmd)
    187     return 0
    188 

CalledProcessError: Command '['java', '-cp', 'C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\guava-19.0.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\istack-commons-runtime-2.21.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\jaxb-core-2.2.11.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\jaxb-runtime-2.2.11.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\jcommander-1.48.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\jpmml-converter-1.0.8.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\jpmml-sklearn-1.0.0.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\jpmml-xgboost-1.0.6.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\pmml-agent-1.2.17.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\pmml-model-1.2.17.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\pmml-model-metro-1.2.17.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\pmml-schema-1.2.17.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\pyrolite-4.12.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\serpent-1.12.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\slf4j-api-1.7.21.jar;C:\\Anaconda2\\lib\\site-packages\\sklearn2pmml\\resources\\slf4j-jdk14-1.7.21.jar', 'org.jpmml.sklearn.Main', '--pkl-estimator-input', 'c:\\users\\5239647\\appdata\\local\\temp\\estimator-fwa91n.pkl.z', '--pkl-mapper-input', 'c:\\users\\5239647\\appdata\\local\\temp\\mapper-kmzk1k.pkl.z', '--pmml-output', './DT.pmml']' returned non-zero exit status 1
```

Help me to resolve this. Thank You.

**Comment by vruusmann** [comment]
SkLearn2PMML version 0.10.0 is not supported anymore.

A couple of leads:

- Does your Python script pass cleanly with the latest SkLearn2PMML version 0.17.4?
- You're showing me the Python exception, which does not contain any actionable information. What does the underlying Java exception say? To understand SkLearn2PMML exception hierarchy better, see this StackOverflow thread: http://stackoverflow.com/a/41701701/1808924
- Can you attach the problematic Pickle files to this issue so that I could look into it myself? It's the ones that are mentioned right after `--pkl-estimator-input` and `--pkl-mapper-input` command-line options - would be `estimator-fwa91n.pkl.z` and `mapper-kmzk1k.pkl.z` in the current case.
- If the above Pickle files contain proprietary information and cannot be shared, then can you reproduce the exception with some publicly available dataset?

**Comment by SJNell** [comment]
Following are the answers to your questions

1. Does your Python script pass cleanly with the latest SkLearn2PMML version 0.17.4?
Yes, It does work and Produce PMML 4.3 version, I am looking to create PMML 4.2 or older version. 
Do you have any supported version through which I can download it and generate PMML 4.2 or older versions?. If so please let me know the paths. Thank You.

I am yet to work on the Other 3 questions.
