### ISSUE TITLE
Scikit-Learn 1.0 incompatibility - the `n_features_` attribute has been renamed to `n_features_in_`

### ISSUE THREAD

**Issue by tdoublep** [jpmml/sklearn2pmml#305]
We've recently encountered an issue using latest version of scikit-learn (v1.0).

The issue is reproduced with the following simple test:
```python
from sklearn.datasets import make_classification
from sklearn.ensemble import RandomForestClassifier
from sklearn2pmml import sklearn2pmml
from sklearn2pmml.pipeline import PMMLPipeline

X,y = make_classification(n_features=30, random_state=42)
clf = RandomForestClassifier(random_state=42)
print(clf.__dict__)
pipeline = PMMLPipeline([("model", clf)]).fit(X, y)
print("Number of features after training: %d" % (pipeline.steps[0][1].n_features_in_))
sklearn2pmml(pipeline, "test.pmml", with_repr=True)
```
which fails with the following:
```bash
Number of features after training: 30
/Users/xxx/anaconda3/envs/pmml-debug/lib/python3.8/subprocess.py:848: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
/Users/xxx/anaconda3/envs/pmml-debug/lib/python3.8/subprocess.py:853: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
Standard output is empty
Standard error:
Sep 30, 2021 12:25:58 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Sep 30, 2021 12:25:58 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 90 ms.
Sep 30, 2021 12:25:58 PM org.jpmml.sklearn.Main run
INFO: Converting PKL to PMML..
Sep 30, 2021 12:25:58 PM sklearn2pmml.pipeline.PMMLPipeline initTargetFields
WARNING: Attribute 'sklearn2pmml.pipeline.PMMLPipeline.target_fields' is not set. Assuming y as the name of the target field
Sep 30, 2021 12:25:58 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: The transformer object of the first step (Python class sklearn.ensemble._forest.RandomForestClassifier) does not specify the number of input features
	at sklearn2pmml.pipeline.PMMLPipeline.initActiveFields(PMMLPipeline.java:560)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:217)
	at org.jpmml.sklearn.Main.run(Main.java:217)
	at org.jpmml.sklearn.Main.main(Main.java:143)

Exception in thread "main" java.lang.IllegalArgumentException: The transformer object of the first step (Python class sklearn.ensemble._forest.RandomForestClassifier) does not specify the number of input features
	at sklearn2pmml.pipeline.PMMLPipeline.initActiveFields(PMMLPipeline.java:560)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:217)
	at org.jpmml.sklearn.Main.run(Main.java:217)
	at org.jpmml.sklearn.Main.main(Main.java:143)

Traceback (most recent call last):
  File "test.py", line 10, in <module>
    sklearn2pmml(pipeline, "test.pmml", with_repr=True)
  File "/Users/xxx/anaconda3/envs/pmml-debug/lib/python3.8/site-packages/sklearn2pmml/__init__.py", line 258, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```
It looks like the `n_features_in_` is properly set after training the classifier.

The same issue exists for the RandomForestRegressor also.

Please let me know if I can provide any more info to help, or if the issue should be reported in jpmml-sklearn instead. 

My software env is clean conda env (python=3.8) with following packages installed from pip:
```
$ pip freeze
certifi==2021.5.30
joblib==1.0.1
numpy==1.21.2
pandas==1.3.3
python-dateutil==2.8.2
pytz==2021.1
scikit-learn==1.0
scipy==1.7.1
six==1.16.0
sklearn-pandas==2.2.0
sklearn2pmml==0.74.4
threadpoolctl==2.2.0
```

**Comment by vruusmann** [comment]
> We've recently encountered an issue using latest version of scikit-learn (v1.0).

The SkLearn2PMML/JPMML-SkLearn stack has not been migrated to Scikit-Learn 1.0 yet. Tha latest tested&verified version is 0.24.

> It looks like the n_features_in_ is properly set after training the classifier.

The JPMML-SkLearn library is generally looking for the `n_features_` attribute:
https://github.com/jpmml/jpmml-sklearn/blob/1.6.30/src/main/java/sklearn/Estimator.java#L52-L60

Looks like this attribute was deprecated in favour of the `n_features_in_` attribute in Scikit-Learn 1.0.

> The same issue exists for the RandomForestRegressor also.

Probably applies to all estimator classes... 

> Please let me know if I can provide any more info to help, or if the issue should be reported in jpmml-sklearn instead

This issue right here is totally sufficient - the underlying technical problem (renamed attribute) is completely obvious.

In the meantime, you can work around this issue by inserting a (pseudo-)transformer step into the first position of your pipeline, so that there would be an alternative source of "number of features" information.

Also, if you fitted the pipeline with Pandas' `DataFrame` (has column names) instead of Numpy array (does not have column names; they have to be generated automatically based on other available evidence - triggers this "unknown number of features" issue), then this issue wouldn't manifest itself.

**Comment by tdoublep** [comment]
Thanks a lot for the suggested work-arounds, this should be totally fine for the time being.
