### ISSUE TITLE
Features with zero importance are dropped when using sklearn2pmml

### ISSUE THREAD

**Issue by XinlinSong** [jpmml/sklearn2pmml#314]
Hello, 

When I was saving a pipeline to PMML file, I found that features with 0 importances are automatically dropped in the PMML file. Is this behavior intended? How does sklearn2pmml function know which feature has 0 importance?

Please see the following example:

```
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import make_classification
from pypmml import Model
from sklearn2pmml import PMMLPipeline, sklearn2pmml

# generate some training data
X, y = make_classification(n_samples=100, n_features=4, n_classes=2)
df = pd.DataFrame(X, columns=['A', 'B', 'C', 'D'])

# add a constant column which won't have any prediction power
df['E'] = 0

lg = LogisticRegression()
lg.fit(df, y)

pipeline = PMMLPipeline([
    ('classifier', lg)
])
pipeline.active_fields = np.array(['A', 'B', 'C', 'D' , 'E']).astype(str)
sklearn2pmml(pipeline, 'lg_model.pmml', with_repr=True, debug=False)

# the saved PMML model automatically removed column E
lg_pmml = Model.load('lg_model.pmml')
print(lg_pmml.inputNames) # The output is 'A', 'B', 'C', 'D'
```

Thank you for the help!!

**Comment by vruusmann** [comment]
> I found that features with 0 importances are automatically dropped in the PMML file. Is this behavior intended?

Yes, absolutely.

This behaviour has been discussed many times over the years, so I won't be repeating it here.

> How does sklearn2pmml function know which feature has 0 importance?

The PMML converter knows exactly which features are **_used by the model_**, and which ones are not. The former are kept, the latter are discarded.

There is no benefit to keeping around unused features.

Please note that I'm speaking about a situation "feature which is not used by a model", whereas you speak about a situation "feature has zero importance". These are conceptually two different things.

**Comment by vruusmann** [comment]
> Please see the following example:

The intended behaviour is that this model should not declare any input fields (aka features). It's an isolated+constant prediction function, why the hell does should it demand features "A", "B", "C" and "D" from the end user?
