### ISSUE TITLE
Generate PMML from a pre-fitted `xgboost.core.Booster` object

### ISSUE THREAD

**Issue by AraceliAL** [jpmml/sklearn2pmml#321]
Good afternoon!

I just wanted to generate a PMML using sklearn2pmml from an imported joblib such as:

```
obj = joblib.load("model.joblib")
pmml_pipeline = make_pmml_pipeline(obj)
sklearn2pmml(pmml_pipeline, "/path/to/model.pmml")
```

I read[ here](https://groups.google.com/g/jpmml/c/Y5Y7wpfEz4s) that this can be done. Nonetheless, it raises an error related with the extraction of steps of this object (obj) : _steps_ = _filter_steps(_get_steps(obj))_ ,it gives a ValueError().

Can I really use this library this way?

Thanks a lot in advance!! :P

**Comment by vruusmann** [comment]
Anyway, please try to give me more information about the original `ValueError`. I'd like to make my `make_pmml_pipeline` utility function smarter.

**Comment by AraceliAL** [comment]
Frist of all thanks for your super fast response!

The object is an XGBoost object ('<xgboost.core.Booster object at 0x7fb2f426d460>'). Wen running it says 
`line 99, in _get_steps  raise ValueError() ValueError`, only that :(, sorry if I am not of very much help.

If I directly apply the PMMLPipeline as you mentioned, now it complains that:

`TypeError: Last step of Pipeline should implement fit or be the string 'passthrough'. '<xgboost.core.Booster object at 0x7f9f2324c7c0>' (type <class 'xgboost.core.Booster'>) doesn't`.

Maybe I should fit the model once again before exporting to pmml?

Thanks a lot one again!! :P

**Comment by AraceliAL** [comment]
Frist of all thanks for your super fast response!

The object is an XGBoost object ('<xgboost.core.Booster object at 0x7fb2f426d460>'). Wen running it says
line 99, in _get_steps raise ValueError() ValueError, only that :(, sorry if I am not of very much help.

If I directly apply the PMMLPipeline([('obj', obj)]) as you mentioned, now it complains that:

TypeError: Last step of Pipeline should implement fit or be the string 'passthrough'. '<xgboost.core.Booster object at 0x7f9f2324c7c0>' (type <class 'xgboost.core.Booster'>) doesn't.

Maybe I should fit the model once again before exporting to pmml?

On the other hand, by selector you mean like feature selection? A priori we do not use that.

Thanks a lot one again!! :P

**Comment by vruusmann** [comment]
> The object is an XGBoost object ('<xgboost.core.Booster object at 0x7fb2f426d460>')

The PMMLPipeline class (just as the underlying Scikit-Learn pipeline class) expects all steps to be instances of Scikit-Learn's estimator class (either a `ModelMixin` or `TransformerMixin`).

Your object is a low-level XGBoost model object, which doesn't satisfy this requirement.

Please "convert" it into a proper Scikit-Learn object instance first. For example, you could create a dummy (ie. pre-fitted) `XGBClassifier` or `XGBRegressor` object (depending on the mining function of your model).

Here's the idea:
```python
obj = joblib.load("model.joblib")

# Convert into a Scikit-Learn object
obj = XGBRegressor()
obj._Booster = obj

pipeline = make_pmml_pipeline(obj)
```

**Comment by vruusmann** [comment]
IMHO, raising a`ValueError` is the correct behaviour in the current situation, because the user is attempting to force an unsupported object type (low-level XGBoost model) into a Scikit-Learn pipeline.

However, this `ValueError` should have a meaningful explanation attached to it, so leaving this issue open.
