### ISSUE TITLE
XGBClassifier to PMML

### ISSUE THREAD

**Issue by AraceliAL** [jpmml/sklearn2pmml#325]
Good afternoon!

I've been trying to export an xgb.train() model to pmml as follows (I checked other issues from sklearn2pmml):

```python
clf = xgboost.train(param, dtrain, num_estimators)
classifier = xgboost.XGBClassifier(**param, use_label_encoder = False)
classifier._Booster = clf

pipeline = make_pmml_pipeline(classifier, active_fields = ['pricePerDistance'], target_fields = ['picked'])
sklearn2pmml(pipeline, "XGBoost.pmml")
```

Nonetheless I get an error about:

SEVERE: Failed to convert PKL to PMML
java.lang.IllegalArgumentException: The value of 'xgboost.sklearn.XGBClassifier.classes_' attribute (null) is not a supported array type

How can I edit this attribute classes_?

Thanks a lot!!!

**Comment by vruusmann** [comment]
> How can I edit this attribute `classes_`?

The `XGBClassifier.classes_` attribute is automatically initialized by the `XGBClassifier.fit(X, y)` method. It's an array that enumerates target categories (unique values, naturally ordered?).

When you're creating a `XGBClassifier` object from scratch, then you need to initialize this attribute yourself.

It's rather straightforward:
```python
import numpy

classifier = xgboost.XGBClassifier(...)
classifier._Booster = mybooster
# THIS!
classifier.classes_ = numpy.asarray(["A", "B", "C"])
```

**Comment by AraceliAL** [comment]
Thanks a lot vruusmann! It worked perfectly! :P
