### ISSUE TITLE
Namespace problems

### ISSUE THREAD

**Issue by ColdTeapot273K** [jpmml/sklearn2pmml#326]
Env:

OS: Linux
Python: 3.9.9
sklearn2pmml: 0.80.0
pandas: 1.4.2

---

Interesting bug with imports & namespaces:

This breaks:
```python
import pandas as pd

from sklearn2pmml.preprocessing.pandas import DataFrameConstructor
from sklearn2pmml.preprocessing import CutTransformer

df_dev = pd.DataFrame({"col_1": [1, 2, 3, 4, 5, 6, 7, 8, 9]})
tr = CutTransformer(bins=[0, 5, 10], labels=["five", "ten"])
tr.fit(df_dev)
tr.transform(df_dev)
# AttributeError: module 'sklearn2pmml.preprocessing.pandas' has no attribute 'cut'
```
This works fine:
```python
import pandas as pd

# from sklearn2pmml.preprocessing.pandas import DataFrameConstructor
from sklearn2pmml.preprocessing import CutTransformer

df_dev = pd.DataFrame({"col_1": [1, 2, 3, 4, 5, 6, 7, 8, 9]})
tr = CutTransformer(bins=[0, 5, 10], labels=["five", "ten"])
tr.fit(df_dev)
tr.transform(df_dev)
# [['five'], ['five'], ['five'], ['five'], ['five'], ['ten'], ['ten'], ['ten'], ['ten']]
# Categories (2, object): ['five' < 'ten']
```

Further inspection shows indeed the absence of the function in question:
 
```python
import pandas as pd
vars(pd)['cut']
# <function pandas.core.reshape.tile.cut(x, bins, right: 'bool' = True, labels=None, retbins: 'bool' = False, precision: 'int' = 3, include_lowest: 'bool' = False, duplicates: 'str' = 'raise', ordered: 'bool' = True)>


import sklearn2pmml.preprocessing.pandas as bastard_pandas
vars(bastard_pandas)['cut']
# KeyError: 'cut'
```

**Comment by vruusmann** [comment]
I noticed this bug myself ~2 weeks ago, and fixed it right away by merging the `sklearn2pmml.preprocessing.pandas` sub-module into its parent module:
https://github.com/jpmml/sklearn2pmml/commit/fff426420666be567d47757730319f6d33bcefd6

I'd really like to have 3rd-party library dependent custom transformers in separate sub-modules, but I'm currently not "Python smart" enough to implement it correctly (esp, across many different Python versions). If you can help, please share ideas!

Anyway, you should upgrade to the latest SkLearn2PMML 0.83.0, to have this import error solved.

The fully qualified name for this transformer is `sklearn2pmml.preprocessing.DataFrameConstructor` now.
