### ISSUE TITLE
Export multiple models

### ISSUE THREAD

**Issue by gegatapetkov** [jpmml/sklearn2pmml#333]
Hi there! 

I have 3-4 models that I would like to export into one .pmml file. I need it to have segmentation like in the examples here - [PMML 4.3 - Multiple models](https://dmg.org/pmml/v4-4/MultipleModels.html) 

Is this by any chance supported by your package? I’ve done some research and as far as I understand it can be exported if all of the models are packed in a “container” (PMMLPipeline), but how do I pack them into one? 

Thank you in advance!

**Comment by vruusmann** [comment]
> I need it to have segmentation like in the examples here - [PMML 4.3 - Multiple models](https://dmg.org/pmml/v4-4/MultipleModels.html)

There are many kinds of segmentations:

- Simple aggregations (eg. `average`).
- Complex aggregations (eg. `weightedAverage`).
- Model chains
- Model selection (eg. `selectFirst`, `selectAll`)

> but how do I pack them into one?

Depending on the kind of segmentation, there already might be an Scikit-Learn wrapper available. For example, you can build (weighted-) averages and voters using `sklearn.ensemble.VotingClassifier` and `sklearn.ensemble.VotingRegressor`.

If you need something custom, feel free to develop a suitable aggregator yourself.

**Comment by vruusmann** [comment]
This use case should be fully addressed by the `sklearn2pmml.ensemble.EstimatorChain` estimator class, which was introduced in SkLearn2PMML 0.86(.1).
