### ISSUE TITLE
Failed to convert MinMaxScaler

### ISSUE THREAD

**Issue by JKyang09** [jpmml/sklearn2pmml#335]
This is my code：

`
  from sklearn.preprocessing import MinMaxScaler
  from sklearn2pmml import make_pmml_pipeline,sklearn2pmml
  from pypmml import Model
  
  def new(X_test):
      pipeline = PMMLPipeline([     ("MinMaxScaler", MinMaxScaler())      ])
      pipeline.fit(X_test)
      sklearn2pmml(pipeline,'./test.pmml',with_repr=True, debug=True)  
      model = Model.fromFile('./test.pmml')
      X_train_scale = model.transform(X_test[:, :7])  
      return X_train_scale
`

and I get this error
`
AttributeError: 'Model' object has no attribute 'transform'
`

can you give me some advice

**Comment by vruusmann** [comment]
The `pypmml.Model` class (and its missing `transform` method) is not related to the Sklearn2PMML project in any way.
