### ISSUE TITLE
Question on `GridSearchCV` prediction post-processing 

### ISSUE THREAD

**Issue by benjaminbluhm** [jpmml/sklearn2pmml#336]
Hi,

Really good to see the newly introduced scikit-learn prediction post-processing functionalities, I feel this is really missing in scikit-learn :-)

Quick question: In the [demo ](https://openscoring.io/blog/2022/05/06/sklearn_prediction_postprocessing/)I can see that prediction post-processing can be implemented on a fitted `Pipeline ` object.

Does your library also provide the same functionality for fitted `GridSearchCV` object? 

I think it would be highly useful, but could not find anything on this in the docs.

Thank you!

**Comment by vruusmann** [comment]
> Quick question: In the demo I can see that prediction post-processing can be implemented on a fitted Pipeline object.
>

The post-processing implementation is nothing but some transformer objects that know how to transform the result data matrices coming from `Pipeline.predict` and `Pipeline.predict_proba` methods.

Unfortunately, a third-party library cannot add new attributes to the core `sklearn.pipeline.Pipeline` class. Therefore, I need to define a new `PMMLPipeline` class, and add them as `PMMLPipeline.predict_transformer`, `PMMLPipeline.predict_proba_transformer` and `PMMLPipeline.apply_transformer` attributes.

For convenience reasons, you can set the initial value of all three transformer attributes via the `PMMLPipeline` constructor. However, you can manually re-assign them at any point in your workflow, before or after fitting the pipeline:

```python
# Initialize predict_transformer
pipeline = PMMLPipeline([...], predict_transformer = ...)
# Nah, lets re-do predict_transformer
pipeline.predict_transformer = ...
pipeline.fit(X, y)
# Nah, lets re-do predict_transformer one more time
pipeline.predict_transformer = ...

sklearn2pmml(pipeline, "ExtendedPipeline.pmml")
```

The goal of post-processing is to transform machine-oriented Scikit-Learn prediction (anonymous numeric scalar) into human-oriented prediction (rich & decorated, complex datatype scalar). The main tool for this transformation is the `sklearn2pmml.postprocessing.BusinessDecisionTransformer` class, but other SkLearn2PMML decorators such as `sklearn2pmml.decoration.Alias` also come in handy oftentimes.

> Does your library also provide the same functionality for fitted GridSearchCV object?

What's the specific issue with `GridSearchCV`?

All three `PMMLPipeline` attributes should not interfere with the grid search procedure in any way. They are just a dummy payload, that should get cloned and get passed on to child pipeline instances. Or do they get discarded, or raise some sort of error somewhere?

See above - if nothing else works, then you can perform the grid search using a normal Scikit-Learn pipeline object. After it has been optimized and fitted, transform it to a PMML pipeline, and attach relevant post-processors:

```
from sklearn2pmml import make_pmml_pipeline, sklearn2pmml
a
pipeline = Pipeline([...])

searcher = GridSearchCV(estimator = pipeline, param_grid = ...)
searcher.fit(X, y)

pmml_pipeline = make_pmml_pipeline(searcher.best_estimator_, active_fields = [...], target_fields = [...])
# THIS!
pmml_pipeline.predict_transformer = ...

sklearn2pmml(pmml_pipeline, "OptimizedExtendedPipeline.pmml")
```

**Comment by benjaminbluhm** [comment]
Thank you for your detailed explanations, really appreciated!

I tested a bit more and I can indeed call: `searcher.best_estimator_.predict_transform()`

What currently does not work and I would do preferrably is to call `searcher.predict_transform()` (in analogy to `searcher.predict()`) but I guess this would reguire some modification on the `GridSearchCV` class.

Thanks again!

**Comment by vruusmann** [comment]
> What currently does not work and I would do preferrably is to call searcher.predict_transform(), but I guess this would reguire some modification on the GridSearchCV class.

Yes, as of Scikit-Learn 1.1.X, this would require creating a `PMMLGridSearchCV(GridSearchCV)` subclass, which declares public "proxy methods" for all `PMMLPipeline` methods.

This approach is pretty much a dead end, because I physically cannot maintain a PMML-enhanched variants of all Scikit-Learn core classes. Subclassing the `sklearn.pipeline.Pipeline` is sufficient challenge for me.

But agreed, that the SkLearn2PMML package is lacking documentation in several important aspects - it can actually do much more than is publicly revealed.

**Comment by benjaminbluhm** [comment]
In any case, for me this change would only be of cosmetic nature as I can easily call `searcher.best_estimator_.predict_transform()` (which has the same effect as calling `searcher.predict_transform()`)

Agree that extended documentation of your library could further boost the usage but I know it's a painful and time consuming task...maybe hosting a Sphinx documentation or providing some example jupyter notebooks in the repo could be a good step in this direction.

Good luck and thanks for contributing this library to the community!
