### ISSUE TITLE
Does sklearn2pmml only support jdk 1.7 rather than 1.8 ?

### ISSUE THREAD

**Issue by enjoyhot** [jpmml/sklearn2pmml#34]
Error: Registry key 'Software\JavaSoft\Java Runtime Environment'\CurrentVersion' has value '1.8', but '1.7' is required.
Error: could not find java.dll
Error: Could not find Java SE Runtime Environment.

**Comment by vruusmann** [comment]
There's something wrong with your local environment (eg. "Error: could not find java.dll"). Perhaps you should re-install your JRE/JDK.

The `sklearn2pmml` package doesn't care about Java version - it works with JDK 1.7 and 1.8. The only requirement is that `java.exe` must be available on system path.
