### ISSUE TITLE
The `Alias` decorator does not have any effect on the Python side

### ISSUE THREAD

**Issue by mmarinaki** [jpmml/sklearn2pmml#343]
Hi @vruusmann! I have been having trouble renaming fields using Alias from sklearn2pmml.decorator. I am using ExpressionTransformer to transform a field, and then hoping to rename it but for some reason Alias is not working. An example of my code:

```python
from sklearn2pmml.decoration import CategoricalDomain, Alias, ContinuousDomain
from sklearn2pmml.preprocessing import ExpressionTransformer

mapper = DataFrameMapper([(['field_1', 'field_2'], Alias(ExpressionTransformer('10-2*X[0]- X[1]'), name="renamed_column"))], df_out=True)
mapper.fit_transform(df_test)
```
This returns a dataframe with a column with the name "field_1field_2" instead of "renamed_column" that we defined through Alias. 

Also when I print out mapper.transformed_names_, this returns "field_1field_2".

Pleas let me know if I am doing something terribly wrong, or this is an issue with the implementation. Thank you!

**Comment by vruusmann** [comment]
See also: https://github.com/jpmml/sklearn2pmml/issues/343

**Comment by vruusmann** [comment]
Right now, the `Alias` decorator does not implement column renaming on the Python side. The explanation is that Scikit-Learn/Python is typically colum name ignorant, so it's not a worthwhile investment to make the `Alias` decorator class any more sophisticated in this area.

The `Alias` decorator should have full effect on the PMML/Java side. If you open the exported PMML file in a text editor, then the corresponding derived field is called `"renamed_column"`, no?

**Comment by vruusmann** [comment]
When working with `DataFrameMapper`, then it's advisable to use its built-in column rename functionality (instead of `sklearn2pmml.decoration.Alias`).

Something like this whould work both on Python and PMML/Java side:
```python
mapper = DataFrameMapper([
  (['field_1', 'field_2'], ExpressionTransformer('10-2*X[0]- X[1]'), {"alias" : "renamed_column"})
)], df_out=True)
mapper.fit_transform(df_test)
```

**Comment by mmarinaki** [comment]
Yes! The derived field is "renamed_column". I was wondering why it was appearing there and I couldn't see the corresponding change in the df!

Perfect thank you so much for the quick response!

**Comment by vruusmann** [comment]
The `sklearn2pmml.decoration.Alias` decorator class now defines both `get_feature_names` and `get_feature_names_out` methods (as detailed in the above commit), but it doesn't help its integration with `sklearn_pandas.DataFrameMapper`, because the latter does not support these attributes.

I tested with SkLearn-Pandas 1.8.0 and 2.2.0, and they're both "broken" in this area.
