### ISSUE TITLE
Post Process the multiple outputs of random forest regressor

### ISSUE THREAD

**Issue by Rajeshyd0308** [jpmml/sklearn2pmml#347]
Hello,
Can I create a PMMLPipeline, where I post process the outputs of my regressor?

```
import argparse
import pandas as pd
import sklearn2pmml
from sklearn.ensemble import RandomForestRegressor
from sklearn.base import BaseEstimator, TransformerMixin

class FeatureSelector(BaseEstimator, TransformerMixin):
    def __init__(self):
        return None

    def fit(self, X=None, y=None):
        return self

    def transform(self, X):
        return X.idxmax(axis="columns")

train_df, targets_df = load_dataset()
targets_df = targets_df[['Column_1', 'Column_2', 'Column_3']]
model = RandomForestRegressor()
model.fit(train_df, targets_df)
pipeline = PMMLPipeline([
    ('clf', model),
    ('transform', FeatureSelector())
])
```

If I run this I get
```
`Traceback (most recent call last):
  File "model_pipeline.py", line 127, in <module>
    main(args)
  File "model_pipeline.py", line 81, in main
    ('transform', FeatureSelector())
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/sklearn2pmml/pipeline/__init__.py", line 55, in __init__
    super(PMMLPipeline, self).__init__(steps = steps, memory = memory, verbose = verbose)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/sklearn/utils/validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/sklearn/pipeline.py", line 118, in __init__
    self._validate_steps()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/sklearn/pipeline.py", line 171, in _validate_steps
    "'%s' (type %s) doesn't" % (t, type(t)))
TypeError: All intermediate steps should be transformers and implement fit and transform or be the string 'passthrough' 'RandomForestRegressor()' (type <class 'sklearn.ensemble._forest.RandomForestRegressor'>) doesn't`
```
The shape of train_df is (5000, 250), the shape of targets_df is (5000, 5)
My random forest regressor here outputs 3 values, and I want to add a step after the random forest regressor to my PMMLPipeline which gives me the column name/ index of the maximum value (what I want to do is similar to np.argmax(X, axis=1)). Can I do it?
I have also looked into FunctionTransformer, ExpressionTransformer but I am unsure how to use it here? Any help is appreciated.

**Comment by vruusmann** [comment]
> ```python
> pipeline = PMMLPipeline([
>     ('clf', model),
>     ('transform', FeatureSelector())
> ])
> ```
> If I run this I get
> ```
> `TypeError: All intermediate steps should be transformers and implement fit and transform or be the string 'passthrough' 'RandomForestRegressor()' (type <class 'sklearn.ensemble._forest.RandomForestRegressor'>) doesn't
> ```

This `TypeError` is raised by the Scikit-Learn framework base layer (not SkLearn2PMML frontend), because by Scikit-Learn conventions it is not permitted to have an estimator object on a non-final pipeline position. In your case, the `RandomForestRegressor` object is located on a second-to-last position, and therefore Scikit-Learn tries to execute it using transformer-style API (ie. the `transform(X)` method).

> My random forest regressor here outputs 3 values

The conversion of multi-output random forest models is currently not supported (but is expected to come in the nearest future).

You'd need to use `sklearn.multioutput.MultiOutputRegressor(RandomForestRegressor) currently.

> I want to add a step after the random forest regressor to my PMMLPipeline which gives me the column name/ index of the maximum value (what I want to do is similar to np.argmax(X, axis=1)). Can I do it?

You can post-process the predictions made by the final estimator step by specifying the `PMMLPipeline.predict_transformer` attribute. Obviously, there is no direct support for the `numpy.argmax` function, but you should be able to implement its logic manually using the `sklearn2pmml.preprocessing.ExpressionTransformer` transformer.

Something like this:
```python
pipeline = PMMLPipeline([...], predict_transformer = EstimatorTransformer("X[1] if X[1] > X[0] else X[0]"))
```

If you're just interested in receiving the maximum predicted value (out of the five predicted values), then the `sklearn2pmml.preprocessing.Aggregator(function = "max")` might be helpful.

**Comment by vruusmann** [comment]
More technical details about post-processing Scikit-Learn predictions: https://openscoring.io/blog/2022/05/06/sklearn_prediction_postprocessing/

**Comment by Rajeshyd0308** [comment]
Hey @vruusmann , 

Is there a more elegant way to do this?
```
pipeline = PMMLPipeline([
        ('mapper', DataFrameMapper(mapper)),
        ('clf', model)
    ], predict_transformer = ExpressionTransformer("0 if (X[0] >= X[1]) and (X[0] >= X[2]) else 1 if (X[1] >= X[0]) and (X[1] >= X[2]) else 2"))
```
I have used ExpressionTransformer to get the index of maximum element. If I had 4 output elements, this implementation gets clumsy. I was wondering if there was a better way to do this?

**Comment by vruusmann** [comment]
You could generate the expression string programmatically... Figure out a formula that generalizes to any number of outputs.

> Is there a more elegant way to do this?

Emulating the `numpy.argmax` function:

1. Calculate the maximum predicted value by applying `sklearn2pmml.preprocessing.Aggregator(function = "max")`.
2. Compare this value one-by-one with predicted values; return the index of the first match.

Implementing the first operation:
```python
FeatureUnion([
  ("identity", "passthrough"),
  ("max", Aggregator(function = "max"))
])
```

Implementing the second operation (please note that the maximum value is the last column, which can be conveniently accessed using the negative array indexing syntax):
```python
ExpressionTransformer("0 if X[0] == X[-1] else 1 if X[1] == X[-1] else ..")
```

This latest expression string should be pretty easy to generate programmatically.
