### ISSUE TITLE
Cannot save SVC model

### ISSUE THREAD

**Issue by SRL94** [jpmml/sklearn2pmml#349]
I have a problem when saving the SVC model using sklearn2pmml. My data is binary classification and my python is 3.6.13. I don't know how to specify the number of outputs. Any help would be appreciated!
My code:
```
train_file = "../Data/train.xlsx"
df_train = pd.read_excel(train_file).iloc[:, 2:9]
X = df_train.iloc[:,0:6].values
y = df_train.iloc[:,-1].values
pipeline = PMMLPipeline([('classifier', svm.SVC())])
pipeline.fit(X, y)
sklearn2pmml(pipeline, 'model.pmml', with_repr=True)
```
Error:
```
Standard output is empty
Standard error:
Exception in thread "main" java.lang.IllegalArgumentException: The estimator object of the final step (Python class sklearn.svm._classes.SVC) does not specify the number of outputs
	at sklearn2pmml.pipeline.PMMLPipeline.initTargetFields(PMMLPipeline.java:564)
	at sklearn2pmml.pipeline.PMMLPipeline.encodePMML(PMMLPipeline.java:132)
	at com.sklearn2pmml.Main.run(Main.java:91)
	at com.sklearn2pmml.Main.main(Main.java:66)

Traceback (most recent call last):
  File "2_SVM.py", line 47, in <module>
    sklearn2pmml(pipeline, 'model.pmml', with_repr=True)
  File "/anaconda3/envs/test/lib/python3.6/site-packages/sklearn2pmml/__init__.py", line 286, in sklearn2pmml
    raise RuntimeError("The SkLearn2PMML application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams")
RuntimeError: The SkLearn2PMML application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams
```

**Comment by vruusmann** [comment]
The (J)PMML converter needs to know how many target fields (aka labels, aka outputs) there will be, and what will be their names.

In the majority of cases this information is picked up automatically when doing `PMMLPipeline.fit(X, y)` - the dimensionality of `y` is the number of target fields, and the column names of `y` will be their names (assuming that the type of `y` is either `pandas.DataFrame` or `pandas.Series`).

If this information could not be collected during `PMMLPipeline.fit(X, y)`, then (J)PMML converter queries the final estimator step for it. For example, the number of target fields typically equals the value of the `estimator.n_outputs_` attribute.

> I don't know how to specify the number of outputs.

You're doing `PMMLPipeline.fit(X, y)`, but for some reason you're destroying any `y` meta-information by converting it from `pandas.DataFrame` to plain Numpy array. You should keep `y` as-is:

```python
df_train = pd.read_excel(train_file).iloc[:, 2:9]
X = df_train.iloc[:,0:6].values
# DONT'T DO THIS
# y = df_train.iloc[:,-1].values
# DO THIS
y = df_train.iloc[:, -1]
```

Alternatively, you can specify the `PMMLPipeline.target_fields` attribute:
```python
pipeline = PMMLPipeline([..])
pipeline.fit(X, y)

# Alternatively, you can do this
pipeline.target_names = ["my_target"]
```

**Comment by SRL94** [comment]
Thank you very much! It works.
