### ISSUE TITLE
Discrepancy with xgboost + TFIDF on prediction between Python and Java

### ISSUE THREAD

**Issue by rllmsu** [jpmml/sklearn2pmml#350]
Hello Villu,

I am using Kaggle sms data to train a tf-idf based model. 
```
spam_tfidf = TfidfVectorizer(
    sublinear_tf=True,
    analyzer='word',
    norm=None,
    token_pattern=r'\w{2,}',
    ngram_range=(1, 1))

param = {
 'learning_rate': 0.03,
 'max_depth': 6,
 'objective': 'binary:logistic',
 'eval_metric': 'auc',
 'booster': 'gbtree',
 'random_state': 1,
 'seed': 19,
 'n_estimators': 60}

clf = xgb.XGBClassifier(**param)

pmml_pipeline = PMMLPipeline([
    ('transformer', spam_tfidf),
    ('classifier', clf)
])

pmml_pipeline.fit(X_train['t1'], y_train)

sklearn2pmml(pmml_pipeline, "p1.pmml", with_repr=True, debug=True)
```

There is no difference in prediction between Python model(clf) and pmml(p1) conversion using sklearn2pmml, when I score the same data set in Python environment.

```
            p1	clf
0	0.100646	0.100646
1	0.690893	0.690893
2	0.100646	0.100646
3	0.115224	0.115224
4	0.100646	0.100646
...	...	...
1667	0.100646	0.100646
1668	0.100646	0.100646
1669	0.306784	0.306784
1670	0.100646	0.100646
1671	0.599164	0.599164
```

However, when I deploy the pmml on Java, it has a big difference in terms of prediction.
using the first row, with both p1 and clf have 0.100646 prediction as an example:

`ProbabilityDistribution{result=0, probability_entries=[1=0.48102915, 0=0.51897085]}`

0.100646  vs 0.48102915. Such a difference applies to the rest data as well.

`I used org.jpmml.evaluator.* library.`
Code part as below:

```
protected Evaluator modelEvaluator;
Map<String, FieldValue> arguments = new LinkedHashMap<>();

List<InputField> inputFields = modelEvaluator.getInputFields();
for(InputField inputField : inputFields){

      String inputName = inputField.getName();

      Object rawValue = inputDataRecord.get(inputName);

      FieldValue inputValue = inputField.prepare(rawValue);

      arguments.put(inputName, inputValue);
}
 Map<String, ?> evaluateResult = modelEvaluator.evaluate(arguments);
```

Could you help please?

Thanks,

**Comment by vruusmann** [comment]
TF(-IDF) and XGBoost don't integrate very well with each other in Scikit-Learn environment. The TF(-IDF) transformation is special, because it outputs a sparse data matrix by default (regular transformations output a dense data matrix). The XGBoost model interprets "sparse entries" as missing cells, when it should be interpreting them as zero-count cells.

Believe or not, but Python predictions are wrong, and (J)PMML predictions are correct! Try it out yourself - Python predictions change when you transform your TF(-IDF) data matrix from sparse to dense representation. (J)PMML predictions are aligned with dense data matrix prediction.

Full explanation here:
https://openscoring.io/blog/2021/02/27/sklearn_tf_tfidf_xgboost_pipeline/

**Comment by rllmsu** [comment]
Thanks so much for the quick response, Villu! I do get Python and Java predictions matched after adding a dense layer for dataset with English only. However, if I include multiple languages, the results are not consistent. Do you have any suggestions. Thanks!

**Comment by vruusmann** [comment]
> However, if I include multiple languages, the results are not consistent.

Multiple languages in a single dataset, or multiple datasets with a single language in each? What language(s) - some Latin family language, or some Asian language?

Could be several things. Perhaps related to stop-words, perhaps some RegEx/Unicode interaction (TF-IDF tokens are extracted using a RegEx pattern, which has multiple RegEx compiler flags available). You have the dataset, you should be able to figure out a common pattern between matching/mismatching sentences easily.

Possibly related to https://github.com/jpmml/jpmml-sklearn/issues/165
