### ISSUE TITLE
Does pipleline support custom fit_transform?

### ISSUE THREAD

**Issue by qianjiangchao1992** [jpmml/sklearn2pmml#353]
I need a custom method for data cleaning, and then encapsulate it into a transform

**Comment by vruusmann** [comment]
> Does pipleline support custom fit_transform?

The `PMMLPipeline` meta-estimator class does not discriminate between steps based on their "origin". You can mix standard Scikit-Learn steps with third-party steps (eg. Imbalanced-Learn, XGBoost) or your own custom steps.

This question was probably meant as "How do I develop and use my own custom transformer class?". Well, it has been explained before, but the explanation is scattered between several issues in JPMML-SkLearn/Sklearn2PMML projects, and the JPMML mailing list.

For starters, see how I've implemented standard Scikit-Learn transformers in the JPMML-SkLearn project. Implementing a custom transformer will be technically exactly the same.
