### ISSUE TITLE
Renaming multiple columns with the `Alias` decorator

### ISSUE THREAD

**Issue by hjh1011** [jpmml/sklearn2pmml#359]
I am currently working on 3 classes multi-classification problem with `xgb.XGBClassifier`. In the binary classification case, I can easily add an extra column `Predicted_y` into the final output with
```python
alias = Alias(ExpressionTransformer("X[1]"), name='Predicted_y', prefit=True)
PMML_pp = PMMLPipeline(steps=steps, predict_proba_transformer = alias)
```
However, Is it possible if I wish to take the default 3 column output of my model and rename and add them as, for example, `predicted_proba_class0, predicted_proba_class1, predicted_proba_class2` ? Thank you

**Comment by vruusmann** [comment]
> Is it possible if I wish to take the default 3 column output of my model and rename and add them
>

You only want to rename columns (for example, you don't like JPMML default naming scheme like `probability(<value>)`), not do anything useful with them?

If so, then seems like a new issue - develop an API for customizing default names (there is already an API for renaming transformed field names, but not for renaming model output field names).

Anyway, in Scikit-Learn, you can do "parallel" feature transformations using the `sklearn.pipeline.FeatureUnion` meta-transformer:
https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.FeatureUnion.html

This will rename all three output columns:
```python
alias_3d = FeatureUnion([
  ("first", Alias(ExpressionTransformer("X[0]"), name = "first_proba", prefit = True)),
  ("second", Alias(ExpressionTransformer("X[1]"), name = "second_proba", prefit = True)),
  ("third", Alias(ExpressionTransformer("X[2]"), name = "third_proba", prefit = True)),
])
```

This `alias_3d` transformation will give you a `(, 3)` data matrix as output when doing `TransformerMixin.(fit_)transform(X)`.

**Comment by vruusmann** [comment]
> If so, then seems like a new issue - develop an API for customizing default names (there is already an API for renaming transformed field names, but not for renaming model output field names).

Another perspective - simply add multi-feature support to the `sklearn2pmml.decoration.Alias` class.

Something like this:
```python
alias = Alias(IdentityTransformer(), name = ["first_proba", "second_proba", "third_proba"], prefit = True)
```

**Comment by hjh1011** [comment]
> > Is it possible if I wish to take the default 3 column output of my model and rename and add them
> 
> You only want to rename columns (for example, you don't like JPMML default naming scheme like `probability(<value>)`), not do anything useful with them?
> 
> If so, then seems like a new issue - develop an API for customizing default names (there is already an API for renaming transformed field names, but not for renaming model output field names).
> 
> Anyway, in Scikit-Learn, you can do "parallel" feature transformations using the `sklearn.pipeline.FeatureUnion` meta-transformer: https://scikit-learn.org/stable/modules/generated/sklearn.pipeline.FeatureUnion.html
> 
> This will rename all three output columns:
> 
> ```python
> alias_3d = FeatureUnion([
>   ("first", Alias(ExpressionTransformer("X[0]"), name = "first_proba", prefit = True)),
>   ("second", Alias(ExpressionTransformer("X[1]"), name = "second_proba", prefit = True)),
>   ("third", Alias(ExpressionTransformer("X[2]"), name = "third_proba", prefit = True)),
> ])
> ```
> 
> This `alias_3d` transformation will give you a `(, 3)` data matrix as output when doing `TransformerMixin.(fit_)transform(X)`.

This works for me, Thank you!

**Comment by vruusmann** [comment]
> This works for me

The proposed solution is too much typing. Consider refactoring it into a reusable utility function:

```python
def make_column_renamer(names):
  steps = []
  i = 0
  for name in names:
    # Append a two-element tuple
    steps.append((name, Alias(ExpressionTransformer("X[" + str(i) + "]", name = name, prefit = True))))
    i = i + 1
  return FeatureUnion(steps)
```
