### ISSUE TITLE
LabelEncoder + Inputer + LabelBinarizer in mapper fails

### ISSUE THREAD

**Issue by paubelsan** [jpmml/sklearn2pmml#36]
Hi,

It looks like setting a Label Binarizer after an Imputer in a mapper fails.

```
mapper = DataFrameMapper([      
           (['column'], [LabelEncoder(), Imputer(), LabelBinarizer()]),                                                                                                                                  
])
```

`-> ValueError: Multioutput target data is not supported with label binarization`

I think that the problem comes from the Imputer. Out of it, the data has dimensions of (1, n_samples) instead of (n_samples, 1). The new CategoricalImputer from the sklearn-pandas works but it can't be exported to PMML. Any help to fix this?

Many thanks!!

**Comment by vruusmann** [comment]
> ValueError: Multioutput target data is not supported with label binarization

This error belongs 100% to Scikit-Learn. It happens even if your workflow doesn't contain any PMML-related classes (eg. `PMMLPipeline`) in it.

The solution is to add support for the `sklearn_pandas.CategoricalImputer` transformer class. Also, should check what else has changed between sklearn_pandas versions 1.3.0 and 1.4.0.

**Comment by paubelsan** [comment]
Ok, thanks! I've seen that the problem comes from calling check_array in Sklearn's imputer, that calls Numpy's atleas_2d and transfroms (n_samples,) to (1,n_samples). Nevertheless I've reported it to sklearn-pandas, as I think it's a DataFrameMapperIssue.
