### ISSUE TITLE
The `StringNormalizer` transformer should perform input validation

### ISSUE THREAD

**Issue by liuhuanshuo** [jpmml/sklearn2pmml#366]
I use sklearn2pmml for conversion, and it works fine in the pipeline.

But when I read the saved pmml and make a prediction, it has a problem
```
 Py4JJavaError                             Traceback (most recent call last)
~/.local/lib/python3.7/site-packages/jpmml_evaluator/__init__.py in evaluateAll(self, arguments_df, nan_as_missing)
    128                 try:
--> 129                         result_records = self.backend.staticInvoke("org.jpmml.evaluator.python.PythonUtil", "evaluateAll", self.javaEvaluator, argument_records)
    130                 except Exception as e:

~/.local/lib/python3.7/site-packages/jpmml_evaluator/py4j.py in staticInvoke(self, className, methodName, *args)
     24                 javaMember = javaClass.__getattr__(methodName)
---> 25                 return javaMember(*args)
     26 

~/.local/lib/python3.7/site-packages/py4j/java_gateway.py in __call__(self, *args)
   1322         return_value = get_return_value(
-> 1323             answer, self.gateway_client, self.target_id, self.name)
   1324 

~/.local/lib/python3.7/site-packages/py4j/protocol.py in get_return_value(answer, gateway_client, target_id, name)
    327                     "An error occurred while calling {0}{1}{2}.\n".
--> 328                     format(target_id, ".", name), value)
    329             else:

Py4JJavaError: An error occurred while calling z:org.jpmml.evaluator.python.PythonUtil.evaluateAll.
: org.jpmml.evaluator.MissingArgumentException: Function "trimBlanks" cannot accept missing value at position 0
 at org.jpmml.evaluator.functions.AbstractFunction.getRequiredArgument(AbstractFunction.java:101)
 at org.jpmml.evaluator.functions.AbstractFunction.getArgument(AbstractFunction.java:76)
 at org.jpmml.evaluator.functions.UnaryFunction.evaluate(UnaryFunction.java:43)
 at org.jpmml.evaluator.ExpressionUtil.evaluateFunction(ExpressionUtil.java:463)
 at org.jpmml.evaluator.ExpressionUtil.evaluateApply(ExpressionUtil.java:426)
 at org.jpmml.evaluator.ExpressionUtil.evaluateExpression(ExpressionUtil.java:167)
 at org.jpmml.evaluator.ExpressionUtil.evaluate(ExpressionUtil.java:129)
 at org.jpmml.evaluator.ExpressionUtil.evaluateExpressionContainer(Expr
```
It seems that it can't handle null values, but my pipeline can work, I just converted it into a pmml file, and under the same data, it doesn't work

In addition, in order to make it easier for you to understand my problem, in fact, I only performed some conversions on the data during the entire process of using sklearn2pmml, specifically the following code
```
mapper_encode = [
 ('d15_once_called_opst_phone_cnt',[CutTransformer(bins = all_num_dict['d15_once_called_opst_phone_cnt'])
                                    ,StringNormalizer(function=None)
                                    ,LookupTransformer(mapping=WOE['d15_once_called_opst_phone_cnt'], default_value=0.0)]),    
 ('d1_called_dur_under_10s_cnt_rt',[CutTransformer(bins = all_num_dict['d1_called_dur_under_10s_cnt_rt'])
                                    ,StringNormalizer(function=None)
                                    ,LookupTransformer(mapping=WOE['d1_called_dur_under_10s_cnt_rt'], default_value=0.0)]),
 ('d15_called_dur_under_10s_cnt_rt',[CutTransformer(bins = all_num_dict['d15_called_dur_under_10s_cnt_rt'])
                                     ,StringNormalizer(function=None)
                                     ,LookupTransformer(mapping=WOE['d15_called_dur_under_10s_cnt_rt'], default_value=0.0)]),
 ('d7_once_opst_phone_cnt_rt',[CutTransformer(bins = all_num_dict['d7_once_opst_phone_cnt_rt'])
                               ,StringNormalizer(function=None)
                               ,LookupTransformer(mapping=WOE['d7_once_opst_phone_cnt_rt'], default_value=0.0)]),
 ('d15_once_opst_phone_cnt_rt',[CutTransformer(bins = all_num_dict['d15_once_opst_phone_cnt_rt'])
                                ,StringNormalizer(function=None)
                                ,LookupTransformer(mapping=WOE['d15_once_opst_phone_cnt_rt'], default_value=0.0)]),
 ('d15_daytime_opst_phone_called_cnt_rt',[CutTransformer(bins = all_num_dict['d15_daytime_opst_phone_called_cnt_rt'])
                                          ,StringNormalizer(function=None)
                                          ,LookupTransformer(mapping=WOE['d15_daytime_opst_phone_called_cnt_rt'], default_value=0.0)]),
 ('d1_under15s_called_opst_phone_cnt_rt',[CutTransformer(bins = all_num_dict['d1_under15s_called_opst_phone_cnt_rt'])
                                          ,StringNormalizer(function=None)
 ```
As a developer, can you see roughly what is going wrong and what direction should I go to fix it?

**Comment by vruusmann** [comment]
> It seems that it can't handle null values, but my pipeline can work,

The Python side is currently performing less sanity checks than the Java side. And the Java side is more correct here.

For example, the trim functionality is not applicable to missing strings:
```python
x = None
x.trim()
```

Raises:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'strip'
```

> in fact, I only performed some conversions on the data during the entire process of using sklearn2pmml, specifically the following code

The sample code does not use "trim whitespace" functionality in any way.

> `StringNormalizer(function=None)`

Seriously, what's the point of this operation?

**Comment by vruusmann** [comment]
Leaving this issue open as a reminder to apply stricted missingness checks all across `sklearn2pmml.preprocessing` module.

Also, perhaps it would be right to disable `StringNormalizer(function = None)` setup.

**Comment by liuhuanshuo** [comment]
> 
> Also, perhaps it would be right to disable `StringNormalizer(function = None)` setup.

StringNormalizer(function = None) is to convert data to STRING format

**Comment by vruusmann** [comment]
> StringNormalizer(function = None) is to convert data to STRING format

I remember telling you earlier, that this transformer IS NOT meant for data type conversions.

Besides, the sequence `[CutTransformer(), LookupTransformer()]` should work perfectly fine using numeric values. There is absolutely no need to convert anything to strings. This just adds failure points.

**Comment by vruusmann** [comment]
>  the sequence [CutTransformer(), LookupTransformer()] should work perfectly fine using numeric values. 

The `CutTransformer` allows you to specify bin labels using the `labels` argument. Take your `LookupTransfotrmer` dict values, and put them in there.

**Comment by liuhuanshuo** [comment]
> I remember telling you earlier, that this transformer IS NOT meant for data type conversions.

I can't believe you remember the dumb question I asked earlier.

Yes, I fully remember what you said at the time, but what I didn't tell you at the time is that when I used CastTransformer conversion in the situation at the time, it didn't work. I tried many functions, only to find that StringNormalizer(function = None ) kick in!

I will follow your tip, remove StringNormalizer and try again

**Comment by liuhuanshuo** [comment]
I followed your suggestion, deleted the StringNormalizer(function = None ) and used CastTransformer for conversion.

Now the converted pmml file prediction will not report an error, but it differs from the pipeline before the conversion in the data containing null values.

The following is the result of the pipeline prediction before conversion, it is correct
![](https://pic.liuzaoqi.com/picgo/202212162155775.png)

And the following is predicted by the pmml file. It seems that if the data contains null values, it is predicted to be None.
![](https://pic.liuzaoqi.com/picgo/202212162158164.png)

**Comment by liuhuanshuo** [comment]
It seems that I encountered some strange problem again

**Comment by vruusmann** [comment]
Will probably delete the `StringNormalizer` transformer one day (likely when SkLearn2PMML version 1.0.0 hits).

All string manipulation functionality (lower, upper, trim) is already available via `sklearn2pmml.preprocessing.ExpressionTransformer`.
