### ISSUE TITLE
Excuse me, can I convert the vgg .pkl trained by pytroch to pmml format through sklean2pmml

### ISSUE THREAD

**Issue by danxuan2022** [jpmml/sklearn2pmml#368]
Excuse me, can I convert the vgg .pkl trained by pytroch to pmml format through sklean2pmml, I found that there are many traditional machine learning that can be successfully converted to pmml, but the deep learning model is used less.

**Comment by vruusmann** [comment]
> can I convert the vgg .pkl trained by pytroch to pmml format through sklean2pmml,

No.

> there are many traditional machine learning that can be successfully converted to pmml, but the deep learning model is used less.

That's the point!

PMML is used for "classical" machine learning (ML) models. Deep learning (DL) is a completely different discipline than ML, and therefore classical ML tools and approaches are not applicable.

For DL, please use ONNX.
