### ISSUE TITLE
Is there a way to generate a derived field using another derived field?

### ISSUE THREAD

**Issue by stars-Universe** [jpmml/sklearn2pmml#372]
Hello,

I'm trying to write some Python code to create two derived fields, one that is generated by multiplying two data fields called `original_product`, and another that is generated by multiplying a constant, let's say 5, to `original_product` called `final_product`. The reason I want to separate this out into two distinct fields is because I will need to use `original_product` again to create another derived field later on, and want to verify the first step can actually be done (i.e., generating one derived field from another in `sklearn2pmml`).

What I have now is the following:

```
# data is a dataframe with x1 and x2 as columns and some arbitrary target field

mapper = DataFrameMapper([
    (["x1", "x2"], Alias(ExpressionTransformer("X[0] * X[1]"), "original_product")),
    (["original_product"], Alias(ExpressionTransformer("X[0]" * 5], "final_product"))])

pipeline = PMMLPipeline([
    ("mapper", mapper),
    ("regression", LinearRegression())
])

pipeline.fit(data[features], data[target])
sklearn2pmml(pipeline, "test.pmml", with_repr=True)

```
With the code written that way, I get a KeyError because `original_product` is derived, therefore not existent within the input set of the Mapper; but, if I remove the tuple for `final_product`, I get a PMML file that correctly creates a `DerivedField` called `original_product` in the `LocalTransformations` section of the Model element.

So, I'm wondering how I can get it to add in `final_product` programmatically. Is there a specific way I should be writing this, either with `DataFrameMapper` or `ColumnTransformer`? Or does `sklearn2pmml` not support derived fields being defined by other derived fields?

**Comment by vruusmann** [comment]
The feature definitions of `DataFrameMapper` are executed in isolation from one another. It is impossible to reference a newly defined feature (eg. "original_product") from within its sibling feature definitions.

But you can always split the data flow inside one feature definition using the `FeatureUnion` meta-transformer.

Something like this:
```python
mapper = DataFrameMapper([
  (["x1", "x2"], Alias(ExpressionTransformer("X[0] * X[1]"), "original_product"), FeatureUnion([("identity", IdentityTransformer()), ("scaled", Alias(ExpressionTransformer("X[0]" * 5], "final_product"))]))
])
```

Now you have one feature definition with two ends - one giving you "original_product", and the other giving you "5 * original_product" aka "final_product".

I didn't run the above code, but it should work fine both in Python and (SkLearn2)PMML.

**Comment by vruusmann** [comment]
Updated my previous code example, because it appears to miss some brackets and stuff.

Here's the same, in expanded format:
```python
split_tail = FeatureUnion([
  ("identity", IdentityTransformer()),
  ("scaled", Alias(ExpressionTransformer("X[0] * 5"), "final_product"))
])

mapper = DataFrameMapper([
  (["x1", "x2"], [Alias(ExpressionTransformer("X[0] * X[1]"), "original_product"), split_tail])
])
```
