### ISSUE TITLE
Pipeline and Loaded Model Gives Different Probabilities

### ISSUE THREAD

**Issue by aliyilmaz61** [jpmml/sklearn2pmml#373]
Hello,
I created a pipeline with pre trained xgboost model and save with sklearn2pmml. When i load model from pmml file and predict result is different from pipeline's proba that is real probabilty of the xgboost.

pipeline = PMMLPipeline(
    steps=[
        ('preprocessor_1', mapper_1),
        ('preprocessor_2',mapper_2),
        ('estimator',digital_xgb_model)
        ])

pipeline.target_fields = ["probability0"]

pipeline.predict_proba(data)

array([[0.14882231, 0.8511777 ]], dtype=float32)

#save pmml
sklearn2pmml(pipeline,"pipeline_digital_xgb_model.pmml")

#load pmml model
from pypmml import Model
pipeline_digital_xgb_model = Model.fromFile('pipeline_digital_xgb_model.pmml')

pipeline_digital_xgb_model.predict(data)

probability(0)	probability(1)
0	0.188476	0.811524

**Comment by vruusmann** [comment]
I don't do support for 3rd party packages such as PyPMML.

Play stupid games, win stupid prizes.

**Comment by aliyilmaz61** [comment]
This is an inappropriate behaving in open source world.
You are not put a foot wrong but you didnt suggest an alternative way instead the third party ones like  pypmml.
