### ISSUE TITLE
what is an x-multiModelChain

### ISSUE THREAD

**Issue by AtharvaGh** [jpmml/sklearn2pmml#374]
Hello, I generated a simple PMML file using this code

```python
knn = RandomForestClassifier(n_neighbors=3)

clf = PMMLPipeline( [ ( "classifier", MultiOutputClassifier(knn, n_jobs=-1 ) ) ] )
clf.fit(X_train, y_train)
clf.score(X_test, y_test)
sklearn2pmml(clf, "rftest.pmml", with_repr=True)
```

But in the pmml file, In the segmentation tag this is appearing
![image](https://user-images.githubusercontent.com/88076183/222705463-bb0114b9-3682-4e50-a7da-58a4b9d59d23.png)

The problem happens when i try to load my pmml file using pypmml

When i change the X-multiModelChain to modelChain like in the pmml 4.4 specification given at [https://dmg.org/pmml/v4-4/MultipleModels.html](url)

Is this a problem with multiOutputClassifier?
Am i misunderstanding something or is there a special way to load these files?

**Comment by vruusmann** [comment]
The `multiModelChain` is a new multiple model method, as proposed/documented in DMG issue no. 233: http://mantis.dmg.org/view.php?id=233

It's a multioutput companion to the existing `modelChain` multiple model method. The `x-` prefix indicates that this is a vendor extension. 

> When i change the X-multiModelChain to modelChain like in the pmml 4.4 specification given at [https://dmg.org/pmml/v4-4/MultipleModels.html](https://github.com/jpmml/sklearn2pmml/issues/url)

If you change `x-multiModelChain` manually to `modelChain`, then you lose multioutput support.

> Am i misunderstanding something or is there a special way to load these files?

It's fully supported across JPMML producers and consumers.
