### ISSUE TITLE
Revert PMML file to Python source code

### ISSUE THREAD

**Issue by liuhuanshuo** [jpmml/sklearn2pmml#387]
A few months ago, I developed a pmml file using sklearn2pmml.

It is through constructing multiple steps such as mapper and model, and then saving the PMMLPipeline file as a pmml file

Now, I want to modify the mapper part of this pmml file, but I lost the original python code, there is only one pmml file

Does sklearn2pmml provide a method to restore the pmml file to the Pipeline in Python?

**Comment by vruusmann** [comment]
The `sklearn2pmml.sklearn2pmml(...)` utility function has `with_repr` boolean parameter. When active, it initializes the `PMMLPipeline.repr_` attribute:

```python
pipeline = PMMLPipeline(...)
pipeline.repr_ = repr(pipeline)
```

If you have the original `PMMLPipeline` object available, then take a look if it has the `repr_` attribute set or not. If it does, then this is Python source code that you're after.

If the original `PMMLPipeline` object is not available, then open the corresponding PMML document in text editor, and see if the value of the `repr_` attribute is embedded in there or not. It should be close to the head section of the file, in the form of a `/PMML/MiningBuildTask/Extension@name="repr"` element. This is the same Python source code.
