### ISSUE TITLE
Revisit the missing value handling of custom transformers

### ISSUE THREAD

**Issue by vruusmann** [jpmml/sklearn2pmml#395]
Discovered here: https://github.com/jpmml/sklearn2pmml/issues/394#issuecomment-1726419346

A transformer class should define a `map_missing_to` attribute when the resulting PMML transdormation element has such capabilities (ie. different processing paths for missing and invalid values).

Right now, only the `ExpressionTransformer` class has both `default_value` and `map_missing_to` attributes.

**Comment by jhaneyrf** [comment]
Here's a sample script that shows the output I see on my system:
---------------------------------------------------------------------------------------------
import pandas as pd
from sklearn2pmml.preprocessing import LookupTransformer

VARIABLE22_DICT = {
        "A": 0,
        "B": 1,
        "C": 2,
        "D": 3}

TRANSFORMER = LookupTransformer(VARIABLE22_DICT, default_value=3), ["variable22"])],
TRANSFORMER.fit(pd.DataFrame({"variable22": ["A", "B", "C", "D"] * 2}))

X = pd.DataFrame({"variable22": ["A"] * 32231 + ["B"] * 92191 + ["C"] * 67099 + ["D"] * 112332 +[None] * 55863})

print(RESULTS = pd.DataFrame(TRANSFORMER.transform(X), columns=["variable22"]))

print("Original counts")
print(X["variable22"].value_counts(dropna=False))

print("Transformed counts")
RESULTS["variable22"].value_counts(dropna=False)
---------------------------------------------------------------------------------------------
Output:

Original counts
D     112332
B     92191
C      67099
None       55863
A        32231
...
Transformed counts
3    168195
1     92191
2     67099
0     32231
------------------------------------------------------------------------
It does appear that LookupTransformer is using the default_value setting to fill NaNs in Python, but the PMML file created by sklearn2pmml does not do that.
