### ISSUE TITLE
'Alias' object has no attribute 'transformer_'

### ISSUE THREAD

**Issue by woodly0** [jpmml/sklearn2pmml#398]
Hello again,

would it be possible for the `predict_proba_transformer` parameter to have an alias? Something like:
```py
pmml_pipe = PMMLPipeline(
    [
        ("mapper", mapper),
        ("clf", LogisticRegression()),
    ],
    predict_proba_transformer=Alias(
        ExpressionTransformer(
            "numpy.floor(9.999 - 9 * X[1])"  # custom
        ),
        "example_score",
    ),
)

pmml_pipe.fit(X, y)
pmml_pipe.predict_proba_transform(X)
```
The code above throws the error in the title.

**Comment by vruusmann** [comment]
According to Scikit-Learn conventions, the `Alias.transformer_` attribute is generated (based on the `Alias.transformer` attribute) by the `Alias.fit(...)` method.

If the `Alias.transformer` attribute holds an already fitted transformer object, then you should indicate it in the Alias constructor using the `prefit = True` flag.

> would it be possible for the predict_proba_transformer parameter to have an alias?

Of course it is.

In your case, the `Alias` object is unfitted. However, it holds an `ExpressionTransformer` object, which is a stateless transformer (its initial/unfitted and final/fitted states are identical).

Just set the `prefit = True` flag, and everything will work fine:

```python
pipeline = PMMLPipeline([...], predict_proba_transforme = Alias(ExpressionTransformer(...), name = "example_score", prefit = True))
```

**Comment by woodly0** [comment]
Thank you Sir. I thought there will be an obvious solution :)

**Comment by woodly0** [comment]
A short additional question: 
If the `predict_proba_transform()` method is called, the default output contains an array of the probabilities (I guess from the `predict_proba()` call) plus the transformed output. Is there a way to remove the initial output fields and only output the last value?

**Comment by vruusmann** [comment]
>  Is there a way to remove the initial output fields and only output the last value?

Use a `Pipeline` object, where the first step is `Alias(ExpressionTransformer(..))`, and the second step is some [`SelectorMixin`](https://scikit-learn.org/stable/modules/generated/sklearn.feature_selection.SelectorMixin.html) or some other column selection-capable meta-transformer. For example, [`ColumnTransformer`](https://scikit-learn.org/stable/modules/generated/sklearn.compose.ColumnTransformer.html) (drop first two columns, passthrough the third column).

**Comment by vruusmann** [comment]
> The following code complains about the fact that the ColumnTransformer is not fitted which I understand but don't know how to resolve. 

The `ColumnTransformer` transformer is (pseudo-)stateful - it inherits its "stateful" property from its member transformers. In principle, both `passthrough` and `drop` should qualify as stateless transformers. But indeed, there is no `prefit` flag to force this knowledge.

If you want to continue the `ColumnTransformer` route, then you must call its `fit(X)` method before inserting it into the pipeline. The easiest way to do it is to compile the post-processor pipeline object in a stepwise manner:

```python
pipeline = PMMLPipeline([...])

# First step
postproc_pipeline = make_pipeline(Alias(ExpressionTransformer(...)))
step1_result = postproc_pipeline.fit_transform(pipeline.predict_proba(X))

# Second step
postproc_pipeline = make_pipeline(postproc_pipeline, ColumnTransformer(...))
step2_result = postproc_pipeline.fit_transform(step1_result)

# Finally, assign the fully-fitted pipeline as post-processing transformer
pipeline.predict_proba_transformer  = postproc_pipeline
```

**Comment by vruusmann** [comment]
> The following code complains about the fact that the ColumnTransformer is not fitted which I understand but don't know how to resolve.

Alternatively, use some stateless (meta-)transformer such as `sklearn2pmml.util.Slicer`.

This should extract the last column:

```python
from sklearn2pmml.util import Slicer

slicer = Slicer(start = -1)
```

If you really want to hard-code your assumptions ("there are three columns overall, and I want to get the third column"):

```python
slicer = Slicer(start = 2, stop = 3)
```

Didn't test the above code. Relying on Python's array slicing syntax as stored in my memory.
