### ISSUE TITLE
ImportError: cannot import name 'LabelBinarizer' from 'sklearn2pmml.preprocessing'

### ISSUE THREAD

**Issue by mmarinaki** [jpmml/sklearn2pmml#408]
Hi! I updated the sklearn2pmml package version from 0.90.2 to 0.101.0 but even with updating, I still get this new error ImportError: cannot import name 'LabelBinarizer' from 'sklearn2pmml.preprocessing' which used to not exist before. Is that a bug? Thought I'd surface!

**Comment by mmarinaki** [comment]
Resolved by changing LabelBinarizer that used to work a couple of months ago to PMMLLabelBinarizer

**Comment by vruusmann** [comment]
There never was a `sklearn2pmml.preprocessingLabelBinarizer` class in the SkLearn2PMML package. It has always been a `PMMLLabelBnarizer` (a missing value-aware equivalent of LB).
