### ISSUE TITLE
Pandas 2.2 FutureWarning for time series offset aliases

### ISSUE THREAD

**Issue by woodly0** [jpmml/sklearn2pmml#416]
Hello Sir,

nothing urgent, but anyway:
```
/sklearn2pmml/util/__init__.py:88: FutureWarning: 'S' is deprecated and will be removed in a future version, please use 's' instead.
```

keep up the good work!

**Comment by vruusmann** [comment]
I wonder if the `s` alias is backwards compatible. There must be a reason why I chose to go with `S` back in the day (or was it simply the most upvoted SO answer?).

Anyway, are you doing some date/time work in PMML? Please share some interesting use cases, would love to expand the package functionality in that direction. Perhaps there's an opportunity to implement some new and interesting transformers, or smth.

**Comment by woodly0** [comment]
> I wonder if the s alias is backwards compatible. There must be a reason why I chose to go with S back in the day (or was it simply the most upvoted SO answer?).

It certainly is for now. I think they changed it recently.

> Anyway, are you doing some date/time work in PMML? Please share some interesting use cases, would love to expand the package functionality in that direction. Perhaps there's an opportunity to implement some new and interesting transformers, or smth.

Sure thing. I am calculating the feature customer age, i.e. number of years, based on `request_ts` and `date_of_birth`. These columns are both of dtype `datetime64[ns]`. That throws the warning mentioned above.

```python
mapper = DataFrameMapper(
    [
        (
            ["request_ts", "date_of_birth"],
            [
                DateTimeDomain(),
                DaysSinceYearTransformer(1999),
                ExpressionTransformer("numpy.floor((X[0] - X[1]) / 365)"),
            ],
            {"alias": "age"},
        ),
        ...
    ])
```
