### ISSUE TITLE
Pandas not installed as dependency

### ISSUE THREAD

**Issue by abdspc** [jpmml/sklearn2pmml#418]
After installing `sklearn2pmml` in a fresh python 3.10.11 environment via pip, I get the following error upon running `import sklearn2pmml` in a python shell:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/aberrian/tmp/.venv/lib/python3.10/site-packages/sklearn2pmml/__init__.py", line 1, in <module>
    from pandas import CategoricalDtype
ModuleNotFoundError: No module named 'pandas'
```

It looks like this error is caused by [this recent commit](https://github.com/jpmml/sklearn2pmml/commit/374e833e48db20a941d4ddef4282a8485946dd2c) where `sklearn-pandas` was removed as a dependency.

**Comment by vruusmann** [comment]
> After installing sklearn2pmml in a fresh python 3.10.11 environment via pip

The full package environment is defined in the requirements file:
https://github.com/jpmml/sklearn2pmml/blob/master/requirements.txt

If you're installing into an absolutely fresh environment, then perhaps you should run this command as well:
```
$ pip install -r requirements.txt
```

At least, that's what I do in GitHub Actions CI. (which is also a fresh environment) 

> It looks like this error is caused by this recent commit where sklearn-pandas was removed as a dependency.

Correct.

I was acting under the assumption that the parent Scikit-Learn package is already bringing in the `pandas` dependency, and child packages such as SkLearn2PMML don't need to do it again. I've got the impression that latest Scikit-Learn versions are already quite tightly integrated with Pandas. For example, everything related to the `set_output` API.

Do you have Scikit-Learn installed in the same environment? What other packages get installed? Perhaps you should move the SkLearn2PMML package to the end of the install list?

**Comment by vruusmann** [comment]
Anyway, the major point is that it should be possible to install the SkLearn2PMML package in an environment which only satisfies those "core" requirements:
https://github.com/jpmml/sklearn2pmml/blob/0.104.1/setup.py#L45-L49

And bonus points if the `sklearn2pmml.sklearn2pmml()` utility function stays fully functional.

The easiest way would be to surround any third party imports in the `/sklearn2pmml/__init__.py` file with an appropriate `try`-`except` construct.
