### ISSUE TITLE
Referencing input feature(s) during the post-processing in PMML pipeline

### ISSUE THREAD

**Issue by andru98** [jpmml/sklearn2pmml#424]
I want to implement a post processing step inside the pmml pipeline like below:

```python
pmml_pipeline=PMMLPipeline([
    ('preprocessor',mapper),
    ('regressor',XGBRegressor(n_estimators=200))
],predict_transformer = ExpressionTransformer("0 if (X[0] == 0)"))
```

(Expression transformer is just an example)

I am trying to implement a custom post-processing step inside a PMMLPipeline in which I want to manipulate the output of the regressor based on certain features of the input data. The goal is to apply multiple if-else conditions to the regressor's output.

Currently, I can only access the output from the regressor. I am looking for a way to modify the regressor's output using a custom function that takes both the input features and the regressor's output into account.Likewise, I want to manipulate the values of regressor output based on the values of certain features of input data—ideally multiple if-else statements based on the values of input data and output of the regressor.

If somebody can give insights on the approach to resolve this, that would be great. I appreciate any help you can provide.

**Comment by vruusmann** [comment]
The SkLearn2PMML package provides the `sklearn2pmml.cross_reference` module that extends Scikit-Learn pipelines with a "memorize column" vs. "recall column" functionality. This helps you "transfer" columns from one pipeline step to any of its successor steps, without building super-complicated `FeatureUnion` and `Pipeline` flows.

Cross-references are discussed here:
https://openscoring.io/blog/2023/11/25/sklearn_feature_cross_references/

In the current case, you need to:

1. Memorize the input feature column(s) using the `sklearn2pmml.cross_reference.Memorizer` pseudo-transformer.
2. Recall the memorized input feature column(s) inside the `PMMLPipeline.predict_transformer` sub-pipeline using the `sklearn2pmml.cross_reference.Recaller` pseudo-transformer.

For example:
```python
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn2pmml.cross_reference import Memory
from sklearn2pmml.cross_reference import make_memorizer_union, make_recaller_union
from sklearn2pmml.pipeline import PMMLPipeline

X, y = load_iris(return_X_y = True, as_frame = True)

memory = Memory()

pipeline = PMMLPipeline([
	("memorizer", make_memorizer_union(memory = memory, names = X.columns.values.tolist())),
	("classifier", DecisionTreeClassifier())
], predict_transformer = make_recaller_union(memory = memory, names = X.columns.values.tolist(), position = "first"))
pipeline.fit(X, y)

yt = pipeline.predict_transform(X)
print(yt)
```

In this example, the `yt` variable now holds a five-column data frame, where the first column is the predicted iris species, and the following four columns are the original iris features. You can apply your `ExpressionTransformer` transformation to this data frame now.

**Comment by vruusmann** [comment]
See also https://github.com/jpmml/sklearn2pmml/issues/425
