### ISSUE TITLE
POST PROCESSING IN PMML 

### ISSUE THREAD

**Issue by andru98** [jpmml/sklearn2pmml#426]
df=sns.load_dataset('tips')

X=df.drop('tip',axis=1) y=df['tip'] memory = Memory() mapper=DataFrameMapper([ (['total_bill'],ContinuousDomain()), (['sex'],[CategoricalDomain(), LabelEncoder()]), (['smoker'],[CategoricalDomain(), LabelEncoder()]), (['day'],[CategoricalDomain(),make_memorizer_union(memory, names = ["day-str"]), OrdinalEncoder()]), (['time'],[CategoricalDomain(), OrdinalEncoder()]), (['size'],[CategoricalDomain(), OrdinalEncoder()]), ],df_out=True)

Is there any way where i get to do two predcition. First the model has predicted with original day values ,
let say we get prediction p .Now suppose i want to replace 'Sun' with 'Thur' keeping all features same and
do prediction in predcit_transformer to get prediction q
Now we want to compare these p and q , if p<q then make p=q+1 .
Is therre any way we can achive this
pipeline = PMMLPipeline([ ('mapper',mapper), ("regressor", LinearRegression()) ], predict_transformer = Pipeline([ ('recaller1',make_recaller_union(memory = memory,names = ["day-str"], position = "first")),

('day_filter',ExpressionTransformer("X[0]='Thur' if x[0]='Sun' else X[0]")) ]) )

**Comment by vruusmann** [comment]
Sorry, if you don't bother to format your issue correctly, I won't bother to answer it.
