### ISSUE TITLE
Generating TransformationDictonary

### ISSUE THREAD

**Issue by kiran90429** [jpmml/sklearn2pmml#43]
Hi,
Can you please explain generating a TransformationDictonary  in pmml for binning. how do i write java code to generate transformation dictonary like this

<TransformationDictionary>

  
  <DefineFunction name="AMPM" dataType="string" optype="categorical">
    

    
    <ParameterField name="TimeVal" optype="continuous" dataType="integer"/>
    

    
    

    <Discretize field="TimeVal">  
      <DiscretizeBin binValue="AM">
        <Interval closure="closedClosed" leftMargin="0" rightMargin="43199"/>
      </DiscretizeBin>
      <DiscretizeBin binValue="PM">
        <Interval closure="closedOpen" leftMargin="43200" rightMargin="86400"/>
      </DiscretizeBin>
    </Discretize>
  </DefineFunction>

  
  <DerivedField name="Shift" dataType="string" optype="categorical">
    <Apply function="AMPM">
      <FieldRef field="StartTime"/>
    </Apply>
  </DerivedField>

  
  <DerivedField name="StartHour" dataType="string" optype="categorical">
    <Apply function="format-datetime">
      <Constant>%H</Constant>
      <FieldRef field="StartTime"/>
    </Apply>
  </DerivedField>

</TransformationDictionary>

**Comment by SMS786** [comment]
Hi Vruu, 
I have a very similar issue , any help would be great.
