### ISSUE TITLE
Multiple sequential model inside a Pipeline

### ISSUE THREAD

**Issue by sulavtimilsina** [jpmml/sklearn2pmml#435]
Hello,

I’m working on a project where I need to build a sequential model pipeline in PMML. My goal is to create a chain of models (specifically XGBRegressor models) where the prediction from each model is passed as an upper bound constraint to the next model. This means each model's prediction should not exceed the output from the previous model in the sequence.

In sklearn, I achieved this by creating a custom transformer that:

Wraps each model.
Sets the predicted output as an upper bound constraint for the following model.
Ensures each model’s prediction does not exceed this upper bound in the pipeline.
Here’s a simplified example of the code I used in sklearn:

```
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.pipeline import Pipeline
from xgboost import XGBRegressor
import numpy as np

# Custom transformer to enforce upper bound constraint
class PassPredictionAsUpperBound(BaseEstimator, TransformerMixin):
    def __init__(self, model):
        self.model = model
        self.upper_bound = None
    
    def fit(self, X, y=None):
        self.model.fit(X, y)
        self.upper_bound = self.model.predict(X)
        return self
    
    def transform(self, X):
        predictions = self.model.predict(X).reshape(-1, 1)
        if self.upper_bound is not None:
            predictions = np.minimum(predictions, self.upper_bound.reshape(-1, 1))
        self.upper_bound = predictions
        return np.hstack([X, predictions])

# Pipeline of models
pipeline = Pipeline([
    ("model_1", PassPredictionAsUpperBound(XGBRegressor())),
    ("model_2", PassPredictionAsUpperBound(XGBRegressor())),
    # Additional models as needed
])

# Fit the pipeline
pipeline.fit(X_train, y_train)
 
```

My Questions:
1. Can I export this pipeline structure to PMML? Specifically, is there support for saving such a sequential pipeline where each model’s output serves as an upper bound for the next?

2. Is there any existing functionality or workaround in PMML to implement upper bound constraints in sequential model chaining?

3. If not supported directly, could you suggest an alternative way to structure this in PMML, or might this feature be considered for future support?

Any guidance or recommendations on how to implement this in PMML would be greatly appreciated.

Thank you!

**Comment by vruusmann** [comment]
> Can I export this pipeline structure to PMML? Specifically, is there support for saving such a sequential pipeline where each model’s output serves as an upper bound for the next?

Just like Scikit-Learn, PMML does not have a pre-defined high-level data structure for this specific business logic. But they both provide you with plenty of low- and mid-level data structures for assembling it yourself.

The main building block will be the good old `OutputField` element - it performs a computation, and exports the result under a new name into the (global-) scope.

```xml
<OutputField name="prediction(step_n)" feature="predictedValue"/>
<OutputField name="clipped(prediction(step_n))" dataType="double" optype="continuous" feature="transformedValue">
  <Apply function="min">
    <!-- Current model's prediction -->
    <FieldRef field="prediction(step_n)"/>
    <!-- The clipped prediction of the previous model -->
    <FieldRef field="clipped(prediction(step_n-1))"/>
  </Apply>
</Output>
```

The above will do. There is no need to over-complicate things.

Your task is to create a SkLearn2PMML package plugin that will recognize your custom `PassPredictionAsUpperBound` class, and will append a similar PMML fragment to each model's `Output` element.

**Comment by sulavtimilsina** [comment]
Thank you for your prompt reply. My another query is, can we store all the intermediate output form each layer and save them. Then later I plan to use them for computation to maintain hierarchy and return all the processed outputs.

**Comment by vruusmann** [comment]
> My another query is, can we store all the intermediate output form each layer and save them. 

What exactly do you mean by "store" and "save"?

In my above comment, the pairs of field values `prediction(step_n)` and `clipped(prediction(step_n))` are exported to global scope. They stay there while the model chain is being evaluated from top to bottom. These value can be referenced and recalled by name at any time (eg. `<FieldRef field="prediction(step_n)"/>`).

**Comment by sulavtimilsina** [comment]
Hi Im sorry for the confusion and too many questions, Im just a newbie in PMML.  I want the two or more models to be embedded in one pipeline. These models are trained on different sets of data but with the same features.  The pipeline code below I have generated has two sample models. I want to get output from both models simultaneously and apply the 10% decrement on the second model's output if it's larger than the first model's output.

But I always get the prediction from the first model only. I don't know what might be the reason. Your help would help me alot.


```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PMML xmlns="http://www.dmg.org/PMML-4_4" version="4.4">
    <Header>
        <Application name="Independent PMML Models" version="1.0"/>
        <Timestamp>2024-10-29T09:00:00Z</Timestamp>
    </Header>
    <DataDictionary>
        <DataField name="y" optype="continuous" dataType="double"/>
        <DataField name="feature1" optype="continuous" dataType="double"/>
        <DataField name="feature2" optype="continuous" dataType="double"/>
        <DataField name="feature3" optype="categorical" dataType="string">
            <Value value="A"/>
            <Value value="B"/>
            <Value value="C"/>
        </DataField>
        <DataField name="feature4" optype="continuous" dataType="double"/>
        <DataField name="feature5" optype="categorical" dataType="string">
            <Value value="X"/>
            <Value value="Y"/>
            <Value value="Z"/>
        </DataField>
    </DataDictionary>

    <!-- First Independent Model -->
    <RegressionModel modelName="FirstModel" functionName="regression" algorithmName="sklearn.linear_model._base.LinearRegression">
        <MiningSchema>
            <MiningField name="y" usageType="target"/>
            <MiningField name="feature1"/>
            <MiningField name="feature2"/>
            <MiningField name="feature3"/>
            <MiningField name="feature4"/>
            <MiningField name="feature5"/>
        </MiningSchema>
        <RegressionTable intercept="356.2943254894766">
            <NumericPredictor name="feature1" coefficient="-88.98845759684346"/>
            <NumericPredictor name="feature2" coefficient="45.80804673940788"/>
            <NumericPredictor name="feature4" coefficient="-7.5319310815020675"/>
            <CategoricalPredictor name="feature3" value="A" coefficient="8.820911694736264"/>
            <CategoricalPredictor name="feature3" value="B" coefficient="-14.697631584548832"/>
            <CategoricalPredictor name="feature3" value="C" coefficient="5.876719889812624"/>
            <CategoricalPredictor name="feature5" value="X" coefficient="15.3121415834575"/>
            <CategoricalPredictor name="feature5" value="Y" coefficient="24.446486205875463"/>
            <CategoricalPredictor name="feature5" value="Z" coefficient="-39.75862778933289"/>
        </RegressionTable>
        <Output>
            <OutputField dataType="double" feature="predictedValue" name="FirstModelOutput" optype="continuous"/>
        </Output>
    </RegressionModel>

    <!-- Second Independent Model -->
    <RegressionModel modelName="SecondModel" functionName="regression" algorithmName="sklearn.linear_model._base.LinearRegression">
        <MiningSchema>
            <MiningField name="y" usageType="target"/>
            <MiningField name="feature1"/>
            <MiningField name="feature2"/>
            <MiningField name="feature3"/>
            <MiningField name="feature4"/>
            <MiningField name="feature5"/>
        </MiningSchema>
        <RegressionTable intercept="331.72103045331755">
            <NumericPredictor name="feature1" coefficient="-156.9227992742706"/>
            <NumericPredictor name="feature2" coefficient="-8.892598127832485"/>
            <NumericPredictor name="feature4" coefficient="-6.229729934847638"/>
            <CategoricalPredictor name="feature3" value="A" coefficient="38.5671783701262"/>
            <CategoricalPredictor name="feature3" value="B" coefficient="48.4250417801713"/>
            <CategoricalPredictor name="feature3" value="C" coefficient="-86.99222015029756"/>
            <CategoricalPredictor name="feature5" value="X" coefficient="51.113170075404796"/>
            <CategoricalPredictor name="feature5" value="Y" coefficient="-21.581668726015856"/>
            <CategoricalPredictor name="feature5" value="Z" coefficient="-29.531501349388865"/>
        </RegressionTable>
        <Output>
            <OutputField dataType="double" feature="predictedValue" name="SecondModelRawOutput" optype="continuous"/>
            <OutputField dataType="double" feature="transformedValue" name="SecondModelOutput" optype="continuous">
                <Apply function="if">
                    <Apply function=">">
                        <FieldRef field="SecondModelRawOutput"/>
                        <FieldRef field="FirstModelOutput"/>
                    </Apply>
                    <Apply function="*">
                        <FieldRef field="FirstModelOutput"/>
                        <Constant>0.90</Constant>
                    </Apply>
                    <FieldRef field="SecondModelRawOutput"/>
                </Apply>
            </OutputField>
        </Output>
    </RegressionModel>

    <!-- MiningModel to include both independent models for simultaneous prediction -->
    <MiningModel modelName="IndependentModels" functionName="regression">
        <MiningSchema>
            <MiningField name="y" usageType="target"/>
            <MiningField name="feature1"/>
            <MiningField name="feature2"/>
            <MiningField name="feature3"/>
            <MiningField name="feature4"/>
            <MiningField name="feature5"/>
        </MiningSchema>
        <Segmentation multipleModelMethod="selectAll">
            <Segment id="1">
                <True/>
                <RegressionModel modelName="FirstModel" functionName="regression">
                    <MiningSchema>
                        <MiningField name="y" usageType="target"/>
                        <MiningField name="feature1"/>
                        <MiningField name="feature2"/>
                        <MiningField name="feature3"/>
                        <MiningField name="feature4"/>
                        <MiningField name="feature5"/>
                    </MiningSchema>
                    <RegressionTable intercept="356.2943254894766">
                        <NumericPredictor name="feature1" coefficient="-88.98845759684346"/>
                        <NumericPredictor name="feature2" coefficient="45.80804673940788"/>
                        <NumericPredictor name="feature4" coefficient="-7.5319310815020675"/>
                        <CategoricalPredictor name="feature3" value="A" coefficient="8.820911694736264"/>
                        <CategoricalPredictor name="feature3" value="B" coefficient="-14.697631584548832"/>
                        <CategoricalPredictor name="feature3" value="C" coefficient="5.876719889812624"/>
                        <CategoricalPredictor name="feature5" value="X" coefficient="15.3121415834575"/>
                        <CategoricalPredictor name="feature5" value="Y" coefficient="24.446486205875463"/>
                        <CategoricalPredictor name="feature5" value="Z" coefficient="-39.75862778933289"/>
                    </RegressionTable>
                    <Output>
                        <OutputField dataType="double" feature="predictedValue" name="FirstModelOutput" optype="continuous"/>
                    </Output>
                </RegressionModel>
            </Segment>
            <Segment id="2">
                <True/>
                <RegressionModel modelName="SecondModel" functionName="regression">
                    <MiningSchema>
                        <MiningField name="y" usageType="target"/>
                        <MiningField name="feature1"/>
                        <MiningField name="feature2"/>
                        <MiningField name="feature3"/>
                        <MiningField name="feature4"/>
                        <MiningField name="feature5"/>
                    </MiningSchema>
                    <RegressionTable intercept="331.72103045331755">
                        <NumericPredictor name="feature1" coefficient="-156.9227992742706"/>
                        <NumericPredictor name="feature2" coefficient="-8.892598127832485"/>
                        <NumericPredictor name="feature4" coefficient="-6.229729934847638"/>
                        <CategoricalPredictor name="feature3" value="A" coefficient="38.5671783701262"/>
                        <CategoricalPredictor name="feature3" value="B" coefficient="48.4250417801713"/>
                        <CategoricalPredictor name="feature3" value="C" coefficient="-86.99222015029756"/>
                        <CategoricalPredictor name="feature5" value="X" coefficient="51.113170075404796"/>
                        <CategoricalPredictor name="feature5" value="Y" coefficient="-21.581668726015856"/>
                        <CategoricalPredictor name="feature5" value="Z" coefficient="-29.531501349388865"/>
                    </RegressionTable>
                    <Output>
                        <OutputField dataType="double" feature="predictedValue" name="SecondModelRawOutput" optype="continuous"/>
                        <OutputField dataType="double" feature="transformedValue" name="SecondModelOutput" optype="continuous">
                            <Apply function="if">
                                <Apply function=">">
                                    <FieldRef field="SecondModelRawOutput"/>
                                    <FieldRef field="FirstModelOutput"/>
                                </Apply>
                                <Apply function="*">
                                    <FieldRef field="FirstModelOutput"/>
                                    <Constant>0.90</Constant>
                                </Apply>
                                <FieldRef field="SecondModelRawOutput"/>
                            </Apply>
                        </OutputField>
                    </Output>
                </RegressionModel>
            </Segment>
        </Segmentation>
        <!-- Updated Output section for proper multiple predictions -->
        <Output>
            <OutputField name="FirstModelOutput" optype="continuous" dataType="double" feature="predictedValue" segmentId="1"/>
            <OutputField name="SecondModelOutput" optype="continuous" dataType="double" feature="transformedValue" segmentId="2"/>
        </Output>
    </MiningModel>
</PMML>

```

**Comment by vruusmann** [comment]
>  I want the two or more models to be embedded in one pipeline. ..  I want to get output from both models simultaneously 

In Scikit-Learn, it is not doable using standard components, because Scikit-Learn doesn't allow you to have more than one estimator object per pipeline. But as you already know, you can "escape" estimators into transformers by embedding them into `sklego.meta.EstimatorTransformer` (or smth similar).

PMML does not have such a restriction. You can define a "model chain" (aka "model sequence"), and put any number of model elements in there. However, the model elements are evaluated sequentially, meaning in the order in which they are listed in model chain. But this is OK for most use cases.

> But I always get the prediction from the first model only.

Your PMML document has the following "superstructure" right now:
```xml
<PMML>
  <RegressionModel/>
  <RegressionModel/>
  <MiningModel>
    <Segmentation multipleModelMethod="selectAll">
      <RegressionModel/>
      <RegressionModel/>
    </Segmentation>
  </MiningModel>
</PMML>
```

Meaning, you have three top-level model elements under the main `PMML` element - two `RegressionModel` elements and then a `MiningModel` element.

Let me guess - you're always getting the prediction of the first `RegressionModel` element ("First Independent Model")?

This is so, because under such "multiple models in a PMML document" most PMML evaluation engines decide to evaluate only the first top-level model element, and tend to ignore all the following top-level model elements.

Now, if you move your `MiningModel` element to the first position, you should start seeing its predictions.

On a quick glance, it appears to me that the current PMML document contains duplicate `RegressionModel` elements? Meaning that the first two standalone models, and the ones that are nested inside the `MiningModel` element are one and the same?

> The pipeline code below I have generated has two sample models. I want to get output from both models 

Your PMML document should have the following "superstructure" then:
```xml
<PMML>
  <MiningModel>
    <Segmentation multipleModelMethod="x-modelChain">
      <RegressionModel/>
      <RegressionModel/>
    </Segmentation>
  </MiningModel>
</PMML>
```

The `x-modelChan` multiple model method (MMM) is an JPMML vendor extension for the multi-output case.

The standard `modelChain` MMM yields the prediction of the last model element that was chosen for evaluation by the associated predicate (In Scikit-Learn, this is called "single output"), whereas the `x-modelChain` MMM yields the predictions of all model elements (In Scikit-Learn, this is called "multi-output").

**Comment by vruusmann** [comment]
@sulavtimilsina TLDR: Modify your sample PMML document in the following ways:

- Delete the first two `RegressionModel` elements, as they appear redundant to me
- Modify the `Segmentation@multipleModelMethod` attribute, by changing it from `selectAll` to `x-multiModelChain`.

Does the prediction work then?

**Comment by sulavtimilsina** [comment]
Hi, Thank you for the quick reply.
Yes those models were redundant so I removed those models and just kept the mining models. Also I changed the multipleModelMethod from "selectAll" to "x-multiModelChain".

But I got following error:

While using pypmml.predict:

```
PMMLError: ('NoSuchElementException', "No value found for 'x-multiModelChain'")
```


While using jpmml_evaluator:

```
JavaError: org.jpmml.evaluator.DuplicateFieldValueException: The value for field "y" has already been defined

```


This is the exact pmml file i used:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<PMML xmlns="http://www.dmg.org/PMML-4_4" version="4.4">
    <Header>
        <Application name="Independent PMML Models" version="1.0"/>
        <Timestamp>2024-10-29T09:00:00Z</Timestamp>
    </Header>
    <DataDictionary>
        <DataField name="y" optype="continuous" dataType="double"/>
        <DataField name="feature1" optype="continuous" dataType="double"/>
        <DataField name="feature2" optype="continuous" dataType="double"/>
        <DataField name="feature3" optype="categorical" dataType="string">
            <Value value="A"/>
            <Value value="B"/>
            <Value value="C"/>
        </DataField>
        <DataField name="feature4" optype="continuous" dataType="double"/>
        <DataField name="feature5" optype="categorical" dataType="string">
            <Value value="X"/>
            <Value value="Y"/>
            <Value value="Z"/>
        </DataField>
    </DataDictionary>

    <!-- MiningModel to include both independent models for simultaneous prediction -->
    <MiningModel modelName="IndependentModels" functionName="regression">
        <MiningSchema>
            <MiningField name="y" usageType="target"/>
            <MiningField name="feature1"/>
            <MiningField name="feature2"/>
            <MiningField name="feature3"/>
            <MiningField name="feature4"/>
            <MiningField name="feature5"/>
        </MiningSchema>
        <Segmentation multipleModelMethod='x-multiModelChain'>
            <Segment id="1">
                <True/>
                <RegressionModel modelName="FirstModel" functionName="regression">
                    <MiningSchema>
                        <MiningField name="y" usageType="target"/>
                        <MiningField name="feature1"/>
                        <MiningField name="feature2"/>
                        <MiningField name="feature3"/>
                        <MiningField name="feature4"/>
                        <MiningField name="feature5"/>
                    </MiningSchema>
                    <RegressionTable intercept="356.2943254894766">
                        <NumericPredictor name="feature1" coefficient="-88.98845759684346"/>
                        <NumericPredictor name="feature2" coefficient="45.80804673940788"/>
                        <NumericPredictor name="feature4" coefficient="-7.5319310815020675"/>
                        <CategoricalPredictor name="feature3" value="A" coefficient="8.820911694736264"/>
                        <CategoricalPredictor name="feature3" value="B" coefficient="-14.697631584548832"/>
                        <CategoricalPredictor name="feature3" value="C" coefficient="5.876719889812624"/>
                        <CategoricalPredictor name="feature5" value="X" coefficient="15.3121415834575"/>
                        <CategoricalPredictor name="feature5" value="Y" coefficient="24.446486205875463"/>
                        <CategoricalPredictor name="feature5" value="Z" coefficient="-39.75862778933289"/>
                    </RegressionTable>
                    
                </RegressionModel>
            </Segment>
            <Segment id="2">
                <True/>
                <RegressionModel modelName="SecondModel" functionName="regression">
                    <MiningSchema>
                        <MiningField name="y" usageType="target"/>
                        <MiningField name="feature1"/>
                        <MiningField name="feature2"/>
                        <MiningField name="feature3"/>
                        <MiningField name="feature4"/>
                        <MiningField name="feature5"/>
                    </MiningSchema>
                    <RegressionTable intercept="331.72103045331755">
                        <NumericPredictor name="feature1" coefficient="-156.9227992742706"/>
                        <NumericPredictor name="feature2" coefficient="-8.892598127832485"/>
                        <NumericPredictor name="feature4" coefficient="-6.229729934847638"/>
                        <CategoricalPredictor name="feature3" value="A" coefficient="38.5671783701262"/>
                        <CategoricalPredictor name="feature3" value="B" coefficient="48.4250417801713"/>
                        <CategoricalPredictor name="feature3" value="C" coefficient="-86.99222015029756"/>
                        <CategoricalPredictor name="feature5" value="X" coefficient="51.113170075404796"/>
                        <CategoricalPredictor name="feature5" value="Y" coefficient="-21.581668726015856"/>
                        <CategoricalPredictor name="feature5" value="Z" coefficient="-29.531501349388865"/>
                    </RegressionTable>
                    
                </RegressionModel>
            </Segment>
        </Segmentation>
        <Output>
          <OutputField dataType="double" feature="predictedValue" name="FirstModelOutput" optype="continuous" segmentId = "1"/>
          <OutputField dataType="double" feature="predictedValue" name="SecondModelOutput" optype="continuous" segmentId = "2"/>
        </Output>
        
    </MiningModel>
</PMML>

```


The code I used to inference is:
```
import pandas as pd
from pypmml import Model
from jpmml_evaluator import make_evaluator
import numpy as np
model = Model.load('./chained_model.pmml')

input_data = pd.DataFrame({
    'feature1': [0.9],         
    'feature2': [0.3],          
    'feature3': ['A'],        
    'feature4': [4],            
    'feature5': ['X']          
})

model.predict(input_data)


# Using jpmml_evaluator
evaluator = make_evaluator("./chained_model.pmml").verify()
evaluator.predict(input_data)
```

**Comment by vruusmann** [comment]
> JavaError: org.jpmml.evaluator.DuplicateFieldValueException: The value for field "y" has already been defined

In you PMML document, you have three instructions that can be interpreted as "evaluate the model, and assign its value to the `y` variable":

1. Line 27, as `MningModel/MiningSchema/MiningField@name="y"`
2. Line 39 as `RegressionModel/MiningSchema/MiningField@name="y"`
3. Line 64, as another `RegressionModel/MiningSchema/MiningField@name="y"`

The JPMML-Evaluator is basically telling you that you cannot re-assign the value of the `y` variable multiple times.

But don't despair - the fix is extremely simple, simply delete the `MiningField` declarations on lines 39 and 64 (ie. keep the top-level `MiningModel` one, and delete the nested `RegressionModel` ones), and it should work just fine!

**Comment by vruusmann** [comment]
@sulavtimilsina Once you get the hand-crafted PMML document making predictions, get back to this thread, and let's discuss how we can generate it automatically using SkLearn2PMML/Scikit-Learn.

Quick hint - it can be done using the `sklearn2pmml.ensemble.EstimatorChain` meta-estimator:
https://github.com/jpmml/sklearn2pmml/blob/0.111.1/sklearn2pmml/ensemble/__init__.py#L219-L281

**Comment by sulavtimilsina** [comment]
I made the changes as  you suggested, but still got this error:
```
JavaError: org.jpmml.evaluator.DuplicateFieldValueException: The value for field null has already been defined
```

I would love to use ```sklearn2pmml.ensemble.EstimatorChain```. Can you please suggest me, how I can implement the above idea?

**Comment by vruusmann** [comment]
> JavaError: org.jpmml.evaluator.DuplicateFieldValueException: The value for field null has already been defined

OK, my bad!

My previous advice (https://github.com/jpmml/sklearn2pmml/issues/435#issuecomment-2446578954) would have been appropriate for a single output model case (eg. the `modelChain` multiple model method), where the goal is to return a single value as a result.

However, here we're dealing with a multi-output model case (eg, the `x-multiModelChain` multiple model method).

It means that the top-level `MiningModel` element is just a dummy wrapper. The actual prediction work is performed by two nested `RegressionModel` elements, and - most importantly - we want to have both of their predictions in the result set.

Here's my updated advice:

1. Restore `MiningField` elements on lines 39 and 64. However, since they refer to two separate predictions, you must give them different names. For example, rename the first target to `y1` and the second one to `y2`.
2. You also need to update the `/PMML/DataDictionary` element, and add the definitions of `y1` and `y2` field there. If you're dealing with regression-type problems, then they are both `continuous+double` type fields. Simply duplicate the existing `/PMML/DataDictionary/DataField@name="y"` element (line 8), and give them matching names `y1` and `y2`.
3.  Bring the top-level `MiningModel/MiningSchema` element up-to-date with the above changes. You must also declare there that the current model will be yielding two target fields `y1` and `y2` (which are actually computed by nested models).

Sample mining schemas:
```xml
<!-- multi-output regressor, which yields the predictions of its nested single-output regressors -->
<MiningModel>
  <MiningSchema>
    <MiningField name="y1" usageType="target"/>
    <MiningField name="y1" usageType="target"/>
  </MiningSchema>

  <Segmentation multipleModelMethod="x-multiModelChain">
    <!-- first sngle-output regressor -->
    <Segment>
      <RegressionModel>
        <MiningSchema>
          <MiningField name="y1" usageType="target"/>
        </MiningSchema>
      </RegressionModel>
    </Segment>
    <!-- second single-output regressor -->
    <Segment>
      <RegressionModel>
        <MiningSchema>
          <MiningField name="y2" usageType="target"/>
        </MiningSchema>
      </RegressionModel>
    </Segment>
  </Segmentation>
</MiningModel>
```

> I would love to use sklearn2pmml.ensemble.EstimatorChain.

Let's get the manually coded PMML document working first.

It's important that you understand its internal structure and data flows, before you start automating its generation.

**Comment by sulavtimilsina** [comment]
Hi @vruusmann Your feedbacks helped me to go through the PMML basic format. This was a initial run I tested in linear regression. My main task is to carry this out using XGBoost Regressor, since it has so many models inside each model, how can we nest these structures?
The only difference from above will be instead of using linear regression in each model, I want to use XGBoost regression.

```
<PMML xmlns="http://www.dmg.org/PMML-4_4">
    <Header>...</Header>
    <DataDictionary>...</DataDictionary>

    <!-- Outer Mining Model -->
    <MiningModel functionName="regression">
        <MiningSchema>...</MiningSchema>

        <Segmentation multipleModelMethod="x-multiModelChain">

            <!-- First Model as a Segmentation -->
            <Segment id="Model_1">
                <MiningModel functionName="regression">
                    <Segmentation multipleModelMethod="sum">
                        <!-- Include the TreeModel structure for Model 1 here -->
                    </Segmentation>
                </MiningModel>
            </Segment>

            <!-- Second Model as a Segmentation -->
            <Segment id="Model_2">
                <MiningModel functionName="regression">
                    <Segmentation multipleModelMethod="sum">
                        <!-- Include the TreeModel structure for Model 2 here -->
                    </Segmentation>
                </MiningModel>
            </Segment>

        </Segmentation>
    </MiningModel>
</PMML>
```


Is this basic structure correct?

**Comment by vruusmann** [comment]
> This was a initial run I tested in linear regression. My main task is to carry this out using XGBoost Regressor..

In the above example (https://github.com/jpmml/sklearn2pmml/issues/435#issuecomment-2447920838), I probably should have used an abstract `<$MyModel>` element (in place of a concrete `RegressionModel` element).

The `LinearRegressor` estimator yields a PMML document with a `/PMML/RegressionModel` main model element, whereas  the `XGBRegressor` estimator yields `/PMML/MiningModel` instead. So, to upgrade you example from linear regression to XGBoost, simply replace the model elements, and that's it.

> .. since it has so many models inside each model, how can we nest these structures?

You don't need to change anything about the internal structure of XGBoost's `MiningModel` element, except for making sure that its mining schema has a correct/unique `MiningField@name` attribute value for the sole target field (by default they are all `y`, you must ensure that they're unique, or you'll be facing a `DuplicateField(Value)Exception` again).

> Is this basic structure correct?

Yes, that's correct.

If you're going to compile the "sequence model" PMML document by hand, then you might consider writing a small Python script that first generates the top-level `MiningModel` element (the one having the `x-multiModelChain` multiple model method), and then iterates over standalone XGBoost PMML documents, and extracts and copies over their `/PMML/MiningModel` elements (while adding/renaming `MiningSchema` elements as appropriate).

**Comment by sulavtimilsina** [comment]
Thanks, @vruusmann I was able to get outputs. Sorry for making this thread so long.

Now I have to implement some post-processing rules to the outputs I got at last.
I have to make sure the second output is always greater than the first one by 5 (let's say).

I tried keeping the output field in the top-level MiningModel:

```

<PMML>
    <MiningModel functionName="regression">
        <MiningSchema>
            <!-- References to fields used in the model -->
        </MiningSchema>

       <Output>
            <!-- Constant y1, use as-is -->
            <OutputField name="y1" dataType="double" optype="continuous" feature="predictedValue">
                <FieldRef field="y1"/>
            </OutputField>


                <!-- Adjust y2 based on y1 -->
            <OutputField name="Adjusted_y2" dataType="double" optype="continuous" feature="transformedValue">
                <Apply function="if">
                    <Apply function="lessThan">
                        <Apply function="-">
                            <FieldRef field="y2"/>
                            <FieldRef field="y1"/>
                        </Apply>
                        <Constant dataType="double">5</Constant>
                    </Apply>
                    <Apply function="+">
                        <FieldRef field="y1"/>
                        <Constant dataType="double">5</Constant>
                    </Apply>
                    <FieldRef field="y2"/>
                </Apply>
            </OutputField>
        </Output>


        <Segmentation multipleModelMethod="x-multiModelChain">

            <Segment id="1">
                <MiningModel functionName="regression" algorithmName="XGBoost (GBTree)" x-mathContext="float">
                </MiningModel>
            </Segment>

            <Segment id="2">
                <MiningModel functionName="regression" algorithmName="XGBoost (GBTree)" x-mathContext="float">
                </MiningModel>
            </Segment>

        </Segmentation>
    </MiningModel>
</PMML>


```


I get the error like this:

```
JavaError: org.jpmml.evaluator.EvaluationException: Expected 1 target field, got 2 target fields

```


And if I try to put the output field inside each segment's MiningModel, ```y1``` cannot be acquired by next segment for comparision.

How can I get over this bug?

**Comment by vruusmann** [comment]
> And if I try to put the output field inside each segment's MiningModel, y1 cannot be acquired by next segment for comparision.

I'm citing PMML's [field scoping](https://dmg.org/pmml/v4-4-1/FieldScope.html) rules by heart, but they should be the following for model chains (including the multi-output model chain):

- The target field is not visible to downstream models by default. It must be re-exported using an `OutputField` element.
- The output fields are visible to subsequent output fields in the current model, and to all downstream models.

So, in your case, you must do the following:

- Re-export the first model's prediction by appending an `OutputField` element to its output.
- Re-export the second model's prediction by appending an `OutputField` element to its output.
- Compare the above two output field values.

Schematically:
```xml
<MiningModel>
  <Segmentation>
    <Segment>
      <Model>
        <Output>
          <OutputField name="export(y1)" feature="predictedValue" isFinalResult="false"/>
        </Output>
      </Model>
    </Segment>
    <Segment>
      <Model>
        <Output>
          <OutputField name="export(y2)" feature="predictedValue" isFinalResult="false"/>
          <OutputField name="adjusted(y2)" feature="transformedValue">
            <Apply function="max">
              <Apply function="+">
                <FieldRef field="export(y1)"/>
                <Constant dataType="integer">5</Constant>
              </Apply>
              <FieldRef field="export(y2)"/>
            </Apply>
          </OutputField>
        </Output>
      </Model>
    </Segment>
  </Segmentation>
</MiningModel>
```

Please note that I'm setting `OutputField@isFinalResult="false"` for helper output fields, so that they don't unnecessarily show up in the model schema.

**Comment by sulavtimilsina** [comment]
Thank you so much. I figured that out by experimentation myself. I was just waiting for your respnse incase if there was any approach not to print unnecessary output fields again and again. And just print the final ones after adjustment.

**Comment by vruusmann** [comment]
> I was just waiting for your respnse incase if there was any approach not to print unnecessary output fields again and again.

Can't think of an simpler approach than the one presented above (https://github.com/jpmml/sklearn2pmml/issues/435#issuecomment-2460365497).

Ideally, you could leave out these two `export(yn)` output fields, and compare `y1` and `y2` directly in the `adjusted(y2)` output field.

The scope of target fields is actually a bit underspecified in the PMML field scoping page. The JPMML-Evaluator library should actually work with direct target fields references, but for greater compatibility with other PMML engines, adding the explicit "re-export into the current model's scope" is recommended.

> And just print the final ones after adjustment.

Well, it should be possible to get rid of `export(yn)` output fields at the top level by inserting a helper model element level into the hierarchy.

Adding this helper layer manually would be too much work, but once you go and automate the process (eg. by writing a Python script), it might be worth considering.
