### ISSUE TITLE
publish wheels

### ISSUE THREAD

**Issue by dimbleby** [jpmml/sklearn2pmml#437]
I notice that this package publishes only source distrifbutions, so that every user has to build the wheel themselves. Better for package owners to build and publish wheels once and for all.

I did not find a workflow in this repository for publishing or I would have submitted a pull request. If you are doing this manually a typical workflow would be something like

```
python -m pip install build twine
python -m build
twine publish dist/*
```

**Comment by vruusmann** [comment]
> I notice that this package publishes only source distributions, so that every user has to build the wheel themselves.

I'm not very experienced in Python packaging matters. Just a week or so ago, switched from `distutils` to `setuptools`, which already seemed like a large step forward.

What kind of difference does source vs wheel make in the first place? The SkLearn2PMML package does not contain any non-Python code, so what's there to compile? Or you means something like turning `*.py` files to `*.pyc` files?

> If you are doing this manually a typical workflow would be something like ..

I've been doing it manually so far:

```
python setup.py sdist
python3.11 -m twine upload dist/sklearn2pmml-${version}.tar.gz
```

**Comment by dimbleby** [comment]
Because there is nothing to compile publishing a wheel is easy for you - you do not need to worry about different wheels for different platforms, the same wheel will work for everyone.

Generally publishing a wheel is desirable.  The way that installing a python package works is that it is always from wheel: so if you do not publish a wheel then every consumer of your package has to build the wheel themselves from your source distribution.  That is slower and has some non-zero chance to go wrong.  Much better for the publisher to build the wheel once and for all.

The flow with invoking `setup.py sdist` directly is considered [deprecated](https://packaging.python.org/en/latest/discussions/setup-py-deprecated/) these days, `python -m build` is the usually recommended replacement.
