### ISSUE TITLE
How do you use Dataframe mapper for LabelEncoding the target column

### ISSUE THREAD

**Issue by setuc** [jpmml/sklearn2pmml#45]
Hi,
 I am trying to do a multi class text classification and here is an excerpt of the classifier that I was playing with where 
X = pandas dataseries which has sentences
y = pandas dataseries with classes as text

I am trying to make label encoding of the target values part of the pipeline. I have gone through the main.py to try and understand how to tackle this but besides the sentiment text classification, I was unable to find anything. Any guidance on this will be super helpful. 
Is the the limitation of sklearn_pandas?

    def build_classifier(classifier, name, with_proba=True):
        mapper = DataFrameMapper([
            (ytl, LabelEncoder()),
            (X, None)
        ])
        pipeline = PMMLPipeline([
            ("mapper", mapper),
            ("tf-idf",
             TfidfVectorizer(analyzer="word", strip_accents=None, lowercase=True,
                             tokenizer=Splitter(), stop_words="english", norm=None, dtype=(
                 np.float32 if isinstance(classifier, RandomForestClassifier) else np.float64))),
            ("classifier", classifier)
        ])
        pipeline.fit(X, ytl)
        store_pkl(pipeline, name + ".pkl")
        score = pd.DataFrame(pipeline.predict(X), columns=["Score"])
        if (with_proba == True):
            score_proba = pd.DataFrame(pipeline.predict_proba(X), columns=classifier.classes_)
            score = pd.concat((score, score_proba), axis=1)
        store_csv(score, name + ".csv")
        sklearn2pmml(pipeline, name +".pmml", with_repr=True)

    build_classifier(RandomForestClassifier(random_state=13, n_jobs=-1), "RandomForest")
``

When I run this i get the following error

> /home/mluser/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py:216: FutureWarning: numpy not_equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  flag = np.concatenate(([True], aux[1:] != aux[:-1]))
/home/mluser/anaconda3/lib/python3.6/site-packages/numpy/lib/arraysetops.py:275: FutureWarning: numpy equal will not check object identity in the future. The comparison did not return the same result as suggested by the identity (`is`)) and will change.
  return aux[:-1][aux[1:] == aux[:-1]]
Traceback (most recent call last):
  File "/home/mluser/Dropbox/Code/parallelEvaluators/temp/sklearn-pmml-multiout.py", line 229, in <module>
    build_sentiment(RandomForestClassifier(random_state=13, n_jobs=-1), "RandomForestBrand")
  File "/home/mluser/Dropbox/Code/parallelEvaluators/temp/sklearn-pmml-multiout.py", line 219, in build_sentiment
    pipeline.fit(X, ytl)
  File "/home/mluser/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 268, in fit
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/__init__.py", line 39, in _fit
    return Pipeline._fit(self, X, y, **fit_params)
  File "/home/mluser/anaconda3/lib/python3.6/site-packages/sklearn/pipeline.py", line 234, in _fit
    Xt = transform.fit_transform(Xt, y, **fit_params_steps[name])
  File "/home/mluser/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 1352, in fit_transform
    X = super(TfidfVectorizer, self).fit_transform(raw_documents)
  File "/home/mluser/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 839, in fit_transform
    self.fixed_vocabulary_)
  File "/home/mluser/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 762, in _count_vocab
    for feature in analyze(doc):
  File "/home/mluser/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 241, in <lambda>
    tokenize(preprocess(self.decode(doc))), stop_words)
  File "/home/mluser/anaconda3/lib/python3.6/site-packages/sklearn/feature_extraction/text.py", line 207, in <lambda>
    return lambda x: strip_accents(x.lower())
AttributeError: 'numpy.ndarray' object has no attribute 'lower'

When I remove the dataframemapper, I get an error while generating the pmml file

    def build_classifier(classifier, name, with_proba=True):
        # mapper = DataFrameMapper([
        #     (ytl, LabelEncoder()),
        #     (X, None)
        # ])
        pipeline = PMMLPipeline([
            #("mapper", mapper),
            ("tf-idf",
             TfidfVectorizer(analyzer="word", strip_accents=None, lowercase=True,
                             tokenizer=Splitter(), stop_words="english", norm=None, dtype=(
                 np.float32 if isinstance(classifier, RandomForestClassifier) else np.float64))),
            ("classifier", classifier)
        ])
        pipeline.fit(X, ytl)
        store_pkl(pipeline, name + ".pkl")
        score = pd.DataFrame(pipeline.predict(X), columns=["Score"])
        if (with_proba == True):
            score_proba = pd.DataFrame(pipeline.predict_proba(X), columns=classifier.classes_)
            score = pd.concat((score, score_proba), axis=1)
        store_csv(score, name + ".csv")
        sklearn2pmml(pipeline, name +".pmml", with_repr=True)

    build_classifier(RandomForestClassifier(random_state=13, n_jobs=-1), "RandomForest")

I get the following error where it is not able to convert the text classes into integer

> /home/mluser/anaconda3/bin/python /home/mluser/Dropbox/Code/parallelEvaluators/temp/sklearn-pmml-multiout.py
Jul 21, 2017 11:55:23 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jul 21, 2017 11:55:36 AM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 12587 ms.
Jul 21, 2017 11:55:36 AM org.jpmml.sklearn.Main run
INFO: Converting..
Jul 21, 2017 11:55:36 AM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: 2s Factory
	at sklearn2pmml.PMMLPipeline$1.apply(PMMLPipeline.java:248)
	at sklearn2pmml.PMMLPipeline$1.apply(PMMLPipeline.java:241)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:638)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at org.jpmml.converter.PMMLUtil.addValues(PMMLUtil.java:121)
	at org.jpmml.converter.PMMLUtil.addValues(PMMLUtil.java:110)
	at org.jpmml.converter.PMMLEncoder.createDataField(PMMLEncoder.java:173)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:96)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)

>Exception in thread "main" java.lang.IllegalArgumentException: 20s Factory
	at sklearn2pmml.PMMLPipeline$1.apply(PMMLPipeline.java:248)
	at sklearn2pmml.PMMLPipeline$1.apply(PMMLPipeline.java:241)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:638)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at org.jpmml.converter.PMMLUtil.addValues(PMMLUtil.java:121)
	at org.jpmml.converter.PMMLUtil.addValues(PMMLUtil.java:110)
	at org.jpmml.converter.PMMLEncoder.createDataField(PMMLEncoder.java:173)
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:96)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)
Traceback (most recent call last):
  File "/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/__init__.py", line 140, in sklearn2pmml
    subprocess.check_call(cmd)
  File "/home/mluser/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-cp', '/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-converter-1.2.3.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/guava-20.0.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jaxb-core-2.2.11.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/serpent-1.18.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/istack-commons-runtime-2.21.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.25.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.1.7.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-agent-1.3.6.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/slf4j-api-1.7.25.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-schema-1.3.6.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jaxb-runtime-2.2.11.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pyrolite-4.19.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.3.3.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-lightgbm-1.0.7.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-model-1.3.6.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-model-metro-1.3.6.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jcommander-1.48.jar', 'org.jpmml.sklearn.Main', '--pkl-pipeline-input', '/tmp/pipeline-e9v7_63h.pkl.z', '--pmml-output', 'RandomForest.pmml']' returned non-zero exit status 1.

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/home/mluser/Dropbox/Code/parallelEvaluators/temp/sklearn-pmml-multiout.py", line 229, in <module>
    build_classifier(RandomForestClassifier(random_state=13, n_jobs=-1), "RandomForest")
  File "/home/mluser/Dropbox/Code/parallelEvaluators/temp/sklearn-pmml-multiout.py", line 226, in build_classifier
    sklearn2pmml(pipeline, name +".pmml", with_repr=True)
  File "/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/__init__.py", line 142, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams

>Process finished with exit code 1

Keeping the LabelEncoding outside makes it a success:

    ytl = LabelEncoder().fit_transform(yt)

    def build_classifier(classifier, name, with_proba=True):
        # mapper = DataFrameMapper([
        #     (ytl, LabelEncoder()),
        #     (X, None)
        # ])
        pipeline = PMMLPipeline([
            #("mapper", mapper),
            ("tf-idf",
             TfidfVectorizer(analyzer="word", strip_accents=None, lowercase=True,
                             tokenizer=Splitter(), stop_words="english", norm=None, dtype=(
                 np.float32 if isinstance(classifier, RandomForestClassifier) else np.float64))),
            ("classifier", classifier)
        ])
        pipeline.fit(X, ytl)
        store_pkl(pipeline, name + ".pkl")
        score = pd.DataFrame(pipeline.predict(X), columns=["Score"])
        if (with_proba == True):
            score_proba = pd.DataFrame(pipeline.predict_proba(X), columns=classifier.classes_)
            score = pd.concat((score, score_proba), axis=1)
        store_csv(score, name + ".csv")
        sklearn2pmml(pipeline, name +".pmml", with_repr=True)

    build_classifier(RandomForestClassifier(random_state=13, n_jobs=-1), "RandomForest")

No errors  this time

> Jul 21, 2017 11:58:30 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jul 21, 2017 11:58:43 AM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 12595 ms.
Jul 21, 2017 11:58:43 AM org.jpmml.sklearn.Main run
INFO: Converting..
Jul 21, 2017 11:58:43 AM sklearn2pmml.PMMLPipeline encodePMML
WARNING: The 'target_field' attribute is not set. Assuming y as the name of the target field
Jul 21, 2017 11:58:48 AM org.jpmml.sklearn.Main run
INFO: Converted in 4783 ms.
Jul 21, 2017 11:58:48 AM org.jpmml.sklearn.Main run
INFO: Marshalling PMML..
Jul 21, 2017 11:58:59 AM org.jpmml.sklearn.Main run
INFO: Marshalled PMML in 11532 ms.
Process finished with exit code 0

**Comment by vruusmann** [comment]
You would be using class `DataFrameMapper` as usual. The fact that the fitted pipeline will undergo conversion to PMML does not give it any superpowers.

> I am trying to make label encoding of the target values part of the pipeline.

Target value transformations is not a standard Scikit-Learn practice. It is assumed that the `y` parameter (of the `Classifier.fit(X, y)` method) is in its "original" representation, and the classifier class will transform it internally (if necessary).

So, in case of multi-class classification, you would be passing a Pandas dataseries as the `y` parameter, and the classifier class will construct a `LabelEncoder` and apply it behind the scenes.

> Keeping the LabelEncoding outside makes it a success:

Your pipeline should be fitted just fine even without explicit `ytl = LabelEncoder().fit_transform(yt)`.

Please not that `DataFrameMapper` is only applied to the `X` parameter (of the `Classifier.fit(X, y)` method). Other column mappings (eg. `ytl` in the first two code examples) will be ignored.

**Comment by setuc** [comment]
But even when i try to do this

    ytlc = LabelEncoder()
    ytlc.fit(yt)
    ytl = ytlc.transform(yt)
    store_pkl(ytlc, 'lables.pkl')
    yt_pkl= load_pkl('lables.pkl')

    tempPipeline = PMMLPipeline([
        ("encoder", ytlc)])

    sklearn2pmml(tempPipeline, "lables.pmml", with_repr=False, debug=True)
    mapper = DataFrameMapper([
        (yt, LabelEncoder()),
    ])

I run into the following error.

>/home/mluser/anaconda3/bin/python /home/mluser/Dropbox/Code/parallelEvaluators/temp/sklearn-pmml-multiout.py
python:  3.6.1
sklearn:  0.18.2
sklearn.externals.joblib: 0.10.3
pandas:  0.20.2
sklearn_pandas:  1.5.0
sklearn2pmml:  0.20.3
java -cp /home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-converter-1.2.3.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/guava-20.0.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jaxb-core-2.2.11.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/serpent-1.18.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/istack-commons-runtime-2.21.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.25.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.1.7.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-agent-1.3.6.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/slf4j-api-1.7.25.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-schema-1.3.6.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jaxb-runtime-2.2.11.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pyrolite-4.19.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.3.3.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-lightgbm-1.0.7.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-model-1.3.6.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-model-metro-1.3.6.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jcommander-1.48.jar org.jpmml.sklearn.Main --pkl-pipeline-input /tmp/pipeline-szbmpkap.pkl.z --pmml-output lables.pmml
Jul 21, 2017 4:09:22 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jul 21, 2017 4:09:22 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 14 ms.
Jul 21, 2017 4:09:22 PM org.jpmml.sklearn.Main run
INFO: Converting..
Jul 21, 2017 4:09:22 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:74)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)

> Exception in thread "main" java.lang.IllegalArgumentException
	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:74)
	at org.jpmml.sklearn.Main.run(Main.java:144)
	at org.jpmml.sklearn.Main.main(Main.java:93)
Traceback (most recent call last):
  File "/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/__init__.py", line 140, in sklearn2pmml
    subprocess.check_call(cmd)
  File "/home/mluser/anaconda3/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['java', '-cp', '/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-converter-1.2.3.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/guava-20.0.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jaxb-core-2.2.11.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/serpent-1.18.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/istack-commons-runtime-2.21.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.25.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.1.7.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-agent-1.3.6.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/slf4j-api-1.7.25.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-schema-1.3.6.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jaxb-runtime-2.2.11.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pyrolite-4.19.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.3.3.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-lightgbm-1.0.7.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-model-1.3.6.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-model-metro-1.3.6.jar:/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jcommander-1.48.jar', 'org.jpmml.sklearn.Main', '--pkl-pipeline-input', '/tmp/pipeline-szbmpkap.pkl.z', '--pmml-output', 'lables.pmml']' returned non-zero exit status 1.

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/home/mluser/Dropbox/Code/parallelEvaluators/temp/sklearn-pmml-multiout.py", line 226, in <module>
    sklearn2pmml(tempPipeline, "lables.pmml", with_repr=False, debug=True)
  File "/home/mluser/.local/lib/python3.6/site-packages/sklearn2pmml/__init__.py", line 142, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams
Preserved joblib dump file(s):  /tmp/pipeline-szbmpkap.pkl.z

**Comment by setuc** [comment]
@vruusmann 
Based on what you mention, the second come in the original post has the fit where i am not doing label encoding. The fit works perfectly, But when it tried to generate the PMML file, it throws this error

>/home/mluser/anaconda3/bin/python /home/mluser/Dropbox/Code/parallelEvaluators/temp/sklearn-pmml-multiout.py
Jul 21, 2017 11:55:23 AM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Jul 21, 2017 11:55:36 AM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 12587 ms.
Jul 21, 2017 11:55:36 AM org.jpmml.sklearn.Main run
INFO: Converting..
Jul 21, 2017 11:55:36 AM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
**java.lang.IllegalArgumentException: 2s Factory**
**at sklearn2pmml.PMMLPipeline$1.apply(PMMLPipeline.java:248**

**Comment by vruusmann** [comment]
> Exception in thread "main" java.lang.IllegalArgumentException
> at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:74)

This exception is thrown when the PMMLPipeline does not contain any `Estimator` objects.

In other words, it's impossible to convert a no-op pipeline to PMML.

**Comment by setuc** [comment]
> This exception is thrown when the PMMLPipeline does not contain any Estimator objects.

Thanks for the quick response....

**Comment by setuc** [comment]
Quick update:
>Jul 21, 2017 11:55:36 AM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: **2s Factory**
at sklearn2pmml.PMMLPipeline$1.apply(PMMLPipeline.java:248

The 2s Factory is a class. The original code works when I do label encoding, else fails with the above error message. 
I saw that IRIS fit is based on similar categorical data, but somehow this one fails.

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException: 2s Factory
> at sklearn2pmml.PMMLPipeline$1.apply(PMMLPipeline.java:248

Target categories shouldn't contain whitespace characters:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn2pmml/PMMLPipeline.java#L247-L249

So, replace `2s Factory` with `2s_Factory`, and everything should be fine.

You do have access to the full source code of SkLearn2PMML/JPMML-SkLearn(/JPMML-Evaluator) software stack. Use it to your advantage.

**Comment by setuc** [comment]
@vruusmann THANK YOU THANK YOU THANK YOU
