### ISSUE TITLE
Not working jpmml-converter version with GradientBoostingClassifier

### ISSUE THREAD

**Issue by sabba** [jpmml/sklearn2pmml#49]
The jpmml-converter-1.2.3.jar included in the current release, generates a wrong PMML document.

The second segment of the multiple model does not read the output produced by the first one (tree ensemble), generating a constant prediction.

This is an example of segment generated with the version 1.2.3
```
<Segment id="2">
    <True/>
    <RegressionModel functionName="classification" normalizationMethod="none">
        <MiningSchema>
            <MiningField name="TARGET" usageType="target"/>
        </MiningSchema>
        <Output>
            <OutputField name="probability(-1)" optype="continuous" dataType="double" feature="probability" value="-1"/>
            <OutputField name="probability(1)" optype="continuous" dataType="double" feature="probability" value="1"/>
        </Output>
        <RegressionTable intercept="1.0" targetCategory="1"/>
        <RegressionTable intercept="0.0" targetCategory="-1"/>
    </RegressionModel>
</Segment>
```

This is the same segment generated with a version >= 1.2.4
```
<Segment id="2">
    <True/>
    <RegressionModel functionName="classification" normalizationMethod="none">
        <MiningSchema>
            <MiningField name="TARGET" usageType="target"/>
            <MiningField name="transformedDecisionFunction(1)"/>
        </MiningSchema>
        <Output>
            <OutputField name="probability(-1)" optype="continuous" dataType="double" feature="probability" value="-1"/>
            <OutputField name="probability(1)" optype="continuous" dataType="double" feature="probability" value="1"/>
        </Output>
        <RegressionTable intercept="0.0" targetCategory="1">
            <NumericPredictor name="transformedDecisionFunction(1)" coefficient="1.0"/>
        </RegressionTable>
        <RegressionTable intercept="0.0" targetCategory="-1"/>
    </RegressionModel>
</Segment>
```

To solve the issue is required to update the static jars included in sklearn2pmml.

**Comment by vruusmann** [comment]
This is a very-very odd bug report. The SkLearn2PMML project is based on the JPMML-SkLearn library, which includes two integration test cases for `GradientBoostingClassifier`:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/java/org/jpmml/sklearn/ClassifierTest.java#L57-L60
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/java/org/jpmml/sklearn/ClassifierTest.java#L147-L150

If the JPMML-SkLearn library was generating incorrect PMML markup for the second segment, then these integration test should cause the build process to error out.

The working copy of JPMML-SkLearn already includes JPMML-Converter library version 1.2.4:
https://github.com/jpmml/jpmml-sklearn/commit/79a4547bb4ef8debcfd04f2cbe658ed9419f9cf2

So, you need to wait a couple more days until SkLearn2PMML version 0.20.4 is released, which shall be based on the latest and greatest JPMML-SkLearn library version.

**Comment by sabba** [comment]
Hi Villu, 
yes is very odd!

In order to understand the issue i checked out JPMML-SkLearn to version 1.3.3 which depend of jpmml-converter-1.2.3 and te full test suite run green.

Then, I tried to export a PMML document using the converter-executable-1.3.3.jar produced in "target" with the following command and the tree was surprising right!

`java -jar converter-executable-1.3.3.jar --pkl-pipeline-input ..\src\test\resources\pkl\GradientBoostingAudit.pkl --pmml-output GradientBoostingAudit.pmml`

Could be the case that the jar included statically as jpmml-converter-1.2.3 in SkLearn2PMML was not generated from the right code base?

I'va have installed SkLearn2PMML using pip pointing to the git repository.

Thank you for the support!

**Comment by vruusmann** [comment]
> Could be the case that the jar included statically as jpmml-converter-1.2.3 in SkLearn2PMML was not generated from the right code base?

I've experienced a situation, where the `resources` directory of an installed sklearn2pmml package contains several versions of the same library JAR file (eg. JPMML-Converter versions 1.2.0, 1.2.3). The JVM then adds the first out-of-date JAR file (eg. 1.2.0) to classpath, and ignores the second up-to-date JAR file (eg. 1.2.3). Such classpath conflicts may lead to all sorts of unexpected outcomes, starting with JVM class loader/verifier errors and ending with incorrectly generated PMML markup.

Could it be that you had multiple versions of the JPMML-Converter library in the `resources` directory? This could happen if you install a new version of the sklearn2pmml package, without properly uninstalling the old version first.

Anyway, a good "fix" for library errors is to 1) delete the `sklearn2pmml` subdirectory from the `site-packages` directory of your active Python installation, and 2) install a the latest version of the sklearn2pmml package from GitHub.

**Comment by sabba** [comment]
> Could it be that you had multiple versions of the JPMML-Converter library in the resources directory? This could happen if you install a new version of the sklearn2pmml package, without properly uninstalling the old version first.

I think is not my case because i never installed before the package... BUT, In order to have locally this pull request (that you merged today) https://github.com/jpmml/jpmml-sklearn/pull/46 I have put a recompiled version of the `jpmml-sklearn` jar inside my `resources` directory.

Could be this the root cause?

**Comment by vruusmann** [comment]
> I have put a recompiled version of the jpmml-sklearn jar inside my resources directory.

For documentation purposes, these are the steps for updating the JPMML-SkLearn dependency of the SkLearn2PMML package:

1. Update JPMML-SkLearn version in `pom.xml`. When working with locally tweaked JPMML-SkLearn library, then the version identifier is typically `1.3-SNAPSHOT`.
2. Manually delete all JAR files from the `/sklearn2pmml/resources` directory (only `__init__.py` should remain).
3. Execute Apache Maven build `mvn clean package`. This will download the JPMML-SkLearn library, and all its transitive dependencies into the `/sklearn2pmml/resources` directory.
4. Optionally, update the version identifier in `sklearn2pmml/metadata.py`. For example, introduce some sort of suffix to signal that this is a "tweaked" version, not an official version.

**Comment by sabba** [comment]
Ok! Thank You.
