### ISSUE TITLE
Dealing with categorical variables to predict new values in the input feature

### ISSUE THREAD

**Issue by chandimsett** [jpmml/sklearn2pmml#50]
In sklearn pipeline we are able to create transformations for categorical variables via cat codes. Cat codes transformation is able to deal with new values while predicting, where as Label Encoder in sklearn2pmml isnt able to predict the new values, which were not available during training. My model can have new values for a column as an input feature while testing which would be a problem if we are using Label Encoder. Can you suggest a way how to deal with the PMML with the encoding, either in python or in JPMML side.

**Comment by vruusmann** [comment]
> Cat codes transformation is able to deal with new values while predicting

Could you tell me more about this fabulous "Cat codes" transformation? Which Python class, in which Python package? Perhaps it would be appropriate to incorporate it into JPMML-SkLearn and SkLearn2PMML projects.

> Can you suggest a way how to deal with the PMML with the encoding, either in python or in JPMML side.

When dealing with categorical features, then the first transformation of a pipeline should be `sklearn2pmml.decoration.CategoricalDomain`, which lets you customize missing value and invalid value treatments according to the PMML specification.

You could try the following parametrizations:

- `CategoricalDomain(invalid_value_treatment = "as_is")` - Invalid values are dispatched to the model. It is assumed that the model contains logic for detecting and handling these.
- `CategoricalDomain(invalid_value_treatment = "as_missing")` - Invalid values are converted to missing values, and then dispatched to the model.
- `CategoricalDomain(invalid_value_treatment = "as_missing", missing_value_replacement = "1.0")`. Convert invalid values to missing values, and then perform missing value replacement. The total effect is that the model sees invalid values as "1.0".
