### ISSUE TITLE
Imputations for Categorical Non-numerical Data

### ISSUE THREAD

**Issue by chandimsett** [jpmml/sklearn2pmml#52]
Hello,
I was trying to deal with missing/new values with Imputer(). I was able to handle numerical encodings by imputation using Imputer() and LabelEncoder() chained together in a sklearn2pmml dataframemapper pipeline. But I was not able to deal with input features having non-numerical content. Imputer() fails in that case. So I tried writing my own CustomImputer to deal with non numerical categorical variables. But I am getting an error from Java side while creating a PMML, where as the python pipeline is error free.

> INFO: Converting..
> 	at sklearn.Initializer.encodeFeatures(Initializer.java:53)
> 	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:93)
> 	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:122)
> 	at org.jpmml.sklearn.Main.run(Main.java:144)
> 	at org.jpmml.sklearn.Main.main(Main.java:93)
> java.lang.IllegalArgumentException: com.highradius.ai.jpmml.functions.NonNumericalImputer(document_type)
> 	at org.jpmml.converter.PMMLEncoder.toCategorical(PMMLEncoder.java:145)
> 	at sklearn.preprocessing.LabelEncoder.encodeFeatures(LabelEncoder.java:97)
> 	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
> Aug 17, 2017 11:33:08 AM org.jpmml.sklearn.Main run
> SEVERE: Failed to convert
> java.lang.IllegalArgumentException: com.highradius.ai.jpmml.functions.NonNumericalImputer(document_type)
> 	at org.jpmml.converter.PMMLEncoder.toCategorical(PMMLEncoder.java:145)
> 	at sklearn.preprocessing.LabelEncoder.encodeFeatures(LabelEncoder.java:97)
> 	at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
> 	at sklearn.Initializer.encodeFeatures(Initializer.java:53)
> 	at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:93)
> 	at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:122)
> 	at org.jpmml.sklearn.Main.run(Main.java:144)
> 	at org.jpmml.sklearn.Main.main(Main.java:93)

Following is my Data frame mapper:

```
mapper = DataFrameMapper([(['amount'],[Imputer(strategy='median'),CustomTransformFunctionGenerator(function="Binning",arguments="10,100,1000,10000")]),
                          ('document_type',[CustomTransformFunctionGenerator(function="NonNumericalImputer"),LabelEncoder()]),
                          ])
```

**Comment by vruusmann** [comment]
Have you seen the [SkLearn2PMML-Plugin](https://github.com/jpmml/sklearn2pmml-plugin) project? You should follow its README step by step.

At the moment you appear to be mixing JPMML-Evaluator Java-backed UDFs with SkLearn2PMML. Things don't work that way.

**Comment by chandimsett** [comment]
Hi , thanks for the reply , I followed the very same  [https://github.com/jpmml/sklearn2pmml-plugin](url) link to create my custom Imputer , as the default Imputer doesn't work for non numerical values. And it works , but if I have some non numerical column which I want to impute and then LabelEncode  , I get the following  error.

> INFO: Converting..
> at sklearn.Initializer.encodeFeatures(Initializer.java:53)
> at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:93)
> at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:122)
> at org.jpmml.sklearn.Main.run(Main.java:144)
> at org.jpmml.sklearn.Main.main(Main.java:93)
> java.lang.IllegalArgumentException: com.highradius.ai.jpmml.functions.NonNumericalImputer(document_type)
> at org.jpmml.converter.PMMLEncoder.toCategorical(PMMLEncoder.java:145)
> at sklearn.preprocessing.LabelEncoder.encodeFeatures(LabelEncoder.java:97)
> at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
> Aug 17, 2017 11:33:08 AM org.jpmml.sklearn.Main run
> SEVERE: Failed to convert
> java.lang.IllegalArgumentException: com.highradius.ai.jpmml.functions.NonNumericalImputer(document_type)
> at org.jpmml.converter.PMMLEncoder.toCategorical(PMMLEncoder.java:145)
> at sklearn.preprocessing.LabelEncoder.encodeFeatures(LabelEncoder.java:97)
> at sklearn_pandas.DataFrameMapper.initializeFeatures(DataFrameMapper.java:75)
> at sklearn.Initializer.encodeFeatures(Initializer.java:53)
> at sklearn.pipeline.Pipeline.encodeFeatures(Pipeline.java:93)
> at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:122)
> at org.jpmml.sklearn.Main.run(Main.java:144)
> at org.jpmml.sklearn.Main.main(Main.java:93)


This is my Mapper : 
`mapper = DataFrameMapper([
                          ('document_type',[CustomTransformFunctionGenerator(function="NonNumericalImputer"),LabelEncoder()])
                          ])`
