### ISSUE TITLE
Error Converting PMMLPipeline to PMML file

### ISSUE THREAD

**Issue by TaihuaLi** [jpmml/sklearn2pmml#53]
I'm trying to cover ta pipeline, containing a DataFrameMapper, such as 
```
DataFrameMapper (
[(col, [CategoricalDomain(), LabelEncoder()]) for col in df.columns] + [ (numerical columns), None]
)
```
and an estimator, and so the pipeline looks like
```
PMMLPipeline([
    ("Preprocess", DataFrameMapper),
    ("estimator", GradientBoostingRegressor())
])
```
This is how I output PMML file
`sklearn2pmml(pipeline, 'path/GBRegression.pmml', with_repr=True, debug=True)`

Here is the debug info:
Python: 3.6.2
sklearn: 0.19.0
sklearn.externals.joblib: 0.11
pandas: 0.20.3
sklearn_pandas: 1.5.0
sklearn2pmml: 0.22.0
java -cp  (path to the modules above) output_pmml_path
Preserved job lib dump file(s): /tmp/pipeline-0vx5splj.pkl.z

I'm not sure what's wrong and cannot find a solution from previous issues. :/

**Comment by vruusmann** [comment]
What's the error message?

**Comment by TaihuaLi** [comment]
RuntimeError: The JPMML-Sklearn conversion application has failed. The Java process ...

That's all I got. So I tried to fit the mapper and model 1) individually before putting them into the pipeline 2) together after putting them into the pipeline. For either case, when I call pipeline.predict(new_data), it works.

**Comment by TaihuaLi** [comment]
this is the full java output

```
java -cp /home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/guava-20.0.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/istack-commons-runtime-2.21.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jaxb-core-2.2.11.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jaxb-runtime-2.2.11.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jcommander-1.48.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-converter-1.2.5.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-lightgbm-1.0.9.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-sklearn-1.3.6.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/jpmml-xgboost-1.2.1.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-agent-1.3.7.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-model-1.3.7.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-model-metro-1.3.7.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pmml-schema-1.3.7.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/pyrolite-4.19.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/serpent-1.18.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/slf4j-api-1.7.25.jar:/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/resources/slf4j-jdk14-1.7.25.jar org.jpmml.sklearn.Main --pkl-pipeline-input /tmp/pipeline-pgh9sou4.pkl.z --pmml-output data/Final/GBRegression.pmml
Preserved joblib dump file(s):  /tmp/pipeline-pgh9sou4.pkl.z
```

**Comment by vruusmann** [comment]
> RuntimeError: The JPMML-Sklearn conversion application has failed. The Java process ...

What's printed to **before** this line? It's a twenty-something lines long stack trace of a Java exception (probably some `java.lang.IllegalArgumentException`).

**Comment by TaihuaLi** [comment]
Traceback (most recent call last):

  File "<ipython-input-3-8a8ff05922ab>", line 1, in <module>
    sklearn2pmml(pipe, "data/Final/GBRegression.pmml", with_repr=True, debug=True)

  File "/home/tli/.local/lib/python3.6/site-packages/sklearn2pmml/__init__.py", line 142, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams")

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams

**Comment by vruusmann** [comment]
Alternatively, send me the `/tmp/pipeline-pgh9sou4.pkl.z` file, so that I can re-run the conversion process in my computer (using the JPMML-SkLearn command-line application), and see the Java exception myself.

**Comment by TaihuaLi** [comment]
Just sent it to your email

**Comment by vruusmann** [comment]
Have received your pickle file via e-mail. 

Conversion attempt using the [JPMML-SkLearn](https://github.com/jpmml/jpmml-sklearn) command-line application:
```
$ java -jar target/converter-executable-1.3-SNAPSHOT.jar --pkl-input pipeline-3meonk5w.pkl.z --pmml-output pipeline.pmml
```

Indeed, the conversion fails with a Java exception:
```
aug 22, 2017 10:58:00 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
aug 22, 2017 10:58:00 PM org.jpmml.sklearn.Main run
INFO: Parsed PKL in 166 ms.
aug 22, 2017 10:58:00 PM org.jpmml.sklearn.Main run
INFO: Converting..
aug 22, 2017 10:58:00 PM sklearn2pmml.PMMLPipeline encodePMML
WARNING: The 'target_field' attribute is not set. Assuming y as the name of the target field
aug 22, 2017 10:58:00 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.NullPointerException
        at org.jpmml.converter.ValueUtil.asInt(ValueUtil.java:103)
        at sklearn.ensemble.gradient_boosting.GradientBoostingRegressor.getNumberOfFeatures(GradientBoostingRegressor.java:39)
        at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:129)
        at org.jpmml.sklearn.Main.run(Main.java:144)
        at org.jpmml.sklearn.Main.main(Main.java:93)

Exception in thread "main" java.lang.NullPointerException
        at org.jpmml.converter.ValueUtil.asInt(ValueUtil.java:103)
        at sklearn.ensemble.gradient_boosting.GradientBoostingRegressor.getNumberOfFeatures(GradientBoostingRegressor.java:39)
        at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:129)
        at org.jpmml.sklearn.Main.run(Main.java:144)
        at org.jpmml.sklearn.Main.main(Main.java:93)
```

**Comment by vruusmann** [comment]
I suspect that the problem is related to Scikit-Learn library version. You appear to be using SkLearn 0.19.0, but the SkLearn2PMML package was last tested & approved with SkLearn 0.18.2.

The above Java exception indicates that the internal structure of the `GradientBoostingRegressor` class has changed in SkLearn 0.19.0. The SkLearn2PMML package doesn't know about this change yet.

You could try two things at the moment:

- Just to be sure that the rest of your SkLearn pipeline works OK, temporarily replace `GradientBoostingRegressor` class with some other regressor type (eg. `LinearRegression` or `XGBRegressor`). The conversion should then succeed.
- Can you downgrade (at least for the remainder of this week) to SkLearn 0.18.X? The old `GradientBoostingRegressor` class should be OK, as proven by this integration test:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/test/resources/main.py#L370

I have started work on upgrading the SkLearn2PMML package to SkLearn 0.19.0, but it won't be finished until next week. The internal structure of several classes have changed.

**Comment by TaihuaLi** [comment]
So I just tried both.. downgraded the scikit-learn to 0.18.2 and switched to xgboost. Both options gave me the same error (not sure about the Java exception yet)

**Comment by TaihuaLi** [comment]
UPDATE (error fixed):

I saw this Java warning:
```
aug 22, 2017 10:58:00 PM sklearn2pmml.PMMLPipeline encodePMML
WARNING: The 'target_field' attribute is not set. Assuming y as the name of the target field
```
Originally, I passed the y variable as a Pandas Series and did not specify the pipe.target_field. I then tried pass the y variable as pandas data frame and set the column name equal to the pipe.target_field. Then the .pmml is generated without problem. 

I used scikit-learn 0.19.0 so I don't thin that's the problem.

**Comment by deltawi** [comment]
@TaihuaLi I am facing the same issue, could you please clarify how did you solve this. I don't understand how you passed the y variable as pandas data frame and  set the column name to pipe.target_field ? could you share some code ? 

This is how I create my pipeline:

```
from category_encoders import OrdinalEncoder
from xgboost import XGBClassifier
categorical_transformer = Pipeline(steps=[
    ('WOEEnc', OrdinalEncoder(handle_missing='missing'))])

preprocessor = ColumnTransformer(remainder='passthrough',
    transformers=[
       ('cat', categorical_transformer, [col for col in cat_vars if col not in cols_to_drop])])

clf = Pipeline(steps=[('preprocessor', preprocessor),
                      ('classifier', XGBClassifier(**params))])
```

Versions: 
```
python: 3.7.9
sklearn: 0.24.1
sklearn2pmml: 0.69.0
joblib: 0.17.0
sklearn_pandas: 2.1.0
pandas: 1.2.1
numpy: 1.20.0
openjdk: 13.0.1
```

**Comment by vruusmann** [comment]
@deltawi This issue was closed **_three and a half years ago_**.

Your issue must be something different. Please open a new issue, and paste the full SkLearn2PMML exception stack trace into it.

Also, adding a fully reproducible sample case always helps.
