### ISSUE TITLE
Multiple Models

### ISSUE THREAD

**Issue by paubelsan** [jpmml/sklearn2pmml#56]
Hi,
Is there any way to create and export multiple models to PMML format as described in: [PMML 4.3 - Multiple Models](http://dmg.org/pmml/v4-3/MultipleModels.html)?

Thanks!

**Comment by vruusmann** [comment]
All ensemble models (ie. all Scikit-Learn modules under `sklearn.ensemble`) are encoded using the `MiningModel` element. For example, this is the conversion logic for the `sklearn.ensemble.VotingClassifier` estimator type:
https://github.com/jpmml/jpmml-sklearn/blob/master/src/main/java/sklearn/ensemble/voting_classifier/VotingClassifier.java

Seems pretty simple and straightforward to me.

Are you just wondering, or have some specific Scikit-Learn estimator type in mind?
