### ISSUE TITLE
I am getting an error net.razorvine.pickle.InvalidOpcodeException: invalid pickle opcode: 240

### ISSUE THREAD

**Issue by skamath58** [jpmml/sklearn2pmml#57]
I am getting the above error when I try to execute the sample code given for sklearn2pmml (the DecisionTreeIris.pmml creation). I can create a pickle file using Python and am able to read this file (just random fields) I have attached the file that works (pickle.dat) and file that does not work (pipeline.pkl.z)

Appreciate some help to resolve this.
[jpmml-sklearn-picklefiles.zip](https://github.com/jpmml/sklearn2pmml/files/1272999/jpmml-sklearn-picklefiles.zip)

**Comment by vruusmann** [comment]
Just for the reference, what are your Python, (c)Pickle and/or Joblib versions?

**Comment by skamath58** [comment]
Python : 2.7.13 (as part of Anaconda2)
Pickle $Revision: 72223 $ (does not give version)
Joblib 0.11

**Comment by vruusmann** [comment]
Interesting, everything works fine in my computer (just upgrading the JPMML-SkLearn library to support Scikit-Learn version 0.19.0).

I took a brief look into Python's pickling code, and couldn't find a reference to opcode `240` (in hex that would be `0xF0`). Could you do me a favour and try to locate the definition/usage of that opcode for me?

**Comment by skamath58** [comment]
**I am also not able to locate the code! I am getting these two op codes 240 and 254, none of which I can see in the net.razorvine/pyrolite/4.4/net/razorvine/pickle/Opcodes.java file!**

Not sure if this is going to help!
I am getting the 240 in the Java and 254 for python.

Storage storage = PickleUtil.createStorage(this.input);
object = PickleUtil.unpickle(storage); //the errror
............................................
Failed to parse PKL
net.razorvine.pickle.InvalidOpcodeException: invalid pickle opcode: 240
	at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:355)
	at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:78)
	at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
	at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:99)
	at com.metlife.datascience.TestPickle.run(TestPickle.java:46)
	at com.metlife.datascience.TestPickle.main(TestPickle.java:29)

For Python (code: essentially from the Github
import pandas
import subprocess
import pickle
import joblib
print   joblib.__version__
#print pickle.__version__
print subprocess.check_output(["java", "-version"], stderr=subprocess.STDOUT)
iris_df = pandas.read_csv("Iris.csv")
from sklearn2pmml import PMMLPipeline
from sklearn.tree import DecisionTreeClassifier
iris_pipeline = PMMLPipeline([
	("classifier", DecisionTreeClassifier())
])
iris_pipeline.fit(iris_df[iris_df.columns.difference(["Species"])], iris_df["Species"])
from sklearn2pmml import sklearn2pmml
#sklearn2pmml(iris_pipeline, "DecisionTreeIris.pmml", with_repr = True)
sklearn2pmml(iris_pipeline, "DecisionTreeIris.pmml")
python testskml2pmml.py gives me the error
-----------------------------------
C:\jpmml-sklearn-master>python testskml2pmml.py
0.11
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)

Sep 03, 2017 1:54:35 PM org.jpmml.sklearn.Main run
INFO: Parsing PKL..
Sep 03, 2017 1:54:35 PM org.jpmml.sklearn.Main run
SEVERE: Failed to parse PKL
net.razorvine.pickle.InvalidOpcodeException: invalid pickle opcode: 254
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:355)
        at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:78)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
        at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:99)
        at org.jpmml.sklearn.Main.run(Main.java:103)
        at org.jpmml.sklearn.Main.main(Main.java:93)

Exception in thread "main" net.razorvine.pickle.InvalidOpcodeException: invalid
pickle opcode: 254
        at net.razorvine.pickle.Unpickler.dispatch(Unpickler.java:355)
        at org.jpmml.sklearn.PickleUtil$1.dispatch(PickleUtil.java:78)
        at net.razorvine.pickle.Unpickler.load(Unpickler.java:122)
        at org.jpmml.sklearn.PickleUtil.unpickle(PickleUtil.java:99)
        at org.jpmml.sklearn.Main.run(Main.java:103)
        at org.jpmml.sklearn.Main.main(Main.java:93)
Traceback (most recent call last):
  File "testskml2pmml.py", line 32, in <module>
    sklearn2pmml(iris_pipeline, "DecisionTreeIris.pmml")
  File "C:\Users\skamath\AppData\Roaming\Python\Python27\site-packages\sklearn2p
mml\__init__.py", line 142, in sklearn2pmml
    raise RuntimeError("The JPMML-SkLearn conversion application has failed. The
 Java process should have printed more information about the failure into its st
andard output and/or error streams")
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java proc
ess should have printed more information about the failure into its standard out
put and/or error streams

**Comment by vruusmann** [comment]
Sorry, should have been more clear with my help request: can you locate the definitions of those opcodes on the Python side? You appear to be using some non-standard Pickle version, which is difficult to troubleshoot in other computers.

So, does your Pickle installation come with source code? If it does, then can you search it, and try to find any uses of `240` (or `0xF0`) constants?

Once you can show me where/how the Python side uses those opcodes, then I should be able to implement them in the Java/Pyrolite/JPMML-SkLearn side.

For example, I can't find anything relevant here: https://github.com/python/cpython/blob/3.6/Lib/pickle.py

**Comment by vruusmann** [comment]
Not enough information to do anything about this issue.
