### ISSUE TITLE
Using sklearn2pmml with multiprocessing.pool blocks database connections

### ISSUE THREAD

**Issue by Artamus** [jpmml/sklearn2pmml#58]
Hi,

I have set up a Python program that pulls data from the database using psycopg2 into pandas dataframes and then does random forest regression (via sklearn) on that data. To be able to use the fitted models elsewhere I wanted to use sklearn2pmml, but even just adding the import statement caused the code to stall on the database connection line.

For clarification, each thread has its own ` with psycopg2.connect(CONNECTION_STRING) as conn: ` statement, which is the point at which the program stalls.

**Comment by vruusmann** [comment]
There definitely isn't any "locking mechanisms" coded into the `sklearn2pmml` package that would prevent it from being used with other (specific-) Python packages, including the `psycopg2` package.

> even just adding the import statement caused the code to stall on the database connection line.

I'm not familiar with the `psycopg2` package. My best guess is that perhaps the `psycopg2` and `sklearn2pmml` package depend on some common package, but there is a versioning conflict or smth, that blocks the execution.

Can you work around the problem by doing your database work first, and importing `sklearn2pmml` functionality after that?

Alternatively, move the PMML conversion work to a separate Python script:

1. In your main script, fetch data, train RF model using Scikit-Learn, and save the model into a temporary file in `pickle` data format.
2. In a helper PMML conversion script, load the RF model from the temporary file, import the `sklearn2pmml.sklearn2pmml` conversion function, and produce the final PMML file.

**Comment by Artamus** [comment]
That is exactly what I resorted to doing for now, thanks.

**Comment by vruusmann** [comment]
Let's hope that `multiprocessing.pools` has been fixed during the past 4 years.
