### ISSUE TITLE
Does n_jobs/nthread carry over to the .pmml execution

### ISSUE THREAD

**Issue by TaihuaLi** [jpmml/sklearn2pmml#59]
When creating a .pmml file on a sklearn/xgboost model, does n_jobs or nthread carry over?

For example, in the PMMLPipeline, if I set the model parameter, n_jobs = -1, it will fit using all the CPU available on my machine. When someone else gets my .pmml file and execute the code in Java, and when the model is making a prediction, does it using all the CPU units on his/her machine?

Thanks!

**Comment by TaihuaLi** [comment]
Correct: PMMLPipeline doesn't fit model on data using all CPU even with n_jobs / nthread != 1. Problem solved.

**Comment by vruusmann** [comment]
> When creating a .pmml file on a sklearn/xgboost model, does `n_jobs` or `nthread` carry over?

Model training and model deployment are separate concerns, and their "runtime preferences" are typically not shareable.

PMML is about representing the prediction algorithm. Different PMML engines may choose to devise a different execution plan for the same PMML document (eg. a naive PMML engine does all computations serially, whereas a smart PMML engine may do some/all computations in parallel).

BWT, if you're currently working on SkLearn/XGBoost, then you might want to check out the following announcement: https://groups.google.com/d/msg/jpmml/k6eWMXp8kAQ/xmfmb5wbAQAJ

**Comment by TaihuaLi** [comment]
@vruusmann Thank you! It's really helpful!
