### ISSUE TITLE
Latency difference between PMML model and Sklearn pkl model

### ISSUE THREAD

**Issue by nejatb** [jpmml/sklearn2pmml#65]
Hi,
I have two models trained on the same set of data with the same number of features and the same classifiers. One of them was produced using sklearn pipeline and saved as pkl file and the other produced using PMMLPipeline and stored as a pmml. When I apply the two models on the same set of data, the pkl model classifies each input ten times faster than the java loaded pmml model. Is this behavior expected? The two pipelines are attached below. Thank you so much for your help.

    pipeline = Pipeline([

        ('union', FeatureUnion(
            transformer_list=[
                ('InputField1', Pipeline([
                    ('selector', ItemSelector(key='InputField1')),
                    ('vect', TfidfVectorizer(stop_words='english')),
                    ])),

                ('InputField2', Pipeline([
                    ('selector', ItemSelector(key='InputField2')),
                    ('vect', TfidfVectorizer(stop_words=None)),
                    ]))
                ],
        ('select', SelectKBest(chi2, k=5000)),
        ('clf', LinearSVC(dual=False, tol=1e-3)),
    ])

and 

    pipeline = PMMLPipeline([
        ("mapper", DataFrameMapper([
                    ("InputField1", TfidfVectorizer(stop_words = 'english',
                                                norm = None,
                                                tokenizer = Splitter(),
                                                ngram_range = (1,1),
                                                max_df = 0.9,
                                                min_df = 2
                                                )),
                    ("InputField2",TfidfVectorizer(stop_words = 'english',
                                                norm = None,
                                                tokenizer = Splitter(),
                                                ngram_range = (1,1),
                                                max_df = 0.7,
                                                min_df = 5
                                            ))
                    ],df_out=True) ),

        ("selector", SelectKBest(chi2,k=5000)),
        ("classifier", SVC(kernel='linear', tol=1e-3)),
    ])

Also, I had two other questions:

- is there support of LinearSVC in sklearn2PMML?
- Can we do evaluation of a pmml model in java using batches?

**Comment by vruusmann** [comment]
> ('select', SelectKBest(chi2, k=5000))

You're working with a "bag of words" text classification model, which operates on 5000 keywords.

Scikit-Learn calculates these 5000 keyword contributions by doing a single "big" function invocation, whereas (J)PMML does the same by doing 5000 "small" function invocations. The cost of text operations between Python and Java should be comparable(?), so the ten times performance decrease should be solely attributable to function invocation overhead.

You could try repeating this experiment with 500, 2'000 and 10'000 keywords and report back your findings. I expect the performance decrease to be less of an issue with smaller keyword sets, and more of an issue with bigger keyword sets.

If this performance decrease is unacceptable for your use case, then:
1. Limit the size of keyword sets from 5'000 to something (significantly-) smaller.
2. Just keep using Scikit-Learn.

> Is there support of LinearSVC in sklearn2PMML?

Not yet. See https://github.com/jpmml/jpmml-sklearn/issues/56

> Can we do evaluation of a pmml model in java using batches?

(J)PMML is designed to operate on individual data records.

You can group data records in your application in whatever way you want, but the JPMML-Evaluator library will still score them one by one. Conceptually, it is possible to extend the JPMML-Evaluator library to perform "vectorized operations" in specific cases, but fully building out this capability is not a priority at the moment.

**Comment by nejatb** [comment]
Hi.
I tried what you suggested and in fact, the same pmml model with 500 features runs 10 times faster. 
Thank you for your prompt answers.
