### ISSUE TITLE
PMMLPipeline fit error

### ISSUE THREAD

**Issue by Alexkevin** [jpmml/sklearn2pmml#66]
My code is : 
```python
import  pandas 
from sklearn.datasets import load_iris
iris= load_iris()
iris_df = pandas.DataFrame(data = iris.data,columns = iris.feature_names)
from sklearn2pmml import PMMLPipeline
from sklearn_pandas import DataFrameMapper
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
iris_pipeline = PMMLPipeline([
("classifier", LGBMClassifier())
])
iris_pipeline.fit(iris_df,iris.target,{"classifier__categorical_feature": ['petal_length_(cm)']})
```

And got error:

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-54787f088d4c> in <module>()
      2 ("classifier", LGBMClassifier())
      3 ])
----> 4 iris_pipeline.fit(iris_df,iris.target,{"classifier__categorical_feature": ['petal_length_(cm)']})

TypeError: fit() takes from 2 to 3 positional arguments but 4 were given

**Comment by vruusmann** [comment]
You appear to be using incorrect Python syntax for passing extra (PMML)Pipeline arguments. The correct syntax would be:
```Python
iris_pipeline = PMMLPipeline([
  ("classifier", LGBMClassifier())
])
iris_pipeline.fit(iris_df, iris.target, classifier__categorical_feature = ["petal length (cm)"])
```

**Comment by Alexkevin** [comment]
Sorry for troubling you again !

```python
import  pandas
import numpy as np 
from sklearn.datasets import load_iris
iris= load_iris()
iris_df = pandas.DataFrame(data = iris.data,columns = iris.feature_names)
from sklearn2pmml import PMMLPipeline
from sklearn_pandas import DataFrameMapper
from sklearn2pmml.decoration import ContinuousDomain,CategoricalDomain
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
iris_df['petal'] = np.random.randint(10,size = iris_df.shape[0])
iris_df['petal'] = iris_df['petal'].astype("category")
iris_df['target'] = iris.target

iris_pipeline = PMMLPipeline([
		("mapper",DataFrameMapper([('petal',CategoricalDomain(with_data = False)),(['sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],ContinuousDomain(with_data = False))])),

("classifier", LGBMClassifier())
])

iris_pipeline.fit(iris_df.drop("target",axis = 1),iris_df['target'],classifier__categorical_feature=['petal'])
```

I got the following error:

UserWarning: categorical_feature in Dataset is overrided. New categorical_feature is ['petal']
  warnings.warn('categorical_feature in Dataset is overrided. New categorical_feature is {}'.format(sorted(list(categorical_feature))))
/Users/shuangyang.wsy/anaconda/lib/python3.6/site-packages/lightgbm/basic.py:642: UserWarning: max_bin keyword has been found in `params` and will be ignored. Please use max_bin argument of the Dataset constructor to pass this parameter.
  'Please use {0} argument of the Dataset constructor to pass this parameter.'.format(key))
/Users/shuangyang.wsy/anaconda/lib/python3.6/site-packages/lightgbm/basic.py:648: LGBMDeprecationWarning: The `max_bin` parameter is deprecated and will be removed in 2.0.12 version. Please use `params` to pass this parameter.
  'Please use `params` to pass this parameter.', LGBMDeprecationWarning)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-aa58aa0882f2> in <module>()
     20 ])
     21 
---> 22 iris_pipeline.fit(iris_df.drop("target",axis = 1),iris_df['target'],classifier__categorical_feature=['petal'])

/Users/shuangyang.wsy/anaconda/lib/python3.6/site-packages/sklearn/pipeline.py in fit(self, X, y, **fit_params)
    257         Xt, fit_params = self._fit(X, y, **fit_params)
    258         if self._final_estimator is not None:
--> 259             self._final_estimator.fit(Xt, y, **fit_params)
    260         return self
    261 

/Users/shuangyang.wsy/anaconda/lib/python3.6/site-packages/lightgbm/sklearn.py in fit(self, X, y, sample_weight, init_score, eval_set, eval_names, eval_sample_weight, eval_init_score, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks)
    663                                         verbose=verbose, feature_name=feature_name,
    664                                         categorical_feature=categorical_feature,
--> 665                                         callbacks=callbacks)
    666         return self
    667 

/Users/shuangyang.wsy/anaconda/lib/python3.6/site-packages/lightgbm/sklearn.py in fit(self, X, y, sample_weight, init_score, group, eval_set, eval_names, eval_sample_weight, eval_init_score, eval_group, eval_metric, early_stopping_rounds, verbose, feature_name, categorical_feature, callbacks)
    453                               verbose_eval=verbose, feature_name=feature_name,
    454                               categorical_feature=categorical_feature,
--> 455                               callbacks=callbacks)
    456 
    457         if evals_result:

/Users/shuangyang.wsy/anaconda/lib/python3.6/site-packages/lightgbm/engine.py in train(params, train_set, num_boost_round, valid_sets, valid_names, fobj, feval, init_model, feature_name, categorical_feature, early_stopping_rounds, evals_result, verbose_eval, learning_rates, keep_training_booster, callbacks)
    176     # construct booster
    177     try:
--> 178         booster = Booster(params=params, train_set=train_set)
    179         if is_valid_contain_train:
    180             booster.set_train_data_name(train_data_name)

/Users/shuangyang.wsy/anaconda/lib/python3.6/site-packages/lightgbm/basic.py in __init__(self, params, train_set, model_file, silent)
   1292             self.handle = ctypes.c_void_p()
   1293             _safe_call(_LIB.LGBM_BoosterCreate(
-> 1294                 train_set.construct().handle,
   1295                 c_str(params_str),
   1296                 ctypes.byref(self.handle)))

/Users/shuangyang.wsy/anaconda/lib/python3.6/site-packages/lightgbm/basic.py in construct(self)
    843                                 weight=self.weight, group=self.group, init_score=self.init_score,
    844                                 predictor=self._predictor, silent=self.silent, feature_name=self.feature_name,
--> 845                                 categorical_feature=self.categorical_feature, params=self.params)
    846             if self.free_raw_data:
    847                 self.data = None

/Users/shuangyang.wsy/anaconda/lib/python3.6/site-packages/lightgbm/basic.py in _lazy_init(self, data, label, max_bin, reference, weight, group, init_score, predictor, silent, feature_name, categorical_feature, params)
    666                 else:
    667                     raise TypeError("Wrong type({}) or unknown name({}) in categorical_feature"
--> 668                                     .format(type(name).__name__, name))
    669             if categorical_indices:
    670                 if "categorical_feature" in params or "categorical_column" in params:

TypeError: Wrong type(str) or unknown name(petal) in categorical_feature
