### ISSUE TITLE
Prediction result not consistent in python and java(with pmml)

### ISSUE THREAD

**Issue by MouH** [jpmml/sklearn2pmml#69]
**Task**: Chinese text classification
**Problem**: I trained the model in Python with sklearn, and export the model with sklearn2pmml. However, the prediction/predict_proba result with the same sentence is different in Python and Java.

Training Detail:

``` python
pipeline = PMMLPipeline([
    ("tfidf", TfidfVectorizer(
                norm = None,
                analyzer = "word",
                token_pattern = None, 
                tokenizer = Splitter()
            )),
    ("chi", SelectKBest(chi2, k=4750)),
    ("classifier", RandomForestClassifier(
                n_estimators=10, 
                class_weight="balanced", 
                max_depth=46,
                criterion="gini"
            ))
])

model = pipeline.fit(train_x, train_y)
# train_x is list of string (feature separate by space)
# [u"上次 不说 腾讯 和 华为 撕逼 么", u"今天 天气 真好", ....]
# train_y is list of int
# [1, -1, ...]
```
After training I exported the model with:

```
sklearn2pmml(model, "model_test.pmml", with_repr = True, debug = True)
``` 

The Java part:
```java
InputStream in = new FileInputStream(new File("....../model_test.pmml"));
PMML pmml = PMMLUtil.unmarshal(in);
ModelEvaluatorFactory modelEvaluatorFactory = ModelEvaluatorFactory.newInstance();
ModelEvaluator<?> modelEvaluator = modelEvaluatorFactory.newModelEvaluator(pmml);
Map<FieldName, String> input = new HashMap<>();

input.put(new FieldName("x1"), "...................................");
Map<FieldName, ?> res = modelEvaluator.evaluate(input);

ProbabilityDistribution pd = (ProbabilityDistribution) res.get(modelEvaluator.getTargetFieldName());
Integer output = (Integer) pd.getResult();

System.out.println("Prediction Result: " + output);

for (String s : pd.getCategoryValues()) {
    System.out.println(s + ":" + pd.getProbability(s));
}

```

**Result**

python: 
```
Prediction Result: 0
-1:0.34243086  
0:0.47817318
1:0.17939596
```

Java:
```
Prediction Result: 0
-1:0.309083158794952
0:0.450241973874403
1:0.240674867330645
```

I tried to check the source code, but did not find the reason, please help.

I can help to recreate the phenomenon

**Comment by vruusmann** [comment]
The "bag of words" modeling workflow has been tested with the English text. My assumption is that it should work with other languages as well, but I haven't really tested it. However, this issue, and some other issues (a complaint from one Arabic language user, received via e-mail) suggest that something may be amiss.

To begin troubleshooting, I would need your help. First, to understand the scope/severity of the problem, could you answer the following four questions: https://github.com/jpmml/jpmml-evaluator/issues/82#issuecomment-344304993

Second, can you provide a toy dataset (around 100 labeled data records) that would demonstrate the problem? I'd like to train a model locally, and then compare Scikit-Learn and (J)PMML tokenization behaviour - maybe they interpret whitespace or punctuation characters differently.
