### ISSUE TITLE
Can I put pandas replace into PMMLpipeline?

### ISSUE THREAD

**Issue by LmYjQ** [jpmml/sklearn2pmml#71]
df.replace(-1, np.nan) before model fitting

**Comment by vruusmann** [comment]
The converter applications retrieves the list of instructions from the `pickle` file. If you can suggest a way how such "direct DataFrame manipulation operations" can be pickled, then it should be possible to teach the converter application about it.

Is this kind of value mapping (`-1` -> `NaN`) really necessary? Both `sklearn2pmml.decoration.ContinuousDomain` and `sklearn.preprocessing.Imputer` transformations can treat custom values as a missing value:
```Python
mapper = DataFrameMapper([
  ("x", [ContinuousDomain(missing_values = -1), Imputer(missing_values = -1)])
])
```
