### ISSUE TITLE
Support for user-specified applicability domains

### ISSUE THREAD

**Issue by vruusmann** [jpmml/sklearn2pmml#72]
`Domain` subclasses should allow the data scientist to directly specify the intended applicability domain of the model.

For example, specifying that the continuous feature "Age" must be in range between `0` and `120`:
```Python
mapper = DataFrameMapper([
  ("Age", ContinuousDomain(data_min = 0, data_max = 120))
])
```

**Comment by rwjmiller** [comment]
Please could you clarify the current intended functionality of `ContinuousDomain` after a model has been converted to PMML? I would have expected that if one used e.g.

    ContinuousDomain(outlier_treatment='as_extreme_values', low_value = 0, high_value = 1)

then it should be possible to score data containing any (non-missing) value for a variable treated this way, even if it lies outside the range of values present in the training data. 

In practice, however, I have found that although outliers are handled as expected when calling the `predict` method of a PMMLPipeline within Python, scoring the corresponding pmml on values outside the range present in the training data using the openscoring service results in errors.

Is this a known issue?

**Comment by vruusmann** [comment]
> Please could you clarify the current intended functionality of ContinuousDomain after a model has been converted to PMML?

Class `ContinuousDomain` learns the range of valid values from the training data.

This issue is about having a mechanism to overrule that behaviour, so that the range of valid values could be set manually.

> ContinuousDomain(outlier_treatment='as_extreme_values', low_value = 0, high_value = 1)

It should be possible to make it work partially, if you disable learning the range of valid values by specifying `with_data = False`?

Haven't tested it so thoroughly. Maybe the Python side should throw an exception if `with_data = True`, and the user is supplying incompatible `low_value` and `high_value` attributes (cannot be checked inside the `__init__` method, but could be checked later on inside the `fit(X)` method).

> scoring the corresponding pmml on values outside the range present in the training data using the openscoring service results in errors.

Examples of such errors?

There was some confusion about outlier definition/treatment, which was cleared quite recently by the DMG.org here:
http://mantis.dmg.org/view.php?id=202

So, I hope that you're "complaining" about an up-to-date Openscoring version, not some ancient version.

**Comment by vruusmann** [comment]
See https://github.com/jpmml/jpmml-lightgbm/issues/16 for additional user requirements.

**Comment by vruusmann** [comment]
I've implemented full invalid value treatment in https://github.com/jpmml/sklearn2pmml/commit/c47c1e5ae0070ac2296d8ea7dc6aded6262e5572.

In brief, the data that is passed to `Domain.fit(X, y)` is considered to represent the **valid** value space. Everything else is considered to represent the **invalid** value space.

If one doesn't like this convention, then it's always possible to suppress the learning of the **valid** value space by specifying `Domain(with_data = False)`.
