### ISSUE TITLE
self defined transform functions giving error

### ISSUE THREAD

**Issue by sharmasw** [jpmml/sklearn2pmml#84]
I am trying to create a PMML file with self defined pre-processing steps and model using Sklearn2PMML below is the script:
In the script I have defined my own (actually copied from the sklearn website), "ItemSelector".

from the error messages in console I figure out at that particular point my code crashes. Please support  or guide how to solve this problem.

```
import pandas as pd
from sklearn import model_selection,preprocessing,metrics
from sklearn.pipeline import Pipeline,FeatureUnion
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.preprocessing import FunctionTransformer, Imputer
from sklearn import linear_model, ensemble

from sklearn2pmml import PMMLPipeline
from sklearn2pmml import sklearn2pmml
import sklearn
sklearn.__version__
```
'0.19.1'

```
data=pd.read_csv('mpg_data_example.csv')

class ItemSelector(BaseEstimator, TransformerMixin):
    def __init__(self, key):
        self.key = key

    def fit(self, x, y=None):
        return self

    def transform(self, data_dict):
        return data_dict[[self.key]]

pipdi=Pipeline([('prepro',FeatureUnion(            [
                ('t1',Pipeline([('extract',ItemSelector(key='mpg'))])),
            ])),
               ('estimator', ensemble.RandomForestRegressor())])

pipdi.fit(data,data['mpg'])

```
Pipeline(memory=None,
     steps=[('prepro', FeatureUnion(n_jobs=1,
       transformer_list=[('t1', Pipeline(memory=None, steps=[('extract', ItemSelector(key='mpg'))]))],
       transformer_weights=None)), ('estimator', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_...timators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False))])

`pipdi.predict(data)`

array([ 18.  ,  15.  ,  18.  ,  16.  ,  17.  ,  15.  ,  14.  ,  14.  ,
        14.  ,  15.  ,  15.  ,  14.  ,  15.  ,  14.  ,  24.  ,  22.  ,
        18.  ,  21.  ,  27.  ,  26.  ,  25.  ,  24.  ,  25.  ,  26.  ,
        21.  ,   9.9 ,   9.9 ,  11.  ,   9.5 ,  27.  ,  28))

```
pipdi=PMMLPipeline([('prepro',FeatureUnion(            [
                ('t1',Pipeline([('extract',ItemSelector(key='mpg'))])),
            ])),
               ('estimator', ensemble.RandomForestRegressor())])
```

`pipdi.fit(data,data['mpg'])`

PMMLPipeline(steps=[('lala', FeatureUnion(n_jobs=1,
       transformer_list=[('t1', Pipeline(memory=None, steps=[('extract', ItemSelector(key='mpg'))]))],
       transformer_weights=None)),
       ('estimator', RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False))])

`pipdi.predict(data)`

array([ 18.  ,  15.  ,  18.  ,  16.  ,  17.  ,  15.  ,  14.  ,  14.  ,
        14.  ,  15.  ,  15.  ,  14.  ,  15.  ,  14.  ,  24.  ,  22.  ,
        18.  ,  21.  ,  27.  ,  26.  ,  25.  ,  24.  ,  25.  ,  26.  ,
        21.  ,  10.  ,  10.  ,  11.  ,   9.4 ,  27.  ,  28.  ,  25.  ,
        25.  ,  19.  ,  16.  ,  17.  ,  19.  ,  18.  ,  14.  ,  14.  ,
        14.  ,  14.  ,  12.  ,  13.  ,  13.  ,  18.  , ))

`sklearn2pmml(pipdi, "DecisionTreeIris.pmml", with_repr = True)`

here I get the error:

CalledProcessError                        Traceback (most recent call last)
~\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn2pmml\__init__.py in sklearn2pmml(pipeline, pmml, user_classpath, with_repr, debug)
    269                 try:
--> 270                         subprocess.check_call(cmd)
    271                 except CalledProcessError:

~\AppData\Local\Continuum\anaconda3\lib\subprocess.py in check_call(*popenargs, **kwargs)
    290             cmd = popenargs[0]
--> 291         raise CalledProcessError(retcode, cmd)
    292     return 0

RuntimeError: The JPMML-SkLearn conversion application has failed. The Java process should have printed more information about the failure into its standard output and/or error streams

Feb 28, 2018 2:28:08 PM org.jpmml.sklearn.Main run
SEVERE: Failed to convert
java.lang.IllegalArgumentException: Tuple contains an unsupported value (Python
class __main__.ItemSelector)
        at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:43)
        at com.google.common.collect.Lists$TransformingRandomAccessList.get(Lis
s.java:625)
        at sklearn.TransformerUtil.getHead(TransformerUtil.java:35)
        at sklearn2pmml.PMMLPipeline.encodePMML(PMMLPipeline.java:140)
        at org.jpmml.sklearn.Main.run(Main.java:145)
        at org.jpmml.sklearn.Main.main(Main.java:94)
Caused by: java.lang.ClassCastException: Cannot cast net.razorvine.pickle.objec
s.ClassDict to sklearn.Transformer
        at java.lang.Class.cast(Unknown Source)
        at org.jpmml.sklearn.CastFunction.apply(CastFunction.java:41)
        ... 5 more

**Comment by vruusmann** [comment]
> java.lang.IllegalArgumentException: Tuple contains an unsupported value (Python
class main.ItemSelector)

Translation: "The Python-side (Scikit-Learn pipeline) uses transformer class `main.ItemSelector`, which is not defined on the Java side".

There's a [SkLearn2PMML-Plugin](https://github.com/jpmml/sklearn2pmml-plugin) project, which will guide you step-by-step through the process of implementing your own estimator and transformer types.
