### ISSUE TITLE
Issue in release 0.31: ExpressionTransformer.get_params() returns {'expr': None}

### ISSUE THREAD

**Issue by AndreDCMartins** [jpmml/sklearn2pmml#86]
I am applying `sklearn.model_selection.cross_val_predict` on top of a PMMLPipeline in which I have an ExpressionTransformer.
In previous releases of sklearn2pmml this worked fine, but with 0.31.0, I have the error that the expression in ExpressionTransformer is empty. This is related to the fact that ExpressionTransformer now inherits the BaseEstimator class and the `get_params` method, but this method returns `{'expr': None}` instead of `{'expr': self.expr_}`.

`cross_val_predict` clones the pipeline object and all transformers inside of it. If the transformers don't have a `get_params` method then it applies a copy.deepcopy() which copies all attributes (reason why it worked in release 0.30). However, when the transformer has a `get_params` method it only clones the parameters returned by the method.

I suggest to define `get_params` to return the `expr_` attribute.

**Comment by vruusmann** [comment]
Wouldn't it work, if the `expr_` attribute is renamed to `expr` (ie. using the same name as in the constructor)? The trailing underscore character looks like a typo anyway.

**Comment by AndreDCMartins** [comment]
Yes, I think it would and I agree that it's probably the best way to do it.

The other transformers in `sklearn2pmml.preprocessing`, they all set the attribute with the parameter name, so they shouldn't have this issue.
