### ISSUE TITLE
Error with RegressionTree model and Extra-Trees model 

### ISSUE THREAD

**Issue by uestcGJ** [jpmml/sklearn2pmml#94]
Hi,when i try to convert python trained model to pmml use sklearn2pmml ,i got some problem.
The model i used is ExtraTreesRegressor,when try to transfer it to pmml, i got error as fellow:
  File "E:\ProgramFiles\anaconda\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
and when i change decode way to gb2312, it shows as:
RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams

My java version is 1.8.0_91,and something interesting is that when i try to convert LinerRegression or LogisticRegression model they all run well. Moreover,i run your demo code about iris data, the first example(which uses DecisionTreeClassifier model) shows the same error as ExtraTreesRegressor model while the second one(logistic regression example)runs well .So would pelase tell me what's wrong it could be? Thank u~

**Comment by uestcGJ** [comment]
oops,my python2.7 environment is:
('python: ', '2.7.13')
('sklearn: ', '0.18')
('pandas: ', u'0.20.0')
('sklearn_pandas: ', '1.6.0')
('sklearn2pmml: ', '0.35.0')

**Comment by vruusmann** [comment]
> RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams.

What was printed to std out/error streams? I need to see the stack trace of the underlying Java exception in order to diagnose this issue.

Alternatively, you may attach the problematic pickle file here so that I could debug it locally.

**Comment by uestcGJ** [comment]
The error message just including "RuntimeError: The JPMML-SkLearn conversion application has failed. The Java executable should have printed more information about the failure into its standard output and/or standard error streams" and **there is no any other detail information**. So i can't got what's wrong with my code, then i tried your code as shown in the **README** file  part **Usage**,the  result shown that the **decision tree model** demo report the same error as my code,while the **logistic regression model** runs well. So,i guess some problem with my building environment,it was:
('python: ', '2.7.13')
('sklearn: ', '0.18')
('pandas: ', u'0.20.0')
('sklearn_pandas: ', '1.6.0')
('sklearn2pmml: ', '0.35.0')
But i don't know what's the real problem and why the logistic regression model demo runs well but decision tree model fails in my computer..... So,could u please give me some suggestion? How can i fix the problem? thanks a lot~

**Comment by vruusmann** [comment]
Your demo code works just fine - the size of the generated `boston_forecast.pmml` file is 41.2 MB.

The problem resides in your computer. Perhaps you're using some outdated Scikit-Learn/Python/OS/Architecture combination. For example, the sklearn2pmml package may have problems with pickle files that have been saved on 32-bit OS/Architecture.

**Comment by vruusmann** [comment]
Another way how to see the Java exception - save the fitted pipeline as a pickle file, and then use the [JPMML-SkLearn](https://github.com/jpmml/jpmml-sklearn) command-line application for conversion.
