### ISSUE TITLE
CategoricalDomain check new category

### ISSUE THREAD

**Issue by bozhang0504** [jpmml/sklearn2pmml#96]
Hi Villu,

For CategoricalDomain definition, is there any way to check if new category appears in new data and impute it?

I guess what I'm looking for is the similar function of `ContinuousDomain`'s `outlier_treatment` in `CategoricalDomain`.

Thanks,
Bohan

**Comment by xiaowei1234** [comment]
https://scikit-learn.org/stable/modules/generated/sklearn.impute.SimpleImputer.html#sklearn.impute.SimpleImputer

simple imputer supports most_frequent or constant value for categorical imputation

**Comment by vruusmann** [comment]
I believe that this issue has been fixed by now.

There's a tutorial about feature specifications available here: https://openscoring.io/blog/2020/02/23/sklearn_feature_specification_pmml/
