### ISSUE TITLE
Float literals tripping up evaluator?

### ISSUE THREAD

**Issue by pcallier** [jpmml/sklearn2pmml#99]
Hi there, this may just be a case of something caused by our internal setup, but I have a pmml of an xgboost model generated by sklearn2pmml 0.36.0.  The response variable is float and binary, and i with what I assume is a somewhat recent change, the regression tables in the regression model section name the targetCategory with `.0` in the literals:

```
					<RegressionTable intercept="0.0" targetCategory="1.0">
						<NumericPredictor name="xgbValue" coefficient="1.0"/>
					</RegressionTable>
					<RegressionTable intercept="0.0" targetCategory="0.0"/>
				</RegressionModel>
```
Our evaluation system uses jpmml-evaluator 1.3.1 and with a pmml specified like the above, the evaluated output is all zeros. If the literals don't have decimal places, it is happy and produces nonzero outputs with the expected values:
```
					<RegressionTable intercept="0.0" targetCategory="1">
						<NumericPredictor name="xgbValue" coefficient="1.0"/>
					</RegressionTable>
					<RegressionTable intercept="0.0" targetCategory="0"/>
				</RegressionModel>
```
I realize we are using an older pmml-evaluator version but the evaluation team is cagey about upgrading.  Is there an easy way to address this, like by displaying literals without decimal places when possible?  Casting the response to integer before training resolves the issue also but we would need to start doing that across a lot of models. Thanks for any insight you can offer.

**Comment by vruusmann** [comment]
Related discussion:
https://groups.google.com/forum/#!topic/jpmml/X1tUOdTDwY0

In brief, the JPMML-Evaluator library currently maintains category levels as `java.lang.String`. If the `DataField` element defines category levels as `"0"` and `"1"`, but the `RegressionTable` element defines category levels as `"0.0"` and `"1.0"` then, according to `String#equals(String)` they are not "the same thing".

The solution is to unify category levels across all elements. Would be trivial to implement using the Visitor API:
```Java
PMML pmml = ...

Visitor visitor = new org.jpmml.model.visitors.AbstractVisitor(){
  @Override
  public VisitorAction visit(RegressionTable regressionTable){
    String targetCategory = regressionTable.getTargetCategory();
    if(targetCategory.endsWith(".0")){
      targetCategory = targetCategory.substring(0, targetCategory.length() - ".0".length());
      regressionTable.setTargetCategory(targetCategory);
    }
    return super.visit(regressionTable);
  }
};

visitor.applyTo(pmml);
```

Alternatively, you might update `DataField/Value` elements, and append ".0" there.

**Comment by vruusmann** [comment]
Opened a new issue with the JPMML-XGBoost project.

**Comment by vruusmann** [comment]
@pcallier Any reproducible test case about this issue?
